### ISSUE TITLE
Source typing container logs 

### ISSUE THREAD

**Issue by sayeedc** [splunk/splunk-connect-for-kubernetes#109]
Right now, source types are derived from the container or pod name. Are there any plans to provide the option for users to set the source type? This allows users to create the same containers with a common source type rather different ones. I've seen over 1000 sourcetypes created on a single cluster.

**Comment by matthewmodestino** [comment]
Hey Sayeed!

Technically you can set the sourcetype by customizing the `jq_transformer` filter in the logging configmap:

https://github.com/splunk/splunk-connect-for-kubernetes/blob/ec00d8fcf6b4030cca0ea434d8b54a606add85d0/manifests/splunk-kubernetes-logging/configMap.yaml#L177

Ideally, I'd like to see us support setting the sourcetype, among other options in annotations.

**Comment by sayeedc** [comment]
Hey Matt

Ideally, I'd like the users to set the sourcetype from Openshift (maybe via labels or annotations) since how containers are named is controlled by them. It can be anything, which makes setting source types via jq difficult.

**Comment by chaitanyaphalak** [comment]
Currently a user can set the sourcetype using https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-kubernetes-logging/values.yaml#L108
I know its static, for setting sourcetypes dynamically through labels and annotations will require a significant overhaul of the current implementation.

**Comment by rockb1017** [comment]
resolved as part of #294
