### ISSUE TITLE
Buffering to Kafka

### ISSUE THREAD

**Issue by sayeedc** [splunk/splunk-connect-for-kubernetes#119]
Can Splunk connect for Kubernetes support sending to HEC via Kafka? This enables off node buffering, filtering, routing etc.

**Comment by matthewmodestino** [comment]
Hey Sayeedc!

I, personally, have not tried this. Can Kafka even catch HEC traffic??

**Comment by sayeedc** [comment]
I'm not sure and probably a question for the Kafka gurus.

**Comment by dtregonning** [comment]
Hi @sayeedc - Unfortunately this is not supported. We have the Splunk Connect for Kubernetes to read and ingest Records from Splunk to Kafka but that would require getting what you need out of Kubernetes into Kafka.
