### ISSUE TITLE
Could we redirect a specific container log an an Index

### ISSUE THREAD

**Issue by aakashbhalla1** [splunk/splunk-connect-for-kubernetes#121]
Could we redirect a specific container log an an Index

Let me know if you need details.

**Comment by aakashbhalla1** [comment]
Also for a native log format could we add a field for IndexName

logs:
  nginx-access:
    from:
      file:
        path: "/var/log/nginx-containers/host.access.log"
#    multiline:
#      firstline: /\d{4}-\d{2}-\d{2}/
    sourcetype: "nginx:access"
    indexName: "nginx"

**Comment by aakashbhalla1** [comment]
fluentd:monitor-agent are only going to default index there are no provision to put an indexName field to it.

**Comment by matthewmodestino** [comment]
Hi aakashbhalla1!

You definitely can, using fluentd filters and our built in jq_transformer, you can dynamically set the index based on various variables that fluentd tags the log with as it moves through the pipeline. 

Will work on getting a good reference doc and how-to to help users learn and extend their config, and will see how much of it we can expose via helm, vs directly editing the templates.

**Comment by alanzchan** [comment]
Hi,

I'm having the same issue. I see that we can only define sourcetypes in values.yaml. Do you have any examples or documentation that can route different container logs to separate indexes?

**Comment by alanzchan** [comment]
Just wanted to follow up on this issue. I was wondering if there were any updates.

**Comment by rockb1017** [comment]
resolved as part of #294
