### ISSUE TITLE
Move splunk-kubernetes-* chart directories to ease installation using local file repos

### ISSUE THREAD

**Issue by ron1** [splunk/splunk-connect-for-kubernetes#129]
Move 3 splunk-kubernetes-* chart directories to be sub-directories of directory splunk-connect-for-kubernetes/charts. This simplifies installations from the local file system. Here, simply update the repository entries in the requirements.yaml with values like "file://./charts/splunk-kubernetes-<moduleName>" in order to accomplish a WebServer-less, Tiller-less installation from the local file system using command:

```
helm template --name my_splunk-connect -f my_values . | kubectl create -f -
```

**Comment by rockb1017** [comment]
this has been done. Thank you. closing.
