### ISSUE TITLE
Define serviceAccount for use by splunk-kubernetes-logging DaemonSet

### ISSUE THREAD

**Issue by ron1** [splunk/splunk-connect-for-kubernetes#131]
Define serviceAccount for use by splunk-kubernetes-logging DaemonSet. 

Add the following as immediate child of spec.template.spec

```
serviceAccountName: {{ template "splunk-kubernetes-logging-fullname" . }}
```

Also create serviceAccount and its required RBAC.

**Comment by chaitanyaphalak** [comment]
Merged as part of https://github.com/splunk/splunk-connect-for-kubernetes/pull/180
