### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by bilby91** [splunk/splunk-connect-for-kubernetes#132]
Hello,

We are relaying on this project for our production workloads currently and we were wondering if there is any formal release schedule for this project ? 

Thanks

**Comment by bilby91** [comment]
Ping!

**Comment by dtregonning** [comment]
@dbaldwin-splunk

**Comment by BenjaminLepple** [comment]
@dbaldwin-splunk

**Comment by chaitanyaphalak** [comment]
@abbas-splunk

**Comment by chaitanyaphalak** [comment]
We are planning to do a release around .conf 2019.

**Comment by rehevkor5** [comment]
... which apparently is October 22 - 24, 2019.

**Comment by chaitanyaphalak** [comment]
Closing as resolved in https://github.com/splunk/splunk-connect-for-kubernetes/releases/tag/1.3.0
