### ISSUE TITLE
ADDON-21548: The source dimension isn't  being captured correctly

### ISSUE THREAD

**Issue by hexecute** [splunk/splunk-connect-for-kubernetes#133]
We've seen this on a few Splunk deployment types now. The source dimension ends in "//" because it's constructed as `source ${record['node']}/${record['pod-name']}/${record['name']}` or `source ${record['node']}/${record['pod-name']}/${record['container-name']}`. However, the metrics data coming in sometimes has "pod-name" and sometimes has "pod_name" (note the dash versus the underscore). Sometimes, it has "container-name" and sometimes it lacks that dimension entirely. It's unclear to me why this is happening.

![Example 1](https://user-images.githubusercontent.com/4483014/56317995-094fac00-6113-11e9-8c60-4b547b7848c0.png)
![Example 2](https://user-images.githubusercontent.com/4483014/56318003-0ce33300-6113-11e9-9378-b53e9d9f6c31.png)

**Comment by chaitanyaphalak** [comment]
Need more context on this issue, the kubernetes version you are using, the kubernetes flavor you are using and the configmaps for metrics and metrics aggregator components you are using. Thanks.

**Comment by hexecute** [comment]
This has been reported by a few people.

Kubectl versions: 1.13.4, ?
Kubernetes versions: 1.11.8, 1.14.0, ?
Kubernetes flavors: Minikube, KOPS on AWS, manually-created multi-node cluster
Configmaps are the default ones from this repo.

The .yaml file used to set up SCK are variants of this:

[sample.yaml.txt](https://github.com/splunk/splunk-connect-for-kubernetes/files/3104655/sample.yaml.txt)

**Comment by jasonmcboyd** [comment]
@chaitanyaphalak I am seeing this as well.

clientVersion:
  buildDate: "2019-02-28T13:37:52Z"
  gitVersion: v1.13.4
  goVersion: go1.11.5
  major: "1"
  minor: "13"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-03-01T22:49:39Z"
  gitVersion: v1.11.8-eks-7c34c0
  goVersion: go1.10.8
  major: "1"
  minor: 11+
  platform: linux/amd64

As @hexecute said, the [metrics plugin for fluentd](https://github.com/splunk/fluent-plugin-kubernetes-metrics) sometimes reports the pod name field as "pod_name" and sometimes as "pod-name". For example, the "kube.pod.uptime" metric reports the field as "pod-name" while the "kube.pod.tasks.state" metrics reports the field as "pod_name".

Additionally, the recoreds reported by the [metrics aggregator plugin for fluentd](https://github.com/splunk/fluent-plugin-k8s-metrics-agg) exclude the "pod-name" and "cluster-name" fields entirely but the fluentd.conf file for the metrics aggregator is trying to use them to construct the source field.

**Comment by chaitanyaphalak** [comment]
I have tagged it as a bug for now, we will look into it. Thanks @hexecute @jasonmcboyd

**Comment by princeba84** [comment]
Did anyone get solution for this. I have same problem- Different names for same dimension (namespace/pod-namespace) ,(pod-name,pod_name)
Highly appreciated if you can share something on this ?
