### ISSUE TITLE
Support for K8s hosted Splunk Enterprise

### ISSUE THREAD

**Issue by fbongiovanni29** [splunk/splunk-connect-for-kubernetes#138]
After installing Splunk Enterprise following this walkthrough:
https://www.splunk.com/blog/2018/12/17/deploy-splunk-enterprise-on-kubernetes-splunk-connect-for-kubernetes-and-splunk-insights-for-containers-beta-part-1.html

We've been unable to figure out how to set up the chart so that the splunk connect chart can communicate with it properly. Is there support & documentation for this?

**Comment by chaitanyaphalak** [comment]
I would suggest look at your http event collector(HEC) service in kubernetes(for the splunk cluster) and use that service name(for eg. hec.svc.local) as the http event collector(HEC) endpoint in the configuration yaml files for splunk connect for kubernetes

**Comment by matthewmodestino** [comment]
Hi fbongiovanni!

Apologies for the delayed response! 

https://www.splunk.com/blog/2019/02/11/deploy-splunk-enterprise-on-kubernetes-splunk-connect-for-kubernetes-and-splunk-insights-for-containers-beta-part-2.html

See "Deploy a Kubernetes Service for HEC" in Part 2 of that blog which sets up a HEC service and deploys a HEC token across the indexers.

**Comment by fbongiovanni29** [comment]
Real sorry for the delayed response, and thank you very much! We may go with one of these solutions, we have a Splunk Support member working with us no. Think this would be good to close
