### ISSUE TITLE
Anyway to override or add env tag for logging?

### ISSUE THREAD

**Issue by dmxlsj** [splunk/splunk-connect-for-kubernetes#140]
I have multiple Kubernetes clusters for different environments and I would like to tag `env` or `environment` depending on the environment. I used to do this using `_meta` but not sure if this still works.

Currently I see pre-populated value `env=172` (not sure what this means or where from) on Splunk and I wonder if I can override this value to something like `env=stage`, `env=prod`, etc, or create a new tag something like `environment=stage`

**Comment by deepamshah20** [comment]
Has anyone got an answer for this?? We are looking to do the same...

**Comment by chaitanyaphalak** [comment]
you can use the clusterName field for eg. https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-kubernetes-logging/values.yaml#L316
Closing this for now, create a new issue if this work for you. Thanks.

**Comment by dmxlsj** [comment]
I am not sure if this is a known issue but, yes we are using `cluster_name` on production.
However search with the field is not always populated. I need to dig further but it only works for some specific `sourcetypes`, and some of the containers are not working with `cluster_name` at all.

**Comment by chaitanyaphalak** [comment]
You can have a look at the following PR https://github.com/splunk/splunk-connect-for-kubernetes/pull/185 and the commit merged to develop https://github.com/splunk/splunk-connect-for-kubernetes/commit/2addba7458d9e30a31f7bb861f9cdc71cb155dca

If you find more issues, please file a new issue letting us know which metrics/events are missing the cluster name field. Thanks.
