### ISSUE TITLE
Support containerd runtime for IBM Cloud Kubernetes compatibility

### ISSUE THREAD

**Issue by jeffywu** [splunk/splunk-connect-for-kubernetes#143]
**What would you like to be added**:
IBM Cloud Kubernetes 1.11+ runs containerd as the Docker runtime which causes the log locations and log formats to be different from the defaults in this app.

The log paths are as follows:
/var/log/pods symlinks to /var/data/kubeletlogs, the format of kubelets logs directory is:

> Your logging tool might use the container stderr/stdout directory /var/log/pods/<pod_uuid>/<container_name>/*.log to access logs. In Docker, this directory is a symlink to /var/data/cripersistentstorage/containers/<container_uuid>/<container_uuid>-json.log whereas in containerd you access the directory directly without a symlink.
Reference:  https://cloud.ibm.com/docs/containers?topic=containers-cs_versions#containerd

Would be nice to parametrize the volume mounts so we can configure this from values.yaml.

The log format is CRIO, which there is a log parser for, but not sure if this is in the docker image yet: https://github.com/fluent/fluent-bit/pull/667

Blog Post:
https://www.ibm.com/blogs/bluemix/2019/01/ibm-cloud-kubernetes-service-supports-containerd/

**Why is this needed**:
We want to be able to support IBM cloud platform for our blockchain customers.

**Comment by matthewmodestino** [comment]
So far looks to be simple updates to the configmap to account for the change and the new filters required. Correlation becomes `pod_uid` + `container_name`

**Comment by jeffywu** [comment]
The log path may be changed as described here: https://github.com/kubernetes/kubernetes/issues/58638#issuecomment-385126031
