### ISSUE TITLE
how can we set sourcetype to namespace.

### ISSUE THREAD

**Issue by beth2016** [splunk/splunk-connect-for-kubernetes#144]
How can we set sourcetype to the name of the namespace?

**Comment by chaitanyaphalak** [comment]
I am assuming you want to do this for logging. You will need to do some changes to the helm template for logging, specifically in https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-kubernetes-logging/templates/_helpers.tpl#L96-L109 . This can be done by setting .sourcetype = .namespace or .sourcetype = set_namespace($parts[1]) in the extract_container_info function. If you think this will help the community surrounding this project, you can do the above implementation in a generic configurable way. I will be happy to review the pull request. Thanks.
