### ISSUE TITLE
HEC returns 400 {"text":"Error in handling indexed fields","code":15} to metrics-agg

### ISSUE THREAD

**Issue by waarg** [splunk/splunk-connect-for-kubernetes#147]
**What happened**:

HEC returns 400 Bad Request - {"text":"Error in handling indexed fields","code":15} to metrics-aggregator

**What you expected to happen**:

HEC return 200

**How to reproduce it (as minimally and precisely as possible)**:

Deploy Splunk Connect for Kubernetes using Helm chart with mostly defaults (aside from a few changes to customise eg cluster_name) to a Rancher cluster hosted in AWS EC2, enable logging, metrics and objects, observe error in metrics-agg pod.

**Anything else we need to know?**:

There are many, many log lines being sent with this error. 

Here is some output with debug on:

```
Failed POST to https://xxxxxxxx/services/collector, response: {"text":"Error in handling indexed fields","code":15}
Failed request body: {"host":"","time":"1557389128.8188767","event":"metric","index":"kubernetes_events","source":"source","fields":{"metric_name":"kube.container.memory.request","_value":0.0,"name":"ecr-creds-updater-job","image":"xxxxxxxx","node":"xxxxxxxx","cluster_name":"sandbox","source":"xxxxxxxx"}}

```
I have tested using CURL to post the failed request body direct to the HEC, modifying the body until it worked. The culprit appears to be the unquoted 0.0 value in "_value":0.0. When I modify the body to quote this value, the post succeeds and HEC returns 200 OK.

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.13.5-rancher1-2
- OS (e.g: `cat /etc/os-release`):
RHEL 7.6
- Splunk version:
7.0.1
- Others:
Rancher v2.2.2

**Comment by waarg** [comment]
Possibly related to #136 as we are seeing 

`Unexpected error raised. Stopping the timer. title=:metric_scraper error_class=SocketError error="Failed to open TCP connection to rancher-clust-worker:10250 (getaddrinfo: Name does not resolve)"`

in the metrics pods

**Comment by chaitanyaphalak** [comment]
Hey @waarg , thanks for the issue report. It seems as if the node name is not resolvable in your kubernetes cluster. I would say try to curl on the worker node you have(rancher-clust-worker:10250) and see if that works, if it dosent it means we have some dns resolution issues which you can dig into. if the above suggestions dont work out for you, please feel free to reach out. Thanks.

**Comment by waarg** [comment]
Hi @chaitanyaphalak , thanks for your reply.

I think in this case #136 may be unrelated. I tweaked my deployment to use fieldPath: status.hostIP instead of node name and the connection error above went away. I see there is a PR open which may resolve #136 so that's good.

However, the original 400 bad request error raised on this issue remains.

**Comment by chaitanyaphalak** [comment]
Hey @waarg i suspect that you trying to send metrics to an events index, can you check if the index you created "kubernetes_events" is a metrics index, if not please create a metrics index and send metrics to that. Let me know if that works out for you. Thanks.

**Comment by waarg** [comment]
Hi @chaitanyaphalak 

Thanks for your response before. I have been testing this some more with curl. I can confirm I am posting to a metrics index. 

When posting the following body to the HEC it returns 400 bad request {"text":"Error in handling indexed fields","code":15}:

`curl -v -X POST "https://xxxxxxxxxxxxx/services/collector" -H 'Authorization: Splunk xxxxxxxxxxx' -H 'Content-Type: application/json' -d '{"host":"server01","time":"1562251426.295","event":"metric","index":"kubernetes_metrics","source":"source","fields":{"metric_name":"kube.container.cpu.limit","_value":0,"name":"rancher-logging-fluentd","image":"rancher/fluentd:v0.1.13","node":"k8s-np-worker-xx.xx.xx.xx","cluster_name":"cluster","source":"k8s-np-worker-xx.xx.xx.xx//"}}'`

This fails with the same error. 

However, this request works:

`curl -v -X POST "https://xxxxxxxxxxxxx/services/collector" -H 'Authorization: Splunk xxxxxxxxxxx' -H 'Content-Type: application/json' -d '{"host":"server01","time":"1562251426.295","event":"metric","index":"kubernetes_metrics","source":"source","fields":{"metric_name":"kube.container.cpu.limit","_value":"0","name":"rancher-logging-fluentd","image":"rancher/fluentd:v0.1.13","node":"k8s-np-worker-xx.xx.xx.xx","cluster_name":"cluster","source":"k8s-np-worker-xx.xx.xx.xx//"}}'`

You will notice that in the second body the value of _value is quoted, while in the first it is not.

It seems that the value of "_value" has to be quoted, otherwise HEC returns 400 bad request. Is this something that I can fix somewhere in the helm chart configuration?

Thanks again.

**Comment by TechnicalMercenary** [comment]
@chaitanyaphalak Can this issue be re-opened? I'm experiencing the same issue and I can confirm that in my test as well, if the value for "_value" is quoted then the issue goes away

**Comment by chaitanyaphalak** [comment]
@TechnicalMercenary can you provide more context on the issue, which kubernetes flavor you are using? the configs you are using, basically everything in the issue template. Thanks :)

**Comment by chaitanyaphalak** [comment]
Hey @waarg , sorry for the late reply, but this issue that you are facing isn't a simple helm chart fix. For this you will have to add a fix to the metrics-agg plugin specifically at https://github.com/splunk/fluent-plugin-k8s-metrics-agg/blob/develop/lib/fluent/plugin/in_kubernetes_metrics_aggregator.rb#L403

**Comment by TechnicalMercenary** [comment]
**What happened**:

No metrics from the metrics pod is being sent ( or arriving ) in our splunk dashboard.  Seeing errors like the following in the logs for the pod `splunk-kubernetes-metrics-66b5567cc9-czlls`

`2019-08-02 16:42:38 +0000 [error]: #0 Failed POST to https://input-prd-p-dp26j479nmxg.cloud.splunk.com:8088/services/collector, response: {"text":"Error in handling indexed fields","code":15}
2019-08-02 16:42:53 +0000 [error]: #0 Failed POST to https://input-prd-p-dp26j479nmxg.cloud.splunk.com:8088/services/collector, response: {"text":"Error in handling indexed fields","code":15}
2019-08-02 16:43:08 +0000 [error]: #0 Failed POST to https://input-prd-p-dp26j479nmxg.cloud.splunk.com:8088/services/collector, response: {"text":"Error in handling indexed fields","code":15}`

**What you expected to happen**:

No errors in the logs and K8s metrics appearing...

**How to reproduce it (as minimally and precisely as possible)**:

I turned on debug and captured some of the json, then using the json I made a curl to our HEC url...

`> curl -k https://input-prd-p-dpXXXXXnmxg.cloud.splunk.com:8088/services/collector -H 'Authorization: Splunk 99400ED5-E000-478A-XXXX-A8073FBE8016' -d '{"host":"ip-10-241-80-37.us-west-2.compute.internal","time":"1564611441.2898638","event":"metric","source":"kube.pod.tasks.state","fields":{"metric_name":"kube.pod.tasks.state","_value":0.0,"pod_name":"splunk-kubernetes-objects-67cc7d59b8-qr82b","image":"sha256:342c5dda59df0a26788052ea1a71ec019a6d8a1f3f1ecf2a20fa746205d86d3b","namespace":"default","node":"ip-10-241-80-37.us-west-2.compute.internal","source":"ip-10-241-80-37.us-west-2.compute.internal/"}}'

{"text":"Error in handling indexed fields","code":15}`

**IF** I quote the `_value` ,  then.....

`> curl -k https://input-prd-p-dpXXXXXnmxg.cloud.splunk.com:8088/services/collector -H 'Authorization: Splunk 99400ED5-E000-478A-XXXX-A8073FBE8016' -d '{"host":"ip-10-241-80-37.us-west-2.compute.internal","time":"1564611441.2898638","event":"metric","source":"kube.pod.tasks.state","fields":{"metric_name":"kube.pod.tasks.state","_value”:”0.0”,”pod_name":"splunk-kubernetes-objects-67cc7d59b8-qr82b","image":"sha256:342c5dda59df0a26788052ea1a71ec019a6d8a1f3f1ecf2a20fa746205d86d3b","namespace":"default","node":"ip-10-241-80-37.us-west-2.compute.internal","source":"ip-10-241-80-37.us-west-2.compute.internal/"}}'

{"text":"Success","code":0}`

**Anything else we need to know?:**


I have tested using CURL to post the failed request body direct to the HEC, modifying the body until it worked. The culprit appears to be the unquoted 0.0 value in "_value":0.0. When I modify the body to quote this value, the post succeeds and HEC returns 200 OK.

**Environment:**

Kubernetes version (use kubectl version):
`
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-2e569f", GitCommit:"2e569fd887357952e506846ed47fc30cc385409a", GitTreeState:"clean", BuildDate:"2019-07-25T23:13:33Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
`

Image:      splunk/k8s-metrics:1.1.1

**Comment by chaitanyaphalak** [comment]
Hey @TechnicalMercenary its seems you are using eks, we fully support eks. I observed you are using Splunk Version 6.6.3.2, I dont think that version of Splunk has metrics support.
If you change the version on this page https://docs.splunk.com/Documentation/Splunk/7.3.1/Metrics/GetStarted to 6.6.3 nothing shows up, suggesting metrics support was added later. Can you confirm this?

**Comment by TechnicalMercenary** [comment]
ok, I just saw this too when going back through documentation etc.  

That's affirmative.  I'll contact our support and see what it's going to take to upgrade.

Thanks
