### ISSUE TITLE
Can we use deployment metadata to set the index name for logging?

### ISSUE THREAD

**Issue by beth2016** [splunk/splunk-connect-for-kubernetes#148]
Hi,
Is there a way we can use deployment metadata (labels or annotations) to set the index name for splunk logging?  
thanks.

**Comment by chaitanyaphalak** [comment]
@beth2016 nope, the index name is usually preconfigured by the user before installing splunk logging. Let me know if you have ideas on implementing this, or you can send us a Pull Request. Thanks. Have an awesome day.

**Comment by beth2016** [comment]
For splunk k8s object (not splunk logging),  i see that namespace metadata are captured.  Which plugin/component does that piece?

**Comment by chaitanyaphalak** [comment]
https://github.com/splunk/fluent-plugin-kubernetes-objects

**Comment by chaitanyaphalak** [comment]
resolved as part of https://github.com/splunk/splunk-connect-for-kubernetes/pull/294
