### ISSUE TITLE
make fluentd:monitor-agent verbosity configurable

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-connect-for-kubernetes#150]
**What would you like to be added**:

The total volume of logging for the `fluentd:monitor-agent` sourcetype needs to allow for reduction in resolution to reduce daily ingest. I would like to see guidance on how to disable it and how to control the resolution based on how much of it you are willing to index per day. 

Today, in practice, I just disable in the configmap, but would like to explore reduction in interval, as the data can be made very useful for a diagnostics dashboard :

```
@include system.conf
@include source.containers.conf
@include source.docker.conf
@include source.files.conf
@include source.journald.conf
#@include monit.conf
@include output.conf
```

**Why is this needed**:

some customers have millions of events for fluentd:monitor-agent across their 10s of collector pods. Adds up...Probably better used in metric store. 

Looks like mine is doing about 30K events daily, to the tune of 3MB

![image](https://user-images.githubusercontent.com/31549209/57883832-59468f00-77f5-11e9-997c-086c88971343.png)

**Comment by bdschaap** [comment]
The default emit_interval is 60 seconds.  You can reduce its log volume by specifying a higher value such as this.

    <source>
      @id fluentd-monitor-agent
      @type monitor_agent
      @label @SPLUNK
      tag monitor_agent
      emit_interval 300
    </source>

**Comment by matthewmodestino** [comment]
perfect! thanks!
