### ISSUE TITLE
Metrics Aggregator Host Field Is Blank

### ISSUE THREAD

**Issue by jasonmcboyd** [splunk/splunk-connect-for-kubernetes#154]
**What happened**:
All records reported by the metrics aggregator have a blank "host" field. The fluent.conf file for the metrics aggregator is trying to set the "host" field from the "MY_NODE_NAME" environment variable but no such environment variable exists on the host and as far as I can tell that variable is not set anywhere in the helm deployment. In any case, it seems like this would set the "host" field to a static value. Honest question, does it make sense that the "host" name should be a static value? Maybe it does for aggregate metrics? 

**What you expected to happen**:
I expect the "host" field to not be blank.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy kubernetes metrics aggretgator

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
clientVersion:
  buildDate: "2019-02-28T13:37:52Z"
  compiler: gc
  gitCommit: c27b913fddd1a6c480c229191a087698aa92f0b1
  gitTreeState: clean
  gitVersion: v1.13.4
  goVersion: go1.11.5
  major: "1"
  minor: "13"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-03-01T22:49:39Z"
  compiler: gc
  gitCommit: 7c34c0d2f2d0f11f397d55a46945193a0e22d8f3
  gitTreeState: clean
  gitVersion: v1.11.8-eks-7c34c0
  goVersion: go1.10.8
  major: "1"
  minor: 11+
  platform: linux/amd64

- Ruby version (use `ruby --version`):
ruby 2.5.2p104 (2018-10-18 revision 65133) [x86_64-linux-musl]

- OS (e.g: `cat /etc/os-release`):
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.2
PRETTY_NAME="Alpine Linux v3.8"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"

- Splunk version:
Splunk Cloud, Version 7.0.8.5

- Others:
Docker Image: splunk/k8s-metrics-aggr:1.1.0

**Comment by matthewmodestino** [comment]
Hey @jasonmcboyd!

Can you share you values file and helm deploy command? or are you using manifests?

**Comment by chaitanyaphalak** [comment]
@jasonmcboyd can you try out the SCK 1.2.0 release and let us know if that works for you? It looks like you are using eks, but i just wanted to confirm that too. Thanks.

**Comment by MarcoSchaar** [comment]
hi 
with release 1.2.0 host field is still blank

**Comment by matthewmodestino** [comment]
i verified this as well. Will add to the list of things to do. Easy to fix with `jq_transformer`
