### ISSUE TITLE
AKS master node logs - Azure Diagnostics vs fluentd

### ISSUE THREAD

**Issue by stephen-cairns** [splunk/splunk-connect-for-kubernetes#156]
Hi 
We were having a closer look at the Fluentd documentation and see it that it captures Kubernetes System Component logs.  The link for Kubernetes System Components calls out master components e.g. kube-apiserver, kube-scheduler, kube-controller-manager, etcd, cloud-controller-manager

This is practically the same data as the Azure AKS Diagnostics settings required to collect master node logs (https://docs.microsoft.com/en-us/azure/aks/view-master-logs) Diagnostics Log capture includes: kube-apiserver, kube-controller-manager, kube-scheduler, kube-audit, cluster-autoscaler

My initial thoughts are we would be doubling up collecting both these things and maybe we could only use FluentD which will give us both worker and master nodes logs.  

I am trying to figure out if AKS will have any different master logs than say a standard Kubernetes cluster.  Would like to avoid collecting twice but equally we don't want to miss anything.  Any advice would be welcomed.

**Comment by chaitanyaphalak** [comment]
For all the kubernetes system components there is one source for logs viz. the pods themselves. I would say that they should be the same in Azure AKS and this project, but I would still recommend you to try and compare both to see if there is a critical difference for you. Please report back to us if you find out that this project is missing some critical logs and we will add support for them. Thanks.
