### ISSUE TITLE
kubernetes metrics is taking invalid sourcetype=httpevent

### ISSUE THREAD

**Issue by Ramesh5a7** [splunk/splunk-connect-for-kubernetes#159]
Logs are updating as below. splunk connect for kubernetes is not able to pick the sourcetype.

    6/1/194:21:25.349 AM   metric
    6/1/194:21:25.349 AM   metric
    6/1/194:21:25.349 AM   metric
    6/1/194:21:25.349 AM   metric
    6/1/194:21:25.349 AM   metric

We have downloaded the code and configured as below.

Only changes we made:
In configMap.yaml, lines 210/211 changed HEC Host and Port
In secret.yaml, changed hec token to base64 encode.

**Comment by matthewmodestino** [comment]
Perfect. How are you searching them?

**Comment by Ramesh5a7** [comment]
index="kubernetes_metrics"

**Comment by matthewmodestino** [comment]
```
| mcatalog values(metric_name) AS metric_name WHERE index=eks_metrics by host, source, sourcetype
```

Does this return info for you?

Splunk metrics use `mstats` or `mcatalog` commands, but you should really just install the metric workspace app!

**Comment by Ramesh5a7** [comment]
I have installed metric workspace app!
when i opened the metrics tab i see 500 internal server error.

![image](https://user-images.githubusercontent.com/51321081/58809674-f8fb7e00-8639-11e9-9308-ec6eda6f3b94.png)

**Comment by matthewmodestino** [comment]
Restart Splunk.

**Comment by Ramesh5a7** [comment]
Restarted. now i am able to open metrics page. i have selected time picker last 30 days.... still it is showing blank and no metrics.

![image](https://user-images.githubusercontent.com/51321081/58815413-28fc4e80-8645-11e9-9c87-7ea222593aef.png)

**Comment by dtregonning** [comment]
@Ramesh5a7 Looks like we are sending metrics to an event based index. Can we just confirm its configured as a metrics index.
When you go to the Settings -> Data -> indexes page.
What "Type" of index is kubernetes_metrics??

<img width="654" alt="Screen Shot 2019-06-03 at 3 34 55 PM" src="https://user-images.githubusercontent.com/17054614/58839124-a27c4880-8615-11e9-9bed-16519cd16b7a.png">

**Comment by Ramesh5a7** [comment]
Yes, it is showing Events. i don't see any option to change it...
Any idea how to change?


![image](https://user-images.githubusercontent.com/51321081/58848243-70b1c300-86a3-11e9-8b4f-f68d6e0777a8.png)

**Comment by Ramesh5a7** [comment]
Thank you So much. I have changed the index type to metrics. now metrics are working. 

![image](https://user-images.githubusercontent.com/51321081/58848644-fbdf8880-86a4-11e9-84d7-a02758dd796c.png)
![image](https://user-images.githubusercontent.com/51321081/58848698-2c272700-86a5-11e9-9163-cf301a264150.png)




![image](https://user-images.githubusercontent.com/51321081/58848528-98edf180-86a4-11e9-8c9a-672d523d86c9.png)

**Comment by dontregonning** [comment]
Your welcome @Ramesh5a7 - Happy metrics searching
