### ISSUE TITLE
how can we make index_key available for splunk-objects?

### ISSUE THREAD

**Issue by beth2016** [splunk/splunk-connect-for-kubernetes#160]
Just like in spunk-logging,  how can we make index_key available for splunk-objects?
Basically, i want to redirect the splunk objects to diferent index based on the variable index_key.  Thanks.

**Comment by chaitanyaphalak** [comment]
@beth2016 that is not currently supported. You may want to head over to https://github.com/splunk/fluent-plugin-kubernetes-objects and submit a feature request.

**Comment by matthewmodestino** [comment]
You will need to use the `jq_transformer` to add the index field as part of the filters before they get sent with the hec plugin, similar to how we use it to set the source, etc. 

```
    <filter kube.**>
      @type jq_transformer
      jq '.record.index = "my_index" | .record'
    </filter>

```

similar to

https://github.com/splunk/splunk-connect-for-kubernetes/blob/7292e173e4fdc496e92ba4ebc3a187abb62e0a37/manifests/splunk-kubernetes-objects/configMap.yaml#L39-L42

**Comment by beth2016** [comment]
@matthewmodestino   Thanks.   I will give that a try.  You are awesome.
