### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by rhockenbury** [splunk/splunk-connect-for-kubernetes#163]
**What would you like to be added**:
Support for Windows Server 2019 nodes. 

**Why is this needed**:
Since 1.14, Kubernetes has GA support for running Windows server containers.  Splunk should be able to offer a logging solution for hybrid clusters.  Fluentd can run on windows, and the daemonsets for splunk-connect do not need privileged container support so there are no technical blockers.

**Comment by dbaldwin-splunk** [comment]
Are you planning on running this in Azure or on-prem datacenter deployment?

**Comment by rhockenbury** [comment]
On-premise in the short-term, but eventually Azure.

**Comment by halovanic** [comment]
Is there any interest in continuing this feature? AKS, GKE, EKS and Openshift all now have reached general availability for hybrid clusters with Windows Server 2019 nodes.
