### ISSUE TITLE
Feature: Reuse / Rename existing K8s secret

### ISSUE THREAD

**Issue by VincentS** [splunk/splunk-connect-for-kubernetes#17]
We need the option to reference an existing secret in K8s instead of creating a new one when the Splunk Helm Chart is deployed. In our K8s Instances all Secrets are created through a separate process / additional tooling. 

Goal:
- Can reference a exsiting secret
- Able to change secret name to fit into our global Name Schema

**Comment by VincentS** [comment]
#10

**Comment by mohanayalamanchi** [comment]
trying to deploy metric sub chart. Unfortunately pods isn't running because of the issue.
Error from server (BadRequest): a container name must be specified for pod test-metric-splunk-kubernetes-metrics-b4f946587-f4gxg, choose one of: [splunk-heapster splunk-fluentd-heapster]

**Comment by mohanayalamanchi** [comment]
Trying to install metric sub chart. Unfortunately pod is failing with following message.
Error from server (BadRequest): a container name must be specified for pod test-metric-splunk-kubernetes-metrics-b4f946587-f4gxg, choose one of: [splunk-heapster splunk-fluentd-heapster]

**Comment by mohanayal** [comment]
Trying to install metric sub chart. Unfortunately pod is failing with following message.
Error from server (BadRequest): a container name must be specified for pod test-metric-splunk-kubernetes-metrics-b4f946587-f4gxg, choose one of: [splunk-heapster splunk-fluentd-heapster]

**Comment by dbaldwin-splunk** [comment]
@luckyj5

**Comment by chaitanyaphalak** [comment]
Addressed in SCK 1.2
