### ISSUE TITLE
Add file buffer feature for fluentd

### ISSUE THREAD

**Issue by sspreitzer** [splunk/splunk-connect-for-kubernetes#177]
I would like a file based buffering feature to be added to splunk-connect.

It is necessary to reduce the risk of loosing important loggings, for example if a node crashes.

There is a "pos" feature on reading logs, that sets the position of already read lines. But I am not convinced, that this is a sufficient solution. There might be a chance of loosing logs when a node crashes from the time reading the file (and setting the pos), to the time sending the event to Splunk.

**Comment by chaitanyaphalak** [comment]
Have you considered using https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-kubernetes-logging/values.yaml#L268-L276
I think that will be sufficient for your use case. Let us know otherwise, Thanks.

**Comment by sspreitzer** [comment]
Hi @chaitanyaphalak 

Perfect, thank you! I was looking at the manifests, its static memory buffer there.
