### ISSUE TITLE
k8s_metrics and k8s_metrics_aggr stopped reporting after a few hours

### ISSUE THREAD

**Issue by beth2016** [splunk/splunk-connect-for-kubernetes#187]
**What happened**:
k8s_metrics and k8s_metrics_aggr stopped reporting after a few hours
**What you expected to happen**:
I expect it to to continously collect datapoints
**How to reproduce it (as minimally and precisely as possible)**:
Leave it running.  I have k8s clusters with 2 worker nodes.   after a few hours, you will not see any data in the dashboard.  No errors in the logs of the pods.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4+icp-ee", GitCommit:"d03f6421b5463042d87aa0211f116ba4848a0d0f", GitTreeState:"clean", BuildDate:"2019-01-17T13:14:09Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4+icp-ee", GitCommit:"d03f6421b5463042d87aa0211f116ba4848a0d0f", GitTreeState:"clean", BuildDate:"2019-01-17T13:14:09Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Ruby version (use `ruby --version`):
ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux-gnu]

- OS (e.g: `cat /etc/os-release`):
NAME="SLES"
VERSION="12-SP3"
VERSION_ID="12.3"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp3"

- Splunk version:
7.3.0

- Others:

**Comment by matthewmodestino** [comment]
Hi, can you please check Splunk or the output of your logging pods with `kubectl logs-f` see if they crashed or errored out or can no longer connect to HEC?

**Comment by beth2016** [comment]
seems ok now.
