### ISSUE TITLE
Current RHEL image version on Redhat Catalog does not work and is not the latest

### ISSUE THREAD

**Issue by sayeedc** [splunk/splunk-connect-for-kubernetes#188]
**What happened**:
Pulled in image for v1.1.1 which is RHEL based from the Redhat registry. Container is created but crashed because it cannot find the fluentd execution path.

Also v1.2 is not available on the Redhat registry which we need to use as we can no longer pull in docker hub images anymore (blocked by security).

Error: failed to start container "splunk-fluentd-k8s-logs": executable not found in $PATH

**What you expected to happen**:
Container should run as normal just like the debian based images

**How to reproduce it (as minimally and precisely as possible)**:
Pull the image in from redhat.io and run the logging daemonset with the latest config.
If it fails run the container in debug mode and look for the fluentd pather which is actually missing but can be found if you run the docker hub based images

**Anything else we need to know?**:
Can you update the RHEL image to v1.2 which has the journal position file fix. Thank you.

**Environment**:
- Kubernetes version (use `kubectl version`): Openshift v3.10 K8S v1.13
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version: 7.1.2
- Others:

**Comment by rockb1017** [comment]
since 1.4.3, new images are being released for new redhat UBI base image.
