### ISSUE TITLE
Ability to select metrics we are interested in

### ISSUE THREAD

**Issue by beth2016** [splunk/splunk-connect-for-kubernetes#189]
<

**What would you like to be added**:
Is it possible to specify only the metrics we need?  Otherwise it is capturing too many metrics, some of which we dont care much for.

**Why is this needed**:
To reduce the # of metrics

**Comment by chaitanyaphalak** [comment]
closing this as a duplicate of https://github.com/splunk/splunk-connect-for-kubernetes/issues/181
let me know if you need this reopened

**Comment by bdschaap** [comment]
This request seems different than #181.  I believe this issue is asking for the ability to choose specific metrics to ingest while the other issue is asking for different polling frequencies per metric.  I can see there being some overlap in terms of the work being done though.

**Comment by bibin-sebastian** [comment]
Can we know the status of this PR ? I am also stuck with this problem where there are a number of pods we are not interested in . just because of that, we cannot use this awesome connector . Is there any manual work around for the interim?

**Comment by luckyj5** [comment]
@bibin-sebastian Are you looking for a way to disable all of the metrics or log collection from the pods you are not interested in? 
There is a way to disable log collection via https://github.com/splunk/splunk-connect-for-kubernetes/blob/main/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml#L19.

**Comment by bibin-sebastian** [comment]
@luckyj5 I have already disabled the logging part. I am only pulling metrics and objects.  I am looking for ways to configure fluentd to reduce the metrics ingested.
