### ISSUE TITLE
Azure Monitor vs SCK 

### ISSUE THREAD

**Issue by sayeedc** [splunk/splunk-connect-for-kubernetes#191]
What’s a better approach for grabbing logs from managed k8s and Openshift clusters on Azure?

Azure provides their own fluentd agent which run on our nodes and sends data to Azure Monitor. The agent supports container and infrastructure  log collection.

Are there any constraints to deploying the Splunk add-on for Azure Monitor to pull in the data compared with the SCK agent? I know the SCK will strip out any JSON.

**Comment by matthewmodestino** [comment]
In my experience with customers thus far, managed Openshift does not allow you to implement cluster level logging. 

They only provided 2 option, Option 1: File-based sidecar, Option 2: Streaming-based sidecar. 

I am hoping that they change that and allow Splunk configs to run like we would in other cloud providers, as a native option.
