### ISSUE TITLE
Host Field is blank - logging and objects

### ISSUE THREAD

**Issue by kousik93** [splunk/splunk-connect-for-kubernetes#192]
**What happened**:
The host field in splunk is blank for all the logs.
The Host field is set to SPLUNK_HEC_HOST environment variable and that variable doesnt exist and is not passed in both logging chart and objects chart.
 
`host "#{ENV['SPLUNK_HEC_HOST']}"`

Related to https://github.com/splunk/splunk-connect-for-kubernetes/issues/154

**What you expected to happen**:
The 'host' for logs to be set to the Kubernetes node name.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy splunk-connect and check for the host field in logs metadata on UI.

**Environment**:
- Kubernetes version (use `kubectl version`):
clientVersion:
  buildDate: "2019-03-26T00:05:06Z"
  compiler: gc
  gitCommit: 641856db18352033a0d96dbc99153fa3b27298e5
  gitTreeState: clean
  gitVersion: v1.14.0
  goVersion: go1.12.1
  major: "1"
  minor: "14"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-03-25T06:30:48Z"
  compiler: gc
  gitCommit: 16236ce91790d4c75b79f6ce96841db1c843e7d2
  gitTreeState: clean
  gitVersion: v1.11.9
  goVersion: go1.10.8
  major: "1"
  minor: "11"
  platform: linux/amd64

- Ruby version (use `ruby --version`):
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]

- OS (e.g: `cat /etc/os-release`):
macOS High Sierra
10.13.6 (17G6030)

- Splunk version:
7.2.6
Build:
c0bf0f679ce9

**Comment by chaitanyaphalak** [comment]
closed as part of https://github.com/splunk/splunk-connect-for-kubernetes/pull/193

**Comment by rfaircloth-splunk** [comment]
This was partially fixed the manifest examples don't reflect the same change

**Comment by rfrodrigues16** [comment]
Is there any plan to release new version of SCK with this fix soon?
Thanks,

**Comment by chaitanyaphalak** [comment]
@rfaircloth-splunk the manifests are updated only at the time of release

**Comment by chaitanyaphalak** [comment]
@rfrodrigues16 we havent planned a release yet.

**Comment by rfrodrigues16** [comment]
Thanks for the prompt response. Is there any workaround meanwhile?

**Comment by chaitanyaphalak** [comment]
Current workaround is manually patching the 1.2.0 release

**Comment by rfrodrigues16** [comment]
Got it. Thank you.
