### ISSUE TITLE
cluster_name field not added to journald and file logs

### ISSUE THREAD

**Issue by kousik93** [splunk/splunk-connect-for-kubernetes#194]
**What happened**:
In splunk, the cluster_name metadata field is not being set for non container logs. 
When I search for kube:docker logs for example, if i add a cluster_name field to the search, logs don't show up.

Sample search:
`index="myindex" sourcetype="kube:docker" cluster_name="mycluster"`

This does not return results ^

**What you expected to happen**:
I would like to to see all logs from a cluster irrespective of source when just search for cluster_name and index. 

**How to reproduce it (as minimally and precisely as possible)**:
Just deploy splunk-connect and search for cluster_name field for logs with sourcetype="kube:docker"

**Environment**:
- Kubernetes version (use `kubectl version`):
clientVersion:
buildDate: "2019-03-26T00:05:06Z"
compiler: gc
gitCommit: 641856db18352033a0d96dbc99153fa3b27298e5
gitTreeState: clean
gitVersion: v1.14.0
goVersion: go1.12.1
major: "1"
minor: "14"
platform: darwin/amd64
serverVersion:
buildDate: "2019-03-25T06:30:48Z"
compiler: gc
gitCommit: 16236ce91790d4c75b79f6ce96841db1c843e7d2
gitTreeState: clean
gitVersion: v1.11.9
goVersion: go1.10.8
major: "1"
minor: "11"
platform: linux/amd64

- Ruby version (use `ruby --version`):
Ruby version (use ruby --version):
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]

- OS (e.g: `cat /etc/os-release`):
macOS High Sierra
10.13.6 (17G6030)

- Splunk version:
7.2.6
Build:
c0bf0f679ce9

**Comment by sayeedc** [comment]
I’ve managed to solve this problem by putting the cluster level fields in a separate filter on top of the existing default ones. Try using a <filter **>your fields</filter>.

**Comment by kousik93** [comment]
I believe this is fixed with https://github.com/splunk/splunk-connect-for-kubernetes/pull/195
Closing this issue.
