### ISSUE TITLE
Update fields.conf on Splunk side to make metadata fields searchable

### ISSUE THREAD

**Issue by ahmed-kira** [splunk/splunk-connect-for-kubernetes#196]
<

**What would you like to be added**:
Include in readme the need for customer to update fields.conf on search heads so that metadata fields are searchable. Something like this:

_**When logs are flowing to Splunk with the default configuration, you are able to create the following searches:
index=myindex namespace=*
index=myindex namespace::nameofnamespace
**However, the following search will NOT work:**
index=myindex namespace=nameofnamespace

To address this issue, add the following lines to fields.conf on your search heads in $SPLUNK_HOME/etc/system/local/fields.conf or better yet, in a custom app directory ($SPLUNK_HOME/etc/apps/MYCUSTOMAPP/local/fields.conf

[namespace]
INDEXED = true

[pod]
INDEXED = true

[container_name]
INDEXED = true

[container_id]
INDEXED = true

[cluster_name]
INDEXED = true

You will need to do this for any other metadata/annotated field you are passing to Splunk.**_

**Why is this needed**:
So customers can effectively search their Kubernetes logs in Splunk

**Comment by mhoogcarspel-splunk** [comment]
Also, fields isn't shared out by default

`.../MYCUSTOMAPP/metadata/local.meta (or default.meta): 
[fields] 
access = read : [ * ], write : [ admin ] 
export = system`
