### ISSUE TITLE
Kubernetes logs in the "default" namespace have the namespace value "main"

### ISSUE THREAD

**Issue by hexecute** [splunk/splunk-connect-for-kubernetes#202]
I've pinpointed where the issue is although I'm wary of making changes myself as I don't know why the line was introduced in the first place. Skip to "Anything else we need to know?" for the root cause.

**What happened**:
Kubernetes logs in the "default" namespace are being reported as being from the namespace "main" in Splunk.

**What you expected to happen**:
Kubernetes logs in the "default" namespace should be reported as being from the "default" namespace in Splunk.

**How to reproduce it (as minimally and precisely as possible)**:
1. Set up SCK with a pod in the "default" namespace
2. Look at the "namespace" field for the logs for that pod on Splunk

**Anything else we need to know?**:
There was a commit to support index routing [1]. This added a feature where logs could be forwarded to an index with the same name as the log's namespace. The default namespace for logs is "default". The default index for Splunk is "main". There was logic added to make sure logs from "default" namespace go into the "main" index [2]. However, in a separate file [3], the namespace field is also converted from "default" to "main".

`def set_namespace(value): if value == \"default\" then \"main\"else value end; `

This seems very wrong as it breaks log correlation.

You can contact me over Slack as I am a Splunk employee.

[1] https://github.com/splunk/splunk-connect-for-kubernetes/commit/96df23c52c4af454d3671b92682f8dd8f8a03acc
[2] https://github.com/splunk/splunk-connect-for-kubernetes/commit/96df23c52c4af454d3671b92682f8dd8f8a03acc#diff-dcb43995d0de88c51cf7a3d031a436dc
[3] https://github.com/splunk/splunk-connect-for-kubernetes/blob/06e877daa21cff4420ededd069e20774e5b584d8/manifests/splunk-kubernetes-logging/configMap.yaml#L182

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.4
- OS (e.g: `cat /etc/os-release`): MacOS High Sierra
- Splunk version: 7.3.0

**Comment by chaitanyaphalak** [comment]
Yes @hexecute its part of the design, if you have ideas for a better implementation, please file a PR against develop. Thanks

**Comment by hexecute** [comment]
Can you clarify? Is it part of the design that `"default" namespace gets routed to "main index` or that `"default" namespace should be referred to as "main" namespace`? I understand the former but not the latter.

**Comment by chaitanyaphalak** [comment]
@hexecute "default" namespace gets routed to "main" index is the design

**Comment by matthewmodestino** [comment]
you cannot set an index to "default" in splunk. Kubernetes has an index called default, splunk just has a default concept, but the actual index name is "main"

**Comment by hexecute** [comment]
I understand that. However, the data itself is getting changed because of the implementation of the namespace-index routing. You can't distinguish between a Kubernetes namespace named "default" and a Kubernetes namespace named "main" because the data is the same after SCK processing.

**Comment by chaitanyaphalak** [comment]
You can specify a different index using "indexRoutingDefaultIndex" if you dont want the data from "default" namespace to route to "main" index.

**Comment by hexecute** [comment]
"if you dont want the data from "default" namespace to route to "main" index"
This isn't about routing but data integrity. The logic for routing shouldn't be modifying the logs data to achieve the desired behavior. 


Your suggestion is a good workaround (`indexRouting = false` and `indexRoutingDefaultIndex = default`), and we'll use that in our setup for now. I might create a PR in my spare time later.

**Comment by dtregonning** [comment]
@hexecute - I agree. We should preserve the value of default for namespace and route to an index determined by indexRoutingDefaultIndex's value. Would appreciate a PR if you do have time, it would be great.

**Comment by chaitanyaphalak** [comment]
This issue is addressed in https://github.com/splunk/splunk-connect-for-kubernetes/pull/215
