### ISSUE TITLE
Metric Pods are showing warning on SSLv3 

### ISSUE THREAD

**Issue by rufengxu** [splunk/splunk-connect-for-kubernetes#205]
**What happened**:
I used the latest images and deployed pods for logging, object and metrics.  Logging and objects are doing fine.
However, there is no metric data,and there are a lot of warnings in the log
2019-07-25 19:28:34 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-07-25 19:28:35 +0000 chunk="58e866e7cba287657ae4de26104023bd" error_class=OpenSSL::SSL::SSLError error="SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: wrong version number"

**What you expected to happen**:
I expect no errors and the data are flowing in the metric index to Splunk.

**How to reproduce it (as minimally and precisely as possible)**:
1. I downloaded the manifest files
2.  updated the secret file with the HEC token.
3. updated two config file with hec_host
4. In the configMap.yaml, I have the config inside the system
      use_rest_client_ssl true   (it is set up by default, I did not change)
      insecure_ssl true  (I added this based on one case in this forum)
5. Applied the secret file and config files
6. run kubectl create.  All the pods are running, but no data to Splunk.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
         GKE
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version: 7.3
- Others:

**Comment by chaitanyaphalak** [comment]
I think we need to add support for SSLv3 for metrics.

**Comment by matthewmodestino** [comment]
Hey @rufengxu, did you get this sorted?

**Comment by chaitanyaphalak** [comment]
Hey @rufengxu which version of k8s on GKE?

**Comment by timdeluxe** [comment]
We yesterday update to latest helm chart version and also still do have a very similar error on the metrics agents:
`2020-09-08 13:46:20 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:cadvisor_metric_scraper error_class=RestClient::SSLCertificateNotVerified error="SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)"`
and therefore disabled the metrics agents.

Please reopen and work on this topic!

We are running v1.17.7 of K8S on Azure.

**Comment by matthewmodestino** [comment]
@timdeluxe this can be resolved by setting the following setting in your metric chart:


https://github.com/splunk/splunk-connect-for-kubernetes/blob/53d5b0c1e333ad04c16a556aedd137f15c95a630/helm-chart/splunk-connect-for-kubernetes/values.yaml#L888

K8s uses self-signed certs on kubelet and k8s api in many setups.

Please verify your configmaps of the offending pod.
