### ISSUE TITLE
metrics-agg logging info messages. Should move to debug. 

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-connect-for-kubernetes#206]
**What would you like to be added**:

I would like the Metrics-Agg pod to stop logging each scrape, unless I elevate the logging level for investigation. 

**Why is this needed**:

Unnecessary noise/indexing from the pod. 

![image](https://user-images.githubusercontent.com/31549209/61962412-6de29880-af97-11e9-973a-0c66bfb1b026.png)

![image](https://user-images.githubusercontent.com/31549209/61962273-28be6680-af97-11e9-8958-225df6c992b9.png)

should be silent like the other pods in the solution when running normally.

**Comment by chaitanyaphalak** [comment]
Its merged in already at https://github.com/splunk/fluent-plugin-k8s-metrics-agg/commit/5a7d00f5ae0195cacb0f2fbe18b2b2efc45fff29

**Comment by matthewmodestino** [comment]
thank you kindly, sir!

I assume I have to either build image or await next tag, right?

**Comment by chaitanyaphalak** [comment]
Yep, we havent released it yet, but you can build your own image from the dockerfile on that repo if you need it. Thanks :)
