### ISSUE TITLE
Parsing error on configMap template

### ISSUE THREAD

**Issue by jarleborsheim** [splunk/splunk-connect-for-kubernetes#208]
Using the development branch of splunk-connect-for-kubernetes in our development cluster, we discovered that the pod stopped sending logs.

Looking at the logs for the splunk-connect-for-kubernetes pod we saw this error: 
```
111:     @type jq_transformer
112:     jq ".record.source = \"namespace:#{ENV['MY_NAMESPACE']}/pod:#{ENV['MY_POD_NAME']}\" | .record.sourcetype = \"fluentd:monitor-agent\" | .record.cluster_name = "cluster_name" | .record"

     -------------------------------------------------------------------------------------------------------------------------------------------------------------------^
```

It seems to me that there is a problem with not escaped double quotes, or wrapping the line in single quotes instead, in the file /helm-chart/splunk-kubernetes-logging/templates/configMap.yaml on line 212?

https://github.com/splunk/splunk-connect-for-kubernetes/blob/4bbeb829e65996076e9a0e4161c8e174d1ad8190/helm-chart/splunk-kubernetes-logging/templates/configMap.yaml#L212

It looks like it was introduced in this commit: https://github.com/splunk/splunk-connect-for-kubernetes/commit/2addba7458d9e30a31f7bb861f9cdc71cb155dca
And if you look at line 196, a similar change has been wrapped in single quoutes :)

https://github.com/splunk/splunk-connect-for-kubernetes/blob/4bbeb829e65996076e9a0e4161c8e174d1ad8190/helm-chart/splunk-kubernetes-logging/templates/configMap.yaml#L196

**Comment by chaitanyaphalak** [comment]
Hey @jarleborsheim thanks for reporting the issue. It would be awesome if you could file a pull request :)

**Comment by jarleborsheim** [comment]
Sure. Will do.
