### ISSUE TITLE
is it ok to increase the replica for metricsAggr? 

### ISSUE THREAD

**Issue by beth2016** [splunk/splunk-connect-for-kubernetes#211]
is it ok to increase the replica for metricsAggr to increase performance for example? 
Or is it useless and the replicas will just collect the same data?   thanks

**Comment by chaitanyaphalak** [comment]
Hi @beth2016, the way metrics-aggrgator is architected, all the replicas will collect the same data, so it will result in a lot of duplication :). LMK if you any other questions :)

**Comment by beth2016** [comment]
perfect.  thats what i need to know.  thanks.
