### ISSUE TITLE
kube:obejcts:events:watch are not capturing all events

### ISSUE THREAD

**Issue by beth2016** [splunk/splunk-connect-for-kubernetes#212]
So i switch from pull to watch for events after Fluent Plugin Kubernetes Objects v1.1.2 was released.  But i seem to be only getting a couple of events, not all events.  A lot of events are missing.   I could go back to pull, but pull is returning duplicate events every 15 mins.  So, I really like to get watch working.  Please advice.  thanks.

objects:
  core:
    v1:
      - name: pods
      - name: namespaces
      - name: nodes
      - name: events
        mode: watch

**Comment by matthewmodestino** [comment]
Hey Beth, 

This is a known issue with the objects pods version `kube-objects:1.1.1` or earlier. 

Can you please patch your objects deploy to the latest tag on dockerhub? 

`kube-objects:1.1.2`

you can update your helm chart with this parameter:

https://github.com/matthewmodestino/container_workshop/blob/a5b10ec0cf72850af4a8872473b4e85805fcc2bf/splunk_connect_for_kubernetes/kubernetes_connect.yaml#L24

or just edit the deployment directly and update it.

**Comment by beth2016** [comment]
@matthewmodestino  thank you.  that works.   much appreciated.
