### ISSUE TITLE
unable to install metrics chart

### ISSUE THREAD

**Issue by mohanayal** [splunk/splunk-connect-for-kubernetes#22]
Trying to install metric sub chart. Unfortunately pod is failing with following message.

Error from server (BadRequest): a container name must be specified for pod test-metric-splunk-kubernetes-metrics-b4f946587-f4gxg, choose one of: [splunk-heapster splunk-fluentd-heapster]

Fluentd container is failing and following are the container logs.

2018-07-11 11:49:22 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2018-07-11 11:49:23 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Could not parse jq filter: def extract_labels:\r\n  . as $labels | reduce range(length) as $n ({}; if $n % 2 == 0 then .[\"label.\" + $label
bels[$n + 1] else . end);\r\n\r\ndef extract_metric:\r\n  if length % 2 == 0\r\n  then (.[:-2] | extract_labels) + {metric: (.[-2] | gsub(\"/\"; \".\")), resource_id: .[-1]}\r\n  else (.[:-1] | extract_labels) + {metric: (.[-1] | gsub(\"/\"; \".\"))}\r\n  end
ef extract_container:\r\n  split(\".\") | {container_type: \"pod\", node: .[1], namespace: .[3], pod: .[5], container: .[7]} + (.[8:] | extract_metric) | .metric = \"kube.container.\" + .metric | . ;\r\n  \r\ndef extract_syscontainer:\r\n  split(\".\") | {con
 \"sys\", node: .[1], container: .[3]} + (.[4:] | extract_metric) | .metric = \"kube.container.\" + .metric | . ;\r\n  \r\ndef extract_pod:\r\n  split(\".\") | {node: .[1], namespace: .[3], pod: .[5]} + (.[6:] | extract_metric) | .metric = \"kube.pod.\" + .me
\n  \r\ndef extract_namespace:\r\n  split(\".\") | {namespace: .[1]} + (.[2:] | extract_metric) | .metric = \"kube.namespace.\" + .metric | . ;\r\n  \r\ndef extract_node:\r\n  split(\".\") | {node: .[1]} + (.[2:] | extract_metric) | .metric = \"kube.node.\" +
 ;\r\n  \r\ndef extract_cluster:\r\n  split(\".\") | .[1:] | extract_metric | .metric = \"kube.cluster.\" + .metric | . ;\r\n\r\ndef extract:\r\n  if contains(\".container.\")\r\n  then extract_container\r\n  elif contains(\".sys-container.\")\r\n  then extra
ner\r\n  elif contains(\".pod.\")\r\n  then extract_pod\r\n  elif startswith(\"namespace.\")\r\n  then extract_namespace\r\n  elif startswith(\"node.\")\r\n  then extract_node\r\n  elif startswith(\"cluster.\")\r\n  then extract_cluster\r\n  else {}\r\n  end;
eapster/namespace:\\(env.MY_NAMESPACE)/pod:\\(env.MY_POD_NAME)\" as $source | .record | to_entries | map({value, source: $source} + (.key | extract)) | ., error: Could not parse jq filter: def extract_labels:\r\n  . as $labels | reduce range(length) as $n ({}
== 0 then .[\"label.\" + $labels[$n]] = $labels[$n + 1] else . end);\r\n\r\ndef extract_metric:\r\n  if length % 2 == 0\r\n  then (.[:-2] | extract_labels) + {metric: (.[-2] | gsub(\"/\"; \".\")), resource_id: .[-1]}\r\n  else (.[:-1] | extract_labels) + {met
| gsub(\"/\"; \".\"))}\r\n  end;\r\n  \r\ndef extract_container:\r\n  split(\".\") | {container_type: \"pod\", node: .[1], namespace: .[3], pod: .[5], container: .[7]} + (.[8:] | extract_metric) | .metric = \"kube.container.\" + .metric | . ;\r\n  \r\ndef ext
ainer:\r\n  split(\".\") | {container_type: \"sys\", node: .[1], container: .[3]} + (.[4:] | extract_metric) | .metric = \"kube.container.\" + .metric | . ;\r\n  \r\ndef extract_pod:\r\n  split(\".\") | {node: .[1], namespace: .[3], pod: .[5]} + (.[6:] | extr
| .metric = \"kube.pod.\" + .metric | . ;\r\n  \r\ndef extract_namespace:\r\n  split(\".\") | {namespace: .[1]} + (.[2:] | extract_metric) | .metric = \"kube.namespace.\" + .metric | . ;\r\n  \r\ndef extract_node:\r\n  split(\".\") | {node: .[1]} + (.[2:] | e
c) | .metric = \"kube.node.\" + .metric | . ;\r\n  \r\ndef extract_cluster:\r\n  split(\".\") | .[1:] | extract_metric | .metric = \"kube.cluster.\" + .metric | . ;\r\n\r\ndef extract:\r\n  if contains(\".container.\")\r\n  then extract_container\r\n  elif co
s-container.\")\r\n  then extract_syscontainer\r\n  elif contains(\".pod.\")\r\n  then extract_pod\r\n  elif startswith(\"namespace.\")\r\n  then extract_namespace\r\n  elif startswith(\"node.\")\r\n  then extract_node\r\n  elif startswith(\"cluster.\")\r\n
_cluster\r\n  else {}\r\n  end;\r\n\r\n \"heapster/namespace:\\(env.MY_NAMESPACE)/pod:\\(env.MY_POD_NAME)\" as $source | .record | to_entries | map({value, source: $source} + (.key | extract)) | ., error: jq: error: syntax error, unexpected INVALID_CHARACTER
quoting issues?) at <top-level>, line 1:\ndef extract_labels:\r                   \njq: 1 compile error\n"
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/gems/fluent-plugin-jq-0.5.1/lib/fluent/plugin/jq_mixin.rb:17:in `rescue in configure'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/gems/fluent-plugin-jq-0.5.1/lib/fluent/plugin/jq_mixin.rb:12:in `configure'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/plugin.rb:164:in `configure'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/agent.rb:130:in `add_match'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/agent.rb:72:in `block in configure'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/agent.rb:64:in `each'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/agent.rb:64:in `configure'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:112:in `configure'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/engine.rb:131:in `configure'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/engine.rb:96:in `run_configure'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:795:in `run_configure'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:579:in `dry_run'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:597:in `supervise'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:502:in `run_supervisor'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/bin/fluentd:8:in `<top (required)>'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/bin/fluentd:23:in `load'
  2018-07-11 11:49:23 +0000 [debug]: /usr/local/bundle/bin/fluentd:23:in `<main>'

 kubectl logs test-metric-splunk-kubernetes-metrics-b4f946587-znqnm -c splunk-heapster
I0711 11:48:54.169991       1 heapster.go:78] /heapster --source=kubernetes --sink=statsd:udp://127.0.0.1:9001
I0711 11:48:54.170153       1 heapster.go:79] Heapster version v1.5.1
I0711 11:48:54.170319       1 configs.go:61] Using Kubernetes client with master "https://10.0.0.1:443" and version v1
I0711 11:48:54.170333       1 configs.go:62] Using kubelet port 10255
I0711 11:48:54.390631       1 driver.go:104] statsd metrics sink using configuration : {host:127.0.0.1:9001 prefix: numMetricsPerMsg:5 protocolType:etsystatsd renameLabels:map[] allowedLabels:map[] customizeLabel:0x15f2560}
I0711 11:48:54.390682       1 driver.go:104] statsd metrics sink using configuration : {host:127.0.0.1:9001 prefix: numMetricsPerMsg:5 protocolType:etsystatsd renameLabels:map[] allowedLabels:map[] customizeLabel:0x15f2560}
I0711 11:48:54.390711       1 heapster.go:202] Starting with StatsD Sink
I0711 11:48:54.390714       1 heapster.go:202] Starting with Metric Sink
I0711 11:48:54.569104       1 heapster.go:112] Starting heapster on port 8082
E0711 11:49:06.370532       1 driver.go:159] statsd metrics sink - failed to send some metrics : write udp 127.0.0.1:41485->127.0.0.1:9001: write: connection refused

==================================================

configmap.yaml file 

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "=" . }}
  labels:
    app: {{ template "splunk-kubernetes-metrics.name" . }}
    chart: {{ template "splunk-kubernetes-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  fluent.conf: |
    # system wide configurations
    <system>
      log_level {{ or .Values.logLevel .Values.global.logLevel | default "info" }}
    </system>

    <source>
      @type udp
      tag raw.metrics.udp
      port 9001
      message_length_limit 100m
      <parse>
        @type jq
        jq 'split("\n") | reduce .[] as $item ({}; ($item | rindex(":")) as $i | .[$item[:$i]] = ($item[$i+1:-2] | tonumber))'
      </parse>
    </source>

    <match raw.metrics.udp>
      @type jq
      jq {{ include "splunk-kubernetes-metrics.jq_filter" . | quote }}
      remove_tag_prefix raw
    </match>

    <match metrics.udp>
      @type splunk_hec
      data_type metric
      metric_name_key metric
      metric_value_key value
      protocol {{ or .Values.splunk.hec.protocol .Values.global.splunk.hec.protocol }}
      {{- with or .Values.splunk.hec.host .Values.global.splunk.hec.host }}
      hec_host {{ . }}
      {{- end }}
      {{- with or .Values.splunk.hec.port .Values.global.splunk.hec.port }}
      hec_port {{ . }}
      {{- end }}
      hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
      host "#{ENV['SPLUNK_HEC_HOST']}"
      {{- with or .Values.splunk.hec.indexName .Values.global.splunk.hec.indexName }}
      index {{ . }}
      {{- end }}
      source ${tag}
      insecure_ssl {{ or .Values.splunk.hec.insecureSSL .Values.global.splunk.hec.insecureSSL | default false }}
      {{- if or .Values.splunk.hec.clientCert .Values.global.splunk.hec.clientCert }}
      client_cert /fluentd/etc/splunk/hec_client_cert
      {{- end }}
      {{- if  or .Values.splunk.hec.clientKey .Values.global.splunk.hec.clientKey }}
      client_key /fluentd/etc/splunk/hec_client_key
      {{- end }}
      {{- if or .Values.splunk.hec.caFile .Values.global.splunk.hec.caFile }}
      ca_file /fluentd/etc/splunk/hec_ca_file
      {{- end }}
      <buffer>
        @type memory
        {{- $limit := .Values.resources.sidecar.limit }}
        chunk_limit_size {{ if $limit.memory }}{{ template "splunk-kubernetes-logging.convert-memory" $limit.memory }}{{ else }}{{ "500m" }}{{ end }}
        chunk_limit_records 100000
        flush_interval 5s
        flush_thread_count 1
        overflow_action block
        retry_max_times 3
      </buffer>
    </match>

**Comment by Gimi** [comment]
Hi @mohanayal , could you share your values file which you used to install the chart?

**Comment by matthewmodestino** [comment]
Hi @mohanayal!

Did you have any luck getting this up and running? Do you still require assistance?

**Comment by dbaldwin-splunk** [comment]
Closing because there are no updates.
