### ISSUE TITLE
Is there any workaround for the requirement of administrator access to the Kubernetes cluster?.

### ISSUE THREAD

**Issue by nathpree** [splunk/splunk-connect-for-kubernetes#221]
Dear All,

We have a centralized open shift cluster. As per the prequisites for the Splunk Connect For Kubernetes we need to have administrator access to your Kubernetes cluster. As far as I understood that the running Splunk connect for kubernetes DaemonSet will need only access to the /var/logs/container*. We cannot get the administrative privilege due to the company security requirement. Only cloud administrator have this rights. Is there any workaround without admin rights or with minimum cluster level rights, that we could still implement the solution in our node. 
Or can we ask our cloud adminstrator to deploy the DaemonSet on our behalf.

Regards,

Preetam

**Comment by matthewmodestino** [comment]
Hi Preetam,

Docker logging can only be accessed by root, so no, you cannot deploy this solution without your cluster admin.

Please work with them to deploy, as this solution has immense value for the Openshift admin team!

https://docs.splunk.com/Documentation/InfraApp/1.4.0/Admin/AddDataOpenShift

**Comment by chaitanyaphalak** [comment]
@nathpree let us know if you need help, closing this for now.
