### ISSUE TITLE
journal position file

### ISSUE THREAD

**Issue by sayeedc** [splunk/splunk-connect-for-kubernetes#225]
**What happened**:

logging pods are crashing and the error message on pods is
2019-08-12 13:20:13 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf" 
 
2019-08-12 13:20:13 +0000 [error]: [journald-journal] failed to read data from plugin storage file path="/var/log/splunkd-fluentd-journald-journal.pos.json" error_class=Fluent::ConfigError error="Invalid contents (not object) in plugin storage file: '/var/log/splunkd-fluentd-journald-journal.pos.json'" 
 
2019-08-12 13:20:13 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Unexpected error: failed to read data from plugin storage file: '/var/log/splunkd-fluentd-journald-journal.pos.json'"

**What you expected to happen**:

Journal files should be read without corrupting the position file. Only 14 out of 58 pods are crash lopping.

**How to reproduce it (as minimally and precisely as possible)**:

Configure SCK to read from everything in the journal with a position file. 

**Anything else we need to know?**:
The problem may related to a known issue on Fluentd: https://github.com/fluent-plugin-systemd/fluent-plugin-systemd/issues/68 

I've raised a support case with Splunk as this is affecting our production environment with an impact to users.

**Environment**: PROD
- Kubernetes version (use `kubectl version`): 1.13
- Ruby version (use `ruby --version`): 
- OS (e.g: `cat /etc/os-release`): RHEL 7.6
- Splunk version: 7.1.2
- Others: Splunk SCK 1.0.1

**Comment by chaitanyaphalak** [comment]
@sayeedc at the end of this issue - https://github.com/fluent-plugin-systemd/fluent-plugin-systemd/issues/68 they said that fluentd has merged changes upstream and updating to the latest version of fluentd can fix the issues. I see you are on SCK 1.0.1 which was released in Jun 27 2018(https://github.com/splunk/splunk-connect-for-kubernetes/releases/tag/v1.0.1), its a fairly old release could you let us know which version of fluentd-hec you are using - https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-kubernetes-logging/values.yaml#L262

**Comment by sayeedc** [comment]
@chaitanyaphalak I am using fluentd-hec:1.0.1. I can't upgrade until SCK is available on the RHEL as we can only use images from the Openshift Catalog.

**Comment by chaitanyaphalak** [comment]
I suspect the older fluentd-hec image is the problem.

**Comment by sayeedc** [comment]
@chaitanyaphalak When will the latest version be available on Redhat’s container registry?

**Comment by chaitanyaphalak** [comment]
@sayeedc its not planned yet, @abbas-splunk is the product manager and he will be able to give more insights on this.
