### ISSUE TITLE
Is it possible to get the kubernetes events into splunk with this tool? 

### ISSUE THREAD

**Issue by dmcnaught** [splunk/splunk-connect-for-kubernetes#23]
Sorry for opening an issue if this isn't the right place, but it is possible to get the kubernetes events into splunk with this tool?

```
kubectl get events --all-namespaces
```
Thanks
--Duncan

**Comment by dbaldwin-splunk** [comment]
@dmcnaught I would recommend looking at the documentation under the readme for the main page of this repo and then read the documentation under the Helm charts.  Deploying the complete set of charts will include a plug-ins for logs, meta data, and metrics to be pushed through HEC.

**Comment by dmcnaught** [comment]
So, no then? afaik the kubernetes events don't come under those categories

**Comment by Gimi** [comment]
Hi @dmcnaught , yes, this tool can collect events. It's done by the `splunk-kubernetes-objects` chart.

**Comment by Gimi** [comment]
BTW, event is just one of the many kinds of objects in kubernetes, and the `splunk-kubernetes-objects` chart was designed to collect all those data.

**Comment by matthewmodestino** [comment]
hey @dmcnaught! 

As @Gimi said, yes we do pull kube events into Splunk with this, let me know if you need a hand getting going!

Otherwise can we close this issue?

**Comment by dmcnaught** [comment]
Cool - thanks for confirming. I'll work on setting it up as priorities allow 👍
