### ISSUE TITLE
failed to POST 

### ISSUE THREAD

**Issue by ticteam** [splunk/splunk-connect-for-kubernetes#234]
hello, 

got installed with: 
helm install --name splunk-fluentd  \
--set global.splunk.hec.host=SPLUNK-SERVER-ADRESS \
--set global.splunk.hec.token=TOKEN \
--set global.splunk.hec.port=443 \
--set splunk-kubernetes-metrics.splunk.hec.indexName=my-metrics-index \
https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.2.0/splunk-connect-for-kubernetes-1.2.0.tgz

Installation looks fine, all needed are running.

**What happened**:
following error in the kubectl logs splunk-fluentd-splunk-kubernetes-logging-*
[error]: #0 Failed POST to https://SPLUNK-SERVER-ADRESS/services/collector, response: <html><head><title>Object moved    </title></head><body>                                                                                       

**What you expected to happen**:
the right adress for the POST should be https://SPLUNK-SERVER-ADRESS/services/collector/event <— /event is missing in the adress

I had double checked with a curl , that work with https://SPLUNK-SERVER-ADRESS/services/collector/event 

**Anything else we need to know?**:
the port 443 is correct ! 

is there a way to change the URI or maybe to add the missing /event ?

thanks

christoph

**Comment by chaitanyaphalak** [comment]
Hi @ticteam we are currently using https://docs.splunk.com/Documentation/Splunk/7.3.1/RESTREF/RESTinput#services.2Fcollector

what version of splunk are you on? is it splunk cloud?

Also can you post the redacted SPLUNK-SERVER-ADRESS you are using

Are metrics and objects components working fine?

Also for the following installation method
helm install --name splunk-fluentd 
--set global.splunk.hec.host=SPLUNK-SERVER-ADRESS 
--set global.splunk.hec.token=TOKEN 
--set global.splunk.hec.port=443 
--set splunk-kubernetes-metrics.splunk.hec.indexName=my-metrics-index 

you have not specified indexes for objects and logs

Thanks.

**Comment by ticteam** [comment]
issue can be closed, configuration was faulty from my site, I need to have another product at the moment, sorry 4 that....

**Comment by humblefool007** [comment]
hi I am facing this issue currently can u guys please help on this
