### ISSUE TITLE
Plans for compatibility with Splunk Cloud?

### ISSUE THREAD

**Issue by callafeucht** [splunk/splunk-connect-for-kubernetes#24]
We'd love to use this app in our Splunk instance, but Splunk support has informed us that this app is currently incompatible with Splunk Cloud. Are there any plans to add that compatibility?

**Comment by dbaldwin-splunk** [comment]
@callafeucht This connector resides outside Splunk Cloud and sends data through HEC which is fully supported.  What is your case number?

**Comment by callafeucht** [comment]
@dbaldwin-splunk it's case number 991602. Please note that the case was not opened specifically for this plugin, but we address it within the overall conversation.

**Comment by matthewmodestino** [comment]
hey @callafeucht!

Any luck getting sorted with cloud? Let me know if I can assist in getting you up and running!

**Comment by callafeucht** [comment]
@matthewmodestino I don't believe we ever did get things sorted, but my teammate @jmbradshaw79 can give more information.

**Comment by jmbradshaw79** [comment]
Yes, I got it sorted. I only deployed the logging chart since we are not on version 7 yet. I also deployed with a  modified image to leverage the fluent-plugin-kubernetes_metadata_filter gem.

**Comment by dbaldwin-splunk** [comment]
@jmbradshaw79 @callafeucht I'm closing this issue for now since you are deployed.  If you have any more issues with support, please re-open or contact us.
