### ISSUE TITLE
What is your release schedule?

### ISSUE THREAD

**Issue by vidarw** [splunk/splunk-connect-for-kubernetes#245]
Hi,
We have multiple production workloads waiting for new features in the development branch.
When can we expect these changes to be available in a stable branch/release?
It has been 3 months since the last push to master.

Best regards,
Vidar

**Comment by chaitanyaphalak** [comment]
We are planning to do a release around .conf 2019.

**Comment by rehevkor5** [comment]
... which apparently is October 22 - 24, 2019.

**Comment by ciiqr** [comment]
Yikes, this release cadence doesn't seem terrible compatible with using splunk at a company that wants to move fast...

**Comment by dtregonning** [comment]
@ciiqr - thats a fair comment. We are restructuring a lot on our end to continue to actively develop and improve this product continuously(we are actively working on the code base daily)but we do have a big issue with release cadence. We know we need to get things out quicker and more often.

**Comment by chaitanyaphalak** [comment]
Closing as this issue is a duplicate of https://github.com/splunk/splunk-connect-for-kubernetes/issues/132
