### ISSUE TITLE
splunk/kube-objects:1.1.2

### ISSUE THREAD

**Issue by bdschaap** [splunk/splunk-connect-for-kubernetes#247]
I noticed that the splunk/kube-objects:1.1.2 image is available.  However, the SCK release is still referencing 1.1.0 even though some of the code base references 1.1.2.  Is there any information on what changed in 1.1.2?

**Comment by chaitanyaphalak** [comment]
Release summary for 1.1.2 - https://github.com/splunk/fluent-plugin-kubernetes-objects/releases/tag/1.1.2

The image will be updated in the next release for SCK.
