### ISSUE TITLE
updateStrategy configurable

### ISSUE THREAD

**Issue by tehlers320** [splunk/splunk-connect-for-kubernetes#248]
**What would you like to be added**:
A config option to set updateStrategy

**Why is this needed**:
Today when you change the agent it does not update and defaults to `OnDelete`

**Comment by tehlers320** [comment]
it’s using the old default due to use of extensions/v1beta1? See https://v1-13.docs.kubernetes.io/docs/reference/federation/extensions/v1beta1/definitions/#_v1beta1_daemonset and https://v1-13.docs.kubernetes.io/docs/reference/federation/extensions/v1beta1/definitions/#_v1beta1_daemonsetspec

**Comment by chaitanyaphalak** [comment]
@tehlers320 We would be happy to review a PR for the same.

**Comment by chaitanyaphalak** [comment]
This issue was addressed in https://github.com/splunk/splunk-connect-for-kubernetes/releases/tag/1.3.0. The default update strategy is now a rolling update strategy. I don't think we need a configurable option for this. If you feel otherwise please file an issue again. Thanks.

**Comment by chaitanyaphalak** [comment]
https://github.com/splunk/splunk-connect-for-kubernetes/pull/283 this PR adds this for the other deployments/daemonsets
