### ISSUE TITLE
Include cluster_name and customMetadata in all output

### ISSUE THREAD

**Issue by rehevkor5** [splunk/splunk-connect-for-kubernetes#249]
**What would you like to be added**:

Currently, clusterName and customMetadata is only added to the container logs (`tail.containers.**` filter). It should be added to other logs such as those coming from journald and non-container files, in order to be able to distinguish those logs based on cluster name and other user-provided customMetadata.

**Why is this needed**:

It is not currently possible to search the Splunk logs produced by this component by cluster name or customMetadata. This means that all the journald and file logs are mixed together and difficult to separate in Splunk.

**Comment by chaitanyaphalak** [comment]
@rehevkor5 We would be happy to review a PR for the same.

**Comment by rehevkor5** [comment]
If it was easier to test, I probably would do that. As it is, it depends on finding time to figure out how to test & debug it. I don't see any instructions for developers here, but maybe there are some elsewhere?

**Comment by chaitanyaphalak** [comment]
There are no instructions explicitly mentioned here on the github repo. But you can get started by cloning the repo, modifying the helm charts, testing them by deploying them, adding them to a commit and submitting a PR.

**Comment by chaitanyaphalak** [comment]
Resolved as part of https://github.com/splunk/splunk-connect-for-kubernetes/pull/294
