### ISSUE TITLE
Forced to set insecure_ssl to true in fluent.conf when communicating with Splunk Cloud

### ISSUE THREAD

**Issue by marko8904** [splunk/splunk-connect-for-kubernetes#25]
The only pod that gives us issues is splunk-kubernetes-objects which responds with

> 2018-07-20 23:59:59 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Invalid Kubernetes API v1 endpoint https://100.64.0.1:443/api: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)"

To resolve this we are forced to set insecure_ssl to true in ConfigMap.

What causes the issue and how can we fix it?

**Comment by dbaldwin-splunk** [comment]
@Gimi @dtregonning Can one of you look into this?

**Comment by marko8904** [comment]
It turns out that the issue stems from the Kubernetes API setup itself. A proper SSL certificate is not attached to the API host which triggers the error above from Fluent. Closing this issue as it is not affected by the Splunk Add-on.
