### ISSUE TITLE
Kubernetes 1.16 support

### ISSUE THREAD

**Issue by mguissine** [splunk/splunk-connect-for-kubernetes#250]
We are planning to use this plugin to pull Kubernetes logs and metrics into Splunk. Is the Kubernetes 1.6 supported and if not, are there plans to support it in the near future? 

Thanks

**Comment by chaitanyaphalak** [comment]
Are you talking about kubernetes 1.16 because kubernetes 1.6 is a very old version.

**Comment by mguissine** [comment]
sorry, my bad, you right I meant 1.16

**Comment by matthewmodestino** [comment]
I dont know of any changes that would cause any issues.

**Comment by chaitanyaphalak** [comment]
I havent explicitly tested it on k8s 1.16, its something we could put effort into when its generally available.

**Comment by xetix** [comment]
1.16 is now in GA. And you seem to have made changes needed in repos. Any release planned?

**Comment by chaitanyaphalak** [comment]
Yes it works, tested with minikube k8s 1.16

**Comment by bdschaap** [comment]
Do you recall which version of SCK you used when testing K8s 1.16?  We're about to upgrade to K8s 1.16 and would like to head off potential issues.

**Comment by matthewmodestino** [comment]
you should absolutely use the latest!
