### ISSUE TITLE
Ingesting logs for K8s master components when they're not defined as pods

### ISSUE THREAD

**Issue by bdschaap** [splunk/splunk-connect-for-kubernetes#252]
The K8s master components on my Rancher Kubernetes Engine (RKE) cluster aren't defined as pods.  However, they do run as containers in Docker and the files are available in /var/lib/rancher/rke/log/kube-apiserver*.log.  I'm able to ingest the logs by using the source.files.conf approach for log file sources.  I also had to mount /var/lib/rancher/rke/log in the splunk-kubernetes-logging daemonset manifest.
1) Is this the right way to ingest these logs?  
2) Can you confirm that the source.containers.conf approach does require the container to be running within a pod?

**Comment by chaitanyaphalak** [comment]
1) Yes you will have to mount that volume, as by default we only mount the following locations https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-kubernetes-logging/templates/daemonset.yaml#L85

2) Everything runs as a pod in k8s, what other way are you thinking of running the container as?

**Comment by bdschaap** [comment]
Thanks for the response.  My master components aren't running as pods in RKE from what I can tell.  For example, this command doesn't return any results when searching on my RKE cluster.
`kubectl get pods --all-namespaces | find "apiserver"`

I do see it running as a container though.
```
docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS               NAMES
856190301ef0        rancher/hyperkube:v1.14.6-rancher1     "/opt/rke-tools/entr…"   2 weeks ago         Up 2 weeks                              kube-apiserver
```
However, it does return results on my local Docker Desktop cluster.  I've also seen it running as a pod in minikube.  I have no trouble ingesting the K8s master component logs from Docker Desktop.
```
kubectl get pods --all-namespaces | find "apiserver"
kube-system       kube-apiserver-docker-desktop                            1/1     Running            35         34d
```

**Comment by chaitanyaphalak** [comment]
It looks like RKE implements the kubernetes control plane in a different way by deploying those components as containers on the nodes - https://rancher.com/docs/rke/latest/en/config-options/services/

You may have mount the volumes in the daemonset to get logs from those nodes.

**Comment by bdschaap** [comment]
Thank you.  Yes I had to mount the volumes in the daemonset.  I'll try to get a PR in that shows the configuration that I had to use to get the logs to get the master logs to ingest for RKE.

**Comment by Mojito2110** [comment]
Hello @bdschaap , Did you find a solution to ingest both pod/container logs and RKE logs with SCK? Thanks for your help.

**Comment by bdschaap** [comment]
Yes I'm able to ingest both pod/container logs as well as RKE logs with SCK.  To ingest the RKE master logs do the following.  

Mount the volumes on the logging daemonset like this.
```
volumeMounts:
- name: rkelog
  mountPath: /var/lib/rancher/rke/log
  readOnly: true
volumes:
- name: rkelog
hostPath:
  path: /var/lib/rancher/rke/log
```

Then include something similar to this for source.files.conf in the logging ConfigMap.

```
...
fluent.conf: |-
  @include source.containers.conf
...
source.files.conf: |-
# This fluentd conf file contains sources for log files other than container logs.
<source>
  @id tail.file.etcd
  @type tail
  @label @SPLUNK
  tag tail.file.kube:etcd-server
  path /var/lib/rancher/rke/log/etcd*.log
  pos_file /var/log/splunk-fluentd-etcd.pos
  read_from_head true
  path_key source
  <parse>
	@type json
	time_key time
	time_type string
	time_format %Y-%m-%dT%H:%M:%S.%N
  </parse>
</source>
<source>
  @id tail.file.kube-apiserver
  @type tail
  @label @SPLUNK
  tag tail.file.kube:kube-apiserver
  path /var/lib/rancher/rke/log/kube-apiserver*.log
  pos_file /var/log/splunk-fluentd-kube-apiserver.pos
  read_from_head true
  path_key source
  <parse>
	@type json
	time_key time
	time_type string
	time_format %Y-%m-%dT%H:%M:%S.%NZ
	localtime false
  </parse>
</source>
...
```

**Comment by Mojito2110** [comment]
Hello @bdschaap thx helped me
