### ISSUE TITLE
k8s Namespace Naming is not consistent	

### ISSUE THREAD

**Issue by csiess-splunk** [splunk/splunk-connect-for-kubernetes#256]
**What happened**:

I noticed that, at least, for CPU and Memory data from a POD the namespace field is not consistently named:

On kube.pod.memory.usage.bytes its namespace

On kube.pod.cpu.usage its pod-namespace

**What you expected to happen**:

The namespace field should be consistent.

- Kubernetes version (use `kubectl version`):

1.15.0

**Comment by chaitanyaphalak** [comment]
looks related to https://github.com/splunk/splunk-connect-for-kubernetes/issues/133

**Comment by princeba84** [comment]
Did this issue already solved. I still have inconsistency between names of dimensions for metrics (namespace vs pod-namespace, ) Thanks in advance for your suggestions?
