### ISSUE TITLE
Config Reloader

### ISSUE THREAD

**Issue by bdschaap** [splunk/splunk-connect-for-kubernetes#258]
Can you provide guidance on automatically reloading config when a change has been made?  I've been deleting the pod after making a config change but not deploying updated daemonsets and/or deployment at the same time.

**Comment by chaitanyaphalak** [comment]
use helm upgrade?
https://github.com/helm/helm/blob/master/docs/helm/helm_upgrade.md

**Comment by bdschaap** [comment]
Sorry I should have mentioned that I'm just using the K8s manifests and not Helm.

**Comment by chaitanyaphalak** [comment]
If you are using manifests can't you just kubectl apply and all the kubernetes objects are updated?

**Comment by bdschaap** [comment]
The configmaps are updated but I don't think the SCK pods that are currently running are aware of the changes.  

Perhaps this could be an enhancement request for SCK?  In Prometheus there is a "reload" endpoint.  A generic file watcher container (not a Prometheus component) does an HTTP post to the endpoint of the running pods when it sees that the configmaps have changed.

**Comment by chaitanyaphalak** [comment]
If you are using manifests you may want to try kubectl rollout restart - https://blog.questionable.services/article/kubernetes-deployments-configmap-change/

**Comment by bdschaap** [comment]
Thanks that may be a possibility down the road but need to look into it further.  I'm still using version 1.14.

**Comment by chaitanyaphalak** [comment]
Let us know what you decide on, we would love to recommend the same to other community members.
