### ISSUE TITLE
Passing index name to HEC from annotations & processing logs NOT sent to STDOUT

### ISSUE THREAD

**Issue by ahmed-kira** [splunk/splunk-connect-for-kubernetes#262]
Attached set of configurations setup and executed in production @ Cisco include the following customizations:
- integrating the kubernetes_metadata plugin to pull an annotation from Kubernetes API and populate as the index name for events going to HEC
- processing logs NOT written to STDOUT. 

[CiscoModifiedSCK.zip](https://github.com/splunk/splunk-connect-for-kubernetes/files/3741399/CiscoModifiedSCK.zip)

**Comment by matthewmodestino** [comment]
I have had asks from other customers to collab on rewriting a better meta plugin. 

Let us know if you see any issues with the existing one!

**Comment by varunsufi** [comment]
@ahmed-kira can you give access to your config zip. How have you integrated the kubernetes_metadata plugin.

**Comment by rockb1017** [comment]
it has been implemented since 1.4.0. closing. thank you.
