### ISSUE TITLE
Docker Images need "latest" tag on dockerhub

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-connect-for-kubernetes#264]
**What happened**:

The dockerhub published images do not include a "latest" tag. 

**What you expected to happen**:

Should be able to simply point to latest tag and get the latest image

**How to reproduce it (as minimally and precisely as possible)**:

I used the dev branch develop templates, and a values.yaml that set the image for each chart. I tried using the new "tag" option in values.yaml, but it didnt render, so k8s defaulted to latest, and failed to pull the images.

**Anything else we need to know?**:

We should double check the dev branch values.yaml options for setting image tags, ensure it is working as planned.

**Environment**:
- Kubernetes version (use `kubectl version`):

 kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:53:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:46:28Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Ruby version (use `ruby --version`):

n/a

- OS (e.g: `cat /etc/os-release`):

UBUNTU 18.04 Running Microk8s

- Splunk version:

latest

- Others:

**Comment by rockb1017** [comment]
I can start working on this. 
1. always publish "latest" tagged image from sub repos for every release. 
2. make sure image name and tag is properly rendered.

**Comment by avpatel257** [comment]
Any progress on this? We're facing the same issue. Looks like helm is not reading the image tag version specified in the `values.yaml` and always try to pull the latest image.

Not sure why the `latest` tag not getting updated with every release.

**Comment by vinitmasaun** [comment]
We are not able to get any logs from the containers.  We've tried adjusting the log path pattern in the splunk-logging section of the values.yaml but still cant get any logs to index.

**Comment by matthewmodestino** [comment]
@avpatel257 this shouldnt be a blocker if you set the `values.yaml` correctly. what version are yuo using? also using latest tag is not a good idea in practice, heavily recommend you pin to an imgae version.

**Comment by rockb1017** [comment]
latest tags has been added to docker hub registry. Thanks!
