### ISSUE TITLE
RBAC for Logging Daemonset

### ISSUE THREAD

**Issue by bdschaap** [splunk/splunk-connect-for-kubernetes#270]
RBAC configuration is needed for the Logging daemonset.  The ServiceAccount is defined but ClusterRole and ClusterRoleBinding need to be added.

If anyone has configured this yet can you please share your ClusterRole config?

**Comment by rockb1017** [comment]
for logging daemonset, is it not working for your env? 
it only needs to interact with mounted paths. read and write. so it doesn't need k8s access specification.

**Comment by matthewmodestino** [comment]
@bdschaap, what distribution of k8s are you using?

**Comment by bdschaap** [comment]
Apologies I'm good now.  I thought I wasn't able to get something working w/o RBAC but I was mistaken.  Still a bit of a noob with K8s.

Also, I'm using Rancher Kubernetes Engine (RKE) as well as Azure Kubernetes Service (AKS).
