### ISSUE TITLE
SCK Logging pod went to Error status after node restart

### ISSUE THREAD

**Issue by rfrodrigues16** [splunk/splunk-connect-for-kubernetes#272]
**What happened**:
Logging pod could not restart automatically after a k8s node restart: 

==> v1/Pod(related)
NAME                                                           READY  STATUS   RESTARTS  AGE
splunk-connect-splunk-kubernetes-logging-2rw5j                 1/1    Running  0         24s
splunk-connect-splunk-kubernetes-logging-bdfjz                 1/1    Running  0         24s
splunk-connect-splunk-kubernetes-logging-g5d8d                 1/1    Running  0         24s
splunk-connect-splunk-kubernetes-logging-n5kn9                 1/1    Running  0         24s
splunk-connect-splunk-kubernetes-logging-qlvls                 0/1    Error    2         24s
splunk-connect-splunk-kubernetes-logging-zhsw4                 1/1    Running  0         24s
splunk-connect-splunk-kubernetes-metrics-6fcnz                 1/1    Running  0         24s
splunk-connect-splunk-kubernetes-metrics-7fw7m                 1/1    Running  0         24s
splunk-connect-splunk-kubernetes-metrics-agg-5c5cb6657b-nnfwd  1/1    Running  0         24s
splunk-connect-splunk-kubernetes-metrics-l8v4w                 1/1    Running  0         24s
splunk-connect-splunk-kubernetes-metrics-ld9jz                 1/1    Running  0         24s
splunk-connect-splunk-kubernetes-metrics-nb74b                 1/1    Running  0         24s
splunk-connect-splunk-kubernetes-metrics-xh26t                 1/1    Running  0         24s
splunk-connect-splunk-kubernetes-objects-6bc8c4b8f5-x7tw9      1/1    Running  0         24s

eccd@director-0-csaeccd:~> kubectl logs splunk-connect-splunk-kubernetes-logging-qlvls -n splunk
2019-09-20 15:50:18 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2019-09-20 15:50:18 +0000 [warn]: [containers.log] 'encoding' and 'from_encoding' are same encoding. No effect
2019-09-20 15:50:18 +0000 [warn]: 'filters' parameter is deprecated: filters has been renamed as matches
2019-09-20 15:50:18 +0000 [warn]: 'filters' parameter is deprecated: filters has been renamed as matches
2019-09-20 15:50:18 +0000 [error]: [journald-kubelet] failed to read data from plugin storage file path="/var/log/splunkd-fluentd-journald-kubelet.pos.json" error_class=Fluent::ConfigError error="Invalid contents (not object) in plugin storage file: '/var/log/splunkd-fluentd-journald-kubelet.pos.json'"
2019-09-20 15:50:18 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Unexpected error: failed to read data from plugin storage file: '/var/log/splunkd-fluentd-journald-kubelet.pos.json'"

It seems that the issue a corrupted "/var/log/splunkd-fluentd-journald-kubelet.pos.json" file. I could only restart the pod after deleting the corrupted file and restarting the pod manually.

**What you expected to happen**:

The pod should detect the corrupted file and restart automatically.

**How to reproduce it (as minimally and precisely as possible)**:

Try to restart k8s node(s) where the SCK is deployed and running. It is an intermittent issue.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:45:27Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:40:58Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Ruby version (use `ruby --version`):
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]

- OS (e.g: `cat /etc/os-release`):
NAME="SLES"
VERSION="15-SP1"
VERSION_ID="15.1"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp1"

- Splunk version: SCK 1.2.0 / Splunk Enterprise 7.1.4
- Others:

**Comment by chaitanyaphalak** [comment]
Do you know why the file got corrupted?
Looks like an issue on your node.

**Comment by rfrodrigues16** [comment]
The issue was verified during HA tests on our k8s cluster. The node has been forcefully restarted.
The problem seems to be the same as reported in the issue [245](https://github.com/fluent/fluentd-kubernetes-daemonset/issues/245) on “fluentd-kubernetes-daemonset”.

**Comment by chaitanyaphalak** [comment]
From the thread it looks like it was fluentd bug. I think, it will get fixed in the next release for Splunk Connect For Kubernetes.

**Comment by rfrodrigues16** [comment]
Is there a target date for the next SCK release?

**Comment by chaitanyaphalak** [comment]
There is no target date as such, but we are trying to get it out as soon as possible.

**Comment by chaitanyaphalak** [comment]
The latest release should address this issue - https://github.com/splunk/splunk-connect-for-kubernetes/releases/tag/1.3.0
