### ISSUE TITLE
Openshift 4.2 is compatible with splunk connect v 1.2.0?

### ISSUE THREAD

**Issue by mygithubthrowaway** [splunk/splunk-connect-for-kubernetes#277]
As title, thanks

**Comment by matthewmodestino** [comment]
I have deployed successfully on 4.2 using the cri-o settings available in the develop branch. 

https://github.com/splunk/splunk-connect-for-kubernetes/blob/32bcc6fbcb642012bdf1f8e3d7a609cdad8fd7de/helm-chart/splunk-kubernetes-logging/values.yaml#L52

**Comment by mygithubthrowaway** [comment]
Hi Metthew, thanks for your kind reply, I have 2 questions:

1) how i can deploy the chart from develop branch? I just need to make a tar.gz of repo or what?
2) Do you edit the values from logs section too? This: 
* https://github.com/splunk/splunk-connect-for-kubernetes/blob/master/helm-chart/splunk-kubernetes-logging/values.yaml#L150 
because in cri-o the unit file is not `docker.service` and the path of logs is different from docker

Thanks again

**Comment by matthewmodestino** [comment]
Version 1.3.0 is available now, no need for dev branch. Yeah, journald inputs can be updated as well as needed.

**Comment by chaitanyaphalak** [comment]
Closing as resolved with https://github.com/splunk/splunk-connect-for-kubernetes/releases/tag/1.3.0
