### ISSUE TITLE
Hostname field is missing

### ISSUE THREAD

**Issue by paulalex** [splunk/splunk-connect-for-kubernetes#278]
Hi,

I hope this is the last time I need any assistance as I think we are very close to moving to splunk cloud from hosted. 

One of the things we have had help with was editing the `_helpers.tpl` template in `splunk-kubenernetes-logging` so that we could send logs to indexes specific to applications running on the cluster.

There is an issue now that whilst the indexes are receiving data from namespaces the logs in splunk cloud do not have the hostname field set, and I do not really understand the syntax of the templates so am looking to see if I can get some help with amending the function to include hostname.

We had some help to write an additional function called setIndex which is called inside the function below and it works fine, I just need to know how to add the hostname in the function below if this is possible:

```
def extract_container_info:
  (.source | ltrimstr("/var/log/containers/") | split("_")) as $parts
  | ($parts[-1] | split("-")) as $cparts
  | .pod = $parts[0]
  | .namespace = $parts[1]
  | .index = set_index($parts[1])  
  | .container_name = ($cparts[:-1] | join("-"))
  | .container_id = ($cparts[-1] | rtrimstr(".log"))
  | .cluster_name = "{{ or .Values.kubernetes.clusterName .Values.global.kubernetes.clusterName | default "cluster_name" }}"
  | .;
```
Any help would be appreciated.

**Comment by paulalex** [comment]
I have since found this: https://github.com/splunk/splunk-connect-for-kubernetes/pull/193/files

Implementing this has fixed my issues, thanks!

**Comment by chaitanyaphalak** [comment]
Awesome @paulalex . We are releasing SCK with that patch soon.
