### ISSUE TITLE
Allow to use file buffer

### ISSUE THREAD

**Issue by Gimi** [splunk/splunk-connect-for-kubernetes#28]
Currently, the charts use memory as fluentd output buffer, and it can not be customized. We want to make the buffer section customizable, so that people can switch to other buffer system, e.g. file, if they want.

**Comment by dbaldwin-splunk** [comment]
@dtregonning @luckyj5 ^^ Please review issue.

**Comment by dtregonning** [comment]
fixed with https://github.com/splunk/splunk-connect-for-kubernetes/pull/60
#60
