### ISSUE TITLE
splunk-splunk-kubernetes-objects => Error: container has runAsNonRoot and image will run as root

### ISSUE THREAD

**Issue by jsiegele** [splunk/splunk-connect-for-kubernetes#286]
Hi,
 since we are run Splunk within a restriced environment, where we are not allowing root-Images.
we faced the following Problem:

```
splunk-splunk-kubernetes-objects => Error: container has runAsNonRoot and image will run as root
```

Our solution looks like this:
we added to the Deployment the following "securityContext
```      
securityContext:
   runAsUser: 10001
```
>> https://medium.com/@k8spin/rootless-containers-on-kubernetes-part-2-dfff67f899a6

Did we miss something?

**What would you like to be added**:
Possibilty to set the Security-Context within the values.yaml

**Why is this needed**:
We are running the Pods within a restricted environment

**Comment by matthewmodestino** [comment]
HI! can you please tell us more about your environment and your deployment method? is this Openshift? OSS k8s? Are you using helm?

**Comment by chaitanyaphalak** [comment]
Which version of SCK are you using? Also which k8s distribution?

**Comment by jsiegele** [comment]
Hi!
  SCK: version: 1.2.0
  Object - image; kube-objects:1.1.0
  Kubernetes Distro: PKS 1.5
  We are using your HELM-Charts and we are deploying them via ArgoCD.

Thank you!

Am Do., 14. Nov. 2019 um 20:20 Uhr schrieb Chaitanya Phalak <
notifications@github.com>:

**Comment by chaitanyaphalak** [comment]
PKS is not supported as of now. This PR https://github.com/splunk/splunk-connect-for-kubernetes/pull/240 adds support for it, but is not complete yet. If you want you can try it out and create a PR for us. We will be happy to review it.
