### ISSUE TITLE
Define the number of deployment’s revision history within the values.yaml (default: 10)

### ISSUE THREAD

**Issue by jsiegele** [splunk/splunk-connect-for-kubernetes#291]
**What would you like to be added**:
Define the number of deployment’s revision history within the values.yaml (default: 10)
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit

**Why is this needed**:
we want to define a lower number ...

**Comment by chaitanyaphalak** [comment]
@jsiegele we will be happy to review a PR for the same.
