### ISSUE TITLE
Does this tool support "kubectl logs" command after the setup

### ISSUE THREAD

**Issue by sanpal1** [splunk/splunk-connect-for-kubernetes#292]
Hello ,

Once we configure Splunk connect for Kubernetes, can we still use "kubectl logs <pod_name>" to view realtime logs? When i tried Splunk driver for docker, I was unable to do kubectl logs.

I am using Kops for creating and managing the cluster.

Thanks

**Comment by chaitanyaphalak** [comment]
yes
