### ISSUE TITLE
Splunk-Kubernetes-Logging pod crashes

### ISSUE THREAD

**Issue by vbottu** [splunk/splunk-connect-for-kubernetes#293]
### Tried in version 1.3.0
I am trying to install splunk-connect-for-kubernetes using helm, i cloned the git repo to my local and updated the requirements.yml to point to my local subcharts within the repo and did a "helm dep update" which is successful. I updated teh values file with splunk hec token and other details like the indexname for each component, metrics and objects pods are running fine but the logging pod is crashed with in the below error.
` [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Could not parse jq filter: def find_sourcetype(pod; container_name):\r container_name + \"/\" + pod |\r if startswith(\"dns-controller/dns-controller\") then \"kube:dns-controller\"\r elif startswith(\"sidecar/kube-dns\") then \"kube:kubedns-sidecar\"\r elif startswith(\"dnsmasq/kube-dns\") then \"kube:dnsmasq\"\r elif startswith(\"etcd-container/etcd-server\") then \"kube:etcd\"\r elif startswith(\"etcd-container/etcd-server-events\") then \"kube:etcd-events\"\r elif startswith(\"kube-apiserver/kube-apiserver\") then \"kube:kube-apiserver\"\r elif startswith(\"kube-controller-manager/kube-controller-manager\") then \"kube:kube-controller-manager\"\r elif startswith(\"autoscaler/kube-dns-autoscaler\") then \"kube:kube-dns-autoscaler\"\r elif startswith(\"kube-proxy/kube-proxy\") then \"kube:kube-proxy\"\r elif startswith(\"kube-scheduler/kube-scheduler\") then \"kube:kube-scheduler\"\r elif startswith(\"kubedns/kube-dns\") then \"kube:kubedns\"\r else empty\r end;\r \r def set_namespace(value):\r if value == \"default\"\r then \"main\"else value\r end;\r \r def extract_container_info:\r   (.source | ltrimstr(\"/var/log/containers/\") | split(\"_\")) as $parts\r   | ($parts[-1] | split(\"-\")) as $cparts\r   | .pod = $parts[0]\r   | .namespace = set_namespace($parts[1])\r   | .container_name = ($cparts[:-1] | join(\"-\"))\r   | .container_id = ($cparts[-1] | rtrimstr(\".log\"))\r   | .cluster_name = \"cluster_name\"\r   | .;\r \r .record | extract_container_info | .sourcetype = (find_sourcetype(.pod; .container_name) // \"kube:container:\\(.container_name)\"), error: Could not parse jq filter: def find_sourcetype(pod; container_name):\r container_name + \"/\" + pod |\r if startswith(\"dns-controller/dns-controller\") then \"kube:dns-controller\"\r elif startswith(\"sidecar/kube-dns\") then \"kube:kubedns-sidecar\"\r elif startswith(\"dnsmasq/kube-dns\") then \"kube:dnsmasq\"\r elif startswith(\"etcd-container/etcd-server\") then \"kube:etcd\"\r elif startswith(\"etcd-container/etcd-server-events\") then \"kube:etcd-events\"\r elif startswith(\"kube-apiserver/kube-apiserver\") then \"kube:kube-apiserver\"\r elif startswith(\"kube-controller-manager/kube-controller-manager\") then \"kube:kube-controller-manager\"\r elif startswith(\"autoscaler/kube-dns-autoscaler\") then \"kube:kube-dns-autoscaler\"\r elif startswith(\"kube-proxy/kube-proxy\") then \"kube:kube-proxy\"\r elif startswith(\"kube-scheduler/kube-scheduler\") then \"kube:kube-scheduler\"\r elif startswith(\"kubedns/kube-dns\") then \"kube:kubedns\"\r else empty\r end;\r \r def set_namespace(value):\r if value == \"default\"\r then \"main\"else value\r end;\r \r def extract_container_info:\r   (.source | ltrimstr(\"/var/log/containers/\") | split(\"_\")) as $parts\r   | ($parts[-1] | split(\"-\")) as $cparts\r   | .pod = $parts[0]\r   | .namespace = set_namespace($parts[1])\r   | .container_name = ($cparts[:-1] | join(\"-\"))\r   | .container_id = ($cparts[-1] | rtrimstr(\".log\"))\r   | .cluster_name = \"cluster_name\"\r   | .;\r \r .record | extract_container_info | .sourcetype = (find_sourcetype(.pod; .container_name) // \"kube:container:\\(.container_name)\"), error: jq: error: syntax error, unexpected INVALID_CHARACTER (Unix shell quoting issues?) at <top-level>, line 1:\ndef find_sourcetype(pod; container_name):\r container_name + \"/\" + pod |\r if startswith(\"dns-controller/dns-controller\") then \"kube:dns-controller\"\r elif startswith(\"sidecar/kube-dns\") then \"kube:kubedns-sidecar\"\r elif startswith(\"dnsmasq/kube-dns\") then \"kube:dnsmasq\"\r elif startswith(\"etcd-container/etcd-server\") then \"kube:etcd\"\r elif startswith(\"etcd-container/etcd-server-events\") then \"kube:etcd-events\"\r elif startswith(\"kube-apiserver/kube-apiserver\") then \"kube:kube-apiserver\"\r elif startswith(\"kube-controller-manager/kube-controller-manager\") then \"kube:kube-controller-manager\"\r elif startswith(\"autoscaler/kube-dns-autoscaler\") then \"kube:kube-dns-autoscaler\"\r elif startswith(\"kube-proxy/kube-proxy\") then \"kube:kube-proxy\"\r elif startswith(\"kube-scheduler/kube-scheduler\") then \"kube:kube-scheduler\"\r elif startswith(\"kubedns/kube-dns\") then \"kube:kubedns\"\r else empty\r end;\r \r def set_namespace(value):\r if value == \"default\"\r then \"main\"else value\r end;\r \r def extract_container_info:\r   (.source | ltrimstr(\"/var/log/containers/\") | split(\"_\")) as $parts\r   | ($parts[-1] | split(\"-\")) as $cparts\r   | .pod = $parts[0]\r   | .namespace = set_namespace($parts[1])\r   | .container_name = ($cparts[:-1] | join(\"-\"))\r   | .container_id = ($cparts[-1] | rtrimstr(\".log\"))\r   | .cluster_name = \"cluster_name\"\r   | .;\r \r .record | extract_container_info | .sourcetype = (find_sourcetype(.pod; .container_name) // \"kube:container:\\(.container_name)\")                                         \njq: 1 compile error\n"`
Please let me know if I am missing something here.

**Comment by chaitanyaphalak** [comment]
Did you try installing a release from https://github.com/splunk/splunk-connect-for-kubernetes/releases/tag/1.3.0 ?

**Comment by vbottu** [comment]
I tried and it works,if I try to instal from my local chart the pod always crashes.

**Comment by chaitanyaphalak** [comment]
Use the makefile to generate the tar gz. Use that to install. I guess "helm dep update" is messing something up for you.
