### ISSUE TITLE
The chart does not support adding multiple Hosts

### ISSUE THREAD

**Issue by ritwiksin** [splunk/splunk-connect-for-kubernetes#295]
I tried adding multiple Splunk hosts to the values file but it does not support it.

I wanted to make it redundant so I tried adding several hosts but it did not support this!  So I created a Kubernetes Endpoint (which points to the Splunk hosts) and a Service which points to this Endpoint, and I added this service as a Host in the Chart.

Now, the problem is it’s not doing a round-robin. I guess it resolves the DNS and caches the IP. If the first IP in the list is unreachable, then it starts sending it to another IP on the list.

How do I add multiple Hosts in the values file?

**Comment by chaitanyaphalak** [comment]
@ritwiksin We dont support adding multiple hosts. You could try to put a load balancer in front of all your splunk hosts and use the loadbalancer as the host for the connector.
