### ISSUE TITLE
Upgrade the default Heapster image to a newer version

### ISSUE THREAD

**Issue by Gimi** [splunk/splunk-connect-for-kubernetes#30]
There are a lot of issues have been fixed since v1.5.1. Some bug fixings like this https://github.com/kubernetes/heapster/issues/1935 is critical for people to get the right metrics.

**Comment by dbaldwin-splunk** [comment]
@luckyj5

**Comment by dbaldwin-splunk** [comment]
We are going to migrate from heapster to metric server because of heapster deprecation announcement with Kubernetes 1.11.  Will close issue after heapster replacement.

**Comment by llarsson** [comment]
Oh, thank you for planning to move to metric server! 

Should perhaps a new issue be made just to track that migration for people like me who read the documentation and almost decide to not use this plugin because it relies on Heapster?

**Comment by dbaldwin-splunk** [comment]
@llarsson Some changes from the metrics server implementation.  PR here: https://github.com/splunk/fluent-plugin-kubernetes-metrics/pull/1

**Comment by dtregonning** [comment]
Heapster is no longer being used for metrics collection. Collection is no achieved via a custom metrics solutions with a homegrown aggregator.
Closing issue
