### ISSUE TITLE
Question: What are the implications of setting kubernetes insecureSSL as true in splunk-kubernetes-objects 

### ISSUE THREAD

**Issue by sanpal1** [splunk/splunk-connect-for-kubernetes#303]
Hello,

Can you please let me know the security implications of Kubernetes: insecureSSL as true in splunk-kubernetes-objects?

If the splunk-kubernetes-objects pod/container get compromised, will the attacker be able to delete or create pods/services etc. inside the cluster?

We are setting up below values as true:

  serviceAccount:
    create: true
  rbac:
    create: true

We use aws-iam-authenticator for Kubernetes authentication and don't think there is an easy way to get the authentication token (which expires every 15 minutes) in the Splunk config.

Thanks

**Comment by matthewmodestino** [comment]
Hello!

When enabling RBAC in the chart:

https://github.com/splunk/splunk-connect-for-kubernetes/blob/7541e96e75a428e43ab35210eac3c3a147d2a7e3/helm-chart/splunk-kubernetes-objects/values.yaml#L42-L47

We deploy the `clusterRole` which you can review in the template folder. 

This allows only list and watch verbs. 

When configuring `insecureSSL: true`:

https://github.com/splunk/splunk-connect-for-kubernetes/blob/7541e96e75a428e43ab35210eac3c3a147d2a7e3/helm-chart/splunk-kubernetes-objects/values.yaml#L65-L66

`if insecureSSL is set to true, insecure HTTPS API call is allowed, default false`

which means the objects pod will not validate the certificate Kubernetes cluster is using.

**Comment by sanpal1** [comment]
Thanks for the details. That helps. Closing.
