### ISSUE TITLE
Community support location?

### ISSUE THREAD

**Issue by ksmithut** [splunk/splunk-connect-for-kubernetes#308]
**What would you like to be added**:

Links to where one might find community support mentioned in the "Deploy using YAML" section:

> Please note that installation and debugging for Splunk Connect for Kubernetes through YAML is community-supported only.

**Why is this needed**:

We're currently not using helm and want to make sure we're not missing any configurations. I've looked through the helm charts and it looks like we're missing quite a few values for the HEC configuration (such as host and port) and the Injest API, but I'm not sure what is required to fill out. The manifest files, specifically the ConfigMap ones are particularly hard to grok since the `output.conf` key gets pretty mangled in escape characters and newline breaks in odd places (perhaps a bug in how it gets generated?). Any existing links with people running this without helm would be much appreciated.

**Comment by chaitanyaphalak** [comment]
you can find them here https://github.com/splunk/splunk-connect-for-kubernetes/tree/develop/manifests
Also you could generate them as follows 
helm template --name=my-awesome-sck-deployment --namespace=splunk-sck --values=../sck_values.yaml --output-dir=rendered-charts splunk-connect-for-kubernetes-1.3.0.tgz
