### ISSUE TITLE
imagePullSecret support is missing from daemonset and deployment templates

### ISSUE THREAD

**Issue by bobveznat** [splunk/splunk-connect-for-kubernetes#310]
If you set a pullSecretName and the usePullSecret flag in values.yaml the various daemonset and deployment templates don't actually plug in the pull secret.

For each of the templates I had to add a block like the one here (and I apologize that I cannot send a pull request):

     {{- if .Values.image.usePullSecret }}
     imagePullSecrets:
     - name: {{.Values.image.pullsecretName}}
       {{- end }}

**Comment by rockb1017** [comment]
Thank you. this has been fixed.
