### ISSUE TITLE
deploymentMetricsAggregator template produces invalid k8s manifest file

### ISSUE THREAD

**Issue by bobveznat** [splunk/splunk-connect-for-kubernetes#311]
**What happened**:

I cloned this repo and after updating values.yaml ran helm template ... | kubectl apply .... Helm templates failed to apply with k8s complaining that one of the manifests used some unknown field.

**What you expected to happen**:

The templates to generate valid k8s declarations.

**How to reproduce it (as minimally and precisely as possible)**:

clone this repo and from the helm-chart/splunk-connect-for-kubernetes directory run helm template. You can see that the deployment for the metrics aggregator generates a deployment spec with a field updateStrategy. Unfortunately updateStrategy is not valid for deployments, it works for daemonsets.

**Anything else we need to know?**:

I run behind a pretty restrictive firewall.

I can't submit a pull request but this patch worked for me:

    @@ -8,7 +8,7 @@ metadata:
         release: {{ .Release.Name }}
         heritage: {{ .Release.Service }}
     spec:
    -  updateStrategy:
    +  strategy:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.1

**Comment by rockb1017** [comment]
Thank you. This fix has already been added to #306
