### ISSUE TITLE
How to send only application logs to splunk

### ISSUE THREAD

**Issue by vbottu** [splunk/splunk-connect-for-kubernetes#313]
I am trying to implement splunk connect for one of our clusters and I would like to send only application logs (container logs) , I was able to filter out the other kube related pods and network related pods from sending the logs to splunk, but I would like to exclude services like kubelet ,for example i am using /run/log/journal/*.service in the exclude path but I am still seeing the logs in splunk. 

Also can someone point me to documentation about formatting the logs before sending to splunk.

**Comment by rockb1017** [comment]
in values.yaml file for logging, 
docker daemon and kubelet daemon journal logs are added by default. 
you can overwrite it by change `logs` key
`logs:
  docker:
    from:
      journald:
        unit: docker.service
    timestampExtraction:
      regexp: time="(?<time>\d{4}-\d{2}-\d{2}T[0-2]\d:[0-5]\d:[0-5]\d.\d{9}Z)"
      format: "%Y-%m-%dT%H:%M:%S.%NZ"
    sourcetype: kube:docker
  kubelet: &glog
    from:
      journald:
        unit: kubelet.service
    timestampExtraction:
      regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
      format: "%m%d %H:%M:%S.%N"
    multiline:
      firstline: /^\w[0-1]\d[0-3]\d/
    sourcetype: kube:kubelet`

**Comment by rockb1017** [comment]
so copy the default options from values.yaml to your configuration yaml file. then delete lines for kubelet daemon.

**Comment by doandzhiFt** [comment]
Copying the default options and removing entries for the daemons didn't work for me... Am I doing something wrong or there should be another way to configure it. Also I am looking for a way to set these configurations dynamically (without redeploying splunk connector when a new container appears on the cluster. Can some help with this?

**Comment by vbottu** [comment]
> so copy the default options from values.yaml to your configuration yaml file. then delete lines for kubelet daemon.

I am making the changes in the values.yaml file, where is the configuration yaml file? is it the configmap template? I am using Helm to install, Sorry for the confusion but I didn't get you.

**Comment by rockb1017** [comment]
@vbottu 
configuration yaml file i mentioned was the file you use to deploy this chart with -f option. 
`logs` options are here: 
https://github.com/splunk/splunk-connect-for-kubernetes/blob/ec2b397fe05f4ff43850896e5aab323cb4721917/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml#L176

**Comment by rockb1017** [comment]
@doandzhiFt Could you tell me more of how you have done it? 
on the fluentd side, its config should be provided at the start of it. 

Do you want to remove ingesting daemon logs ? also do you want to apply different configuration to certain containers?

**Comment by rockb1017** [comment]
@vbottu Another brute force way to not ingest any of journald logs is by giving a wrong path for it. Not pretty solution though 
https://github.com/splunk/splunk-connect-for-kubernetes/blob/ec2b397fe05f4ff43850896e5aab323cb4721917/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml#L36

**Comment by vbottu** [comment]
> @vbottu Another brute force way to not ingest any of journald logs is by giving a wrong path for it. Not pretty solution though
> https://github.com/splunk/splunk-connect-for-kubernetes/blob/ec2b397fe05f4ff43850896e5aab323cb4721917/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml#L36

I modified the configmap template to not include the journald.conf and it is not sending journald logs to splunk. Please let me know if is ok doing this way.
Thanks

**Comment by rockb1017** [comment]
if it does what you want, then it works for me! :) closing it.

**Comment by vinitmasaun** [comment]
I am not able to get any logs from our EKS or minikube cluster.  I am seeing metrics and objects but no logs from the containers.  All the logs in the cluster are getting written to /var/log/containers and in the splunk-logging section of the values.yaml the defaults are kept in place for the log path (/var/log/containers/*.log).  Anyone else encounter this issue?  We are able to get logs using fluentbit but not with this app, which uses fluentd.  On that note, is it possible to incorporate fluentbit into this app instead of fluentd?
