### ISSUE TITLE
unable to view splunk logs with namespace and cluser_name fields

### ISSUE THREAD

**Issue by ramaprasad434** [splunk/splunk-connect-for-kubernetes#318]
**What happened**:

we are able to view logs properly with sourcetype="kube:container:XXXX" but if we use filters like cluster_name="mycluster" or namespace="mynamespace" we are not able to get logs.

**What you expected to happen**:
we should able to filter the logs with cluster_name or namespace

**How to reproduce it (as minimally and precisely as possible)**:
index=my_index   sourcetype="kube:container:cluster-autoscaler" which is working fine
index=my_index   sourcetype="kube:container:cluster-autoscaler"  cluster_name="mycluster" which is not giving proper results.
**Anything else we need to know?**:

**Environment**:  prod and non prod
- Kubernetes version (use `kubectl version`): 1.14
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

- Splunk version: 7.0.13
- Others:

**Comment by chaitanyaphalak** [comment]
https://github.com/splunk/splunk-connect-for-kubernetes#searching-for-sck-metadata-in-splunk this section of the readme will help you to resolve this issue

**Comment by ramaprasad434** [comment]
Thanks you !!!
