### ISSUE TITLE
question to: release cycle

### ISSUE THREAD

**Issue by MarcoSchaar** [splunk/splunk-connect-for-kubernetes#319]
**What would you like to be added**:
would be nice to have a kind of "monthly release"

**Why is this needed**:
keep local deployments secure and up to date with e.g. fixed cve's

**Comment by njferrant** [comment]
+1 - Current CRI-O additions are merged in the development branch and seem to be required for splunk-connect on OpenShift v4.

**Comment by rockb1017** [comment]
Thank you! We are in the process of simplify release process so that we can have faster release cycle.
