### ISSUE TITLE
How to disable kube:container:redirector?

### ISSUE THREAD

**Issue by hugree** [splunk/splunk-connect-for-kubernetes#32]
Hi, 

I am using the logging component to connect K8 with Splunk and in general everything works fine.

I'm using Azure AKS and here are the generated sourcetypes:

> kube:container:redirector	209,236	75.796%	
> kube:container:main	19,837	7.186%	
> fluentd:monitor-agent	18,504	6.703%	
> kube:container:tunnel-front	14,700	5.325%	
> kube:container:azureproxy	11,913	4.316%	
> kube:container:pinkcloud-server	593	0.215%	
> kube:container:tiller	557	0.202%	
> kube:container:heapster	331	0.12%	
> kube:container:splunk-fluentd-k8s-logs	309	0.112%	
> kube:container:heapster-nanny
> 

The first one is generating tons of logs so my main question is how to disable the logging forwarder for a specific component?

Thanks,
Greg

**Comment by matthewmodestino** [comment]
You can absolutely filter at the pod level using the filters in the configMap of the logging pod.

We monitor `/var/log/containers/*` as a default, and you could look at fluentd’s `exclude_path` option, or if you think you’ll have a lot of these, I would make the tail settings more granular, perhaps leveraging the namespace values.

The nullqueue is another option, though personally I prefer getting the config right at the source.

**Comment by hugree** [comment]
@matthewmodestino yeah that does it. Thank you. Quick question... what's the neat way of overwriting only a part of the config that I need? I guess I need to include the whole `source.containers.conf` section?
