### ISSUE TITLE
No more data in sourcetype kube:objects:events

### ISSUE THREAD

**Issue by d2si-spk** [splunk/splunk-connect-for-kubernetes#323]
Possibly not an issue sorry, looking for a troubleshooting lead.

We got everything configured as documented and it was working fine until a few days ago.

All of of a sudden, there was no more data being indexed in the 'kube:objects:events' sourcetype while data in the others object sourcetypes is still being indexed.

[https://ibb.co/pRCGCtj](https://ibb.co/pRCGCtj)

I do not find any relevant error message that would lead me somewhere.

**Comment by matthewmodestino** [comment]
Hi what version are you using? there was a bug in earlier versions that could cause connection to events API to die.

**Comment by d2si-spk** [comment]
Hello Matthew,

Thanks for your feedback.

We have just killed the object pod and object data is now back in Splunk but we still have no clue why it died.

Version is : docker.io/splunk/kube-objects:1.1.2

**Comment by matthewmodestino** [comment]
Hard to say but if you analyze the logs in splunk it may help uncover. There was a bug in the objects image in a past version when it would stop collecting. So if your deploy was an older image, thats probably why.

**Comment by d2si-spk** [comment]
Alright, I guess I will investigate on it if it happens again. Thanks!

**Comment by matthewmodestino** [comment]
have you checked the pod logs and or kube event logs for a trace of what happened??

**Comment by d2si-spk** [comment]
Yeah, I had checked the logs at the time of the issue but did not spot anything that would explain it.

Anyhow, it did not happen again, plus we are finally using another type of event to get our pod stats so it's all good!

Thanks!

**Comment by chaitanyaphalak** [comment]
CLosing as resolved, please open a new one if further assistance is needed.
