### ISSUE TITLE
splunk connect for kubernetes is not compatible with recent versions of kubernetes

### ISSUE THREAD

**Issue by ag0r** [splunk/splunk-connect-for-kubernetes#325]
**What happened**: Helm chart fails to apply with the error `Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1"`

**What you expected to happen**: Helm chart applies successfully

**How to reproduce it (as minimally and precisely as possible)**: Try to install on kubernetes v1.17.2 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.17.2
- Ruby version (use `ruby --version`): NA
- OS (e.g: `cat /etc/os-release`): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Splunk version: 7.3.1
- Others:

**Comment by chaitanyaphalak** [comment]
which version of splunk connect for kubernetes are you using? I think you are on an older version and need to upgrade
