### ISSUE TITLE
Metadata for logs

### ISSUE THREAD

**Issue by Mr-iX** [splunk/splunk-connect-for-kubernetes#326]
Currently we are using Elasticsearch and Kibana on our Openshift 3.11 Clusters.
Now we have installed the splunk connect and it works great. 

Is there any posibility to add metadata like ```kubernetes.container_image, kubernetes.container_image_id, kubernetes.host, kubernetes.labels.deployment, kubernetes.labels.deploymentconfig``` to the events which are sent to splunk?

Currently I found only these metadata information in splunk: ```namespace, pod, container_name, container_id, cluster_name```

**Comment by matthewmodestino** [comment]
Yes, please check out 1.4 release that supports labels as well as lets you control the collector with annotations, etc. https://github.com/splunk/splunk-connect-for-kubernetes/releases

Also we already collect this info with the objects pod as well, which is an alternate way to enrich data in splunk, via lookups, once the data is in splunk.

**Comment by rockb1017** [comment]
closing
