### ISSUE TITLE
Worker nodes logs to splunkcloud

### ISSUE THREAD

**Issue by yrsurya** [splunk/splunk-connect-for-kubernetes#327]
<

**What would you like to be added**:
I am not sure if this exist already but it would be great if we can also implement feature to send worker nodes logs( kubelete, docker , system logs) to splunk cloud so that we no need to install splunkforwader on each workernode to do these
**Why is this needed**:
As we see few times our EKS worker node went to not ready state and not able to find root cause as SSH is not working and EC2 (worker node) just hangs out

**Comment by rockb1017** [comment]
it does have that feature already.  please look configuration values file here:
`logs:
    docker:
      from:
        journald:
          unit: docker.service`
