### ISSUE TITLE
multiline example request for Tomcat logs

### ISSUE THREAD

**Issue by oguzy** [splunk/splunk-connect-for-kubernetes#33]
Below is my exception outline

2018-09-24 11:21:00.428  WARN 1 --- [rter-1-thread-1] c.c.metrics.graphite.GraphiteReporter    : Unable to report to Graphite

> java.net.ConnectException: Connection timed out (Connection timed out)
>         at java.net.PlainSocketImpl.socketConnect(Native Method)
>         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
>         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
>         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
>         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>         at java.net.Socket.connect(Socket.java:589)
>         at java.net.Socket.connect(Socket.java:538)
>         at java.net.Socket.<init>(Socket.java:434)
>         at java.net.Socket.<init>(Socket.java:244)
>         at javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:277)
>         at com.codahale.metrics.graphite.Graphite.connect(Graphite.java:128)
>         at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:166)
>         at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:162)
>         at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:117)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)

What should be the multiline settings?

**Comment by sayeedc** [comment]
For java stack traces, should you use <filter> or <parse> (as described in https://docs.fluentd.org/v1.0/articles/parser_multiline)?

**Comment by VinceMD** [comment]
As described here https://github.com/splunk/splunk-connect-for-kubernetes/issues/111 

As soon as it matches a pattern, it goes in recursive deadlock. Can you help please?
It seems the examples don't use a valid regex. Has that been tested before ?

**Comment by chaitanyaphalak** [comment]
Refer here - https://github.com/splunk/splunk-connect-for-kubernetes/issues/198
