### ISSUE TITLE
Incompatible Container Images in Helm Chart 1.4.0

### ISSUE THREAD

**Issue by mgherman** [splunk/splunk-connect-for-kubernetes#334]
**What happened**:
The -logging and -object pods failed to start. Logs only show a fluentd usage message.

**What you expected to happen**:
The -logging and object pods ran and operate correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Install via Helm chart without overriding the tags for the containers.

**Anything else we need to know?**:
It appears that the default tags for the fluentd-hec and kube-objects containers are incorrect as per  PLUGIN_VERSIONS.sh resulting in containers crashing. Setting the tags to those in the VERSIONS file allows the install to proceed correctly.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.6
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04
- Splunk version: 7.3.3
- Others:

**Comment by fpicot** [comment]
Same issue here. 
It seems to come from #302, which did not update tag for splunk/fluentd-hec in global values.yaml

**Comment by rockb1017** [comment]
Thank you @fpicot created PR to update it 
https://github.com/splunk/splunk-connect-for-kubernetes/pull/336

**Comment by chaitanyaphalak** [comment]
resolved with #336
