### ISSUE TITLE
Splunk logging delay & buffer settings

### ISSUE THREAD

**Issue by kyaparla** [splunk/splunk-connect-for-kubernetes#335]
We were noticing data loss and were able to handle it using below buffer settings.  
retry_forever: true
retry_type: periodic
retry_wait: 5s

But, we still have issues with delays sometimes >15-60mins getting in to splunk.  Below are buffer settings we are using.  Any suggestions on minimizing delay?

"@type": memory
total_limit_size: 500m
chunk_limit_size: 100m
chunk_limit_records: 20000
flush_interval: 5s
flush_thread_count: 8
queued_chunks_limit_size: 8
overflow_action: drop_oldest_chunk
#retry_max_times: 10
retry_forever: true
retry_type: periodic
retry_wait: 5s

Can someone please help understand these settings better?

1. does fluentd send each chunk as one request to splunk?
2. does each chunk, hold data from different sources?
3. is flush thread count, to flush data from buffer or write data to buffer?
4. Our splunk hec has max incoming request size set to 20MB, so what should we use for chunk_limit_size?

**Comment by matthewmodestino** [comment]
Hi!

If you have data loss, buffer tweaking mostly is a temporary solution that is made worse by you trying to buffer and send massive chunks forever.

Lets, step waaaaay back and understand what you had data loss in the first place.

What kind of Splunk environment are you running? Splunk Cloud? On-Prem? how many indexers? 

The first thing to understand is your Splunk indexing rate. If indexers cant keep up they will cause backpressure on fluentd, causing buffer and delays.

While I wait for the answers I’ll take a stab at these, and please double check latest fluentd buffer documentation:

does fluentd send each chunk as one request to splunk?

Yes, a chunk gets posted to HEC, if you look at the pod logs in debug you can watch how.


does each chunk, hold data from different sources?

Yes I believe it does

is flush thread count, to flush data from buffer or write data to buffer?



Our splunk hec has max incoming request size set to 20MB, so what should we use for chunk_limit_size?

Use what your network can indexers can sustain. There is no magic formula for buffers and chunks, it is a product of your enviroment, please revert to defaults and baseline your reality :)

**Comment by matthewmodestino** [comment]
bump, make it anywhere with this?

**Comment by kyaparla** [comment]
Hi Matthew,  Thanks for the response.

We are running EKS cluster on AWS and we have splunk on premise,  with heavy forwarders listening for HEC traffic and with 500MB buffer on each heavy forwarder.  Yes there is a load balancer before heavy forwarders.

I see decent amount of retries on fluentd logs sending chunks,  and after adjusting buffer settings, not seeing any loss but the delay is higher compare to docker Splunk logging driver in AWS.

We also have ICP (IBM cluster) running on premise, where the fluentd performance is much better, but the delay is slightly higher than docker logging driver on premise.  Not sure, if its due to kubernetes writing data to /var/log and fluentd reading from disk vs docker logging driver directly reading from stdout.

Some times 10-20% of events have >20mins delay, whe data generated is at >20MB/sec.  We also see that cpu/memory utilization of fluentd reaches maximum at this rate.

**Comment by vinzent** [comment]
> We were noticing data loss and were able to handle it using below buffer settings.

I think these params still contribute to your issue of data loss:

> "@type": memory

if fluentd is killed you loose all buffered data

> overflow_action: drop_oldest_chunk 

once you reach the limit of 500mb buffered logs chunks will be discarded?

**Comment by vinzent** [comment]
Given your limit on Splunk is 20MB you probably should set chunk_limit_size < 20mb . I would leave some space in case some additional data is accounted to max request size.

**Comment by matthewmodestino** [comment]
Also, 2 items I have seen cause backpressure on fluentd.

1. Your loadbalancer, if possible, should loadbalance the HTTP requests not the commections! each instance of fluentd is a long lived connection, so I have seen HFs become a bottleneck fast.

2. definitely look at the buffer settings, for file and retry logic.

https://docs.fluentd.org/buffer

https://github.com/splunk/fluent-plugin-splunk-hec/blob/develop/README.md#about-buffer

Also make aure you dont make the chunks too big, as you will have to transmit them quickly and indexing large blobs will slow down your pipeline.
