### ISSUE TITLE
CrashLoop when deploying to non-default namespace

### ISSUE THREAD

**Issue by vinitmasaun** [splunk/splunk-connect-for-kubernetes#338]
**What happened**:
Splunk connect for k8s container goes into Crashloop when deploying to a namespace other than default.  For example, we need to deploy to a namespace called 'observability'.  Below is the error from the container log:
 kubectl logs -f -n observability release-name-splunk-kubernetes-logging-jqmj2
2020-02-28 21:07:35 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2020-02-28 21:07:35 +0000 [info]: gem 'fluentd' version '1.9.1'
2020-02-28 21:07:35 +0000 [info]: gem 'fluent-plugin-concat' version '2.4.0'
2020-02-28 21:07:35 +0000 [info]: gem 'fluent-plugin-jq' version '0.5.1'
2020-02-28 21:07:35 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.4.2'
2020-02-28 21:07:35 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.7.0'
2020-02-28 21:07:35 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.2.1'
2020-02-28 21:07:35 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2020-02-28 21:07:35 +0000 [warn]: thread exited by unexpected error plugin=Fluent::Plugin::KubernetesMetadataFilter title=:pod_watch_thread error_class=Fluent::ConfigError error="start_pod_watch: Exception encountered setting up pod watch from Kubernetes API v1 endpoint https://10.96.0.1:443/api: pods is forbidden: User \"system:serviceaccount:observability:release-name-splunk-kubernetes-logging\" cannot list resource \"pods\" in API group \"\" at the cluster scope ({\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"pods is forbidden: User \\\"system:serviceaccount:observability:release-name-splunk-kubernetes-logging\\\" cannot list resource \\\"pods\\\" in API group \\\"\\\" at the cluster scope\",\"reason\":\"Forbidden\",\"details\":{\"kind\":\"pods\"},\"code\":403}\n)"
2020-02-28 21:07:35 +0000 [warn]: thread exited by unexpected error plugin=Fluent::Plugin::KubernetesMetadataFilter title=:namespace_watch_thread error_class=Fluent::ConfigError error="start_namespace_watch: Exception encountered setting up namespace watch from Kubernetes API v1 endpoint https://10.96.0.1:443/api: namespaces is forbidden: User \"system:serviceaccount:observability:release-name-splunk-kubernetes-logging\" cannot list resource \"namespaces\" in API group \"\" at the cluster scope ({\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"namespaces is forbidden: User \\\"system:serviceaccount:observability:release-name-splunk-kubernetes-logging\\\" cannot list resource \\\"namespaces\\\" in API group \\\"\\\" at the cluster scope\",\"reason\":\"Forbidden\",\"details\":{\"kind\":\"namespaces\"},\"code\":403}\n)"
#<Thread:0x000055e388a75b68@namespace_watch_thread@/usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/thread.rb:70 run> terminated with exception (report_on_exception is true):
/usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.2/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:79:in `rescue in start_namespace_watch': start_namespace_watch: Exception encountered setting up namespace watch from Kubernetes API v1 endpoint https://10.96.0.1:443/api: namespaces is forbidden: User "system:serviceaccount:observability:release-name-splunk-kubernetes-logging" cannot list resource "namespaces" in API group "" at the cluster scope ({"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces is forbidden: User \"system:serviceaccount:observability:release-name-splunk-kubernetes-logging\" cannot list resource \"namespaces\" in API group \"\" at the cluster scope","reason":"Forbidden","details":{"kind":"namespaces"},"code":403} (Fluent::ConfigError)
)
                from /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.2/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:70:in `start_namespace_watch'
                from /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.2/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:30:in `set_up_namespace_thread'
                from /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.4.2/lib/fluent/plugin/filter_kubernetes_metadata.rb:283:in `block in configure'
                from /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-02-28 21:07:35 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="start_namespace_watch: Exception encountered setting up namespace watch from Kubernetes API v1 endpoint https://10.96.0.1:443/api: namespaces is forbidden: User \"system:serviceaccount:observability:release-name-splunk-kubernetes-logging\" cannot list resource \"namespaces\" in API group \"\" at the cluster scope ({\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"namespaces is forbidden: User \\\"system:serviceaccount:observability:release-name-splunk-kubernetes-logging\\\" cannot list resource \\\"namespaces\\\" in API group \\\"\\\" at the cluster scope\",\"reason\":\"Forbidden\",\"details\":{\"kind\":\"namespaces\"},\"code\":403}\n)"
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Generate helm manifest with modified values.yaml then use kubectl apply --recursive command to deploy the charts
**Anything else we need to know?**:

**Environment**: Development
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:04Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
- Ruby version (use `ruby --version`):
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
- OS (e.g: `cat /etc/os-release`):
macbook mojave running minikube
- Splunk version:
8.0.1
- Others:

**Comment by rockb1017** [comment]
logging pod now needs service account created with permission to read from kubernetes API server. please edit your values.yaml file to create service account. or please grant right permission to `system:serviceaccount:observability:release-name-splunk-kubernetes-logging` this service account

**Comment by vinitmasaun** [comment]
> logging pod now needs service account created with permission to read from kubernetes API server. please edit your values.yaml file to create service account. or please grant right permission to `system:serviceaccount:observability:release-name-splunk-kubernetes-logging` this service account

Below is the output of the two service account yamls I see in my namespace.  What is not correct with the rolebinding?

kubectl get sa -n monitoring
NAME                                     SECRETS   AGE
default                                  1         3d17h
splunk-1-4-0-splunk-kubernetes-logging   1         3d17h

kubectl get sa splunk-1-4-0-splunk-kubernetes-logging -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"splunk-kubernetes-logging","chart":"splunk-kubernetes-logging-1.4.0","heritage":"Tiller","release":"splunk-1-4-0"},"name":"splunk-1-4-0-splunk-kubernetes-logging","namespace":"monitoring"}}
  creationTimestamp: "2020-02-28T22:14:00Z"
  labels:
    app: splunk-kubernetes-logging
    chart: splunk-kubernetes-logging-1.4.0
    heritage: Tiller
    release: splunk-1-4-0
  name: splunk-1-4-0-splunk-kubernetes-logging
  namespace: monitoring
  resourceVersion: "1320"
  selfLink: /api/v1/namespaces/monitoring/serviceaccounts/splunk-1-4-0-splunk-kubernetes-logging
  uid: 9f5cf8b9-5a77-11ea-afea-6675893171b6
secrets:
- name: splunk-1-4-0-splunk-kubernetes-logging-token-lfq8l

kubectl get sa -n monitoring default -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-02-28T22:06:23Z"
  name: default
  namespace: monitoring
  resourceVersion: "561"
  selfLink: /api/v1/namespaces/monitoring/serviceaccounts/default
  uid: 8e7cd458-5a76-11ea-afea-6675893171b6
secrets:
- name: default-token-m7dxj

**Comment by rockb1017** [comment]
oh i am sorry, let me be correct myself. not only the service account, we need cluster role and that role to be bound to this service account. please refer here: https://github.com/splunk/splunk-connect-for-kubernetes/tree/develop/manifests/splunk-kubernetes-logging

**Comment by vinitmasaun** [comment]
> oh i am sorry, let me be correct myself. not only the service account, we need cluster role and that role to be bound to this service account. please refer here: https://github.com/splunk/splunk-connect-for-kubernetes/tree/develop/manifests/splunk-kubernetes-logging

I am deploying version 1.4.0 as is by downloading the 1.4.0 tgz file.  Do I need to add something extra in my values.yaml file to take care of the binding?  I see the clusterRole.yaml, ClusterRoleBinding.yaml and ServiceAccount.yaml files in the tgz, which I thought would take care of all this when I apply the chart.

**Comment by rockb1017** [comment]
by default, it should be taken care of automatically. Do you see cluster role created in your cluster?

**Comment by vinitmasaun** [comment]
> by default, it should be taken care of automatically. Do you see cluster role created in your cluster?

Below is the output of get clusterrole for my custom namespace (monitoring) where the splunk logging container is deployed.

kubectl get clusterrole -n monitoring
NAME                                                                   AGE
admin                                                                  3d20h
cluster-admin                                                          3d20h
edit                                                                   3d20h
kubernetes-dashboard                                                   3d20h
splunk-1-4-0-splunk-kubernetes-logging                                 3d20h
system:aggregate-to-admin                                              3d20h
system:aggregate-to-edit                                               3d20h
system:aggregate-to-view                                               3d20h
system:auth-delegator                                                  3d20h
system:aws-cloud-provider                                              3d20h
system:basic-user                                                      3d20h
system:certificates.k8s.io:certificatesigningrequests:nodeclient       3d20h
system:certificates.k8s.io:certificatesigningrequests:selfnodeclient   3d20h
system:controller:attachdetach-controller                              3d20h
system:controller:certificate-controller                               3d20h
system:controller:clusterrole-aggregation-controller                   3d20h
system:controller:cronjob-controller                                   3d20h
system:controller:daemon-set-controller                                3d20h
system:controller:deployment-controller                                3d20h
system:controller:disruption-controller                                3d20h
system:controller:endpoint-controller                                  3d20h
system:controller:expand-controller                                    3d20h
system:controller:generic-garbage-collector                            3d20h
system:controller:horizontal-pod-autoscaler                            3d20h
system:controller:job-controller                                       3d20h
system:controller:namespace-controller                                 3d20h
system:controller:node-controller                                      3d20h
system:controller:persistent-volume-binder                             3d20h
system:controller:pod-garbage-collector                                3d20h
system:controller:pv-protection-controller                             3d20h
system:controller:pvc-protection-controller                            3d20h
system:controller:replicaset-controller                                3d20h
system:controller:replication-controller                               3d20h
system:controller:resourcequota-controller                             3d20h
system:controller:route-controller                                     3d20h
system:controller:service-account-controller                           3d20h
system:controller:service-controller                                   3d20h
system:controller:statefulset-controller                               3d20h
system:controller:ttl-controller                                       3d20h
system:coredns                                                         3d20h
system:csi-external-attacher                                           3d20h
system:csi-external-provisioner                                        3d20h
system:discovery                                                       3d20h
system:heapster                                                        3d20h
system:kube-aggregator                                                 3d20h
system:kube-controller-manager                                         3d20h
system:kube-dns                                                        3d20h
system:kube-scheduler                                                  3d20h
system:kubelet-api-admin                                               3d20h
system:node                                                            3d20h
system:node-bootstrapper                                               3d20h
system:node-problem-detector                                           3d20h
system:node-proxier                                                    3d20h
system:persistent-volume-provisioner                                   3d20h
system:public-info-viewer                                              3d20h
system:volume-scheduler                                                3d20h
view                                                                   3d20h

**Comment by rockb1017** [comment]
how about cluster role binding?

**Comment by vinitmasaun** [comment]
> how about cluster role binding?

kubectl get clusterrolebinding -n monitoring
NAME                                                   AGE
cluster-admin                                          3d21h
kubeadm:kubelet-bootstrap                              3d21h
kubeadm:node-autoapprove-bootstrap                     3d21h
kubeadm:node-autoapprove-certificate-rotation          3d21h
kubeadm:node-proxier                                   3d21h
kubernetes-dashboard                                   3d21h
minikube-rbac                                          3d21h
splunk-1-4-0-splunk-kubernetes-logging                 3d21h
storage-provisioner                                    3d21h
system:aws-cloud-provider                              3d21h
system:basic-user                                      3d21h
system:controller:attachdetach-controller              3d21h
system:controller:certificate-controller               3d21h
system:controller:clusterrole-aggregation-controller   3d21h
system:controller:cronjob-controller                   3d21h
system:controller:daemon-set-controller                3d21h
system:controller:deployment-controller                3d21h
system:controller:disruption-controller                3d21h
system:controller:endpoint-controller                  3d21h
system:controller:expand-controller                    3d21h
system:controller:generic-garbage-collector            3d21h
system:controller:horizontal-pod-autoscaler            3d21h
system:controller:job-controller                       3d21h
system:controller:namespace-controller                 3d21h
system:controller:node-controller                      3d21h
system:controller:persistent-volume-binder             3d21h
system:controller:pod-garbage-collector                3d21h
system:controller:pv-protection-controller             3d21h
system:controller:pvc-protection-controller            3d21h
system:controller:replicaset-controller                3d21h
system:controller:replication-controller               3d21h
system:controller:resourcequota-controller             3d21h
system:controller:route-controller                     3d21h
system:controller:service-account-controller           3d21h
system:controller:service-controller                   3d21h
system:controller:statefulset-controller               3d21h
system:controller:ttl-controller                       3d21h
system:coredns                                         3d21h
system:discovery                                       3d21h
system:kube-controller-manager                         3d21h
system:kube-dns                                        3d21h
system:kube-scheduler                                  3d21h
system:node                                            3d21h
system:node-proxier                                    3d21h
system:public-info-viewer                              3d21h
system:volume-scheduler                                3d21h

**Comment by rockb1017** [comment]
I am noticing one thing. 
`serviceAccount` used in the logging daemonset should match the one that is created by this helm chart. 
`splunk-1-4-0-splunk-kubernetes-logging` is different from 
`release-name-splunk-kubernetes-logging`

**Comment by vinitmasaun** [comment]
> I am noticing one thing.
> `serviceAccount` used in the logging daemonset should match the one that is created by this helm chart.
> `splunk-1-4-0-splunk-kubernetes-logging` is different from
> `release-name-splunk-kubernetes-logging`

When I deployed the chart I passed in my own release name like below:

helm template \
  -n splunk-1-4-0 \
  --values ./values/values.yaml \
  --output-dir ./manifests ./charts/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging

**Comment by rockb1017** [comment]
i do not know why your release name didn't get rendered. you should be able to fix it by editing daemonset to use service account name that is created

**Comment by vinitmasaun** [comment]
> i do not know why your release name didn't get rendered. you should be able to fix it by editing daemonset to use service account name that is created

Even if I deploy it without passing in my own release name I get the same result.  The container goes into Crashloop with the same error in logs.  It only works if I deploy it to the default namespace.

**Comment by rockb1017** [comment]
which namespace did you deploy this to? 
`observability` or `monitoring`?

**Comment by rockb1017** [comment]
please make sure all resources are deployed in one namespace and the service account name matches in the daemonset
`kubectl edit daemonset -n NAMESPACE release-name-splunk-kubernetes-logging`

**Comment by vinitmasaun** [comment]
> which namespace did you deploy this to?
> `observability` or `monitoring`?

The namespace observability and monitoring are interchangeable.  I deployed it to monitoring namespace first and then blew away my cluster and started fresh with observability namespace.  I deployed to a single namespace in both cases.

**Comment by vinitmasaun** [comment]
> please make sure all resources are deployed in one namespace and the service account name matches in the daemonset
> `kubectl edit daemonset -n NAMESPACE release-name-splunk-kubernetes-logging`

  nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: release-name-splunk-kubernetes-logging
      serviceAccountName: release-name-splunk-kubernetes-logging
      terminationGracePeriodSeconds: 30
      tolerations:

**Comment by rockb1017** [comment]
so change `serviceAccount: release-name-splunk-kubernetes-logging
serviceAccountName: release-name-splunk-kubernetes-logging
` 
to actual service account created and right role assigned.

**Comment by vinitmasaun** [comment]
> so change `serviceAccount: release-name-splunk-kubernetes-logging serviceAccountName: release-name-splunk-kubernetes-logging `
> to actual service account created and right role assigned.

I just deployed with all defaults to the observability namespace:

kubectl apply --recursive --filename ./manifests -n observability
clusterrole.rbac.authorization.k8s.io/release-name-splunk-kubernetes-logging created
clusterrolebinding.rbac.authorization.k8s.io/release-name-splunk-kubernetes-logging created
configmap/release-name-splunk-kubernetes-logging created
daemonset.apps/release-name-splunk-kubernetes-logging created
secret/splunk-kubernetes-logging created
serviceaccount/release-name-splunk-kubernetes-logging created

kubectl edit daemonset -n observability release-name-splunk-kubernetes-logging
Edit cancelled, no changes made.
(py3) NY013JJLVCG:tmp vinit_masaun$ kubectl get pods -n observability
NAME                                           READY   STATUS             RESTARTS   AGE
release-name-splunk-kubernetes-logging-szm9m   0/1     CrashLoopBackOff   4          2m22s

**Comment by rockb1017** [comment]
`Edit cancelled, no changes made.` 
you didn't save any changes. 
please use `helm` to deploy. 
we don't support deploying with manifests. it is just reference

**Comment by vinitmasaun** [comment]
> `Edit cancelled, no changes made.`
> you didn't save any changes.
> please use `helm` to deploy.
> we don't support deploying with manifests. it is just reference

we cant use helm2 as it depends on tiller, which is not allowed by our security policy.  As far as I understand it, helm 3 is not supported to deploy this app.

**Comment by vinitmasaun** [comment]
> > `Edit cancelled, no changes made.`
> > you didn't save any changes.
> > please use `helm` to deploy.
> > we don't support deploying with manifests. it is just reference
> 
> we cant use helm2 as it depends on tiller, which is not allowed by our security policy. As far as I understand it, helm 3 is not supported to deploy this app.

> > you didn't save any changes. 
       I ran the helm template command before the kubectl apply command to generate the manifests with values.yaml

helm template --values  /tmp/values/values.yaml --output-dir /tmp/manifests /tmp/charts/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging

**Comment by rockb1017** [comment]
we don't officially support helm3 yet, but last time i used it, it works just as well.

**Comment by fshadid96** [comment]
@vinitmasaun were you able to resolve this issue? I am running into the same error

**Comment by vinitmasaun** [comment]
> @vinitmasaun were you able to resolve this issue? I am running into the same error

yes, I used helm3 install method, which resolved my issue.  According to the app developer, helm template and manifest method is not supported with version 1.4.0.

**Comment by fshadid96** [comment]
@vinitmasaun What version did you use? 1.3?

**Comment by vinitmasaun** [comment]
> @vinitmasaun What version did you use? 1.3?

1.4.0

**Comment by wannaknowmo** [comment]
@vinitmasaun  i have the same issue. can you copy paste the helm3 oneliner that you use ?

**Comment by wannaknowmo** [comment]
@vinitmasaun  nevermind i found it in the doc.
