### ISSUE TITLE
Filter journalctl logs with cluster_name

### ISSUE THREAD

**Issue by srikiz** [splunk/splunk-connect-for-kubernetes#339]
**What would you like to be added**:
I am able to filter container logs with cluster_name filter. But I don't find a way to filter all the docker daemon logs from a specific cluster.

**Why is this needed**:
When we have lot of clusters, we can only filter by hostname for journalctl logs. I am wondering if there is an easier way of adding cluster_name filtering to kubelet and docker daemon journalctl logs.

**Comment by rockb1017** [comment]
so you would like to not collect docker and kubelet daemon logs from certain cluster?

**Comment by rockb1017** [comment]
i am assuming you deployed SCK for each cluster, right?

**Comment by srikiz** [comment]
Yes, splunk is deployed in each cluster.
I don't see a problem with the container logs. They have cluster_name field
applied, and able to filter by cluster_name.
It is just that they don't get applied to journal logs.

**Comment by srikiz** [comment]
I would like to collect docker and kubelet daemon logs from all the clusters. The problem is filtering with cluster_name.
We currently have this for containers - https://github.com/splunk/splunk-connect-for-kubernetes/blob/d72982b843c0454a21f23aef1ba2b2f9108691db/manifests/splunk-kubernetes-logging/configMap.yaml#L258

I am wondering if we need to add something like this - https://github.com/splunk/splunk-connect-for-kubernetes/blob/d72982b843c0454a21f23aef1ba2b2f9108691db/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMap.yaml#L39
to journal.conf here https://github.com/splunk/splunk-connect-for-kubernetes/blob/d72982b843c0454a21f23aef1ba2b2f9108691db/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L144?

**Comment by srikiz** [comment]
Just realized I was using 1.2 version and the fix is available in the latest 1.4 version. I think this is good to be closed.
