### ISSUE TITLE
No metrics for pods with short duration

### ISSUE THREAD

**Issue by a-l-h** [splunk/splunk-connect-for-kubernetes#341]
We are relying on pods metrics (memory & cpu request among others) to do billing calculations.

We have noticed that metrics were missing (in Splunk) for pods with short duration (max 10s, avg 5s).

We have also noticed that these metrics could be present for pods with a duration as short as 2s.

Is there anything to adjust to make sure metrics from all pods are being gathered?

Thanks in advance!

**Comment by matthewmodestino** [comment]
hi! the metrics configmap allows setting the scrape interval. I believe we default to 15s, so if you live and die in less, we may not see you.

You can use the kubernetes events data to ensure you always know about a pod in splunk, or you can reduce the collection interval. Also 

Likely a good use case for you to have a look at some of our newest products that leverage signalfx if you are getting down to 1s resolutions.

**Comment by matthewmodestino** [comment]
any luck @d2si-spk ?

**Comment by d2si-spk** [comment]
Hello @matthewmodestino !

Thanks a lot for the feedback!

Do you mean we can edit this part below?

_manifests/splunk-kubernetes-metrics/configMap.yaml & configMapMetricsAggregator.yaml_

data:
  fluent.conf: |
    # system wide configurations
    <system>
      log_level info
    </system>
    <source>
      @type kubernetes_metrics
      tag kube.*
      node_name "#{ENV['NODE_NAME']}"
      use_rest_client_ssl true
      cluster_name cluster_name
      interval **15s**
    </source>

Sorry I did the Splunk side here, so not familiar with the EKS side.

**Comment by rockb1017** [comment]
Yes.
it seems it is a something that can be fixed using right configuration. I will close this.
