### ISSUE TITLE
Not able to enable/disable pods creation based on flags in values.yaml

### ISSUE THREAD

**Issue by vinitmasaun** [splunk/splunk-connect-for-kubernetes#342]
**What happened**:
Using version 1.4.0 the enable: false/true flag in values.yaml doesn't have any effect on whether a logging, metrics, or objects container gets created.
**What you expected to happen**:
Control which container gets created based on the enabled flag set in values.yaml
**How to reproduce it (as minimally and precisely as possible)**:
Set the below flags at the top of values.yaml (this worked in version 1.3.0)
logging:
  enabled: true
objects:
  enabled: false
metrics:
  enabled: false

**Anything else we need to know?**:
As part of my troubleshooting I compared the requirements.yaml files of version 1.3.0 and 1.4.0 and noticed that the condition name has changed to the below in 1.4.0:
condition: splunk-kubernetes-logging.enabled
condition: splunk-kubernetes-objects.enabled
condition: splunk-kubernetes-metrics.enabled

I changed my values.yaml flags to match the above as below, which had no affect.  All containers including the ones set to false still got created:
splunk-kubernetes-logging:
                    enabled: true
splunk-kubernetes-objects:
                    enabled: false
splunk-kubernetes-metrics:
                    enabled: false
**Environment**:
dev
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:04Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
- Ruby version (use `ruby --version`):
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
- OS (e.g: `cat /etc/os-release`):
macOS mojave
- Splunk version:
8.0.1
- Others:

**Comment by vinitmasaun** [comment]
I solved my own problem by further troubleshooting. Basically, the enabled flag in version 1.4.0 now needs to be defined in the respective local config section in the values.yaml file rather than at the top in version 1.3.0

**Comment by holmesb** [comment]
Hi @vinitmasaun, are you able to clarify how you disabled objects and metrics if not by:
splunk-kubernetes-object.enabled = false
splunk-kubernetes-metrics.enabled = false
?  Are you able to give the correct values to change in the "local config section"?

In any case, this is not intuitive.  Not a closed issue.
