### ISSUE TITLE
Add our firelens example to AWS Firelens examples docs

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-connect-for-kubernetes#344]
<

**What would you like to be added**:

We need to make a PR to this repo https://github.com/aws-samples/amazon-ecs-firelens-examples to be listed with examples for customers

**Why is this needed**:

ease of use to get started when customers try firelens

**Comment by PettitWesley** [comment]
Ping. Please do this.

Sincerely,

Wesley, The FireLens Guy

**Comment by PettitWesley** [comment]
Please don't forget about FireLens 😢

**Comment by PettitWesley** [comment]
🙏

**Comment by PettitWesley** [comment]
why tho 😥
