### ISSUE TITLE
Multiple LogLevel 

### ISSUE THREAD

**Issue by fshadid96** [splunk/splunk-connect-for-kubernetes#347]
**What happened**:
I tried to add multiple log level as the following,
  

> logLevel:
      - info
      - debug
      - trace
      - warn
      - error

 but all the containers crashed and I got > CrashLoopBackOff 
and in the logs I got `22 lines
bundler: failed to load command: fluentd (/usr/bin/fluentd)
Fluent::ConfigParseError: got incomplete JSON array configuration at fluent.conf line 60,9
 59:   </buffer>
 60: </match>`

**What you expected to happen**:
I thought it would collect multiple logs level

**How to reproduce it (as minimally and precisely as possible)**:
Try to pass multiple loglevel as I did above 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
clientVersion:
  buildDate: "1970-01-01T00:00:00Z"
  compiler: gc
  gitCommit: $Format:%H$
  gitTreeState: ""
  gitVersion: v0.0.0-master+$Format:%h$
  goVersion: go1.12.12
  major: ""
  minor: ""
  platform: linux/amd64
serverVersion:
  buildDate: "2020-02-03T23:11:39Z"
  compiler: gc
  gitCommit: 94e669a
  gitTreeState: clean
  gitVersion: v1.16.2
  goVersion: go1.12.12
  major: "1"
  minor: 16+
  platform: linux/amd64

- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`): "Red Hat Enterprise Linux Server 7.7 (Maipo)
- Splunk version: 7.6 
- Others:

**Comment by fshadid96** [comment]
logLevel has the proper indentation, I just couldn't figure out how to indent here

**Comment by matthewmodestino** [comment]
i dont believe you can add multiple....just pick one and set it...
