### ISSUE TITLE
how to disable metrics

### ISSUE THREAD

**Issue by MarcoSchaar** [splunk/splunk-connect-for-kubernetes#35]
Hi,
how to deal with [those values](https://github.com/splunk/splunk-connect-for-kubernetes/blob/master/helm-chart/splunk-connect-for-kubernetes/values.yaml)?

When `false` is set in a custom yaml file, e.g. metrics is deployed anyways.

**Comment by matthewmodestino** [comment]
Hi Marco!

Can you please share more details on how exactly you are deploying?

Are you passing a values file to helm? Or deploying the manifests manually?

Please share your yaml and I can try and re-create.

**Comment by runesl** [comment]
Workaround: checkout master source from github, and run make, which will update your local helm repo with a version that supports disabling metrics.

**Comment by dbaldwin-splunk** [comment]
@dtregonning @chaitanyaphalak Can we add a test case in the metrics beta push coming out to address disabling metrics?

**Comment by dontregonning** [comment]
> @dtregonning @chaitanyaphalak Can we add a test case in the metrics beta push coming out to address disabling metrics?

We'll ensure that we have the ability to disable metrics in the new Metrics Beta

**Comment by chaitanyaphalak** [comment]
Addressed in SCK 1.1

**Comment by lufermalgo** [comment]
Hi community,

Thank you for your contributions.

With regard to this issue I am also requiring NOT to collect metrics. Try to disable it based on its indications, however, the metric pods were deployed, these are still collected.

modify the _values.yaml_ file located in the root of _splunk-connect-for-kubernetes_

`## Enabling metrics will install the `splunk-kubernetes-metrics` chart to a kubernetes
## cluster to collect metrics of the cluster to a Splunk indexer/indexer cluster.
metrics:
  enabled: false`

**script**

`export MONITORING_MACHINE=xxx.xxx.xxx.37 && export HEC_TOKEN=6919634d-cb76-4cbd-aef6-55ecdec855ee && export HEC_PORT=8088 && export GLOBAL_HEC_INSECURE_SSL=true && export OBJECTS_INSECURE_SSL=true && export METRICS_INSECURE_SSL=true && export JOURNALD_PATH=/var/log/journal && export SAI_SCK_PROJECT=splunk-connect && export KUBELET_PROTOCOL=https && export METRICS_INDEX=idx_em_metrics_sa && export LOG_INDEX=idx_em_logs_sa && export META_INDEX=idx_em_meta_sa && export CLUSTER_NAME=xxx.xxx.xxx.com && export SCK_DOWNLOAD_ONLY=false && export CORE_OBJ=pods,nodes && export APPS_OBJ= && wget --no-check-certificate http://xxx.xxx.xxx.38:8000/en-US/static/app/splunk_app_infrastructure/openshift_connect/splunk-connect-for-kubernetes-1.2.0.tgz -O splunk-connect-for-kubernetes.tgz && files=("openshift_connect_template.yaml" "deploy_sck_openshift.sh") && for each in "${files[@]}"; do wget -O- --no-check-certificate http://xxx.xxx.xxx.38:8000/en-US/static/app/splunk_app_infrastructure/openshift_connect/"$each" > $each; done && bash deploy_sck_openshift.sh`

Thanks your support

**Comment by rockb1017** [comment]
values.yaml files has default options for the helm chart. for above SAI deployment, it creates a actual yaml file in your directory and use that instead of what is specified in values.yaml. please check the folder where have executed above command. ("kubernetes_connect.yaml")
