### ISSUE TITLE
Use helm versioning properly

### ISSUE THREAD

**Issue by holmesb** [splunk/splunk-connect-for-kubernetes#355]
Following on from [the repo issue](https://github.com/splunk/splunk-connect-for-kubernetes/issues/9), please can we start using helm chart versioning properly?  In other words, bump it in Chart.yaml after every chart change.  This is how charts are managed in the default [stable repo](https://github.com/helm/charts/tree/master/stable).  That way, a `helm repo update` won't cause a mysterious change that could break stuff.  Version pinning is a good thing.

**Comment by chaitanyaphalak** [comment]
@holmesb thats a nice catch, we would love to review a pull request for the same.

**Comment by holmesb** [comment]
This issue doesn't need a PR, it needs a change to every new chart PR.

**Comment by rockb1017** [comment]
Thank you for pointing this out. Whenever we release changes, we will make sure to increate chart version. (branch `main`). new changes will continue to be merged to develop branch without incrementing chart version though.

**Comment by holmesb** [comment]
> "new changes will continue to be merged to develop branch without incrementing chart version"

That means I could install a breaking change without knowing.  This issue is still open.  Doesn't need to be every change to this entire repo, just the respective chart.

**Comment by rockb1017** [comment]
i will reply to the new issue you created https://github.com/splunk/splunk-connect-for-kubernetes/issues/486
