### ISSUE TITLE
Broken link in values.yaml

### ISSUE THREAD

**Issue by holmesb** [splunk/splunk-connect-for-kubernetes#360]
[values.yaml](https://github.com/splunk/splunk-connect-for-kubernetes/blob/20e67c6f2dcf4d06f6efc7cc6763126946a6956f/helm-chart/splunk-connect-for-kubernetes/values.yaml#L431) refers to a broken link: http://dev.splunk.com/view/event-collector/SP-CAAAFB6

Please could someone post the correct one to this issue?

**Comment by matthewmodestino** [comment]
Hey, probably should point here https://dev.splunk.com/enterprise/docs/dataapps/httpeventcollector

**Comment by gliptak** [comment]
@holmesb this was updated via https://github.com/splunk/splunk-connect-for-kubernetes/commit/ddba2d21dc5c6af87243fd71b51d5afec963bff4

**Comment by rockb1017** [comment]
Thank you!
