### ISSUE TITLE
kubernetes entities data should come predefined with the entity_type dimension to be compatible with SAI & ITSI out of the box

### ISSUE THREAD

**Issue by trumpdeck** [splunk/splunk-connect-for-kubernetes#364]
<

**What would you like to be added**:
Currently, the data collected with default configurations are not compatible with SAI and ITSI integration in splunk.

If you look at the SAI simple setup script, they add dimensions to the data (entity_type), that allow the SAI app to identify the data as kubernetes containers and do automatic entity discovery.

Can the splunk-connect-for-kubernetes default ingestion include those dimensions ?

**Why is this needed**:
For compatibility with Splunk App for Infrastructure, and ITSI integration.
https://docs.splunk.com/Documentation/InfraApp/2.0.3/Admin/AddDataKubernetes

Questions : reach @matthewmodestino  for details.

**Comment by sudoritz** [comment]
I would like this as well to make it as the default. as i believe this provides useful views.

**Comment by matthewmodestino** [comment]
i agree. adding the entity_type as a helm value tied to whether openshift is true or not, would be trivial. Currently App for Infra install script uses sed command to insert into rendered metrics daemonset configmap. I have asked the team to PR it.

**Comment by matthewmodestino** [comment]
i will try and get a PR started for this....tired of editing it by hand 🖐

**Comment by matthewmodestino** [comment]
update...i published customized charts here:

https://mattymo.io/code/mattymo/splunk_toronto_usergroup_may_2020#mattymo-sauce

the process I used was:

- clone git repo
- edit metric configmaps to manually add the sed command that app for infrastructure easy script uses (see /appserver/static/kubernetes_connect/)
- make build
- tar up charts
- use these when i deploy

@rockb1017 can we chat about putting this one to bed?

**Comment by rockb1017** [comment]
Hello, 

I am releasing SCK 1.4.3 where you can insert multiline custom filters.
Here is example for SAI script
```
  customFilters:
    node:
      tag: "kube.node.**"
      type: record_modifier
      body: |-
        <record>
          entity_type k8s_node_ocp
        </record>
    pod:
      tag: "kube.pod.**"
      type: record_modifier
      body: |-
        <record>
          entity_type k8s_pod_ocp
        </record>
```

**Comment by matthewmodestino** [comment]
Above is for OpenShift, This one is for OSS K8s:

```
 customFilters:
    node:
      tag: "kube.node.**"
      type: record_modifier
      body: |-
        <record>
          entity_type k8s_node
        </record>
    pod:
      tag: "kube.pod.**"
      type: record_modifier
      body: |-
        <record>
          entity_type k8s_pod
        </record>
