### ISSUE TITLE
log pod name matching

### ISSUE THREAD

**Issue by brianp9906** [splunk/splunk-connect-for-kubernetes#366]
Hello,
I have setup some custom settings for a deployment set of pods and I'm trying to match on pod name for custom sourcetype and multiline regex. I verified my regex on rubular.com for multiline, but I noticed after doing:
helm upgrade sck-14 -f kubernetes_connect.yaml ./splunk-connect-for-kubernetes --recreate-pods

That the custom log sourcetype and multiline isnt getting matched.  I looked at the logs of the sck logging pod to see and it looks correct to me. 

`2020-04-09 20:17:23 +0000 [info]: adding filter in @SPLUNK pattern="tail.containers.var.log.containers.app1-test*app1-test*.log" type="concat"
`
`    <filter tail.containers.var.log.containers.app1-test*app1-test*.log>
      @type concat
      key "log"
      timeout_label "@SPLUNK"
      stream_identity_key "stream"
      multiline_start_regexp "/^\\[\\d{4}-\\d{2}-\\d{2}\\s+\\d{2}:\\d{2}:\\d{2}\\.\\d{3}\\]/"
      flush_interval 5s
      separator ""
      use_first_timestamp true
    </filter>
`

Any idea why its not picking it up?

I found what might be the error related from the sck logging pod:

`2020-04-09 21:14:48 +0000 [warn]: #0 dump an error event: error_class=ThreadError error="deadlock; recursive locking" location="/usr/share/gems/gems/fluent-plugin-concat-2.4.0/lib/fluent/plugin/filter_concat.rb:189:in `synchronize'" tag="tail.containers.var.log.containers.app1-test-deployment-699dc994fc-trzcr_nonprodspace_app1-test-858fbb0ab0e3d67dd35ae3204e15e7880c93c50cc26b58e8d2ae0445e7aea1d8.log" time=2020-04-09 21:14:42.774752405 +0000 record={"stream"=>"stdout", "log"=>"[2020-04-09 13:14:42.774] [ERROR] app-test1 - ldap server error { inspect: [Function: inspect] }", "source"=>"/var/log/containers/app1-test-deployment-699dc994fc-trzcr_nonprodspace_app1-test-858fbb0ab0e3d67dd35ae3204e15e7880c93c50cc26b58e8d2ae0445e7aea1d8.log"}`

**Comment by matthewmodestino** [comment]
https://github.com/splunk/splunk-connect-for-kubernetes/issues/358

its related to this. I am starting an MR this afternoon. otherwise you can try the above.

**Comment by brianp9906** [comment]
Your workaround seems to work for me in terms of multiline log support.  I put a defined sourcetype but that doesnt seem to be catching for both nginx and our app.  Any idea?   (the sourcetype wasnt working before either)
Is the "pod" name definition in my yaml file a regex partial match?  My pod is environment1-nginx but I'm hoping to match all types of nginx pods.

`  logs:
    nginx:
      from:
        pod: nginx
      sourcetype: access_combined
    app1-test:
      from:
        pod: app1-test
      multiline:
        firstline: /^\[\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}/
      sourcetype: app_log
`

**Comment by matthewmodestino** [comment]
what does the rule render to in the configmap?

**Comment by brianp9906** [comment]
There is no sourcetype mentioned in the configmap for the filter tail podname. I see the multiline and separator.  I'm guessing thats where it should be.  I'll look at the files you have more closely to see if I've maybe put it in the wrong location.

**Comment by brianp9906** [comment]
I found that this file was forcing a "kube:" prefix on annotations so I worked around the problem by annotating my pods/deployments with the splunk.com/sourcetype and changing the configmap.yaml file.

Wrong (from SCK 1.4 release):
`sourcetype ${record.dig("kubernetes", "annotations", "splunk.com/sourcetype") ? "kube:" + record.dig("kubernetes", "annotations", "splunk.com/sourcetype") : "kube:container:"+record.dig("kubernetes","container_name")}`

My manual correction:
`sourcetype ${record.dig("kubernetes", "annotations", "splunk.com/sourcetype") ? record.dig("kubernetes", "annotations", "splunk.com/sourcetype") : "kube:container:"+record.dig("kubernetes","container_name")}`

I'm not sure this is the correct way to go about it, but it works. 
The kubenetes_connect.yaml I feed in the helm command doesnt sourcetype properly using something like this:
  logs:
    nginx:
      from:
        pod: nginx
      sourcetype: access_combined
