### ISSUE TITLE
Connection Refused Log error parses HEC port incorrectly, can be misleading

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-connect-for-kubernetes#371]
**What happened**:

While troubleshooting a connection issue to HEC, we found this error:

2020-04-17 12:08:50 +0000 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2020-04-17 12:08:51 +0000 chunk="foo" error_class=Net::HTTP::Persistent::Error error="connection refused: 10.10.10.10:80" due to a down HEC endpoint. 

**What you expected to happen**:

This error led to debugging why the collector was sending to port 80. It was not. It was correctly configured on 8088, so I am thinking this is a bug in the error parsing. The issue was on the far side, but this error made debugging harder. 

**How to reproduce it (as minimally and precisely as possible)**:

Set up a fluentd-hec instance and send to 8088 on a host that doesnt have the port open or is down. 

**Anything else we need to know?**:

Shout out to @runyontr who was made to be the groundskeeper chasing the goose for a while. Thanks for reaching out on Slack!

I had seen this before but forgot to log this. I wish to not allow others to suffer the same scar. :)

**Environment**:
- Kubernetes version (use `kubectl version`):
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:
- Others:

**Comment by williamcodes** [comment]
I got burned by this today

**Comment by cheneysplunk** [comment]
Found similar issue in https://github.com/splunk/fluent-plugin-splunk-hec/issues/184.

Filed a ticket for further investigation. https://jira.splunk.com/browse/ADDON-42388

**Comment by gmcbrien** [comment]
Same issue here. Anyone know if this bug will be fixed any time soon? (It seems I can't open the jira link).
