### ISSUE TITLE
ASCII art breaks ansible

### ISSUE THREAD

**Issue by dza89** [splunk/splunk-connect-for-kubernetes#374]
**What happened**:
We tried to deploy the helm chart with ansible operator.

**What you expected to happen**:
A deployed helm chart

**How to reproduce it (as minimally and precisely as possible)**:
Deploy the helm chart, but with ansible (operator)

**Anything else we need to know?**:
The ASCII art breaks the ansible flow. I would like to request to remove the ASCII art in NOTES.txt.

I'm willing to make the MR, but not without approval, as I have to do it five times. :)

**Comment by matthewmodestino** [comment]
lil project is growin up!  😢 😝 

yeah lets bring the logs up to a business casual, maybe at least a splunk polo on it. 

would be cool to replace it with a simple tag line like Enterprise has when it starts. simple and clean. ..

**Comment by matthewmodestino** [comment]
```[splunk@splunk-splunk-cluster-master-0 bin]$ ./splunk restart
Stopping splunkd...
Shutting down.  Please wait, as this may take a few minutes.
.............
Stopping splunk helpers...

Done.

Splunk> The IT Search Engine.

```

**Comment by dza89** [comment]
https://github.com/splunk/splunk-connect-for-kubernetes/pull/375

**Comment by dza89** [comment]
I've removed the PR, since Ansible Operator with python3 it does work, only looks messy.

```None\nNOTES:\n███████╗██████╗ ██╗     ██╗   ██╗███╗   ██╗██╗  ██╗██╗    \n██╔════╝██╔══██╗██║     ██║   ██║████╗  ██║██║ ██╔╝╚██╗   \n███████╗██████╔╝██║     ██║   ██║██╔██╗ ██║█████╔╝  ╚██╗  \n╚════██║██╔═══╝ ██║     ██║   ██║██║╚██╗██║██╔═██╗  ██╔╝  \n███████║██║     ███████╗╚██████╔╝██║ ╚████║██║  ██╗██╔╝\n╚══════╝╚═╝     ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝\n\nListen to your 
```
