### ISSUE TITLE
kube:objects:nodes frequently gets truncated in Splunk

### ISSUE THREAD

**Issue by jeffwiedemann** [splunk/splunk-connect-for-kubernetes#377]
**What happened**: In some environments, such as the one I'm working in at my customer, I see that events into the sourcetype: kube:objects:nodes are truncated. Default limit of 10k probably isn't big enough and customer will need to update props/transforms. Need to consider a more sane default so customers don't have to do it themselves 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:
- Others:

**Comment by matthewmodestino** [comment]
This will have to be configured on Splunk side of the pipeline but it worth capturing here, as we could build objects sourcetype guidance.

**Comment by skirven4** [comment]
@matthewmodestino  - I'm struggling with trying to concat lines at the HF. What's odd is that it seems to work fine in the Add Data section, but doesn't seem to work in practice on the HEC  endpoint?? If I need to post an issue, please advise. Thanks!

[kube:container:gps-courier]
SHOULD_LINEMERGE=true
LINE_BREAKER=log_level
TRUNCATE=30000
BREAK_ONLY_BEFORE=log_level

**Comment by matthewmodestino** [comment]
You cannot line break at HF! You must do it in Connect for Kubernetes pod.

What exactly are you trying to line break?
