### ISSUE TITLE
Fluentd log delay on specific type of messages

### ISSUE THREAD

**Issue by dengalebr** [splunk/splunk-connect-for-kubernetes#379]
**What happened**:
Hello Team,

We are getting strage issues where only specific type of messages are getting delayed by substantial amount of time like 30+ minutes.

 Those messages are coming out of application only so looks like fluentd getting some issue processing these kinds of messages as its not correctly formed JSON. But eventually these events reach splunk.

The event looks like 

2020-04-22 14:02:14.463109036 +0000 UTC m=+1830615.559689447 write error: Write timeout "{\"level\":\"info\",\"ts\":\"2020-04-22T14:02:14.463Z\",\"msg\":\"Health: Retrying the health for the dependency hsmwrapper in case of error.\",\"hostname\":\"ovk8hsmwrap-dev-epic-25-7-sy4io-58fcd958d-7jrqj\",\"pid\":\"1\",\"app\":\"HSM_Wrapper\",\"version\":\"v0.1\"}\n"

**What you expected to happen**:
We expect these events to reach Splunk on acceptable time like other events. we have validated no pressure on resources during the same time.

Anything else we need to know?:

Environment:

    Kubernetes version (use kubectl version):v1.14.8
    Ruby version (use ruby --version):
    OS (e.g: cat /etc/os-release): CentOS 7.7
    Splunk version: 7.x
    Others:

**Comment by matthewmodestino** [comment]
Hey @dengalebr, 

Do these events have any filters applied? A write timeout is interesting...how big is the event?

**Comment by dengalebr** [comment]
Hey Matt,

we have only one additional filter which is concat for multi line, but this is no different than other events.

The event  is just like above, Application continuously printing similar events but those are without write timeout and no issues for those.

Problematic event:
-------------------------------------
2020-04-22 14:02:14.463109036 +0000 UTC m=+1830615.559689447 write error: Write timeout "{"level":"info","ts":"2020-04-22T14:02:14.463Z","msg":"Health: Retrying the health for the dependency hsmwrapper in case of error.","hostname":"ovk8hsmwrap-dev-epic-25-7-sy4io-58fcd958d-7jrqj","pid":"1","app":"HSM_Wrapper","version":"v0.1"}\n"
---------------------------------------

Working event:
----------------------------------------
{"level":"info","ts":"2020-05-02T14:51:26.679Z","msg":"Health: Retrying the health for the dependency hsmwrapper in case of error.","hostname":"ovk8hsmwrap-dev-epic-25-7-sy4io-58fcd958d-42hx5","pid":"1","app":"HSM_Wrapper","version":"v0.1"}
----------------------------------------

I think there are few exceptions happening within fluentd output, Most of the other delayed messages as well some similar pattern.

Any idea, how we can drill further?

Regards,
Bala

**Comment by matthewmodestino** [comment]
Yes I would be drilling into the fluentd pod logs for the node this app is on and looking for any errors  in concat or processing that would cause it to be dropped.

**Comment by dengalebr** [comment]
Hey Matt,
This is the issue as I dont see any warning / error in fluentd pod, I see similar pattern with few other messages as well. Question is if its getting dropped how come eventually sent after 30/45 minutes? why only that event take long and event before / after reach on time.

**Comment by matthewmodestino** [comment]
Hey Bala, Its not being dropped, sounds like its either stuck in buffer or concat, etc/

**Comment by matthewmodestino** [comment]
hey Bala, I have a hunch. I think its because of retry timer and exponential back off. will ping you to explain.

**Comment by matthewmodestino** [comment]
Hey Bala, one more find for you that may explain any remaining delays. Can you please update your concat filters to use `flush_interval 2` NOT `flush_interval 2s`

https://github.com/splunk/splunk-connect-for-kubernetes/issues/385#issuecomment-629888443

**Comment by dengalebr** [comment]
Ahhhh, Let me try this. I will keep you posted

**Comment by rockb1017** [comment]
@dengalebr Hello, were you able to resolve it?

**Comment by dengalebr** [comment]
@rockb1017 we reduced the delay with fluentd flush interval 2, but we could not resolved it completely.

We still see events delayed by hours during high traffic. In our environments we have spikes of 50k events/Sec from few applications, so delay is still ongoing issue for us. 

We are working with @matthewmodestino for this challenge.

**Comment by rockb1017** [comment]
oh. thanks for the update. 
on the cases of that much load, delay is due to throughput limit of fluentd. Fluentd is known to hit the ceiling around 3k eps. @matthewmodestino has a Universal Forwarder solution that can handle much better throughput.

**Comment by dengalebr** [comment]
Is there any docs which can be referred for limitations around 3k EPS? Fluentd limits are much higher and we do not have consistent load like this, this happen mostly 2/3 times in hour.

We know we are hitting limits but exploring how efficiently we process the buffer fine tuning.

**Comment by matthewmodestino** [comment]
https://docs.fluentd.org/deployment/performance-tuning-single-process

The exact eps depends on many factors, mostly filtering etc. 

We are looking at options to make UF more k8s friendly at the node agent level for instances like this where the logging velocity is so high that you need a real deal enterprise grade collector ;)

**Comment by dengalebr** [comment]
Thanks Matt.

We are looking forward for UF.

What should be recommendations for multi-worker and thread count when volume grows in fluentd. It's good to get the standards for those fluentd settings. Also they way you published buffer parameters what should be max CPU and Memory resources we should keep. Fluentd pod always on high CPU and Memory.

**Comment by matthewmodestino** [comment]
Hey Bala! We have not recommended multi-proc at all as we did not see much benefit or improvement.

Generally, sharing has been easier and more successful.

The fluentd pod can only use one core, so we suggest you give it to it, and usually on a loaded cluster I see about 1GB of Mem...

Hard to say exactly is best, as clusters differ, but Id recommend 1 core and 1GB of ram.

What are you seeing for usage?

**Comment by matthewmodestino** [comment]
Hey @dengalebr have you see the OTel log engine numbers? 

https://github.com/signalfx/splunk-otel-collector-chart/blob/main/docs/advanced-configuration.md#performance-of-native-opentelemetry-logs-collection

Would suggest checking this out!

**Comment by foram-splunk** [comment]
Hey @dengalebr , any updates on this ?

**Comment by foram-splunk** [comment]
Closing this issue . Feel free to re-open it ,if you face the same issue again .
