### ISSUE TITLE
splunk-connect-for-kubernetes-1.4.1 does not run on OpenShift with provided values file

### ISSUE THREAD

**Issue by crdnb** [splunk/splunk-connect-for-kubernetes#380]
**What happened**:
splunk-connect-for-kubernetes-1.4.1 does not run on OpenShift with provided values file (https://github.com/splunk/splunk-connect-for-kubernetes/blob/master/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml).

The pods do not start with error:
`Error creating: pods "splunk-connect-for-kubernetes-splunk-kubernetes-logging-" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000300000, 1000309999] spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]`

When installing splunk-connect-for-kubernetes-1.4.1 with the values file from the release before (1.4.0) it runs and the pods start without en error.

**What you expected to happen**: 
 splunk-connect-for-kubernetes-1.4.1 should run with provided values file for release 1.4.1.

**How to reproduce it (as minimally and precisely as possible)**:
` helm install splunk-connect-for-kubernetes --values values-1.4.0.yaml splunk-connect-for-kubernetes-1.4.1.tgz` --> works

`helm install splunk-connect-for-kubernetes --values values-1.4.1.yaml splunk-connect-for-kubernetes-1.4.1.tgz` --> does not work

**Anything else we need to know?**:
What keys were removed/added in values file between release 1.4.0 and 1.4.1?

**Environment**:
- oc v3.11.146
- kubernetes v1.11.0+d4cacc0
- openshift v3.11.188
- Splunk version: splunk-connect-for-kubernetes-1.4.1.tgz

**Comment by crdnb** [comment]
I specified "splunk-kubernetes-logging" as the serviceaccount name in values file and the serviceaccount name found in the generated daemonset is "splunk-connect-for-kubernetes-splunk-kubernetes-logging"

**Comment by crdnb** [comment]
The three sections are missing in the values files:
- splunk-kubernetes-logging
- splunk-kubernetes-objects
- splunk-kubernetes-metrics
So SCK ignores the configuration in values.yaml and applies default configuration.

**Comment by rockb1017** [comment]
could you send me value-1.4.1.yaml file? how did you generate this file?

**Comment by crdnb** [comment]
Hi @rockb1017 
It's exactly this file: https://github.com/splunk/splunk-connect-for-kubernetes/blob/master/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml

The section keys are missing, so the values file is not valid:
splunk-kubernetes-logging
splunk-kubernetes-objects
splunk-kubernetes-metrics

**Comment by rockb1017** [comment]
that is value file for the subchart. you should use this one. https://github.com/splunk/splunk-connect-for-kubernetes/blob/master/helm-chart/splunk-connect-for-kubernetes/values.yaml

**Comment by crdnb** [comment]
@rockb1017 Thank you for the hint! I did not see this values file, because I followed the instructions on the README. Probably it would be good to have it mentioned there.
Thank you very much

**Comment by rockb1017** [comment]
i am glad it now works! closing
