### ISSUE TITLE
Metric pods are not setting a sourcetype

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-connect-for-kubernetes#381]
**What happened**:

Kubernetes Metrics pods do not set a sourcetype. 

**What you expected to happen**:

We should be setting a sourcetype. 

**How to reproduce it (as minimally and precisely as possible)**:

deploy SCK metrics chart and examine metric payload

![image](https://user-images.githubusercontent.com/31549209/80867160-9acb8680-8c60-11ea-9c2b-b85741149f9d.png)

**Anything else we need to know?**:

This is likely best fixed in a rfull eview of field names we are senfing as the field names are not cleanly normalized to ensure they match across metric types 

**Environment**:
- Kubernetes version (use `kubectl version`):

1.18

- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
Ubuntu 18.04
- Splunk version:
8.0.3
- Others:
DSP 1.1 pictured above

**Comment by harshit-splunk** [comment]
Hey @matthewmodestino, I have drafted a [PR](https://github.com/splunk/splunk-connect-for-kubernetes/pull/684), do you think it's a good idea to keep plugin name as sourcetype and tag as source in both metric and metric-aggr plugin?

**Comment by matthewmodestino** [comment]
Do you have an example of how those fields end up looking using plugin name?

Keeping it simple is probably best. As of now all metrics come in as "httpevent", the default when no sourcetype is set. Simply providing a sourcetype that allows  a user to filter down to "kube:metrics" or "kube:metrics:agg" is enough. Don't want it to be too granular.

https://docs.splunk.com/Documentation/Splunk/8.2.3/Data/Whysourcetypesmatter

**Comment by harshit-splunk** [comment]
@matthewmodestino Thanks for quick reply.
Source will look like `sck-splunk-kubernetes-metrics` and `sck-splunk-kubernetes-metrics-aggregator` in splunk.
`kube:metrics` or `kube:metrics:agg` is better option IMO
Thanks

**Comment by matthewmodestino** [comment]
Yeah I would keep in inline with the other sourcetypes SCK sends which already use the "kube:container:*" or "kube:objects:*". This format is also inline with other Splunk addon sourcetype naming conventions.
