### ISSUE TITLE
Allow kubeletPort to be set separately for metrics and metrics-agg

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-connect-for-kubernetes#384]
<

**What would you like to be added**:

I would like to be able to set the kubelet port for metrics and metrics-agg separately in the helm deploy, similar to how the buffers are handled. 

https://github.com/splunk/splunk-connect-for-kubernetes/blob/ddba2d21dc5c6af87243fd71b51d5afec963bff4/helm-chart/splunk-connect-for-kubernetes/values.yaml#L867

**Why is this needed**:

MicroK8s serves the kubelet metrics on 10255 but the agg metrics on the 10250. I'd imagine it is possible to see this in other k8s distros as well. Today i workaround this by editing the rendered helm charts directly

**Comment by chaitanyaphalak** [comment]
Why isnt 10250 working for you for metrics? Is it because of self signed certificates?

**Comment by matthewmodestino** [comment]
Not sure i get 400 bad request, I can show ya later today if you are free

On May 8, 2020, at 13:42, Chaitanya Phalak <notifications@github.com> wrote:

﻿[ External sender. Exercise caution. ]


Why isnt 10250 working for you for metrics? Is it because of self signed certificates?

**Comment by chaitanyaphalak** [comment]
Fixed as part of https://github.com/splunk/splunk-connect-for-kubernetes/pull/395
