### ISSUE TITLE
[RFC] Should we re-consider the default "collect all" configuration?

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-connect-for-kubernetes#387]
<

**What would you like to be added**:

Wanted to track some discussion from the community, that has come up for me in the field,  about whether the default "collect all" is a sane default as more users adopt the solution. 

**Why is this needed**:

We want to protect users from melting their cluster/fluentd by deploying to a very busy environment with many historical logs. And perhaps encourage more thoughtful onboard and review of over all throughput goal and strategies for scale. 

our input could also look at adding things like `limit_recently_modified` to limit historic files. 

https://github.com/splunk/splunk-connect-for-kubernetes/blob/ddba2d21dc5c6af87243fd71b51d5afec963bff4/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L11-L20

I like the guidance the Splunk-Operator team gave, where you deploy as a Developer in namespace scope vs Admin at Cluster Scope. I think this kind of deploy guidance works here too....

https://github.com/splunk/splunk-operator/blob/master/docs/Install.md#splunk-operator-advanced-installation

**Comment by nick-hills** [comment]
I Agree, for a non k8s Splunk Admin the on-boarding process means that the basic configuration delivers huge volumes of data at once which then has to checked for breaking/extraction properly. The hidden danger whilst looking at this is that the metrics data may be huge in volume vs log data and can easily overwhelm a licence before you realise just how much is being indexed.

The SCFK documentation is reasonably clear if you are experienced with k8s, but for a Splunk focused team the concepts are new and challenging without a fair understanding of helm.

I would like to see clearer guidance (with warnings on volume etc) on selectively enabling specific data types and methods of (pre index) filtering highlighted in the documentation.

**Comment by mhoogcarspel-splunk** [comment]
From a Support point of view I would like the not collect everything by default, especially if there is  good example on how to include the thing you want, because that sets people up from the beginning to know what they're doing and how to filter effectively, instead of overwhelming something and then having to find it going backwards.

(hope that makes sense)
