### ISSUE TITLE
How to add ca in configmap.yaml for object 

### ISSUE THREAD

**Issue by rufengxu** [splunk/splunk-connect-for-kubernetes#388]
**What happened**:
    I deployed the splunk pods fine with the option
    insecureSSL: false
   
   But when I changed it to true, I got ssl error as expected.  I have the cacert file, but I do not know the syntax to add to the configmap.yaml

**What you expected to happen**:
   I can run curl with the flag --cacert, and post the data to the splunk.
   So I expect there is a place in the config file where I can specify the cacert pem file and the splunk will use it. 

**How to reproduce it (as minimally and precisely as possible)**:
    change insecureSSL: true, I got an ssl error.
   

**Anything else we need to know?**:
       But I do not use hem.  I am using the manifest files directly.  

**Environment**:
- Kubernetes version (use `kubectl version`):
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:   7.3
- Others:

**Comment by matthewmodestino** [comment]
hey @rufengxu are you managing the manifests manually? I don’t suggest this.

Please review helm template command which lets you render templates to a directory so you can get the benefit of the helm

https://helm.sh/docs/helm/helm_template/

**Comment by matthewmodestino** [comment]
https://github.com/splunk/splunk-connect-for-kubernetes/issues/38#issuecomment-626243602

**Comment by chaitanyaphalak** [comment]
@rufengxu we officially support helm. If you are using manifest, a possible reason it might not be working is due to whitespacing issues(tabs, spaces etc)
I would recommend you to troubleshoot those.

**Comment by matthewmodestino** [comment]
@rufengxu have you gotten this working correctly yet?

**Comment by rufengxu** [comment]
Hi Matt,

No, not yet.  But I got a doc on manifest file doc.  So you may close this
one then.

Thanks,
Rufeng
