### ISSUE TITLE
Bump version numbers and make a new release 1.0.2 for download.

### ISSUE THREAD

**Issue by runesl** [splunk/splunk-connect-for-kubernetes#39]
please :-)

**Comment by dtregonning** [comment]
New release coming in the near future. :)

**Comment by runesl** [comment]
Define near future...

**Comment by dontregonning** [comment]
> Define near future...

We are working on a release with a team as we speak. Our priority is to replace Heapster as our metrics solution. Once we have that finalized and tested we will be updating versions and will bump the release. So within a few weeks.

**Comment by runesl** [comment]
Thank you for the update.

**Comment by gmichels** [comment]
Can you please make the next release available via a regular Helm repo? It would help people building umbrella charts for comprehensive Kubernetes monitoring :)
