### ISSUE TITLE
Publish splunk-connect Helm Operator on OperatorHub.io

### ISSUE THREAD

**Issue by ron1** [splunk/splunk-connect-for-kubernetes#391]
**What would you like to be added**:

Build splunk-connect Helm Operator using Operator SDK Helm support and publish splunk-connect Operator on OperatorHub.io.

**Why is this needed**:

Some customers might want to run Splunk in a hub/spoke configuration where Splunk itself is deployed on a hub cluster using the Splunk Operator from OperatorHub.io and Splunk Connect is deployed on one or more spoke clusters. In order to provide a consistent management experience for all Splunk-related deployments, it would be useful to have a splunk-connect Operator available on OperatorHub.io. The effort required to build and publish a Helm-based operator using the Operator SDK is minimal.

Wrapping a Helm Chart in an operator also makes it easy for GitOps users to share a large [values.yaml](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/values.yaml) file as a shared Operator CRD instance that is subsequently patched using Kustomize for each deployment.

A few sample Helm Operator repos are listed below: 
`HashiCorp Vault` - https://github.com/noseka1/vault-helm-operator
`CockroachDB` - https://github.com/dmesser/cockroachdb-operator

**Comment by matthewmodestino** [comment]
I’ll go even further and say it should just be part of the existing Splunk Operator!

I’d honestly, LOVE, to ditch helm for another couple Custom Resource Defs (ie. node agent & sidecar) in our Go based operator. 

I also don’t think it wise to start having various operators scattered around...

**Comment by ron1** [comment]
Agree that support for connect functionality from within the slunk operator would be even better.
