### ISSUE TITLE
Unable to specify existing serviceaccount for logging daemonset

### ISSUE THREAD

**Issue by vishalzyy** [splunk/splunk-connect-for-kubernetes#397]
What happened:
When we specify create = false  for splunk-kubernetes-logging the serviceaccount is still created
serviceAccount:
    create: false
    name: test
    usePullSecrets: false

If the service account exist it give following error
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "test" in namespace "testns" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "kube-splunk"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "testns"

What you expected to happen:
Expected logging daemonset to use serviceaccount which was created prior to helm charts deployment

How to reproduce it:
specify create = false for serviceAccount subsection of splunk-kubernetes-logging and specify name of existing serviceaccount

Cause : 
There is not checking in case of logging charts as specified in object and metrics helm charts like 
`{{- if .Values.serviceAccount.create -}}`

Environment:
openshift : 3.11
OS: rhel 7

**Comment by matthewmodestino** [comment]
can you please share your configs and deployment steps?

**Comment by rockb1017** [comment]
starting from 1.4.0, service account is required for logging, because it needs to query from kubernetes API server and enrich the data.

**Comment by rockb1017** [comment]
closing. if you have further questions, please feel free to reopen it.

**Comment by pc-mreeves** [comment]
I should have added my "me too" to this issue vs. creating https://github.com/splunk/splunk-connect-for-kubernetes/issues/400. Apologies...
