### ISSUE TITLE
Multiline events in ECS

### ISSUE THREAD

**Issue by yuri-kozlov** [splunk/splunk-connect-for-kubernetes#40]
Hello.
I do know that Splunk Connect for Kubernetes applies to EKS, yet this is first app that directly targets multiline issue for logs ingestion from containers and maybe you can help / give an advice how ti deal with the issue below.

We are actively using ECS, and have troubles with multiline logs ingestion via Splunk logging driver. After Matthew  presentation "IT1502 - Splunking the DevOps Pipeline: A Buttercup Tale" at .conf18 i had hopes that this problem is being addressed already. But, alas, as far as i see this is true only for EKS for now.

Is Splunk doing anything to help with multiline logs ingestion in ECS? Do you have any suggestions/advices/examples how to make it work?

Thank you in advance,
-Alex

**Comment by matthewmodestino** [comment]
Hey Alex!

We do have some other options for ECS users! Are you using Fargate or running your own EC2s?

**Comment by yuri-kozlov** [comment]
Hi!

> We do have some other options for ECS users! Are you using Fargate or running your own EC2s?
We are running our own EC2s. Fargate isn't an option for security reasons.

**Comment by matthewmodestino** [comment]
Cool! I have seen a couple patterns in that situation, depending on your data and requirements. 

I think a few are worth a look and provide you some choice:

docker-splunk - https://hub.docker.com/r/splunk/splunk/
Now that we have officially supported docker images, you can use the UF as a sidecar, or to read off a shared mounts and avoid the whole docker logging problem altogether :). This works well for apps that may not have been born in the cloud, logging to stderr/stdout. You will likely need this deployment pattern at some point anyhow, so definitely check it out!

fluentd - You could definitely mimic the deployment of Splunk Connect for Kubernetes as a global service, but customize for the docker environment. Would only require few small updates to the logging paths in the configMaps and some of the filtering would need to be updated to ensure the right fields are gathered. Very similar approach to the UF as a global service. This one I have seen in various places, even writing to file and UF picking up and sending!

Other things to look at as well:

[cloudwatch logs to lambda](https://www.splunk.com/blog/2016/11/29/announcing-new-aws-lambda-blueprints-for-splunk.html) - A lambda function based off of our cloudwatch to lambda to HEC blueprint, this unlocks a lot of function and logic that can help re-assemble or massage some logs, if you happen to be using cloudwatch.

Also you can check partner collectors like [Outcold Solutions](https://www.outcoldsolutions.com/) that have logic to allow advanced linebreaking rules, etc that can help with multiline logging!

**Comment by chaitanyaphalak** [comment]
Closed due to inactivity
