### ISSUE TITLE
Firelens Not Launching Using the example Config

### ISSUE THREAD

**Issue by derkkila** [splunk/splunk-connect-for-kubernetes#401]
I tried to run the fluentd_hec per the instructions in the firelens folder. The task gets created but fails to run under a Fargate launch type with the following error message:

> Unable to run task
> One or more of the requested capabilities are not supported.

Is the latest Fargate platform supported or is the example outdated?

**Comment by matthewmodestino** [comment]
Yeah this looks like it needs to be revisited. 

We should also PR against this repo:

https://github.com/aws-samples/amazon-ecs-firelens-examples

**Comment by chaitanyaphalak** [comment]
@derkkila could you tell us more about the exact errors you are facing?

**Comment by chaitanyaphalak** [comment]
@derkkila The issues you are seeing are on the AWS side of things, check if your cluster has access to S3 buckets(attach an IAM policy) etc
this might be a good start to troubleshooting - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_firelens.html

**Comment by derkkila** [comment]
Here is the IAM policy for this role:
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}`

Just as an attempt to get it working.

**Comment by kasai-mitsuru** [comment]
Hi, 

I was also confused with a same problem.

Then, I just found a note
```
For tasks using the Fargate launch type, the only supported config-file-type value is file.
```
at [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_firelens.html#firelens-taskdef-customconfig).

So, config files in s3 is officially not supported on FARGATE.

@derkkila method is a good discovery, but you should be careful that it is not an official approach.


I'm not good at English, and sorry for my poorness of English.

**Comment by derkkila** [comment]
That makes a lot more sense @kasai-mitsuru , thanks! I totally missed that line when reading that page. So the example config shown in these Docs should point out that it only works for ECS and not Fargate.

**Comment by kasai-mitsuru** [comment]
> the example config shown in these Docs should point out that it only works for ECS and not Fargate.

I think so too, I wasted hours with refferencing these Docs.

I'm grad that it seems to help you. :)

**Comment by chaitanyaphalak** [comment]
@kasai-mitsuru @derkkila thanks for clearing out the confusion.

**Comment by chaitanyaphalak** [comment]
Updating docs here - https://github.com/splunk/splunk-connect-for-kubernetes/pull/402
