### ISSUE TITLE
excluding logs sent to splunk by a regex match on a field name

### ISSUE THREAD

**Issue by kjanss** [splunk/splunk-connect-for-kubernetes#404]
Hi,
I am fairly certain it can be done with custom filtering, but it is not at all clear to me from the documentation how to do this:
how to filter out specific log entries coming from a certain pod by regexp matching.

Use case: filter out all ingress logs for one specific website only, without disabling the access log entirely. (so keep the logging for all sites, just prevent one or more sites to have their access log entries sent to splunk. error logs should still be sent)

Could such a setting be documented and an example given ?

(I could successfully filter out the entire ingress controller but this is too much)

**Comment by matthewmodestino** [comment]
Hi please provide more specifics, the best way to filter is using the container path as the k8s pod namespace and container are all embedded:

https://github.com/splunk/splunk-connect-for-kubernetes/blob/75dce82df9aa1149b5a1b9921658f49b2cc5e7db/helm-chart/splunk-connect-for-kubernetes/values.yaml#L59

Can you please be more specific and I can try and provide an example.

Also please read fluentd docs


https://docs.fluentd.org/input/tail

**Comment by kjanss** [comment]
i could filter out a single container or namespace this way.
the use case is this:
- I have 2 ingress rules, one for siteA and one for siteB.
- I send all the traffic to splunk using splunk connect.
- I want the access_log from siteB not to get sent to Splunk.
- I do not want to disable the access_log logging on ingress level so that the logs can be consulted locally if needed.

since the ingress pods log traffic from all ingress rules, they send both sites to Splunk. I want to exclude siteb's logs from getting splunked.

**Comment by matthewmodestino** [comment]
Can you determine the site based on info available in the pod/namespace/container name?

What identifies a “site”?

**Comment by kjanss** [comment]
Hi,

No, if I could do it that way, I could use the container path filtering.
the issue is:
"a site" is "a website", it is identified using its url:
- siteA is running as a pod in deploymentA
- siteB is running as another pod in deploymentB
- both sites are logged through ingress, which is another deployment containing multiple replicas. In other words: logs from siteA and siteB are sent to the common ingress component for their access logs.

I can filter out the container logs from either deployment.
But since the ingress controller is shared and is in a single namespace, the logs are combined. In other other words, the ingress logs show incoming requests for both sites.

I could disable access_log processing, but then I lose the logs. I want to keep the logs within the cluster, but NOT send them all to splunk.

the reason: disk space, performance, licensing

**Comment by matthewmodestino** [comment]
this can still be done using fluentd filtering or props/transforms or data stream processor. please provide sample events.

**Comment by kjanss** [comment]
that would be perfect, but I could use a practical example.
example log entries:
81.246.8.11 - [81.246.8.11] - - [11/Jun/2020:07:10:35 +0000] "GET /static/files/af7ae505a9eed503f8b8e6982036873e.woff2 HTTP/1.1" 200 77352 "https://im.mycompany.be/static/main.689c23742b77be877b4b.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Mattermost/4.2.1 Chrome/61.0.3163.100 Electron/2.0.12 Safari/537.36" 933 0.014 [apps-svc-mm-8000] [] 10.42.10.36:8000 77284 0.012 200 525b2654d5901109e9e012f19336c118

and
78.23.13.144 - [78.23.13.144] - - [11/Jun/2020:07:55:37 +0000] "GET /s/2iiena/8401/0f22f74a0c673511e48ab1bc7ae6af4388aa8dbf/8.3.5/_/download/resources/com.atlassian.auiplugin:split_aui.splitchunk.vendors--f5244b0828/assets/confluence-white.svg HTTP/1.1" 200 2861 "https://confluence.mycompany.be/login.action?os_destination=%2Fpages%2Fviewpage.action%3FpageId%3D38175121&permissionViolation=true" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15" 2229 0.005 [atlassian-svc-cfl-web-8090] [] 10.42.3.4:8090 7035 0.008 200 b2678fb45e12b2bd9c00eaa0bb209d23

Let's say I want to filter out 'im.mycompany.be'

**Comment by kjanss** [comment]
Hello, any chance of getting an example ?

**Comment by matthewmodestino** [comment]
https://docs.fluentd.org/filter/grep

Have you checked the grep filter plugon out? you should be able to match on the ingress rules you want to send and drop the rest...

**Comment by kjanss** [comment]
I guess it could be for example:

```customFilters:
    noMySimpleSiteHttp200:
      tag: tail.containers.**
      type: grep
      body: |
        <exclude>
          key log
          pattern /GET.*200.*www\.my\.simple\.site.*/
        </exclude>
```

(excluding all 200 GETs to a specific ingress rule).

**Comment by matthewmodestino** [comment]
I would only apply to tag that matches your ingress, not all containers.
