### ISSUE TITLE
Feature - Provide functionality to allow for longer lines out of the fluentd process

### ISSUE THREAD

**Issue by skirven4** [splunk/splunk-connect-for-kubernetes#408]
<

**What would you like to be added**:
Provide for the ability to configure fluentd to allow for more characters in a line.
**Why is this needed**:
We are running into situations where lines are too long, causing the fluentd process to break the line. 
Unless I'm missing something, this is not available today.

**Comment by skirven4** [comment]
Is this a duplicate of #377 perhaps?

**Comment by matthewmodestino** [comment]
Can you please provide more info??

Docker truncates at 16K bytes, Splunk does at 10K by default.

What are you seeing?

**Comment by skirven4** [comment]
Yes. Sorry for the delay. I may send over a payload to my Splunk rep to pass to you tomorrow.  
Thanks!


Sent from Yahoo Mail for iPhone


On Wednesday, June 10, 2020, 10:01 PM, Matthew Modestino <notifications@github.com> wrote:




Can you please provide more info??

Docker truncates at 16K bytes, Splunk does at 10K by default.

What are you seeing?

**Comment by skirven4** [comment]
I'm closing this issue. I believe we solved it with the max characters setting from the HEC.
