### ISSUE TITLE
daemonset for logging is created in pod network

### ISSUE THREAD

**Issue by MarcoSchaar** [splunk/splunk-connect-for-kubernetes#41]
Hi,
while deploying logging archive only, the daemonset is created in Pod network instead with cluster node IPs.
Is there a paramater to adjust this deployment accordingly with helm?

**Comment by matthewmodestino** [comment]
Hi Marco!

Can you tell us more about what behavior you are expecting, or more on what the challenge you face is?

The logging pods don't deploy with any endpoints or services, as they only need to send data out of the cluster, are you trying to reach them?

**Comment by MarcoSchaar** [comment]
Hi
issue got resolved locally
