### ISSUE TITLE
High Kube API Server Usage 600+ req/sec

### ISSUE THREAD

**Issue by ekristen** [splunk/splunk-connect-for-kubernetes#410]
**What happened**:

I'm seeing extremely high CPU usage across multiple clusters that have this deployed. High request rate to the Kube API Server for WATCH pod and WATCH namespaces. 

600-700 requests/sec, 8 weeks ago I was at 1.2k requests/second and 12 weeks ago over 2k requests/sec.

I've also witnessed that the fluentd CPU usage has been high during this same period, likely correlated.

**What you expected to happen**:

Not for it to make so many request/per second

**How to reproduce it (as minimally and precisely as possible)**:

Unsure yet, still investigating. As far as I can tell my configuration is standard, nothing out of the ordinary beyond the basic setup.

**Anything else we need to know?**:

A restart of the fluentd-hec container fixes the problem. It appears something is in a tight failure loop and is constantly spawning requests to the kube-apiserver

**Environment**:
- Kubernetes version (use `kubectl version`): 1.5.10
- Ruby version (use `ruby --version`): 
- OS (e.g: `cat /etc/os-release`): rancher-os
- Splunk version: 
- Others:

**Comment by ekristen** [comment]
Saw a lot of buffer errors regarding expired execution to the upstream HEC endpoint. I neglected to copy and paste the exact errors.

**Comment by ekristen** [comment]
Why does every fluentd-hec need to watch pods/namespaces? I thought that the fluentd-hec is only monitoring local pod files? Is that for the metadata it adds on?

**Comment by rockb1017** [comment]
Yes, correct. to enrich event with metadata.

**Comment by rockb1017** [comment]
this seems like a issue fixed with latest SCK release. what version of SCK chart and hec image are you using?

**Comment by ekristen** [comment]
SCK 1.4.0 -- that's good to know, I'll look at upgrading ASAP. If that's fixed then fantastic, maybe this issue will help someone else that runs into this.

**Comment by ekristen** [comment]
Didn't think to look at the release notes only for issues related to this 

From release notes.
> library update which fixes a bug that causes high requests to k8s api server and high CPU usage.

Will upgrade to 1.4.1.

Thanks for pointing that out.

**Comment by rockb1017** [comment]
great! let me know how it goes!

**Comment by matthewmodestino** [comment]
yep, known issue with 1.4.0, see https://github.com/splunk/splunk-connect-for-kubernetes/issues/359

**Comment by ekristen** [comment]
Dupe of #359. 1.4.1 seems to have fixed. Thanks.
