### ISSUE TITLE
Historical data is missing in splunk

### ISSUE THREAD

**Issue by puzzlepri** [splunk/splunk-connect-for-kubernetes#411]
Hello team,

Recently started testing openshift logging with splunk-connect-for-kubernetes.  I dont see historical data in splunk  which does exist in splunk logging pod.

**Comment by matthewmodestino** [comment]
Hello!

The logging pods will pick up the data from /var/log/containers which is a symlink to files on disk. 

If those files have rotated, we will not see them. 

If you want those logs I would look at making a separate input that can scoop up any rolled logs...but this should be a now time thing....not a config to run with going forward....
