### ISSUE TITLE
Metrics disabled

### ISSUE THREAD

**Issue by hopik007** [splunk/splunk-connect-for-kubernetes#412]
**What happened**:
We would like to avoid sending metrics data to the splunk.
I have configured:

  splunk-kubernetes-metrics:
    enabled: false

but metrics configuration was deployed:

NAME                                                  DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
daemonset.apps/my-release-splunk-kubernetes-logging   5         5         5       5            5           beta.kubernetes.io/os=linux   9m50s
daemonset.apps/my-release-splunk-kubernetes-metrics   5         5         5       5            5           beta.kubernetes.io/os=linux   9m50s

NAME                                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/my-release-splunk-kubernetes-metrics-agg   1/1     1            1           9m50s
deployment.apps/my-release-splunk-kubernetes-objects       1/1     1            1           9m50s

NAME                                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/my-release-splunk-kubernetes-metrics-agg-6f6494d6cf   1         1         1       9m50s
replicaset.apps/my-release-splunk-kubernetes-objects-588948c4f        1         1         1       9m50s
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.18 client ; 1.16 server 
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:
- Others:

**Comment by matthewmodestino** [comment]
please share the full values.yaml and commands used to deploy. 

Likely just an issue with the config of the values.yaml
