### ISSUE TITLE
Problems cloning events that originated from Splunk Connect for Kubernetes

### ISSUE THREAD

**Issue by osvaldopina** [splunk/splunk-connect-for-kubernetes#416]
I´m trying to clone events that originated from Splunk Connect for Kuberntes and store that copy in another index (This is the first step, in the future, I will separate some events to be transformed and stored in this other index) . I used the following configuration in props.conf and transforms.conf:

props.conf

[(?::){0}*]
TRANSFORMS-logs_java=clone_trace

[trace]
TRANSFORMS-indice=indice_trace

tranforms.conf

[clone_trace]
REGEX=.
CLONE_SOURCETYPE=trace

[indice_trace]
REGEX=.
DEST_KEY=_MetaData:Index
FORMAT=jaeger_trace

But some events are not being cloned or not being redirected to jaeger_trace index. I was wondering if it could be related to the fact that sourcetype is metadata instead of a field (the difference in search that mandates the use of :: instead of = ). If so what would be the right configuration?

**Comment by chaitanyaphalak** [comment]
@matthewmodestino might be able to help you on this one.

**Comment by matthewmodestino** [comment]
Hi,


Can you clarify why you would clone the events and store them twice?

Sourcetype is always metadata. 

Once the data hits the HTTP Event Collector it enters the Splunk transforms pipeline like any other.

I recommend you take this to our slack usergroups, (splk.it/slack) as I don’t believe it is appropriate to cover Splunk side props/transforms voodoo here.

My username is @mattymo you can reach out and I can direct you to the appropriate rooms covering Splunk indexing configs.

**Comment by osvaldopina** [comment]
Hi, 

I'm cloning as a step in a bigger scenario. After cloning the next step would be to transform data. I need the 2 copies of the events just for a small period for my client application not to break (until one date I will use one search and after that will be another search in the new index with transformed data)

It was not my intention to discuss props/transforms specifics here. It was just to illustrate the issue that I was having.

Anyway, if there is nothing specific to Splunk Connect for Kubernetes I will keep working on props/transforms. 

Thanks a lot!!
