### ISSUE TITLE
Errors in launching fargate task

### ISSUE THREAD

**Issue by kikeyama** [splunk/splunk-connect-for-kubernetes#423]
**What would you like to be added**:

After I register task definition as described in [firelens/README.md](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/firelens/README.md), launching the task failed with the following error.  

```
CannotStartContainerError: ResourceInitializationError: failed to initialize logging driver: failed to get fluentd log driver arguments: logging driver specified of container xxxxxxxx, but no log configuration specified
```

I launched the service with Fargate 1.4.0 to enable EFS volume mount for fluent.conf. It requires `options` in log driver settings in each container.  

For workaround, the following task definition and fluent.conf work for Fargate. (I use `concat` for multiline logs).  

**task definition**

```
  logConfiguration:
    logDriver: awsfirelens
    options:
      '@label': '@CONCAT'
      '@type': relabel
```

`@label: @SPLUNK` should also work in this case.  

**fluent.conf**

```
<system>
  log_level info
</system>

<label @CONCAT>
  <filter **xxxxxxxx**>
    @type concat
    key log
    stream_identity_key stream
    multiline_start_regexp /^[0-9]{4}/\d{2}/\d{2}\s+\d{2}:\d{2}:\d{2}\.\d{6}/
    flush_interval 5s
    timeout_label @SPLUNK
    use_first_timestamp true
  </filter>
  
  <match **>
    @type relabel
    @label @SPLUNK
  </match>
</label>

<label @SPLUNK>
  <match **>
    @type splunk_hec
    protocol http
    hec_host <SPLUNK_HEC_HOST>
    hec_port 8088
    hec_token xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    index ecs
    host_key ec2_instance_id
    source_key ecs_cluster
    sourcetype_key ecs_task_definition
    #source_key ecs_task_arn
    #sourcetype_key container_name
    insecure_ssl true
    <fields>
      container_id
      container_name
      ecs_task_arn
      source
    </fields>
    <format>
      @type single_value
      message_key log
      add_newline false
    </format>
  </match>
</label>
```

**Why is this needed**:

---

For the record, `'@type': ''` also didn't work. fluentd-hec container stopped with the following error logs soon after it started.  

```
2020-07-10 05:38:36 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2020-07-10 05:38:36 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Unknown output plugin ''. Run 'gem search -rd fluent-plugin' to find plugins"
```

This is because `@type` in the task definition was blank and fluentd didn't recognize the blank plugin.  

---

I request firelens/README.md document update that refers to fargate task definition and fluent.conf.

**Comment by rockb1017** [comment]
Hello, we will review and update doc accordingly.
