### ISSUE TITLE
In Splunk the 'cluster_name' variable is not populating with actual name of cluster but instead with default value of cluster_name

### ISSUE THREAD

**Issue by r6ricer** [splunk/splunk-connect-for-kubernetes#426]
**What happened**:
The cluster_name variable value is not populating with the actual name of the cluster instead default value of cluster_name is in the field when querying in Splunk.

**What you expected to happen**:
The actual name of the cluster to be showing under cluster_name variable in Splunk.

**How to reproduce it (as minimally and precisely as possible)**:
Deployed Splunk connect using Helm charts via https://github.com/splunk/splunk-connect-for-kubernetes/tree/develop/helm-chart/splunk-connect-for-kubernetes.

**Anything else we need to know?**:
Using latest Splunk connect for kubernetes 1.4.1 release.

**Environment**:
- Kubernetes version (use `kubectl version`):  GitVersion:"v1.15.7-gke.32"
- Ruby version (use `ruby --version`):  Not installed
- OS (e.g: `cat /etc/os-release`):  Ubuntu 18.04.4 LTS
- Splunk version:  7.3.0
- Others:

**Comment by cheneysplunk** [comment]
Thanks @r6ricer . Make sense to me. Created a Jira ticket https://jira.splunk.com/browse/ADDON-27949. Will plan it in future.

**Comment by chaitanyaphalak** [comment]
Hey @r6ricer did you try setting the value https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/values.yaml#L41 ?

**Comment by yinghe1** [comment]
hi, do we have an estimated timeline when this will be fixed? i have the same issue as r6ricer with the same released version

**Comment by rockb1017** [comment]
@yinghe1 @r6ricer Could you share the values.yaml file you are using.
I would like to know in which case it fails to populate cluster_name field with the value set in the https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/values.yaml#L41

**Comment by yinghe1** [comment]
@rockb1017 does the helm take cluster_name as a parameter? I wonder how does L41 takes a different cluster_name as user indicated. thank you

**Comment by matthewmodestino** [comment]
@yinghe1 yes fo course....here is the spec...not sure what L41 is?

https://github.com/splunk/splunk-connect-for-kubernetes/blob/69a5fa2091401214d53e9fb4e2a7db755cc87d33/helm-chart/splunk-connect-for-kubernetes/values.yaml#L41

`kubernetes.cluster_name` is avail in all sections of the chart (global and local sub chart configs)

**Comment by yinghe1** [comment]
thanks @matthewmodestino . @rockb1017 i confirmed that if i pass in the the right value to helm, it will work. you can close this ticket

**Comment by rockb1017** [comment]
Thank you!
