### ISSUE TITLE
sdn-controller crash with a high number of services and SCK 

### ISSUE THREAD

**Issue by fshadid96** [splunk/splunk-connect-for-kubernetes#431]
**What happened**:

We deployed SCK 1.4 into our OpenShift 4.x cluster.  On an empty cluster, or one with not many pods running it appears to work fine, but as we start to increase the number of pods and services, SCK starts to affect overall cluster health causing total instability of the cluster.  Specifically, it is causing the sdn-controller to crash and recycling almost constantly due to overwhelming the OpenShift API.  We even end up having actual worker nodes go down due to this.  We were able to directly tie this problem to SCK and it occurred in different versions of 4.4.x and 4.5.x of OpenShift.  As soon as we undeployed SCK, we have not had a single hiccup with the cluster and have been entirely stable.

**What you expected to happen**:
The sdn-controller shouldn't crash and the cluster shouldn't have any problems running pods.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy SCK on it's own namespace on a cluster that has at least 70 pods/services running

**Anything else we need to know?**:

**Environment**:
- oversion: 
     Client Version: 4.3.1
     Server Version: 4.5.3
     Kubernetes Version: v1.18.3+3107688

- OS (e.g: `cat /etc/os-release`):  Red Hat Enterprise Linux CoreOS 45.82.202007171855-0
- Splunk version: 7.0.0

- Others:

**Comment by fshadid96** [comment]
Here is a copy of values I am using 


> `#reference https://github.com/splunk/splunk-connect-for-kubernetes for a full configuration file
# Splunk Connect for Kubernetes is a umbraller chart for three charts
# * splunk-kubernetes-logging
# * splunk-kubernetes-objects
# * splunk-kubernetes-metrics

# Use global configurations for shared configurations between sub-charts.
# Supported global configurations:
# Values defined here are the default values.
global:
  logLevel: info
   # - info
   # - debug
   # - trace
   # - warn
   # - error
  splunk:
    hec:
      # host is required and should be provided by user
      host: URL
      # port to HEC, optional, default 8088
      port: PORT
      # token is required and should be provided by user
      token: TOKEN
      # protocol has two options: "http" and "https", default is "https"
      protocol: "http"
      # insecureSSL is a boolean, it indicates should it allow inscure SSL connection (when protocol is "https"). Default is false.
      insecureSSL: true
  kubernetes:
    # The cluster name used to tag logs. Default is cluster_name
    clusterName: "test_openshift_cluster"

# Enabling splunk-kubernetes-logging will install the `splunk-kubernetes-logging` chart to a kubernetes
# cluster to collect logs generated in the cluster to a Splunk indexer/indexer cluster.
splunk-kubernetes-logging:
  enabled: true
  # logLevel is to set log level of the Splunk log collector. Avaiable values are:
  # * trace
  # * debug
  # * info (default)
  # * warn
  # * error
  #logLevel:

  # This is can be used to exclude verbose logs including various system and Helm/Tiller related logs.
  fluentd:
    # path of logfiles, default /var/log/containers/*.log
    path: /var/log/containers/*.log
    # paths of logfiles to exclude. object type is array as per fluentd specification:
    # https://docs.fluentd.org/input/tail#exclude_path
    exclude_path:
    #  - /var/log/containers/kube-svc-redirect*.log
    #  - /var/log/containers/tiller*.log

  # Configurations for container logs
  containers:
    # Path to root directory of container logs
    path: /var/log
    # Final volume destination of container log symlinks
    pathDest: /var/lib/docker/containers
    # Log format type, "json" or "cri"
    logFormatType: cri
    # Specify the log format for "cri" logFormatType
    # It can be "%Y-%m-%dT%H:%M:%S.%N%:z" for openshift and "%Y-%m-%dT%H:%M:%S.%NZ" for IBM IKS
    logFormat: "%Y-%m-%dT%H:%M:%S.%N%:z"

  # Enriches log record with kubernetes data
  k8sMetadata:
    # Pod labels to collect
    podLabels:
      - app
      - k8s-app
      - release

  serviceAccount:
    # Specifies whether a ServiceAccount should be created
    create: false
    # The name of the ServiceAccount to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "splunk-connect-logging"
    # This flag specifies if the user wants to use a secret for creating the serviceAccount,
    # which will be used to get the images from a private registry
    usePullSecrets: false

  # Local splunk configurations
  splunk:
    # Configurations for HEC (HTTP Event Collector)
    hec:
      indexName: "test_openshift_events"
      token: TOKEN
  # Directory where to read journald logs.
  journalLogPath: /run/log/journal

  # Here we have some default timestampExtraction and multiline settings for kubernetes components.
  # So, usually you just need to redefine the source of those components if necessary.
  logs:
    docker:
      from:
        journald:
          unit: docker.service
      timestampExtraction:
        regexp: time="(?<time>\d{4}-\d{2}-\d{2}T[0-2]\d:[0-5]\d:[0-5]\d.\d{9}Z)"
        format: "%Y-%m-%dT%H:%M:%S.%NZ"
      sourcetype: kube:docker
    kubelet: &glog
      from:
        journald:
          unit: kubelet.service
      timestampExtraction:
        regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
        format: "%m%d %H:%M:%S.%N"
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kubelet
    etcd:
      from:
        pod: etcd-server
        container: etcd-container
      timestampExtraction:
        regexp: (?<time>\d{4}-\d{2}-\d{2} [0-2]\d:[0-5]\d:[0-5]\d\.\d{6})
        format: "%Y-%m-%d %H:%M:%S.%N"
    etcd-minikube:
      from:
        pod: etcd-minikube
        container: etcd
      timestampExtraction:
        regexp: (?<time>\d{4}-\d{2}-\d{2} [0-2]\d:[0-5]\d:[0-5]\d\.\d{6})
        format: "%Y-%m-%d %H:%M:%S.%N"
    etcd-events:
      from:
        pod: etcd-server-events
        container: etcd-container
      timestampExtraction:
        regexp: (?<time>\d{4}-[0-1]\d-[0-3]\d [0-2]\d:[0-5]\d:[0-5]\d\.\d{6})
        format: "%Y-%m-%d %H:%M:%S.%N"
    kube-apiserver:
      <<: *glog
      from:
        pod: kube-apiserver
      sourcetype: kube:kube-apiserver
    kube-scheduler:
      <<: *glog
      from:
        pod: kube-scheduler
      sourcetype: kube:kube-scheduler
    kube-controller-manager:
      <<: *glog
      from:
        pod: kube-controller-manager
      sourcetype: kube:kube-controller-manager
    kube-proxy:
      <<: *glog
      from:
        pod: kube-proxy
      sourcetype: kube:kube-proxy
    kubedns:
      <<: *glog
      from:
        pod: kube-dns
      sourcetype: kube:kubedns
    dnsmasq:
      <<: *glog
      from:
        pod: kube-dns
      sourcetype: kube:dnsmasq
    dns-sidecar:
      <<: *glog
      from:
        pod: kube-dns
        container: sidecar
      sourcetype: kube:kubedns-sidecar
    dns-controller:
      <<: *glog
      from:
        pod: dns-controller
      sourcetype: kube:dns-controller
    kube-dns-autoscaler:
      <<: *glog
      from:
        pod: kube-dns-autoscaler
        container: autoscaler
      sourcetype: kube:kube-dns-autoscaler
    kube-audit:
      from:
        file:
          path: /var/log/kube-apiserver-audit.log
      timestampExtraction:
        format: "%Y-%m-%dT%H:%M:%SZ"
      sourcetype: kube:apiserver-audit


 #fluentd image
  # Defines which version of image to use, and how it should be pulled.
  image:
    # The domain of the registry to pull the image from
    registry: REGISTRY
    # The name of the image to pull
    name: "splunk/fluentd-hec"
    # The tag of the image to pull
    tag: "1.2.1"
    # The policy that specifies when the user wants the images to be pulled
    pullPolicy: Always
    # Indicates if the image should be pulled using authentication from a secret
    usePullSecret: false
    # The name of the pull secret to attach to the respective serviceaccount used to pull the image
    pullsecretName:

  # Controls the resources used by the fluentd daemonset
  resources:
    # limits:
    #  cpu: 100m
    #  memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi

  # Controls the output buffer for the fluentd daemonset
  # Note that, for memory buffer, if `resources.limits.memory` is set,
  # the total buffer size should not bigger than the memory limit, it should also
  # consider the basic memory usage by fluentd itself.
  # All buffer parameters (except Argument) defined in
  # https://docs.fluentd.org/v1.0/articles/buffer-section#parameters
  # can be configured here.
  buffer:
    "@type": memory
    total_limit_size: 600m
    chunk_limit_size: 200m
    chunk_limit_records: 100000
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 3

  # This default tolerations allow the daemonset to be deployed on master nodes,
  # so that we can also collect logs from those nodes.
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule

  # Defines which nodes should be selected to deploy the fluentd daemonset.
  nodeSelector:
    beta.kubernetes.io/os: linux

  # = Kubernetes Connection Configs =
  kubernetes:
    # The cluster name used to tag logs. Default is cluster_name
    clusterName: "test_openshift_cluster"
    # Add privileged access to containers for openshift compatability
    openshift: true

# Enabling splunk-kubernetes-objects will install the `splunk-kubernetes-objects` chart to a kubernetes
# cluster to collect kubernetes objects in the cluster to a Splunk indexer/indexer cluster.
splunk-kubernetes-objects:
  enabled: true
  rbac:
    # Specifies whether RBAC resources should be created.
    # This should be set to `false` if either:
    # a) RBAC is not enabled in the cluster, or
    # b) you want to create RBAC resources by yourself.
    create: true

  objects:
    core:
      v1:
        - name: pods
        - name: namespaces
        - name: nodes
        - name: events
          mode: watch

  # = Configure Splunk HEC connection =
  splunk:
    hec:
      indexName: "test_openshift_events"
      token: TOKEN
  #kube Objects
  # Defines which version of image to use, and how it should be pulled.
  image:
    # The domain of the registry to pull the image from
    registry: REGISTRY
    # The name of the image to pull
    name: "splunk/kube-objects"
    # The tag of the image to pull
    tag: "1.1.3"
    # The policy that specifies when the user wants the images to be pulled
    pullPolicy: Always
    # Indicates if the image should be pulled using authentication from a secret
    usePullSecret: false
    # The name of the pull secret to attach to the respective serviceaccount used to pull the image
    pullSecretName:

  # = Resoruce Limitation Configs =
  resources:
    # limits:
    #  cpu: 100m
    #  memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi

  # Controls the output buffer for the fluentd daemonset
  # Note that, for memory buffer, if `resources.limits.memory` is set,
  # the total buffer size should not bigger than the memory limit, it should also
  # consider the basic memory usage by fluentd itself.
  # All buffer parameters (except Argument) defined in
  # https://docs.fluentd.org/v1.0/articles/buffer-section#parameters
  # can be configured here.
  buffer:
    "@type": memory
    total_limit_size: 600m
    chunk_limit_size: 200m
    chunk_limit_records: 10000
    flush_interval: 3s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 3

## Enabling splunk-kubernetes-metrics will install the `splunk-kubernetes-metrics` chart to a kubernetes
## cluster to collect metrics of the cluster to a Splunk indexer/indexer cluster.
splunk-kubernetes-metrics:
  enabled: true

  rbac:
    # Specifies whether RBAC resources should be created.
    # This should be set to `false` if either:
    # a) RBAC is not enabled in the cluster, or
    # b) you want to create RBAC resources by yourself.
    create: true

  # = Splunk HEC Connection =
  splunk:
    hec:
      indexName: "test_openshift_metrics"
      token: TOKEN
  #k8s_metrics
  # Defines which version of image to use, and how it should be pulled.
  image:
    # The domain of the registry to pull the image from
    registry: REGISTRY
    # The name of the image to pull
    name: "splunk/k8s-metrics"
    # The tag of the image to pull
    tag: "1.1.3"
    # The policy that specifies when the user wants the images to be pulled
    pullPolicy: Always
    # Indicates if the image should be pulled using authentication from a secret
    usePullSecret: false
    # The name of the pull secret to attach to the respective serviceaccount used to pull the image
    pullsecretName:

  # Defines which version of image to use, and how it should be pulled.
  imageAgg:
    # The domain of the registry to pull the image from
    registry: "registry.dcc.atagc.com"
    # The name of the image to pull
    name: "splunk/k8s-metrics-aggr"
    # The tag of the image to pull
    tag: "1.1.2"
    # The policy that specifies when the user wants the images to be pulled
    pullPolicy: Always
    # Indicates if the image should be pulled using authentication from a secret
    usePullSecret: false
    # The name of the pull secret to attach to the respective serviceaccount used to pull the image
    pullsecretName:

  # Controls the resources used by the fluentd daemonset
  resources:
    fluent:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 200m
        memory: 300Mi
  # Controls the output buffer for fluentd for the metrics pod
  # Note that, for memory buffer, if `resources.sidecar.limits.memory` is set,
  # the total buffer size should not bigger than the memory limit, it should also
  # consider the basic memory usage by fluentd itself.
  # All buffer parameters (except Argument) defined in
  # https://docs.fluentd.org/v1.0/articles/buffer-section#parameters
  # can be configured here.
  buffer:
    "@type": memory
    total_limit_size: 400m
    chunk_limit_size: 100m
    chunk_limit_records: 10000
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 3

  # Controls the output buffer for fluentd for the metrics aggregator pod
  aggregatorBuffer:
    "@type": memory
    total_limit_size: 400m
    chunk_limit_size: 100m
    chunk_limit_records: 10000
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 3

  # Configure how often SCK pulls metrics for its kubenetes sources. 15s is the default where 's' is seconds.
  metricsInterval: 15s

  # This default tolerations allow the daemonset to be deployed on master nodes,
  # so that we can also collect metrics from those nodes.
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
`

**Comment by fshadid96** [comment]
here is a copy of the values I used 

[sck_values.txt](https://github.com/splunk/splunk-connect-for-kubernetes/files/5003830/sck_values.txt)

**Comment by rockb1017** [comment]
Are you using 1.4.0? it has a known issue that queries API server too much. If so, please use 1.4.1 or 1.4.2.

**Comment by matthewmodestino** [comment]
@rockb1017 can we pull the 1.4.0 tarball or backport metadata fix to 1.4.0?

@fshadid96 sorry to hear you had issues, please confirm the actual chart version you were running.

**Comment by fshadid96** [comment]
@matthewmodestino  @rockb1017  Yes I am using 1.4.0. I will try to use 1.4.2 and see if it doesn't crash the cluster. 

is there a way we can throttle or limit it in a way it doesn't affect the cluster?

**Comment by matthewmodestino** [comment]
@fshadid96 it was a bug in the metadata filter, i know you had a bad first touch, but we have had no issues since patching it, I don't expect you to have to worry once you get updated.

**Comment by rockb1017** [comment]
closing. thank you!
