### ISSUE TITLE
Logs are not sent to Splunk Cloud even though available within splunk-kubernetes-logging container

### ISSUE THREAD

**Issue by rchenzheng** [splunk/splunk-connect-for-kubernetes#434]
**What happened**:
Logs from standard output are not being sent to splunk cloud, even though they do appear within the splunk-kubernetes-logging container in `/var/log/containers/`

For example, the following output logs but are not shown/sent to splunk cloud

```
kubectl exec -ti production-splunk-connect-for-kubernetes-splunk-kubernetes9r8z2 cat /var/log/containers/production-app-f9e08ac43fcd6d403aea3a20facbf0823049afaa638bff6fb60adb4c95417353.log
```

Error logs

```
2020-08-06 18:18:13 +0000 [info]: #0 stats - namespace_cache_size: 6, pod_cache_size: 18, namespace_cache_api_updates: 33, pod_cache_api_updates: 33, id_cache_miss: 33, pod_cache_host_updates: 73, pod_wat
ch_gone_notices: 3
2020-08-06 18:18:43 +0000 [info]: #0 stats - namespace_cache_size: 6, pod_cache_size: 18, namespace_cache_api_updates: 33, pod_cache_api_updates: 33, id_cache_miss: 33, pod_cache_host_updates: 73, pod_wat
ch_gone_notices: 3
2020-08-06 18:18:48 +0000 [info]: #0 disable filter chain optimization because [Fluent::Plugin::KubernetesMetadataFilter, Fluent::Plugin::RecordTransformerFilter] uses `#filter_stream` method.
2020-08-06 18:19:13 +0000 [info]: #0 stats - namespace_cache_size: 7, pod_cache_size: 18, namespace_cache_api_updates: 34, pod_cache_api_updates: 34, id_cache_miss: 34, pod_cache_host_updates: 73, pod_wat
ch_gone_notices: 3
2020-08-06 18:19:43 +0000
```

**What you expected to happen**:
Logs should be appearing from all container's standard output in splunk cloud

**How to reproduce it (as minimally and precisely as possible)**:
```

global:
  logLevel: info
  splunk:
    hec:
      indexName: k8s-logging
      host: http-inputs-MY-INPUT.splunkcloud.com
      port: 443
      token: MY_TOKEN
      protocol: https
      insecureSSL: false
      clientCert: |
      clientKey: |
      caFile: |
  kubernetes:
    clusterName: my-cluster

splunk-kubernetes-logging:
  fluentd:
    exclude_path:
      - /var/log/containers/*_ntnx-system_*.log
  containers:
    pathDest: /var/nutanix/docker/containers

splunk-kubernetes-metrics:
  kubernetes:
    useRestClientSSL: false
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"f3add640dbcd4f3c33a7749f38baaac0b3fe810d", GitTreeState:"clean", BuildDate:"2020-05-20T13:51:56Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Ruby version (use `ruby --version`):
```
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
```
- OS (e.g: `cat /etc/os-release`):
```
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"
```
- Splunk version: helm chart 1.4.2
- Others:

**Comment by matthewmodestino** [comment]
looks like its humming along, what search are you running? Looks to be going in the `main` index?

**Comment by rchenzheng** [comment]
> looks like its humming along, what search are you running? Looks to be going in the `main` index? Can you see fluentd starting tail on the logs you expect?

Yes it does try to tail the logs I expect, but at the end it also shows the following error:

```
06 19:47:23 +0000 [info]: #0 disable filter chain optimization because [Fluent::Plugin::KubernetesMetadataFilter, Fluent::Plugin::RecordTransformerFilter] uses `#filter_stream` method.
```

When querying on the cloud, they don't show up at all.

**Comment by matthewmodestino** [comment]
these are not related..

**Comment by rchenzheng** [comment]
> these are not related..
> 
> try this search
> 
> `index=foo sourcetype::kube:container:*`

Oddly enough, I'm getting logs but nothing outside of the namespace splunk-connect is running on 👎

**Comment by matthewmodestino** [comment]
🤷🏼‍♂️ please review your running configmap and the logs output from the pod. If the pod picks up the logs, then not sure what you have borked...

**Comment by rchenzheng** [comment]
> 🤷🏼‍♂️ please review your running configmap and the logs output from the pod. If the pod picks up the logs, then not sure what you have borked...if you are getting logs from our namespace then the collector is working. Please review the readme about searching for metadata in Splunk

You're right logs were making it there but the search was borked, I got a hold of support and it seems that there was an issue with the fields in the Splunk Cloud side.

The search was broken and I was able to get the logs using the following query

```
index=k8s-logging cluster_name::my-cluster
```
