### ISSUE TITLE
Mount a different directory for logging

### ISSUE THREAD

**Issue by Ian-An** [splunk/splunk-connect-for-kubernetes#437]
Hi,

I'd like to know if it's possible to mount an extra logging directory for example /var/my-antivirus-app/logs?

Thanks

**Comment by rockb1017** [comment]
Yes. but you would have to edit the logging daemonset template file.
add a volume mount that you want and also edit `fluentd.path` from values.yaml file to include the mounted path.

**Comment by rockb1017** [comment]
also I think you could deploy another set of logging daemonset. just edit
`fluentd.path` and `containers.path`

**Comment by Ian-An** [comment]
@rockb1017 thank you
