### ISSUE TITLE
no implicit conversion of nil into String + rescue in expand

### ISSUE THREAD

**Issue by jayntguru** [splunk/splunk-connect-for-kubernetes#439]
**What happened**:

Trying to grab rancher audit logs and it's barfing on most of the entries.

`2020-08-12 17:46:14 +0000 [warn]: #0 dump an error event: error_class=RuntimeError error="failed to expand `record.dig(\"kubernetes\", \"annotations\", \"splunk.com/sourcetype\") ? \"kube:\"+record.dig(\"kubernetes\", \"annotations\", \"splunk.com/sourcetype\") : \"kube:container:\"+record.dig(\"kubernetes\",\"container_name\")` : error = no implicit conversion of nil into String" location="/usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin/filter_record_transformer.rb:310:in `rescue in expand'" tag="tail.containers.var.log.kube-audit.audit-log.json" time=2020-08-12 17:46:14.731134878 +0000 record={"kind"=>"Event", "apiVersion"=>"audit.k8s.io/v1", "level"=>"Metadata", "auditID"=>"f7a04523-eeb3-4c96-adee-4fc9fb87b514", "stage"=>"ResponseComplete", "requestURI"=>"/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager?timeout=10s", "verb"=>"get", "user"=>{"username"=>"system:kube-controller-manager", "groups"=>["system:authenticated"]}, "sourceIPs"=>["127.0.0.1"], "userAgent"=>"kube-controller-manager/v1.17.5 (linux/amd64) kubernetes/e0fccaf/leader-election", "objectRef"=>{"resource"=>"leases", "namespace"=>"kube-system", "name"=>"kube-controller-manager", "apiGroup"=>"coordination.k8s.io", "apiVersion"=>"v1"}, "responseStatus"=>{"metadata"=>{}, "code"=>200}, "requestReceivedTimestamp"=>"2020-08-12T17:46:14.728999Z", "stageTimestamp"=>"2020-08-12T17:46:14.730975Z", "annotations"=>{"authorization.k8s.io/decision"=>"allow", "authorization.k8s.io/reason"=>"RBAC: allowed by ClusterRoleBinding \"system:kube-controller-manager\" of ClusterRole \"system:kube-controller-manager\" to User \"system:kube-controller-manager\""}, "source"=>"/var/log/kube-audit/audit-log.json"} `

**What you expected to happen**:

All logs and no errors.

**How to reproduce it (as minimally and precisely as possible)**:

Parse logs with lines similar to this.

`{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"a27719ec-46cb-42bd-8634-061c217041e1","stage":"ResponseComplete","requestURI":"/api/v1/nodes/catl5plas10004?resourceVersion=0\u0026timeout=10s","verb":"get","user":{"username":"system:node","groups":["system:nodes","system:authenticated"]},"sourceIPs":["127.0.0.1"],"userAgent":"kubelet/v1.17.5 (linux/amd64) kubernetes/e0fccaf","objectRef":{"resource":"nodes","name":"catl5plas10004","apiVersion":"v1"},"responseStatus":{"metadata":{},"code":200},"requestReceivedTimestamp":"2020-08-12T18:08:25.002963Z","stageTimestamp":"2020-08-12T18:08:25.003440Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"system:node\" of ClusterRole \"system:node\" to Group \"system:nodes\""}`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

> kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
> 

- Ruby version (use `ruby --version`):

?

- OS (e.g: `cat /etc/os-release`):

NAME="CentOS Linux"
VERSION="7 (Core)"

- Splunk version:

1.4.1

- Others:

**Comment by chaitanyaphalak** [comment]
how did you configure the audit paths location? 
Did you specify it here https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml#L280?

**Comment by jayntguru** [comment]
I figured it out, I had added the path to the fluentd section [here.](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml#L16)

Once I removed that the errors stopped.

Thank you!
