### ISSUE TITLE
values.yaml: additional comments to splunk-kubernetes-logging.containers.pathDest

### ISSUE THREAD

**Issue by florianzimm** [splunk/splunk-connect-for-kubernetes#440]
**what: add comments in values.yaml to specify different defaults for pathDest**:

**container-logs are found in different default locations, depending on which kubernetes implementation is used. it would be helpful to have a list which kubernetes offering uses which ones. PKS for example uses /var/vcap/store/docker/docker/containers*

**Comment by chaitanyaphalak** [comment]
it would be nice if we could make a list here of the common ones for different distributions and add it all together
