### ISSUE TITLE
Allow customMetadata for metrics and objects

### ISSUE THREAD

**Issue by MikeTomlin19** [splunk/splunk-connect-for-kubernetes#441]
<

**What would you like to be added**:
I'd like the customMetadata labels to be added to the objects and metrics output, not just logging.
**Why is this needed**:
It would be nice to have common labeling across all the output to splunk (logs/metrics/objects),.  This works today for cluster_name, but not if you want to add other metadata labels.

**Comment by chaitanyaphalak** [comment]
you can achieve that using https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/values.yaml#L221
and
https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/values.yaml#L184

**Comment by MikeTomlin19** [comment]
Thanks, @chaitanyaphalak ! I didn't realize fluentd filters could be used.
