### ISSUE TITLE
container application logs to Splunk UI

### ISSUE THREAD

**Issue by indraindrajit71** [splunk/splunk-connect-for-kubernetes#443]
Hello
I wanted to get the logs  of my container application to be visible in Splunk UI. Didn't  wanted to use a sidecar container to achieve that. Is there a possibility via any configmap or something else.

Podname : nfs-pod
container : nfs-server
logpath inside container : /export/nfs-client.log

Though I tried below steps in values.yaml while getting the splunk setup using helm but it doesn't show any logs related to /export/nfs-client.log

    logs:
    nfs:
     from: 
       pod: nfs-pod
       container: nfs-server
       file:
         path: /export/nfs-client.log

```

`kubectl exec -it nfs-pod -n nfs sh
sh-5.0# cat  /export/nfs-client.log`
```

**Comment by chaitanyaphalak** [comment]
hey @indraindrajit71 we dont support this use case, please use the connector in the recommended way https://github.com/splunk/splunk-connect-for-kubernetes#prerequisites

**Comment by indraindrajit71** [comment]
Sure @chaitanyaphalak 
This I took care via making a symlink in the yaml for that specific Process ID:
https://serverfault.com/questions/599103/make-a-docker-application-write-to-stdout

Thanks for getting back. Closing this issue for now.
