### ISSUE TITLE
Splunk metrics pod crash unable to scrape metrics

### ISSUE THREAD

**Issue by rchenzheng** [splunk/splunk-connect-for-kubernetes#444]
**What happened**:
Metrics server keeps crashing/erroring out

```
│ 2020-08-20 02:02:37 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:cadvisor_metric_scraper error_class=RestClient::BadRequest error="400 Bad Request"                             │
│   2020-08-20 02:02:37 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response'                                                      │
│   2020-08-20 02:02:37 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'                                                                      │
│   2020-08-20 02:02:37 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'                                                                         │
│   2020-08-20 02:02:37 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'                                                                      │
│   2020-08-20 02:02:37 +0000 [error]: #0 /usr/share/ruby/net/http.rb:910:in `start'                                                                                                                       │
│   2020-08-20 02:02:37 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'                                                                               │
│   2020-08-20 02:02:37 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'                                                                                │
│   2020-08-20 02:02:37 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'                                                                                 │
│   2020-08-20 02:02:37 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-kubernetes-metrics-1.1.4/lib/fluent/plugin/in_kubernetes_metrics.rb:660:in `scrape_cadvisor_metrics'                         │
│   2020-08-20 02:02:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'                                                                            │
│   2020-08-20 02:02:37 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run_once'                                                                                          │
│   2020-08-20 02:02:37 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.6.0/lib/cool.io/loop.rb:88:in `run'                                                                                               │
│   2020-08-20 02:02:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'                                                                 │
│   2020-08-20 02:02:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'                                                             │
│ 2020-08-20 02:02:37 +0000 [error]: #0 Timer detached. title=:cadvisor_metric_scraper
```

**What you expected to happen**:
Should no be creating any errors

**How to reproduce it (as minimally and precisely as possible)**:

On-prem cluster with kubelet self signed certs with the following config

```
splunk-kubernetes-metrics:
  kubernetes:
    useRestClientSSL: false
```

**Anything else we need to know?**:
On-prem kubernetes

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.10
- Ruby version (use `ruby --version`): ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
- OS (e.g: `cat /etc/os-release`): RHEL 8.2

bash-4.4$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"
- Splunk version: Helm chart 1.4.2
- Others:

**Comment by matthewmodestino** [comment]
I believe this is due to calling the wrong kubelet port...

What flavour of k8s is this?

Can you please verify your `kubeletPort` or `kubeletPortAggregator`

Here's my MicroK8s configs:

```

#local config for metrics chart
splunk-kubernetes-metrics:
  logLevel: debug
  metricsInterval: 60s
  kubernetes:
    kubeletPort: 10255
    kubeletPortAggregator: 10250
    useRestClientSSL: false
    insecureSSL: true
    clusterName: MicroK8s
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-metrics
  splunk:
    hec:
      indexName: em_metrics

```

**Comment by chaitanyaphalak** [comment]
Yeah looks like the metrics daemonset cannot access kubelet rest api

**Comment by anderssv** [comment]
Anyone find a solution to this? Seeing similar behaviour on AKS with the Helm charts. Tried setting the ports and disabling SSL params.

**Comment by matthewmodestino** [comment]
I ran i to this last night when not using `use_rest_client_ssl` on 10250.

Please post the `kubernetes` section of your metrics chart

**Comment by anderssv** [comment]
This is my section. I've tried most combinations (I can think of) of true/false and with/without ports. :)

`
  kubernetes:
    kubeletAddress:
    kubeletPort: 10250
    kubeletPortAggregator: 10250
    useRestClientSSL: false
    insecureSSL: true
    caFile:
    bearerTokenFile:
    secretDir:
    clusterName: test-1-k8s
    openshift: false
`
Is the cluster name important, or just metadata that is applied to the logs?

**Comment by harshit-splunk** [comment]
@rchenzheng
Since you have disabled useRestClientSSL, error 404 is expected as it will sent http request to http server.
```
bash-4.4$ curl  http://192.168.49.2:10250/stats/summary 
Client sent an HTTP request to an HTTPS server.
```

**Comment by harshit-splunk** [comment]
Hey @rchenzheng, since kubelet's read only port is depreciated, we no longer have access to 10255 port (it accepts http connection). So  I would suggest to enable useRestClientSSL and use 10250 port which is default.

**Comment by harshit-splunk** [comment]
Closing the issue for now. Feel free to reopen or create a new issue if needed.
