### ISSUE TITLE
How to get Gke node reboot and shutdown logs using journald Systemd service unit

### ISSUE THREAD

**Issue by shanmukha511** [splunk/splunk-connect-for-kubernetes#445]
**What happened**:
i have implemented the journald configuration in my splunk but still i could not see node reboot logs.

I want to know that my gke node got restarted or not by checking the logs in splunk and i am not sure which systemd service unit holds that data

**What you expected to happen**:

i want to see logs to be reflected wn ever reboot happen on that gke node

**How to reproduce it (as minimally and precisely as possible)**:
 
i have gke cluster and have node running on os Container-optimized os and jst login to gke node and reboot that gke and in splunk we should get some logs stating gke node rebooted.

**Anything else we need to know?**:
configuration using to get journal configuration:

 **source.journald.conf: |-
    # This fluentd conf file contains configurations for reading logs from systemd journal.
    <source>
      @id journald-all
      @type systemd
      @label @CONCAT
      tag journald.journal:all
      path "/var/log/journal"
      matches []
      read_from_head true
      <storage>
        @type local
        persistent true
        path /var/log/splunkd-fluentd-journald-all.pos.json
      </storage>
      <entry>
        field_map {"MESSAGE": "log", "_SYSTEMD_UNIT": "source"}
        field_map_strict true
      </entry>
    </source>**

**Environment**:
- Kubernetes version (use `kubectl version`):  1.15.12-gke.2
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):   Container-Optimized OS (cos)
- Splunk version:
- Others:

**Comment by matthewmodestino** [comment]
we are discussing this on Slack channel. Trying to nail down what exactly SHOULD be collected for reboot to be captured.
