### ISSUE TITLE
Openshift 4.5 audit log: There are 2 and the one identified is not correct

### ISSUE THREAD

**Issue by brianotte** [splunk/splunk-connect-for-kubernetes#449]
**What happened**:  
Installed splunk-connect into an OKD 4.5 cluster

**What you expected to happen**: 
The following 2 audit files identified and sent to SPLUNK:
/var/log/kube-apiserver/audit.log
/var/log/openshift-apiserver/audit.log

**How to reproduce it (as minimally and precisely as possible)**:
100%

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
OKD 4.5 is the upstream Openshift 4.5:
oc version
Client Version: 4.5.0-0.okd-2020-08-12-020541
Server Version: 4.5.0-0.okd-2020-08-12-020541
Kubernetes Version: v1.18.3

- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
OKD uses Fedora CoreOS, which is the upstream RedHat CoreOS
cat /etc/os-release
`NAME=Fedora
VERSION="32.20200629.3.0 (CoreOS)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora CoreOS 32.20200629.3.0"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='32.20200629.3.0'`

- Splunk version:
8.0.5
- Others:

 I am relaying the methodology and the findings in hopes that it can be incorporated into future releases of splunk-connect (_specific for Openshift??_).  NOTE:  I find this release extremely useful and reliable.
 
However, I would like to relay a few points about the process.

- The audit logfile location identified in the values.yaml is incorrect for Openshift and does not exist.
- Needed to specify the metrics index to prevent installation error, even though not collecting metrics or installing (see below values.yaml provided).

**DETAILS:**
In Openshift 4.5, the audit file exist in 2 different files on the 3 master nodes, and is not what is specified in the released version of values.yaml.
 
/var/log/kube-apiserver/audit.log
/var/log/openshift-apiserver/audit.log
 
According to this values.yaml file:
https://github.com/splunk/splunk-connect-for-kubernetes/blob/53d5b0c1e333ad04c16a556aedd137f15c95a630/helm-chart/splunk-connect-for-kubernetes/values.yaml#L321
 
The audit file is located here – but it does not in Openshift 4.5:
/var/log/kube-apiserver-audit.log
 
I included my values.yaml to overwrite and also capture the openshift-apiserver audit log file.  Additionally, all documentation that I could find references helm2 install with tiller.  Openshift 4.5 supports helm3 (with annotations) and that is the process used here.
 
Thank you very much for your help and once again, this is a great tool.  It is much appreciated.
 
Please let me know if there is additional information I can provide.
 
Brian

`global:
  splunk:
    hec:
      host: "splunk.example.com"
      port: "1234"
      token: "REDACTED"
      indexName: "OKD-local-audit"
  kubernetes:
    clusterName: "OKD-local"
    openshift: "true"
splunk-kubernetes-logging:
  containers:
    logFormatType:  "cri"
    logFormat: "%Y-%m-%dT%H:%M:%S.%N%:z"
  logs:
    kube-audit:
      from:
        file:
          path: "/var/log/kube-apiserver/audit.log"
    openshift-apiserver:
      from:
        file:
          path: "/var/log/openshift-apiserver/audit.log"
  nodeSelector:
    node-role.kubernetes.io/master: ""
  kubernetes:
    clusterName: "OKD-local"
    openshift: "true"
splunk-kubernetes-objects:
  enabled: false
  kubernetes:
    clusterName: "OKD-local"
    openshift: "true"
splunk-kubernetes-metrics:
  enabled: false
  kubernetes:
    clusterName: "OKD-local"
    openshift: "true"
  splunk:
    hec:
      indexName: "OKD-local-metrics"`

helm3 install process:
`#/bin/bash

# FUNCTION:  check_return_code_function
# Check return code from previously run command.
# Will display error code and exit with 99 if previous function
# is anything but 0.

check_return_code_function () {
   RETURN_CODE=${?}
   if [ "$RETURN_CODE" -ne 0 ]
   then
      echo "RETURN_CODE is:  ${RETURN_CODE}"
      exit 99
   fi

   echo
   echo "SUCCESS!!!!"
   echo

   sleep 1
}

OCP_PROJECT="splunk-connect-ops"

wget https://github.com/splunk/splunk-connect-for-kubernetes/archive/release/1.4.3.zip
check_return_code_function

unzip 1.4.3.zip
check_return_code_function

oc adm new-project ${OCP_PROJECT} --node-selector="" --as=system:admin
check_return_code_function

oc project ${OCP_PROJECT}
check_return_code_function

helm3 install splunk-kubernetes-logging --namespace=${OCP_PROJECT} -f values.yaml splunk-connect-for-kubernetes-release-1.4.3/helm-chart/splunk-connect-for-kubernetes/
check_return_code_function

oc adm policy add-scc-to-user privileged -z splunk-kubernetes-logging -n ${OCP_PROJECT}
check_return_code_function

#helm3 uninstall splunk-kubernetes-logging --namespace=${OCP_PROJECT}
# check_return_code_function`

**Comment by brianotte** [comment]
Sorry about how the post looks.

**Comment by gp510** [comment]
Thanks @brianotte. I've created tickets for these enhancement requests. We'll consider including them in an upcoming release.

**Comment by matthewmodestino** [comment]
Thanks team, more of an experience thing for openshift users..

basically, when "openshift: true" point at known openshift audit log...

Technically the file path is customizable in kubelet settings, but may as well ship well know defaults for openshift.

**Comment by vinzent** [comment]
I opend a PR that provides an OpenShift 4 values example. https://github.com/splunk/splunk-connect-for-kubernetes/pull/546/files

**Comment by matthewmodestino** [comment]
Having being called to a bunch of "woahhhh thats a lot of logs!" calls around audit, I suggest this NOT be a default, but moved to the helm chart so customer can enable, provide path and bonus points for filter!!!

**Comment by vinzent** [comment]
@matthewmodestino indeed true, huge amount of data sent to Splunk. Unfortunately some sites have some requirements to ship and store it for years.

**Comment by matthewmodestino** [comment]
Im totally down with that! But after you as the customer press the big red button. :)

Also I wonder if docker-splunk image solely for audit would be better and leave fluentd to the app teams? any thoughts on that?
