### ISSUE TITLE
Openshift Audit logs Not getting Captured in Splunk

### ISSUE THREAD

**Issue by devopsksr** [splunk/splunk-connect-for-kubernetes#450]
I have OCP 4.4 multi node cluster in AWS environment and my splunk is also a stand alone instance. we have configured OCP Splunk integration through splunk-connect-for-kubernetes, Our requirement is to send the openshift audit logs aswell like project creation, project deletion, user addition, user deletion in OCP. I gave 
/var/log/kube-apiserver/audit.log
/var/log/openshift-apiserver/audit.log
path in the values.yml file so that openshift level audit logs also captured. But iam not able to see any openshift level audit logs  Does splunk-connect-for kubernetes doesnt capture openshift audit logs ?

I am attaching values.yml file along with the issue please go though it and let me know how to capture openshift audit logs.[
[prodvalues.txt](https://github.com/splunk/splunk-connect-for-kubernetes/files/5177867/prodvalues.txt)

](url)

**Comment by mwang2016** [comment]
@devopsksr this issue is related to #449
