### ISSUE TITLE
Custom filters too much indented

### ISSUE THREAD

**Issue by timdeluxe** [splunk/splunk-connect-for-kubernetes#453]
This line does too much indenting:
https://github.com/splunk/splunk-connect-for-kubernetes/blob/53d5b0c1e333ad04c16a556aedd137f15c95a630/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L298

The blanks in the code already intend the line by 8 blanks and the "indent 8" add another 8, resulting in 16 blanks at least for the first line, resulting in broken code.

Please fix it by either moving it all the way to the left or adding a "-" after the "{{" brackets.

**Comment by mwang2016** [comment]
Thanks @timdeluxe. I've created ticket for the enhancement request. We will consider including it in upcoming release.
