### ISSUE TITLE
daemonset splunk-kubernetes-logging not started on openshift

### ISSUE THREAD

**Issue by schose** [splunk/splunk-connect-for-kubernetes#454]
**What happened**:

When deploying SCK v1.4.3 using helm the daemonset for logging is not starting due to privileged container security settings. 

**What you expected to happen**:

daemonset need to be startet to collect container logsfiles.

**How to reproduce it (as minimally and precisely as possible)**:

start openshift playground: https://learn.openshift.com/playgrounds/openshift44/

```
oc create ns splunk-logging
oc config set-context --current --namespace=splunk-logging

helm install -f config.yml my-splunk-connect https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.4.3/splunk-connect-for-kubernetes-1.4.3.tgz --namespace=splunk-logging

oc describe daemonset/my-splunk-connect-splunk-kubernetes-logging --namespace=splunk-logging

```

Errorevents: 

```
 Warning  FailedCreate  27s (x14 over 68s)  daemonset-controller  Error creating: pods "my-splunk-connect-splunk-kubernetes-logging-" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000160000, 1000169999] spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]

```

**Anything else we need to know?**:

To get this work you need to create a SecurityContextConstraints for the SA User. Example: https://github.com/schose/splunk-connect-for-kubernetes/blob/openshift/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/ssc.yaml

unfortunately this breaks "helm install" functionality. "helm template" + "oc apply" is working.. 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ oc  version
Client Version: 4.4.0-202005290638-1960dd7
Server Version: 4.4.8
Kubernetes Version: v1.17.1+3f6f40d
````
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:
- Others:

**Comment by mwang2016** [comment]
Thank you @schose, I've created ticket for this issue. Our team will look into it.

**Comment by matthewmodestino** [comment]
I have been able to edit the templates directly to remove this:

https://github.com/splunk/splunk-connect-for-kubernetes/blob/53d5b0c1e333ad04c16a556aedd137f15c95a630/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/daemonset.yaml#L49

Looks like in a few clusters ( OpenShift, Gravity, etc) all we need is:

https://github.com/splunk/splunk-connect-for-kubernetes/blob/53d5b0c1e333ad04c16a556aedd137f15c95a630/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/daemonset.yaml#L50

**Comment by rockb1017** [comment]
Thank you Matthew. so does it mean we need to remove line number 49 for openshift and gravity?

**Comment by matthewmodestino** [comment]
I believe we may be able to get rid of it for all...need to test...

**Comment by rockb1017** [comment]
okay thank you!

**Comment by shane-emery** [comment]
Hello, I am also running into this issue.  I have tried removing that line (runAsUser: 0)and still getting similar error message:
oc describe daemonset/splunk-kubernetes-logging --namespace=splunk-connect
Name:           splunk-kubernetes-logging
Selector:       app=splunk-kubernetes-logging,release=splunk-kubernetes-logging
Node-Selector:  beta.kubernetes.io/os=linux
Labels:         app=splunk-kubernetes-logging
                app.kubernetes.io/managed-by=Helm
                chart=splunk-kubernetes-logging-1.4.3
                engine=fluentd
                heritage=Helm
                release=splunk-kubernetes-logging
Annotations:    deprecated.daemonset.template.generation: 1
                meta.helm.sh/release-name: splunk-kubernetes-logging
                meta.helm.sh/release-namespace: splunk-connect
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=splunk-kubernetes-logging
                    release=splunk-kubernetes-logging
  Annotations:      checksum/config: a47f085c03b6aaeed9fb71707cbf5d8d52c5fc385b9f29fed1426d9985e46bb3
                    prometheus.io/port: 24231
                    prometheus.io/scrape: true
  Service Account:  splunk-kubernetes-logging
  Containers:
   splunk-fluentd-k8s-logs:
    Image:      container-registry.icann.org/extra/fluentd-hec:1.2.4
    Port:       <none>
    Host Port:  <none>
    Limits:
      cpu:     100m
      memory:  200Mi
    Requests:
      cpu:     100m
      memory:  200Mi
    Environment:
      K8S_NODE_NAME:      (v1:spec.nodeName)
      MY_NAMESPACE:       (v1:metadata.namespace)
      MY_POD_NAME:        (v1:metadata.name)
      SPLUNK_HEC_TOKEN:  <set to the key 'splunk_hec_token' in secret 'splunk-kubernetes-logging'>  Optional: false
    Mounts:
      /fluentd/etc from conf-configmap (rw)
      /fluentd/etc/splunk from secrets (ro)
      /run/log/journal from journallogpath (ro)
      /var/log from varlog (rw)
      /var/log/pods from varlogdest (ro)
  Volumes:
   varlog:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log
    HostPathType:
   varlogdest:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log/pods
    HostPathType:
   journallogpath:
    Type:          HostPath (bare host directory volume)
    Path:          /run/log/journal
    HostPathType:
   conf-configmap:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      splunk-kubernetes-logging
    Optional:  false
   secrets:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  splunk-kubernetes-logging
    Optional:    false
Events:
  Type     Reason        Age                    From                  Message
  ----     ------        ----                   ----                  -------
  Warning  FailedCreate  2m18s (x39 over 140m)  daemonset-controller  Error creating: pods "splunk-kubernetes-logging-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]

**Comment by jj1yang** [comment]
Shane, Is the problem with the /var/log mount permission being denied on the OKD 4.5/SCK 1.4.3 platform? Thanks. -Jim

**Comment by shane-emery** [comment]
I believe so.  The /var/log from the node can be mounted, but if I look at the fluentd logs or manually login and run an ls command on the folder…I get a permission denied.  I am told it is an issue with SCC policy maybe not in place for the splunk-logging role?

 

Shane Emery
Software Engineer, Platforms
Internet Corporation for Assigned Names and Numbers (ICANN)Direct Line: +1 310-699-4356
Direct Fax: +1 310-699-4356
Skype: shane.emery.icann
www.icann.org

**Comment by shane-emery** [comment]
This got it working for me.
1. readd line 49
2. oc adm policy add-scc-to-user privileged system:serviceaccount:splunk-connect:splunk-kubernetes-logging

**Comment by matthewmodestino** [comment]
bingo...this works because it allows the service account the permission to `runAsUser 0` which is what is required. we do not need privilege!! so you can be sure to set that to false....all you need is "runAsUser 0" because the container logs are stored as "root:root" by default. 

This is the key section in the deployment. 

https://github.com/splunk/splunk-connect-for-kubernetes/blob/8ba455e7f988d129c9bfa13fdcf2025c6c4ae724/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/daemonset.yaml#L52-L54

and as you said the other item is then giving the service account the permission to run the pod as user 0 aka root, but NOT necessarily a "privileged" workload.
