### ISSUE TITLE
Preventing plugin logs getting pushed to Splunk

### ISSUE THREAD

**Issue by ashwanikrsharma** [splunk/splunk-connect-for-kubernetes#458]
**What happened**:
I am using attached fluentd configuration and able to push logs to splunk
[fluentd-config.yaml.zip](https://github.com/splunk/splunk-connect-for-kubernetes/files/5198794/fluentd-config.yaml.zip)

There are logs from plugins also getting pushed to Splunk which I want to avoid. (See image below)
<img width="1425" alt="Screen Shot 2020-09-10 at 7 42 17 AM" src="https://user-images.githubusercontent.com/5451048/92674005-1093dd00-f33a-11ea-8bb7-ef31707266fe.png">
<img width="1014" alt="Screen Shot 2020-09-10 at 7 49 25 AM" src="https://user-images.githubusercontent.com/5451048/92674118-4b961080-f33a-11ea-9af1-5763d729a3b7.png">

**What you expected to happen**:
I want to avoid the logs getting pushed by monitoring agent

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: Kubernates - v1.16.6
- Kubernetes version (use `kubectl version`):
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`): Mac
- Splunk version: 
- Others: Using Docker for Desktop and running single cluster using it locally on Mac

**Comment by rockb1017** [comment]
hi. the data in the image seems to come from object pod. if you don't want objects, you can disable it. 
https://github.com/splunk/splunk-connect-for-kubernetes/blob/23043b915ddcd943a07aa610b9463f88727736ba/helm-chart/splunk-connect-for-kubernetes/values.yaml#L456
make it `false`

**Comment by rockb1017** [comment]
I will close this issue.
