### ISSUE TITLE
Metrics Aggregator Connection Refused errors

### ISSUE THREAD

**Issue by brian-pratt** [splunk/splunk-connect-for-kubernetes#460]
We consistently get these errors with Metrics Aggregator (grabbed with kubectl logs metrics-agg-pod-name).  No firewalls within Kubernetes at all, all of its external to NSX-T.  How do we resolve the connectivity??

2020-09-08 16:22:18 +0000 [error]: #0 Failed to get limit metrics, error=, #<Errno::ECONNREFUSED: Failed to open TCP connection to 10.100.200.1:443 (Connection refused - connect(2) for "10.100.200.1" port 443)>
2020-09-08 16:22:18 +0000 [error]: #0 Failed to get node metrics, error=, #<Errno::ECONNREFUSED: Failed to open TCP connection to 10.100.200.1:443 (Connection refused - connect(2) for "10.100.200.1" port 443)>
2020-09-08 16:22:18 +0000 [error]: #0 Failed to get resource usage metrics, error=, #<Errno::ECONNREFUSED: Failed to open TCP connection to 10.100.200.1:443 (Connection refused - connect(2) for "10.100.200.1" port 443)>
2020-09-08 16:22:33 +0000 [error]: #0 Failed to get resource usage metrics, error=, #<Errno::ECONNREFUSED: Failed to open TCP connection to 10.100.200.1:443 (Connection refused - connect(2) for "10.100.200.1" port 443)>

$ k get svc kubernetes
NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.100.200.1   <none>        443/TCP   413d

Environment Info
PKS 1.7.1 running on NSX-T 2.5.1
No firewalls within Kubernetes at all, all of its external to NSX-T 
Kubernetes 1.16.2 (with some vmware bugs, hence the +vmware version I sent you in chat)
PodSecurityPolicies are in play, but I am using the ones provided by SC
This is all Bosh deployed stuff, I can’t add packages to VMs or change the VM’s at all.

**Comment by rockb1017** [comment]
could you share your `values.yaml` file for metrics chart ?

**Comment by matthewmodestino** [comment]
Possibly pod security policies?

**Comment by brian-pratt** [comment]
Here is the values.yml config:

global:
  logLevel: info
  splunk:
    hec:
      host: REDACTED
      port: 8088
      token: REDACTED
      protocol: http
      insecureSSL: true
  kubernetes:
    # The cluster name used to tag logs. Default is cluster_name
    clusterName: "REDACTED"

splunk-kubernetes-logging:
  enabled: true
  serviceAccount:
    create: true
    name: splunk-connect-sa-logging
  podSecurityPolicy:
    create: true
  splunk:
      indexName: "REDACTED"
  image:
    registry: REDACTED
    name: splunk/fluentd-hec
    tag: 1.2.2

splunk-kubernetes-objects:
  enabled: true
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-connect-sa-objects
  podSecurityPolicy:
    create: true
  kubernetes:
    insecureSSL: true
  splunk:
      indexName: "kubernetes"
  image:
    registry: REDACTED
    name: splunk/kube-objects
    tag: 1.1.3

splunk-kubernetes-metrics:
  enabled: true
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-connect-sa-metrics
  podSecurityPolicy:
    create: true
  splunk:
    hec:
      indexName: "kubernetes_metrics"
  image:
    registry: REDACTED
    name: splunk/k8s-metrics
    tag: 1.1.3
  imageAgg:
    registry: REDACTED
    name: splunk/k8s-metrics-aggr
    tag: 1.1.2
  kubernetes:
    useRestClientSSL: true
    insecureSSL: true

**Comment by rockb1017** [comment]
just in case, could you upgrade SCK chart to latest ? 1.4.3

**Comment by matthewmodestino** [comment]
its gotta be firewall or policy based..have u checked with VMWare support??
