### ISSUE TITLE
Alerts 

### ISSUE THREAD

**Issue by fshadid96** [splunk/splunk-connect-for-kubernetes#463]
Hi, 

I am running SCK 1.4.3 on an Openshift Cluster and I would like to setup Splunk Alerts. Is there any predefined Alerts that could be used?

**Comment by schose** [comment]
There are no predefined alerts by the SCK. There are some alerts and prebuild panels in the "Splunk Add-on for Kubernetes" https://splunkbase.splunk.com/app/3991/ but this app is deprecated.

**Comment by schose** [comment]
There is also an Integration in the Splunk App for Infrastructure (https://splunkbase.splunk.com/app/3975/). There the user could create easys Alerts, but only for metrics.

**Comment by rockb1017** [comment]
Thank you! closing
