### ISSUE TITLE
Interpreting metrics values

### ISSUE THREAD

**Issue by bdschaap** [splunk/splunk-connect-for-kubernetes#465]
I'm having difficult interpreting some of the metrics that SCK collects.  For instance, I have values such as 1587075436 and 1601232839 for kube.node.cpu.usage that are recorded every 5 minute.  The values are both increasing and decreasing over time (not just increasing).  Can someone help me understand how to interpret the values being recorded?

**Comment by rockb1017** [comment]
Are you following this to browse your metrics data? https://docs.splunk.com/Documentation/Splunk/8.0.6/Metrics/Search
it is usage of cpu of certain kubernetes node. the total amount depends on number of CPUs on the node.

**Comment by bdschaap** [comment]
Yes I use mstats.  I ended up figure out my issue after your response.  I appreciate the response.
