### ISSUE TITLE
Using cluster-autoscaler leads to data loss

### ISSUE THREAD

**Issue by ryantate13** [splunk/splunk-connect-for-kubernetes#468]
**What happened**:
Each time the [cluster-autoscaler](https://github.com/kubernetes/autoscaler) scales down our cluster, whatever logs are currently being processed are lost.

**What you expected to happen**:
I'd expect that `SCK` would manage annotations on the node to prevent this from happening.

**How to reproduce it (as minimally and precisely as possible)**:
Write logs quickly enough that each node has not finished processing them before a scale down event occurs.

**Anything else we need to know?**:
The [cluster-autoscaler FAQ](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-prevent-cluster-autoscaler-from-scaling-down-a-particular-node) mentions the specific remediation for this. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16
- Ruby version (use `ruby --version`): ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
- OS (e.g: `cat /etc/os-release`):
```
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"
```
- Splunk version: Enterprise
- Splunk Connect for Kubernetes helm chart version: 1.4.3
- Others: Running on EKS

**Comment by ryantate13** [comment]
Related
<https://github.com/kubernetes/autoscaler/pull/2759>

**Comment by chaitanyaphalak** [comment]
@ryantate13 it would be awesome if you could contribute a PR for this request.
