### ISSUE TITLE
Add chart to a helm chart repository

### ISSUE THREAD

**Issue by DTTerastar** [splunk/splunk-connect-for-kubernetes#470]
**What would you like to be added**:

Can we put this in a proper helm chart repository?

**Why is this needed**:

Helmfile doesn't like raw tgz files, if this is in a helm repository it would be much easier to work with and be like everything else.  Helmfile works just fine w/ custom repos so it doesn't really matter where it goes just needs this setup: https://helm.sh/docs/topics/chart_repository/

**Comment by rockb1017** [comment]
I will be working on this sooner than later. please feel free to comment any other requirements.

**Comment by rockb1017** [comment]
Hello,
our chart is hosted on github pages. you can pull as below
```
helm repo add splunk https://splunk.github.io/splunk-connect-for-kubernetes/

helm show values splunk/splunk-connect-for-kubernetes > values.yaml

helm install sck splunk/splunk-connect-for-kubernetes -f values.yaml
```
