### ISSUE TITLE
Can we run sck as non root user?

### ISSUE THREAD

**Issue by shanmukha511** [splunk/splunk-connect-for-kubernetes#476]
**What happened**:

Trying to run sck instead of root user to fluent user  using fsgroup id of fluent group and pod going for crashbackup with below error. below code using in deamonset

**securityContext:
          runAsUser: 998
          fsGroup: 995**

ERROR

**`/opt/app-root/src` is not writable.
Bundler will use `/tmp/bundler20201001-1-odi77f1' as your home directory temporarily.
2020-10-01 12:10:26 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2020-10-01 12:10:26 +0000 [info]: gem 'fluentd' version '1.9.1'
2020-10-01 12:10:26 +0000 [info]: gem 'fluent-plugin-concat' version '2.4.0'
2020-10-01 12:10:26 +0000 [info]: gem 'fluent-plugin-jq' version '0.5.1'
2020-10-01 12:10:26 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.5.2'
2020-10-01 12:10:26 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.7.0'
2020-10-01 12:10:26 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.2.4'
2020-10-01 12:10:26 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2020-10-01 12:10:27 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Plugin storage path '/var/log/splunkd-fluentd-journald-docker.pos.json' is not readable/writable"**

**What you expected to happen**:

we should be able to run sck using non root user.

**How to reproduce it (as minimally and precisely as possible)**:

in daemon set change run asuser from root  to fluent user id and using fsgroup

**Anything else we need to know?**:

Is it mandate that sck should be run as root user?

**Environment**:

- Kubernetes version (use `kubectl version`): 1.15
- Ruby version (use `ruby --version`): ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
- OS (e.g: `cat /etc/os-release`): 
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]

- Splunk version:
- Splunk Connect for Kubernetes helm chart version: 1.4.3
- Others:

**Comment by matthewmodestino** [comment]
no. container engines put down logs as root/root. 

You can however deploy without the need for privilege pod based on my latest tests

**Comment by shanmukha511** [comment]
Hi @matthewmodestino 

Below is the daemon set i have modified and used init container to change directory permission to fluent user.

**Daemonset**

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: splunk-kubernetes-logging
  labels:
    app: splunk-kubernetes-logging
    engine: fluentd
    version: 1.4.3
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: splunk-kubernetes-logging
  template:
    metadata:
      labels:
        app: splunk-kubernetes-logging
        version: 1.4.3
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '24231'
    spec:
      serviceAccountName: splunk-kubernetes-logging
      nodeSelector:
        beta.kubernetes.io/os: linux
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      initContainers:
      - name: init
        image: busybox:latest
        command: ["sh","-c","chown -R 998:995 /var/log  && chown -R 998:995 /var/lib/docker/containers "]
        volumeMounts:
        - name: varlog
          mountPath: "/var/log"
        - name: varlogdest
          mountPath: "/var/lib/docker/containers"
      containers:
      - name: splunk-fluentd-k8s-logs
        image: docker.io/splunk/fluentd-hec:1.2.4
        imagePullPolicy: Always
         env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SPLUNK_HEC_TOKEN
          valueFrom:
            secretKeyRef:
              name: splunk-kubernetes-logging
              key: splunk_hec_token
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: "/var/log"
        - name: varlogdest
          mountPath: "/var/lib/docker/containers"
          readOnly: true
        - name: journallogpath
	  mountPath: "/run/log/journal"
          readOnly: true
        - name: conf-configmap
          mountPath: "/fluentd/etc"
        - name: secrets
          mountPath: "/fluentd/etc/splunk"
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: "/var/log"
      - name: varlogdest
        hostPath:
          path: "/var/lib/docker/containers"
      - name: journallogpath
        hostPath:
          path: "/run/log/journal"
      - name: conf-configmap
        configMap:
          name: splunk-kubernetes-logging
      - name: secrets
        secret:
          secretName: splunk-kubernetes-logging

But after that /var/log and /var/lib/docker/container will have fluent owner and group permission but issue is here the container files will be newly created and owned by root and fluent user cant read. And we are getting error like below 

**2020-10-07 16:09:38 +0000 [warn]: #0 [containers.log] /var/log/containers/splunk-kubernetes-logging-7qm74_default_splunk-fluentd-k8s-logs-4e3d29f37a4cc6cf5090c14b003060471a09f8815429a592829cdcce689d518f.log unreadable. It is excluded and would be examined next time.**

 how can we fix this?
our end goal is to run pod with fluent user .

**Comment by matthewmodestino** [comment]
no.

Please consult your k8s support/admin.

I do not recommend messing with permissions as they are governed by the container engine and this solution is designed to deploy in standard environments, which over the last few years, afaik, include the need for root to pick up json files.
