### ISSUE TITLE
Support for k8sMetadata podAnnotations

### ISSUE THREAD

**Issue by jason-riddle** [splunk/splunk-connect-for-kubernetes#477]
**What would you like to be added**: Similar to being able to search for pod labels by specifying `podLabels`, I'd like to also be able to search for specific annotations.

**Why is this needed**: Applications such as kube2iam and consul connect rely on certain annotations being defined. Therefore if there is an issue with assigning an IAM role or a troubleshooting consul connect injection pod, you need to know what annotation was used. Having this info readily available in splunk should help greatly with troubleshooting.

**Comment by matthewmodestino** [comment]
Hey Jason, while the log stream doesn't contain annotation today the metadata collected from the "objects" pod does and can be easily correlated with the log data!

what I usually do is create a dashboard powered by the objects data,  that the users then come in and choose dropdowns like, cluster_name, namespace, label, app, then when they click their deployment or pod, the dashboard dynamically brings up all the pod's logs! 

Are you running the objects pod in your deploy?

**Comment by jason-riddle** [comment]
Not currently, but I'll check that out instead! Thanks.
