### ISSUE TITLE
Can't search for fields attached to events

### ISSUE THREAD

**Issue by tjarjoura** [splunk/splunk-connect-for-kubernetes#478]
When events are added to Splunk via fluentd and the HEC collector they get certain fields attached such as "label_app" and "container_name". However, when I try to search on these fields from Splunk it doesn't return any results. I did some digging and found that this is likely the cause: https://community.splunk.com/t5/Splunk-Search/Why-can-t-I-search-for-my-extracted-field/m-p/51642

So it seems like the solution would be to set INDEXED_VALUE=false for these added fields. Is there a way to do that with fluentd? Or is there some other way I should do that? I looked through the docs but didn't see anything related to this.

Of course there is a workaround to do the search by adding `field::value` instead, but it would nice to be able to do it the normal way.

**Comment by gp510** [comment]
Hi @tjarjoura , there are two ways to do this. The one you mentioned above (field::value) and by using fields.conf. https://github.com/splunk/splunk-connect-for-kubernetes#searching-for-sck-metadata-in-splunk
