### ISSUE TITLE
Splunk-connect - Fluentd multi-process for using multiple CPU for pod.

### ISSUE THREAD

**Issue by dengalebr** [splunk/splunk-connect-for-kubernetes#482]
We are looking some help / reference for SCK multi-process sample along with multi-thread (num_threads) configurations.

https://docs.fluentd.org/v/0.12/articles/performance-tuning-multi-process

**What happened**:
We are getting delay in processing and fluentd pod is using max 1 CPU only, we wanted to provide more resources to fluentd pod for faster processing.

**What you expected to happen**:
With more CPU with multi-process and threads we expect better performance and less delay.

**How to reproduce it (as minimally and precisely as possible)**:
we can pump in 20k event/sec and it will delay the processing, Also fluentd pod will be maximum 1 CPU.

**Comment by luckyj5** [comment]
@dengalebr Thanks for raising this, we'll look into it and update you for the same. Thanks!

**Comment by dengalebr** [comment]
Thank you @luckyj5

**Comment by rockb1017** [comment]
Hi, 
in the doc https://docs.fluentd.org/deployment/multi-process-workers, it is specified that only one worker can be assigned to `in_tail` plugin. and the throughput limit comes from this plugin. it cannot tail faster than ~3k eps. 
So even with multi-process setting, it will only slightly increase the throughput. 

On that note, we are actively working on the open-telemetry collector based solution. It scales really well and should be able to handle 20k eps. Let us know if you would be interested in trying when beta version is out.

**Comment by vinzent** [comment]
@rockb1017 will this open-telemetry based solution completly replace this fluentd based solution ?

**Comment by harshit-splunk** [comment]
Hey @dengalebr, we suggest you to migrate to SCK-otel
Why you should migrate to SCK-Otel: https://github.com/signalfx/splunk-otel-collector-chart/blob/main/docs/migration-from-sck.md
Migration guide: https://github.com/signalfx/splunk-otel-collector-chart/blob/main/docs/migration-from-sck.md

**Comment by harshit-splunk** [comment]
Closing the issue for now. Feel free to reopen this issue or create a new one.
