### ISSUE TITLE
Will splunkconnect buffer logging events if network connection is down?

### ISSUE THREAD

**Issue by wrahmann** [splunk/splunk-connect-for-kubernetes#483]
Hi,

Will Splunkconnect ( or fluentd) buffer logging events in case of network failure? If so , what is that memory buffer value? Is it below configuraiton?

  buffer:
    "@type": memory
    total_limit_size: 600m
    chunk_limit_size: 20m
    chunk_limit_records: 10000
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 5
    retry_type: periodic

Wajih

**Comment by luckyj5** [comment]
@wrahmann Yes, it comes with buffer capabilities and it's designed to store incoming stream temporarily before transmitting the stream to its destination (in our case, to Splunk). 
By default, when the buffer gets full, we block all the input plugins from sending more data to buffer, which can be tweaked using a configurable setting  `overflow_action`under buffer config section. 
It comes with built-in retry mechanism to support scenarios where the data couldn't be sent to its destination for number of reasons: - network failure, connectivity issues, capacity exceeded etc. 
More info on memory buffer - https://docs.fluentd.org/buffer/memory
Please let us know if any questions. 
Thanks!

**Comment by vinzent** [comment]
The default buffer config is bound to memory. If your Splunk server isn't reachable for a longer time, you probably will start loosing logs.

AFAIK once the log is transferd to the buffer, the source logfile position is peristed.

`retry_max_times: 5` will discard log chunks after 5 retries. 

Or if the pod is killed, you loose the memory buffer too.

https://docs.fluentd.org/buffer#handling-successive-failures

Possible other situation how you could loose logs:  If your splunk server can't cope with the speed you're delivering messages and `overflow_action: block` is hit, reading of logs is blocked. If your containers are producing logs too fast, it might be that the container logs get rotated before fluentd is able to read them.

**Comment by foram-splunk** [comment]
Hey @wrahmann , are you still facing this issue ? Please let us know .

**Comment by foram-splunk** [comment]
Closing this issue . Feel free to re-open it ,if you face the same issue again .
