### ISSUE TITLE
Metrics not shown correctly

### ISSUE THREAD

**Issue by Christoph-Raab** [splunk/splunk-connect-for-kubernetes#484]
**What happened**:
Memory metrics don't make sense for node / namespace / pod / kubectl top.

**What you expected to happen**:
Memory metrics are consitent.

**How to reproduce it (as minimally and precisely as possible)**:
Run kubectl top for node and pod:
``kubectl top node`` and ``kubectl top pod -n default``.

Sum up all memory metrics for nodes and for the namespace.

In Splunk Search:
Run node and namespace metrics query for last 15 minutes:

Node:
```
| mstats p90(kube.node.memory.usage_bytes) as p90 WHERE index=metrics_index by node 
| eval p90 = p90/10000000000 
| stats sum(p90) as sum_p90
```

Namespace:
```
| mstats p90(kube.namespace.memory.usage) as p90 WHERE index=metrics_index span=5min by name 
| eval p90=p90/1000000
```

Pod:
```
| mstats p90(kube.pod.memory.usage_bytes) as p90 WHERE index=metrics_index span=5min by pod-name 
| eval p90=round(p90/1000000, 0)
```

In my case: (3 nodes, default namespace with 10 pods)
Node:
- kubectl top node: sum 14000
- splunk search for node: 3700

Namespace:
- kubectl top pod -n default: sum = 3950
- splunk search for namespace, value of default: 4740

Pod (one random pod):
- kubectl top pod: 1415
- splunk search for pod: 1478

**Anything else we need to know?**:
Splunk-Kubernetes-Connector is set up with defaults.
```
splunk-kubernetes-metrics:
  splunk:
    hec:
      indexName: metrics_index
```

I don't run splunk, I run kubernetes, send my output to a 3rd party HEC and configured dashboards. What happens in between is a black box for me.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"afea77eefe3272c0f53c4552183ecb16c091db41", GitTreeState:"clean", BuildDate:"2020-09-17T06:32:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Splunk Connect for Kubernetes helm chart version: 1.4.2

**Comment by luckyj5** [comment]
@Christoph-Raab Thanks for reporting this issue. I have created an internal ticket to further investigate and work on this issue. Will reach out if any additional info is needed. Thanks!

**Comment by Christoph-Raab** [comment]
Any update on this?

**Comment by rockb1017** [comment]
Please refer to this page for metrics information 
https://github.com/splunk/fluent-plugin-kubernetes-metrics/blob/develop/metrics-information.md
Also are you calculating `p90` of it and comparing? 
and dividing it by 1 million will not give you right MB.
