### ISSUE TITLE
OCP4 (CRI-O Engine) and the Splunk-connector-for-kubernetes log lines are separated

### ISSUE THREAD

**Issue by mcpdev80** [splunk/splunk-connect-for-kubernetes#487]
**What happened**:

We have currently observed a strange behavior in the logging of the OCP4 (CRI-O Engine) and the Splunk-connector-for-kubernetes
The connector actually works as expected, but individual log lines are separated into several lines

The logs in the Openshift Build-Pod (so far only occurred with these) look completely normal. About as:

`... [INFO] DM :: AVShare :: Messaging :: Payload DM-ES ........ SUCCESS [0.471 s] ....`

The engine of the new Openshift 4 called CRI-O only writes such logs in chunks in the file system of the respective worker node. The log shown looks like this:

~~~ 
.....
2020-10-05T04: 38: 15.957601404 + 00: 00 stdout P [INFO] DM :: AVShare :: Messagi
2020-10-05T04: 38: 15.957613838 + 00: 00 stdout P ng :: Pa
2020-10-05T04: 38: 15.957623665 + 00: 00 stdout P yloa
2020-10-05T04: 38: 15.957633327 + 00: 00 stdout P d DM-
2020-10-05T04: 38: 15.957643860 + 00: 00 stdout P ES ..
2020-10-05T04: 38: 15.957653967 + 00: 00 stdout P ...... SUCC
2020-10-05T04: 38: 15.957663734 + 00: 00 stdout P ESS
2020-10-05T04: 38: 15.957673538 + 00: 00 stdout P [0
2020-10-05T04: 38: 15.957683290 + 00: 00 stdout P .471
2020-10-05T04: 38: 15.957693080 + 00: 00 stdout F s] .....
...
~~~

In this case, the Splunk Connector works properly and then grabs these torn log fragments and sends them to the Splunk. Works as designed but incredibly unattractive in practice.

We have already checked with RedHat. It is completely normal that the log lines are saved in such a torn way. You can't do anything about that. According to RedHat, the splunk-connector is not supported by RH, so no help can be expected here.

The Splunk connector knows that it is the CRI-O engine, because this is stored in the config and in the Helm chart:
Because he always parses the beginning of the line and cuts away the beginning so that only the content of the log remains:

E.g.:
`Log: 2020-10-05T04: 38: 15.957601404 + 00: 00 stdout P [INFO] DM :: AVShare :: Messagi`

Connector is sending this to splunk: `[INFO] DM :: AVShare :: Messagi `

Timestamp up to and including “stdout P / F” is always cut off here.

Helmchart value:  `logFormatType: cri`

The logic behind these lines is as follows: Everything that ends in “stdout P” is an incomplete line (the line is therefore abruptly torn off here). But lines ending in “stdout F” correspond to a complete line or, in this case, a line end. So you can always tell what a complete log line would correspond to (all "stdout P" summarized up to the next "stdout F")

The question is, can you reconfigure the splunk-connector so that it combines these separate log lines (stdout P to the next stdout F) into one line?

**Environment**:
- OpenShift 4.5.14
- Splunk version: Splunk Enterprise 8.0.3
- Splunk Connect for Kubernetes helm chart version: 1.4.2

**Comment by rockb1017** [comment]
Hello,

I think using `concat` plugin and regex parsing, it seems possible but you need to find the pattern for either the start or the end of log data. https://github.com/fluent-plugins-nursery/fluent-plugin-concat

once you have regex pattern, I think you can set it here: 
https://github.com/splunk/splunk-connect-for-kubernetes/blob/fefbcf4a2b9f9e71a18044498dba27aecc9461f6/helm-chart/splunk-connect-for-kubernetes/values.yaml#L163

**Comment by mcpdev80** [comment]
Hi @rockb1017,

Thank you for your help! 

However, I just don't know how and where to install the plugin. 

Could you help us again?

**Comment by rockb1017** [comment]
this plugin is already installed with the image we are using for SCK logging pod. 
just edit the `values.yaml` file you are using to deploy.

I would start by reading thoroughly of the comments on the `values.yaml` file and https://github.com/fluent-plugins-nursery/fluent-plugin-concat this github page docs.

**Comment by vinzent** [comment]
I see, i've created a duplicate issue report: https://github.com/splunk/splunk-connect-for-kubernetes/issues/549
