### ISSUE TITLE
Metrics missing from Analytics

### ISSUE THREAD

**Issue by jurschel** [splunk/splunk-connect-for-kubernetes#488]
**What happened**:
I do not see container_cpu_cfs_throttled_seconds_total when I view metrics as I believe the [fluent plugin for kubernetes](https://github.com/splunk/fluent-plugin-kubernetes-metrics/blob/master/metrics-information.md) that you say you use makes available via cAdvisor metrics.  This value is available for node and pod however to understand if containers are being throttled we need to collect this metric.  It becomes particularly necessary when running in an istio/opa environment where you have multiple sidecar containers in a pod.

**What you expected to happen**:
When I drill into Splunk metrics I expect to see that metric
**How to reproduce it (as minimally and precisely as possible)**:
Drill into the metrics page and find it missing
**Anything else we need to know?**:
No
**Environment**:
- Kubernetes version
v1.14.10-gke.50
- OS 
GKE
- Splunk version
Cloud instance v8.0.2007
- Splunk Connect for Kubernetes helm chart version
1.4.3
- Others:

**Comment by mwang2016** [comment]
Thank you @jurschel , I've created a ticket for this issue. We'll consider including this in an upcoming release.

**Comment by harshit-splunk** [comment]
Hey @jurschel , Metric plugin should collect `container_cpu_cfs_throttled_seconds_total` metric from cAdvisor endpoint by default. (Reference https://github.com/splunk/fluent-plugin-kubernetes-metrics/blob/master/metrics-information.md#cadvisor-metrics)
Is it the case that container is throttling but the metric isn't appearing in the splunk?

**Comment by harshit-splunk** [comment]
Closing the ticket for now. If still facing the issue, feel free to reopen this one ore crate a new one
