### ISSUE TITLE
Source Specific Custom Metadata

### ISSUE THREAD

**Issue by wrahmann** [splunk/splunk-connect-for-kubernetes#491]
<

**What would you like to be added**:
Some of the applications in our environment are writing logs to file on persistent volume and information related to  Kubernetes environment is lost such namespace, pod name etc. For all these logs file, I would like to add metadata which includes this missing information which is known such as namespace or pod name etc.

This inclusion of metadata shall be specific to files only.

**Why is this needed**:
Logs read from the files can be filtered in Splunk base on the namespace, pod name etc.

![image](https://user-images.githubusercontent.com/70699596/97826258-32e02080-1d15-11eb-9ffd-eb04f2fae075.png)

**Comment by cheneysplunk** [comment]
@wrahmann I guess you need an addon with props.conf to add some field extractions for namespace & pod, and install this addon on Splunk forwarder or indexer for log file monitoring? If so, I'm afraid it's out of our scope. Anyways I can help to create a ticket and hopefully our PM can put some comments. Thank you.

**Comment by wrahmann** [comment]
> @wrahmann I guess you need an addon with props.conf to add some field extractions for namespace & pod, and install this addon on Splunk forwarder or indexer for log file monitoring? If so, I'm afraid it's out of our scope. Anyways I can help to create a ticket and hopefully our PM can put some comments. Thank you.

@cheneysplunk 

Thank you so much for your feedback. My understanding was all this data is being passed from fluentd.  If that is correct then it is better to add at the source? 

Do create a ticket and we can follow from there.

**Comment by cheneysplunk** [comment]
@wrahmann , created following ticket and assigned to our PM. Feel free to add more comments there.
https://jira.splunk.com/browse/ADDON-30794
BTW, fluentd input will be available on UF soon. Maybe we can have a try as well. 
To be clear, file monitoring, fluentd input & k8s connector are 3 different GDI solutions. We need to enable fields for search separately.  Saying that this feature request will not be a part of this github repo, but another product in SplunkBase.

**Comment by rockb1017** [comment]
@wrahmann 
To enrich with k8s metadata info, the record need to have `docker.container_id, kubernetes.namespace_name, kubernetes.pod_name, kubernetes.container_name,` to query k8s api server.
https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter

**Comment by gjanders** [comment]
@cheneysplunk please keep in mind that non-Splunk employees do not have access to the internal Splunk jira so therefore cannot add comments!

**Comment by wrahmann** [comment]
> @wrahmann , created following ticket and assigned to our PM. Feel free to add more comments there.
> https://jira.splunk.com/browse/ADDON-30794
> BTW, fluentd input will be available on UF soon. Maybe we can have a try as well.
> To be clear, file monitoring, fluentd input & k8s connector are 3 different GDI solutions. We need to enable fields for search separately. Saying that this feature request will not be a part of this github repo, but another product in SplunkBase.

@cheneysplunk ,
We tried to add our comments but had no access. Please update us if there is feedback available on this JIRA ticket at your end.
