### ISSUE TITLE
How to override docker image pull repo link

### ISSUE THREAD

**Issue by vinitmasaun** [splunk/splunk-connect-for-kubernetes#494]
We have a need to pull docker images from an internal docker respository which caches external repos (e.g docker.io).  How can I override the default docker.io ImagePull repo defined in the deamonset.yml file?

**Comment by rockb1017** [comment]
you can edit from the values.yaml file you use to deploy this chart.

**Comment by vinitmasaun** [comment]
> you can edit from the values.yaml file you use to deploy this chart.

How do define the override?  The example values.yaml doesn't provide the structure or where in the yaml this Image repo should be defined.  In the global section or in the individual subchart section?  Is it just one parameter or do I need to define the entire container spec section?

**Comment by rockb1017** [comment]
you can edit them here
https://github.com/splunk/splunk-connect-for-kubernetes/blob/3e93231eabd83638025378d9338fc3621a569dca/helm-chart/splunk-connect-for-kubernetes/values.yaml#L327

**Comment by rockb1017** [comment]
closing
