### ISSUE TITLE
Multiple Splunk Integration

### ISSUE THREAD

**Issue by wrahmann** [splunk/splunk-connect-for-kubernetes#496]
Hi, 

I have two questions:

Can one deployment of SCK be used to integrate with multiple Splunk HEC?  We have a requirement to copy the logs to a different instance. or Should I run two different instances of SCK?

Another requirement we have is to send the logs to primary Splunk deployment which is replicating the logs to another instance. In case of failure, How can we send the logs to the secondary instance? We do not have a load balancer.

Thanks for your feedback.

**Comment by rockb1017** [comment]
This chart doesn't support sending it to multiple HEC out of the box.
It is possible with customizing the fluentd pipeline to copy the data and send it to a different HEC endpoint. 
you would have to copy this repo locally and edit `template/configmap.yaml`. 
https://docs.fluentd.org/output/copy

**Comment by wrahmann** [comment]
> This chart doesn't support sending it to multiple HEC out of the box.
> It is possible with customizing the fluentd pipeline to copy the data and send it to a different HEC endpoint.
> you would have to copy this repo locally and edit `template/configmap.yaml`.
> https://docs.fluentd.org/output/copy

@rockb1017 

Is it possible to include this in the helm chart? If we modify configmap then there are maintenance issue especially when we need to update SCK etc.

**Comment by mlehner616** [comment]
I have a use case with similar requirements. Using a single HEC token just isn't an option.

**Comment by wrahmann** [comment]
> This chart doesn't support sending it to multiple HEC out of the box.
> It is possible with customizing the fluentd pipeline to copy the data and send it to a different HEC endpoint.
> you would have to copy this repo locally and edit `template/configmap.yaml`.
> https://docs.fluentd.org/output/copy

@rockb1017 

Can you tell us if the new requirement for the implementation of multiple HEC can be done under SCK ?

**Comment by rockb1017** [comment]
I will add this for future releases. IF you can send it to multiple HEC endpoints, how would you like to route some data to HEC1 and others to HEC2 ?

**Comment by wrahmann** [comment]
> IF you can send it to multiple HEC endpoints, how would you like to route some data to HEC1 and others to HEC2 ?

@rockb1017 

Our Splunk team wants application logs to be sent to one HEC and audit logs/Infra logs to the other one i.e. We shall be able to define destination to the different log file. 

If you need more information, do let me know.

**Comment by skirven4** [comment]
Has there been any more thought on this? Maybe what could be done is to be able to add the alternate endpoint as an entry much like you would a multiline entry.
