### ISSUE TITLE
SC4K1.4.3: Long single line log events is truncated after 8192 characters/bytes

### ISSUE THREAD

**Issue by taskar82** [splunk/splunk-connect-for-kubernetes#500]
Splunk Connect for Kubernetes version 1.4.3: Long single line log events is truncated after 8192 characters. Typically a Java exception stack trace.

We are only using default config maps.
Log type is CRI and running OpenShift.
Found a parameter stream_buffer_size, but not found the right place to set this in the config map for logging, but it also seems to just work with json. Are there other "buffers"?

Eventlenght in splunk are always max 8192bytes (8k) for a single line event from our container logs,  watching console logs, we can see that the single line are ok. So looks like fluentd are chopping/truncating before sending it to splunk HEC.

Looking at other types, like object, we see event lenght bigger than 220000bytes

**Environment**:
- Openshift 4.5.18
- Splunk version: 7.3.3
- Splunk Connect for Kubernetes helm chart version: 1.4.3

**Comment by taskar82** [comment]
Our problem looks similar to issue: 
https://github.com/splunk/splunk-connect-for-kubernetes/issues/372

We are seeing it with our java stacktraces (Helm 1.4.3), one example, logged as a single line json in the container: It is 14535 chars in total logged as one single line (local tail confirms), it looks like Fluentd, or some kind of parsing is splitting the line, when its indexed it ends up as TWO events. First event 8192 characters and the next 6343.

**Comment by jonaslar** [comment]
One log line gets split into two events in Splunk, see added files.

[igeflaxagentv1_longevent.log](https://github.com/splunk/splunk-connect-for-kubernetes/files/5595628/igeflaxagentv1_longevent.log)
[splunk_igeflaxagentv2_events.log](https://github.com/splunk/splunk-connect-for-kubernetes/files/5595629/splunk_igeflaxagentv2_events.log)

**Comment by taskar82** [comment]
after some investigation, we have found this to be the same error as discussed in https://github.com/splunk/splunk-connect-for-kubernetes/issues/372
