### ISSUE TITLE
Ability to define sourcetype using annotation without "kube:" modification

### ISSUE THREAD

**Issue by Zenimax-DSpeed** [splunk/splunk-connect-for-kubernetes#501]
https://github.com/splunk/splunk-connect-for-kubernetes/blob/b2f1db705b495e2921f7dd6abfeef03dd40f4b44/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L240

My ruby isn't great, but reading this:
`sourcetype ${record.dig("kubernetes", "annotations", "splunk.com/sourcetype") ? "kube:"+record.dig("kubernetes", "annotations", "splunk.com/sourcetype") : "kube:container:"+record.dig("kubernetes","container_name")}`

My understanding is that I can set the sourcetype of logs using an annotation, _BUT_ I have to have it prefixed with "kube:" (this matches the readme documentation).
This causes a problem that we are looking at migrating to kubernetes, but need to match our existing sourcetypes, which do not have this prefix (and why would you put that in the sourcetype given the other ways of identifying where it's running?).

I believe that to get around this, I would have to modify the chart, or use kustomize to replace that config file, none of which seems particularly maintainable or nice.

Would it be possible to add another annotation, such as "splunk.com/raw_sourcetype" that does not receive the same treatment or assumed conventions?

**Comment by rockb1017** [comment]
I see what you mean. 
we will make it as a customizable field. (so that you can remove any prefix)

**Comment by matthewmodestino** [comment]
hmm, this reminds me, I was told recently told the sourcetype setting in the values.yaml wasnt working, which is theory would also allow you to override the sourcetype...or at least that was the intention:

https://github.com/splunk/splunk-connect-for-kubernetes/blob/fbcd160064f655f10372b22bfedf8ac3ae83464f/helm-chart/splunk-connect-for-kubernetes/values.yaml#L164-L178

annotation method is definitely awesome, but please check on values.yaml definition option and confirm if this option is being rendered right by the helm chart....

**Comment by shashken** [comment]
Is there a solution/workaroud for this? we are experiencing the same problem where we need custom sourcetype
@matthewmodestino @rockb1017 @Zenimax-DSpeed

**Comment by rockb1017** [comment]
yes, it is released yesterday with version 1.4.4. 
please check new values file for sourcetypePrefix

**Comment by shashken** [comment]
@rockb1017 It looks like the sourcetype has a \<prefix\>:container:<container_name> ([this line](https://github.com/splunk/splunk-connect-for-kubernetes/blob/8ba455e7f988d129c9bfa13fdcf2025c6c4ae724/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L240))
I need to specify a custom sourcetype ([like this example](https://github.com/splunk/splunk-connect-for-kubernetes/blob/8ba455e7f988d129c9bfa13fdcf2025c6c4ae724/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml#L149))
Is it possible to do that? if not how can this be fixed?

**Comment by Zenimax-DSpeed** [comment]
> @rockb1017 It looks like the sourcetype has a <prefix>:container:<container_name> ([this line](https://github.com/splunk/splunk-connect-for-kubernetes/blob/8ba455e7f988d129c9bfa13fdcf2025c6c4ae724/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L240))
> I need to specify a custom sourcetype ([like this example](https://github.com/splunk/splunk-connect-for-kubernetes/blob/8ba455e7f988d129c9bfa13fdcf2025c6c4ae724/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml#L149))
> Is it possible to do that? if not how can this be fixed?

Looking at the line:
`sourcetype ${record.dig("kubernetes", "annotations", "splunk.com/sourcetype") ? record.dig("kubernetes", "annotations", "splunk.com/sourcetype") : "{{ .Values.sourcetypePrefix }}:container:"+record.dig("kubernetes","container_name")}`

To me this reads as it will use the "splunk.com/sourcetype" annotation, unmodified, if present. The :container: and prefix are only used as a fallback if there is no annotation. So the answer would appear to be to set an annotation to have whatever sourcetype you want.

**Comment by shashken** [comment]
This makes no sense as annotations are on pod level and sourcetype needs to be set on container level (in sidecar containers case for example) @Zenimax-DSpeed
Don't you think there should be an option to define custom sourcetype?

**Comment by matthewmodestino** [comment]
@shashken the intent was for you to control sourcetype in the log definition section:

https://github.com/splunk/splunk-connect-for-kubernetes/blob/8ba455e7f988d129c9bfa13fdcf2025c6c4ae724/helm-chart/splunk-connect-for-kubernetes/values.yaml#L181

I recall a customer telling me they tried to set the sourcetype in the log definition but had trouble...can you please try setting using log definition linked above?

If that doesnt work lets open an issue, as this feature was supposed to deliver what I think you are asking.

Also, you can use the `customFilters` option for ultimate flexibility to set sourcetype in the fluentd record to whatever you like.
