### ISSUE TITLE
Set default imagePullPolicy to IfNotPresent to avoid hitting Docker Hub Rate Limits

### ISSUE THREAD

**Issue by djschaap** [splunk/splunk-connect-for-kubernetes#506]
**What would you like to be added**:
I would like to see imagePullPolicy set to IfNotPresent by default (rather than the current Always).  Images are already versioned (example: docker.io/splunk/k8s-metrics-aggr:1.1.4) and should not be changing once published, making these frequent checks/pulls unnecessary.

As a workaround, I have updated my local values.yaml files, adding "pullPolicy: IfNotPresent" to the "image" section of splunk-kubernetes-logging, splunk-kubernetes-metrics, and splunk-kubernetes-objects.

**Why is this needed**:
While running several Kubernetes clusters, I have been blocked repeatedly by Docker Hub's rate limiting.  I believe deploying this chart in its default configuration was the cause.

**Comment by rockb1017** [comment]
thanks for raising this!

**Comment by djschaap** [comment]
Would you like a PR?  I can create one if you'd like.

**Comment by djschaap** [comment]
Please ignore my fork/branch - it was incomplete/insufficient.

**Comment by rockb1017** [comment]
thanks! i am already working on this. dont worry!

**Comment by matthewmodestino** [comment]
I believe I got nailed with this yesterday...deployed to my cluster and containers sat in "creating" for a long time....not 100% percent sure its related, but I have my suspicions....

**Comment by rockb1017** [comment]
it has been merged. I will be making a release soon. Thank you
