### ISSUE TITLE
Add helm charts to chartcenter.io

### ISSUE THREAD

**Issue by cabrinha** [splunk/splunk-connect-for-kubernetes#508]
Please add these charts to chartcenter.io: https://github.com/jfrog/chartcenter/blob/master/docs/inclusion.md

This would make it much easier to pull charts.

Similar issue: https://github.com/splunk/splunk-connect-for-kubernetes/issues/470

**Comment by rockb1017** [comment]
Hello,
our chart is hosted on github pages. you can pull as below
```
helm repo add splunk https://splunk.github.io/splunk-connect-for-kubernetes/

helm show values splunk/splunk-connect-for-kubernetes > values.yaml

helm install sck splunk/splunk-connect-for-kubernetes -f values.yaml
```

**Comment by cabrinha** [comment]
> Hello,
> our chart is hosted on github pages. you can pull as below
> 
> ```
> helm repo add splunk https://splunk.github.io/splunk-connect-for-kubernetes/
> 
> helm show values splunk/splunk-connect-for-kubernetes > values.yaml
> 
> helm install sck splunk/splunk-connect-for-kubernetes -f values.yaml
> ```

Sure, it just means that everyone has to add yet another helm repo in order to use this chart.

Adding this chart to chartcenter.io means it will _also_ be available in a centralized repository, similar to the old "stable" helm repo, where you can pull many charts from a centralized repo. It just makes life easier for users.

**Comment by rockb1017** [comment]
thanks for working on that PR. I just left a comment of my approval.

**Comment by rockb1017** [comment]
its been merged there. closing. Thank you again!
