### ISSUE TITLE
[logging] customFilters not rendering properly, allow users to keep journalD / Docker structure

### ISSUE THREAD

**Issue by cabrinha** [splunk/splunk-connect-for-kubernetes#509]
How would one configure the logging chart to insert custom fields into each event?

Using FluentBit, a config section like this:

```
            [FILTER]
                Name modify
                Match *
                Set LoggingAgent fluent-bit
                Set KubeClusterName ${CLUSTER_NAME}
                Set KubeClusterAbbreviation ${CLUSTER_NAME}
                Set KubeClusterRegion ${CLUSTER_REGION}
                Set KubeHostname ${HOST_NAME}
                Set KubeHostIP ${HOST_IP}
```

Adds these fields to each event, shown below.

![Screen Shot 2020-12-04 at 9 16 11 AM](https://user-images.githubusercontent.com/775203/101194233-8f837380-3612-11eb-97f2-7d3e40af714c.png)

When using the `customFilters` map in this helm chart, ([customFilters template](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L308-L318)), it seems the `toYaml $filterDef.body | indent 8` doesn't format the filter code block properly.

Also, the `kubernetes` map in the event of my screenshot seems to be a custom plugin as well. How would I add that to fluentD using this chart?

Seems that the helm template of `toYaml $filterDef.body | indent 8` is causing problems formatting my `<filter>` block.

Example helm config:
```yaml
      splunk-kubernetes-logging:
        customFilters:
          json:
            body: |

              key_name log
                <parse>
                  @type json
                  json_parser json
                </parse>
                replace_invalid_sequence true
                reserve_data true
                emit_invalid_record_to_error false
                reserve_time
```

Resulting fluentD config:
```
      # = custom filters specified by users =
      <filter tail.containers.**>
        @type parser
        |
          key_name log
            <parse>
              @type json
              json_parser json
            </parse>
            replace_invalid_sequence true
            reserve_data true # this preserves unparsable log lines
            emit_invalid_record_to_error false # In case of unparsable log lines keep the error log clean
            reserve_time # the time was already parsed in the source, we don't want to overwrite it with current time.
      </filter>
```

**Comment by luckyj5** [comment]
@cabrinha Thanks for raising this issue and creating a PR for it. 
Will look into it and provide an update for the same. Thanks!

**Comment by rockb1017** [comment]
@cabrinha 
Can you please share values.yaml file you are using? 
And to clarify, are you just trying to add custom fields (key: value) to an actual event? if yes, please take a look at `customMetadata` option here: https://github.com/splunk/splunk-connect-for-kubernetes/blob/fbcd160064f655f10372b22bfedf8ac3ae83464f/helm-chart/splunk-connect-for-kubernetes/values.yaml#L394

**Comment by cabrinha** [comment]
Sure, we can use customMetadata, but in order for it to show up in the event and not be hidden down in the metadata section, and also to keep the journalD / docker logging structure, I had to delete the end of the configMap here:

```
        <format>
          # we just want to keep the raw logs, not the structure created by docker or journald
          @type single_value
          message_key log
          add_newline false
        </format>
```

But the core issue remains, the config is formatted in something like XML, but the [filter section uses toYaml](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L311-L315)

**Comment by sbkg0002** [comment]
Any word on how to get the `customFilters` working in >1.4.3?

**Comment by harshit-splunk** [comment]
I am able to use `customFilter` feature without facing any issue.  

```
$ kubectl version:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ helm version
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

`SCK version: 1.4.10`


I deployed log generator using:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: loggen
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        app: loggen
    spec:
      restartPolicy: Never
      containers:
      - name: loggen
        image: rock1017/log-generator:2.1.0
        env:
        - name: MESSAGE_COUNT
          value: "300000"
        - name: SIZE
          value: "256"
        - name: FREQ
          value: "1"
```

values.yaml:

```
splunk-kubernetes-logging:
  enabled: true
  customFilters:
    loggen_filter:
      tag: tail.containers.var.log.containers.loggen-*.log
      type: record_modifier
      body: |- 
        @id loggen_filter
        <replace>
          key log
          expression /r{3,}/
          replace multiple_r
        </replace>
```

Generated configuration:  
``` 
   <filter tail.containers.var.log.containers.loggen-*.log>
      @type record_modifier
      @id loggen_filter
      <replace>
        key "log"
        expression /r{3,}/
        replace "multiple_r"
      </replace>
    </filter>
```

Source event: 
```
311 | loggen--1-kgb4n | 2021-11-29T08:13:56.701234 | rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
```

Filtered  event:
```
312 | loggen--1-p4rdz | 2021-11-29T08:28:46.632829 | multiple_r
```

**Comment by harshit-splunk** [comment]
@dmduggan @sbkg0002 are you still facing the issue? 
Please let us know.

**Comment by dmduggan** [comment]
No, I believe this was fixed in a later version. Not sure which one but currently on 1.4.7.

**Comment by harshit-splunk** [comment]
@dmduggan 
Thanks for confirming. Closing the issue.
Feel free to reopen or create a new one if needed.
