### ISSUE TITLE
More frequent releases

### ISSUE THREAD

**Issue by jrauschenbusch** [splunk/splunk-connect-for-kubernetes#512]
**What would you like to be added**:

More frequent releases (incl. the Helm Chart) to be able to benefit quickly from the latest bug fixes and improvements.

**Why is this needed**:

SCK is the suggested way by Splunk to get logs out of a Kubernetes cluster.  For this, the support of this component should get more attention by the Splunk development team.

**Comment by mwang2016** [comment]
Hi @jrauschenbusch thanks for bringing this up. We will try to work on this.

**Comment by jrauschenbusch** [comment]
26d later... not really noticeable... Too bad!

**Comment by rockb1017** [comment]
i am working on a release now. Thank you for patience!

**Comment by jrauschenbusch** [comment]
Thx. Please maintain a continuous release cycle as it's crucial for (Dev)Ops teams responsible for stability and security.
