### ISSUE TITLE
Config reload without restarting pods

### ISSUE THREAD

**Issue by holmesb** [splunk/splunk-connect-for-kubernetes#514]
This is a followup to #258 which proposes restarting pods (using kubectl rollout restart) to reload config.  The problem with this is there is downtime while pods restart.

It would be better to use a sidecar which watches for configmap changes and then sends fluentd's [/api/config.gracefulReload](https://docs.fluentd.org/deployment/rpc#http-endpoints) command.  If no PR materialises, I'll create one when I get time.  I've done similar for other charts (eg Jenkins\Grafana).  

(this issue will become redundant if [this ](https://github.com/fluent/fluent-bit/issues/365)feature lands in fluentd - but doesn't look imminent)

**Comment by mwang2016** [comment]
Hi @holmesb thank you for submitting this enhancement request. This is a good idea; if you can submit a PR for this, it will be very helpful.

**Comment by vinzent** [comment]
@mwang2016 I would like to create a PR for that config reload feature. 

there is the https://hub.docker.com/r/jimmidyson/configmap-reload image which OpenShift uses (or uses to builds its own https://github.com/openshift/configmap-reload)

**Comment by vinzent** [comment]
@mwang2016 ?

**Comment by holmesb** [comment]
The more widely used the sidecar image is, the more secure/stable/better.  Also helps if the dockerfile used to build is available, and there's a clear link between the docker image version and the code version used to create it.  

The main Jenkins helm chart in Cloudbees' repo uses [kiwigrid/k8s-sidecar](https://github.com/kiwigrid/k8s-sidecar), which has 10m downloads, and has worked well for me in the past.  It ticks these three boxes.  Yours ticks the first two, but not sure how the docker image version (v5.0) relates to a release on github (v0.2.2).  They seem to have similar functionality.

**Comment by vinzent** [comment]
https://hub.docker.com/r/jimmidyson/configmap-reload  is not built from https://github.com/openshift/configmap-reload . OpenShift forked the repo to build its own. OpenShift has its own private registry (registry.redhat.io). The image source for `jimmidyson/configmap-reload` is here: https://github.com/jimmidyson/configmap-reload .

On Docker Hub the `jimmidyson/configmap-reload` has 50m downloads.
