### ISSUE TITLE
RFE: Make it easier to filter out unwanted metrics

### ISSUE THREAD

**Issue by sowings** [splunk/splunk-connect-for-kubernetes#517]
<

**What would you like to be added**:

In my environment, I've got a lot of software-defined network interfaces. I don't need TX / RX metrics from these, as I'm just focused on the node level. I had to edit the configMap.yaml directly before calling helm to add in a null filter.

**Why is this needed**:

Reduce the noise of unwanted metrics.

**Comment by cheneysplunk** [comment]
Hi @sowings , thanks for your feedback.
Since it's configurable in configMap.yaml, do you mean we should exclude all other metrics but focus on k8s ones by a built-in filter in the yaml?

**Comment by rockb1017** [comment]
could you provide the change you made to the configmap?

**Comment by harshit-splunk** [comment]
Hey @sowings, any updates on this? Were yon able to filter out unwanted metrics?
Please ket us know
