### ISSUE TITLE
Install docs don't cover helm 2

### ISSUE THREAD

**Issue by sowings** [splunk/splunk-connect-for-kubernetes#519]
**What happened**:

# helm show values splunk/splunk-connect-for-kubernetes > values.yaml
Error: unknown command "show" for "helm"
Run 'helm --help' for usage.

**What you expected to happen**:

I expected to get a list of the values to an output file so that I could customize it for my environment.

**How to reproduce it (as minimally and precisely as possible)**:

Make sure your helm is version 2 (mine is 2.15.2), try helm add repo ; helm show values.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.12
- Ruby version (use `ruby --version`): not installed
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04 LTS
- Splunk version: 8.0
- Splunk Connect for Kubernetes helm chart version: 1.4.3
- Others:

**Comment by cheneysplunk** [comment]
@sowings thanks for the feedback.
Created a Jira and assigned to PM for priority & scoping. 
https://jira.splunk.com/browse/ADDON-32048

**Comment by rockb1017** [comment]
https://v2-14-0.helm.sh/docs/helm/#helm-inspect-values
i think this is the command for helm 2.
we will add this to the doc
thank you.

**Comment by harshit-splunk** [comment]
Hey @sowings, thanks for reporting. Docs has been updated in https://github.com/splunk/splunk-connect-for-kubernetes/pull/525 .
Doc: https://github.com/splunk/splunk-connect-for-kubernetes#deploy-with-helm

Thanks
