### ISSUE TITLE
Errors from splunk-fluentd-k8s-logs container

### ISSUE THREAD

**Issue by dwayne-lee** [splunk/splunk-connect-for-kubernetes#52]
With query: index=eks_logs sourcetype="kube:container:splunk-fluentd-k8s-logs"

I am frequently seeing the following error in the logs:

[warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-12-03 17:42:26 +0000 chunk="57c21abb713ca798a76f45298b755dcb" error_class=SocketError error="Failed to open TCP connection to <redacted>.<redacted>.com:443 (getaddrinfo: Name or service not known)"

I'm using port 443 as my Splunk hosts are sitting behind an F5 vip (vip:443 -> splunk hosts:8088)

Everything else (logging, metrics, objects) seems to be working......so what do these errors mean?  Can they be ignored?

Splunk 7.1.3

**Comment by dwayne-lee** [comment]
Edit:  I purposely omitted by FQDN above for security.  It is correct in the actual output.  It seems the DNS settings are unknown inside the container.

**Comment by matthewmodestino** [comment]
Hey @dwayne-lee!

What does a timechart of those errors look like split by host, say over a 7 day period in Splunk?

Would be interesting to understand the frequency of the errors. 

Also can you tell us more about your kubernets deploy? Version, which DNS provider, etc?

Thanks!

**Comment by dwayne-lee** [comment]
ALL Hosts:      72,744 events	(11/29/18 8:00:00.000 AM to 12/6/18 8:32:31.000 AM)
A Single Host:  18,029 events	(11/29/18 8:00:00.000 AM to 12/6/18 8:36:54.000 AM)

[root@kube-master ~]# kubectl describe node kube-master
Name:               kube-master
Roles:              master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/hostname=kube-master
                    node-role.kubernetes.io/master=
Annotations:        flannel.alpha.coreos.com/backend-data: {"VtepMAC":"3a:52:61:aa:73:88"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 10.213.136.228
                    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Tue, 13 Nov 2018 19:40:17 +0000
Taints:             node-role.kubernetes.io/master:NoSchedule
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  OutOfDisk        False   Thu, 06 Dec 2018 13:43:59 +0000   Tue, 13 Nov 2018 19:40:08 +0000   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False   Thu, 06 Dec 2018 13:43:59 +0000   Tue, 13 Nov 2018 19:40:08 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 06 Dec 2018 13:43:59 +0000   Tue, 13 Nov 2018 19:40:08 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 06 Dec 2018 13:43:59 +0000   Tue, 13 Nov 2018 19:40:08 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Thu, 06 Dec 2018 13:43:59 +0000   Tue, 13 Nov 2018 19:40:47 +0000   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  10.213.136.228
  Hostname:    kube-master
Capacity:
 cpu:                2
 ephemeral-storage:  8181Mi
 hugepages-2Mi:      0
 memory:             3879568Ki
 pods:               110
Allocatable:
 cpu:                2
 ephemeral-storage:  7720560218
 hugepages-2Mi:      0
 memory:             3777168Ki
 pods:               110
System Info:
 Machine ID:                 b30d0f2110ac3807b210c19ede3ce88f
 System UUID:                EC219C1E-B496-9EBA-B585-3F6D4697A113
 Boot ID:                    51214336-cbca-4a97-843e-d4789ea81ae3
 Kernel Version:             3.10.0-862.3.2.el7.x86_64
 OS Image:                   CentOS Linux 7 (Core)
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.3.1
 Kubelet Version:            v1.12.2
 Kube-Proxy Version:         v1.12.2
PodCIDR:                     10.244.0.0/24
Non-terminated Pods:         (7 in total)
  Namespace                  Name                                   CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                                   ------------  ----------  ---------------  -------------
  kube-system                etcd-kube-master                       0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-apiserver-kube-master             250m (12%)    0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-controller-manager-kube-master    200m (10%)    0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-flannel-ds-amd64-wjctz            100m (5%)     100m (5%)   50Mi (1%)        50Mi (1%)
  kube-system                kube-proxy-4wrrf                       0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-scheduler-kube-master             100m (5%)     0 (0%)      0 (0%)           0 (0%)
  splunk-connect-k8s         ql-splunk-kubernetes-logging-kvmvt     100m (5%)     0 (0%)      200Mi (5%)       0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource  Requests    Limits
  --------  --------    ------
  cpu       750m (37%)  100m (5%)
  memory    250Mi (6%)  50Mi (1%)
Events:     <none>

**Comment by matthewmodestino** [comment]
To me, it appears you are having some DNS challenges...I find it strange you say it is working though...are all your expected hosts showing up in Splunk? 

Do you have pod with nslookup in it? The logging pod does not have it installed, though if this is a test enviro, it can be installed by hand be exec'ing into the pod, or dropping utility pod in the namespace.  

Can I assume this is a test environment?? You have named the index `eks_logs` but you don't appear to be using eks....

**Comment by matthewmodestino** [comment]
Any updates on this?

**Comment by dtregonning** [comment]
Hey @dwayne-lee - will close issue. Please re-open with any updates or if you continue to have issues.
