### ISSUE TITLE
POD Health 

### ISSUE THREAD

**Issue by nravichandr** [splunk/splunk-connect-for-kubernetes#522]
Sorry, I was offline for a few days and could not reply to the question and hence adding a new issue.

Please refer to Issue #513

What would you like to be added: Add metrics and details of Health of a POD.

Why is this needed: Currently there is no way to find out the health of a POD from logs. For example if a POD is returning a http 500 error it is not logged.

Details:
A request comes through F5 load balancer and calls the WIP (wide ip) of the webservice hosted in openshift. The request will be routed through HAProxy and eventually to the POD. I want to track the request. If a POD instance is bad I am seeing 504 in F5 load balance. But I cannot identify which POD is bad. So we have to recycle the entire container itself. I want to know from which log I can find where the request dropped or failed to reach the POD.

when you say pod, is it SCK pods, or other pods on the cluster? - It is other PODs hosted in OpenShift.
are you looking at metrics data or logging data from kubernetes? I am looking at the logging data from kubernetes.

Is there a way to identify within Kubernetes/OpenShift Logs about the health of PODs when it returns 504 error? I have not been able to find anything  in the logs which indicates that the POD is returning 504. It may not be the POD it might be something else as well. That brings back to my original question, if I can track a request all-the-way from F5 to the POD which is handling that request (both ways - request and response)? Since 504 cannot be tracked inside the POD it has be just one layer above the POD.

**Comment by vinzent** [comment]
Splunk Connect for Kubernetes (SCK) does not expose any service. How does a loadbalancer sending probes make sense in this picture?

If you talk about arbitary _PODs_ , then this nothing SCK can influence. If nobody logs the error, then there is simply no logs to read and send  to splunk.

You probably should look into monitoring your pods inside your cluster with Prometheus and/or defining liveness checks on pods, so they get restarted in case of issues. But again. this is not related to SCK.

**Comment by foram-splunk** [comment]
@nravichandr Should I close this issue?

**Comment by nravichandr** [comment]
Please close
