### ISSUE TITLE
Helm chart version 1.4.4 missing from repo 

### ISSUE THREAD

**Issue by prios-peter-olivo** [splunk/splunk-connect-for-kubernetes#529]
**What happened**:
I was expecting the newest release to be available in the helm repo.

helm search repo splunk
NAME                                	CHART VERSION	APP VERSION	DESCRIPTION
splunk/splunk-connect-for-kubernetes	1.4.3        	1.4.3      	Collect logs, objects (metadata), and metrics w...

**What you expected to happen**:
helm search repo splunk
NAME                                	CHART VERSION	APP VERSION	DESCRIPTION
splunk/splunk-connect-for-kubernetes	1.4.4        	1.4.4      	Collect logs, objects (metadata), and metrics w...

**How to reproduce it (as minimally and precisely as possible)**:
helm search repo splunk

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19.4
- Ruby version (use `ruby --version`): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
- OS (e.g: `cat /etc/os-release`): 
- Splunk version: CLOUD
- Splunk Connect for Kubernetes helm chart version: 1.4.3
- Others:

**Comment by niteenkole** [comment]
same thing for me, it just shows 1.4.3

helm repo add splunk https://splunk.github.io/splunk-connect-for-kubernetes/
"splunk" has been added to your repositories


helm search repo  splunk/splunk-connect-for-kubernetes
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION
splunk/splunk-connect-for-kubernetes    1.4.3           1.4.3           Collect logs, objects (metadata), and metrics w...

**Comment by jrauschenbusch** [comment]
@rockb1017 Could you update the chart repository to make the new version available?

**Comment by jrauschenbusch** [comment]
@mwang2016 Any chance that this will be done in a timely manner?

**Comment by jrauschenbusch** [comment]
@prios-peter-olivo It was released yesterday. I think this ticket can be closed now.

**Comment by rockb1017** [comment]
Thanks! 
Closing
