### ISSUE TITLE
SCK objects stop reporting Pod object data with errors

### ISSUE THREAD

**Issue by kyaparla** [splunk/splunk-connect-for-kubernetes#532]
**What happened**: SCK objects stops reporting pod objects, with following errors
```
[info]: #0 starting fluentd worker pid=7307 ppid=1 worker=0
[info]: #0 fluentd worker is now running worker=0
[error]: #0 Filter failed with .record.source = "namespace:\(env.MY_NAMESPACE)/pod:\(env.MY_POD_NAME)" | .record.sourcetype = (.tag | gsub("\\."; ":")) | .record
[info]: Worker 0 finished unexpectedly with signal SIGKILL
[info]: adding filter pattern="kube.**" type="jq_transformer"
[info]: adding filter pattern="kube.**" type="jq_transformer"
[info]: adding match pattern="kube.**" type="splunk_hec"
[info]: adding source type="kubernetes_objects"
[warn]: #0 both of Plugin @id and path for <storage> are not specified. Using on-memory store.
[info]: adding source type="kubernetes_objects"
```

**What you expected to happen**: See pod objects in splunk

**How to reproduce it (as minimally and precisely as possible)**:  Its intermittent, We noticed it on kubernetes version v1.18, and with more than >100 deployments with approx 40+ nodes each having 8 cpus.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.18
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:
- Splunk Connect for Kubernetes helm chart version:1.4.2
- Others:

**Comment by rockb1017** [comment]
is your pod crashing ? 
Could you share the config you are using?

**Comment by kyaparla** [comment]
No, I dont think pod is crashing.  Here is the values file we are using.

splunk-kubernetes-objects:
  resources:
    limits:
      cpu: 200m
      memory: 400Mi
    requests:
      cpu: 100m
      memory: 200Mi
  objects:
    core:
      v1:
        - name: pods
          mode: pull
        - name: namespaces
          mode: pull
        - name: nodes
          mode: pull
        - name: resource_quotas
          mode: pull
        - name: events
          mode: watch
    apps:
      v1:
        - name: daemon_sets
          mode: pull
        - name: deployments
          mode: pull
        - name: replica_sets
          mode: pull

**Comment by rockb1017** [comment]
Hello, it's been a while. has there been any development on your environment with this?

**Comment by kyaparla** [comment]
@rockb1017 Still seeing this behaviour.  Objects pod suddenly stop sending data, and looks like the process is crashing in a loop.  Please let me know if I can provide any more details.

**Comment by foram-splunk** [comment]
> No, I dont think pod is crashing. Here is the values file we are using.
> 
> splunk-kubernetes-objects: resources: limits: cpu: 200m memory: 400Mi requests: cpu: 100m memory: 200Mi objects: core: v1: - name: pods mode: pull - name: namespaces mode: pull - name: nodes mode: pull - name: resource_quotas mode: pull - name: events mode: watch apps: v1: - name: daemon_sets mode: pull - name: deployments mode: pull - name: replica_sets mode: pull

Hey @kyaparla ,are you still facing this issue? I tried to send data using this in values.yaml but I didn't get any errors . Can you give more details on how to reproduce this ?

**Comment by foram-splunk** [comment]
Closing this issue . Feel free to re-open it ,if you face the same issue again .
