### ISSUE TITLE
Timestamp problem

### ISSUE THREAD

**Issue by wrahmann** [splunk/splunk-connect-for-kubernetes#538]
****What happened**:**
The logs timestamps is being sent in UTC format and not the local format.

****What you expected to happen**:**
The time format shall be configurable and allow user to choose local or UTC time.

**How to reproduce it (as minimally and precisely as possible)**:
The issue is being appearing by default for all the logs sources.

******Anything else we need to know?**:****
I checked the configmap for splunkconnect and it has config definition for two source 

          -  source.containers.conf
          -  source.files.conf
          
In the **source.containers.conf** case, splunkconnect is using the following hard-coded configuration:

            localtime false           #if true, uses local time. Otherwise, UTC is used.

For the **source.files.conf** case, there is no settings at all. I suspect, in this case UTC will be used. 

Questions:
1. Can you please if this configuration is responsible for the UTC time reported to the splunk. If yes, can we pass our configuraiton in values.yaml file?

2. Can it be control from the splunk end?

****Environment**:**
- Splunk Connect for Kubernetes helm chart version:
1.4.3

**Comment by mwang2016** [comment]
Hi @wrahmann Can you check what is the timezone on your server? After you change the timezone, you will need to restart Splunk, it should take the new local timezone automatically.

**Comment by wrahmann** [comment]
> 
> 
> Hi @wrahmann Can you check what is the timezone on your server? After you change the timezone, you will need to restart Splunk, it should take the new local timezone automatically.

Hi @Mei Wang,

Actually we are facing two issues:

1. First one is resolved as some of the servers were using incorrect timezone. 
2. The other problem is because of the buffering of messages , a mismatch in timestamp between splunk and logging event is observed.

In our case, this delay could be as high as 5 seconds. I checked the values.yaml and it has buffering related parameters. We modified flush_out interval to 1 second and that has helped. But I am not sure if this is an appropriate change.

Can you suggest what parameters might need to change to transfer the logs in near realtime?

**Comment by vinzent** [comment]
As you observed, fluentd uses an async buffered way to send logs. I don't think it's possible to send logs "near realtime" as you defined it (< 1s). You would need to configure fluentd to flush on EVERY line if you want "realtime". this would slowdown fluentd and probably overhelm the Splunk HEC side too.

If you have that specific requirements, probably you're better off with a Splunk UF sidecar for the Pod having these requirements. Or have the logger of the app directly log to Splunk. But this is something not in scope with slunk-connect-for-kubernetes.

**Comment by wrahmann** [comment]
Thanks Thomas for your support. 

I am following another thread to extract the timestamp from logs. This will apparently solve the problem. We only don't want a mismatch > 1s  between the splunk  and  logs.
