### ISSUE TITLE
Provide examples/guidance on adding custom fields to the logging configmap

### ISSUE THREAD

**Issue by matthewmodestino** [splunk/splunk-connect-for-kubernetes#54]
We should provide documentation/guidance for users on how to add their own custom fields to the logging configmap and document the `jq_transformer`

For example, we have used filters like this to add an `index` field based on the namespace:

```
 # new filter: set index
      <filter tail.containers.**>
        @type jq_transformer
        jq '.record | .index = "some_"+.namespace+"_string"'
      </filter>

# = output =
      <match **>
        @type splunk_hec
        protocol https
        hec_host host
        hec_port 8088
        hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
        host "#{ENV['SPLUNK_HEC_HOST']}"
        source_key source
        sourcetype_key sourcetype
        index_key index
        insecure_ssl true
        <fields>
          pod
          namespace
          container_name
          container_id
        </fields>


```

**Comment by justinbanks** [comment]
Does this enable us to pass up the cluster name? It appears that was built in at some point, but reverted with: https://github.com/splunk/splunk-connect-for-kubernetes/commit/45a0be058f503d415149de4fdd39a2a365f69202

**Comment by tlynchpin** [comment]
in the above example, should there be "some_" and "_string" in the output?
