### ISSUE TITLE
Q: How to forward logs of a specific namespace to an index? 

### ISSUE THREAD

**Issue by itscatherinelam** [splunk/splunk-connect-for-kubernetes#542]
Currently, I have all of my logs going to a log index in Splunk. However, I'm trying to separate it so that a specific namespace has its own index - I was told that in Splunk, there is a 1:1 relationship between HEC tokens and indexes. I have followed the initial instruction on https://github.com/splunk/splunk-connect-for-kubernetes#managing-sck-log-ingestion-by-using-annotations and annotated the namespace, but for the life of me I cannot figure out where to input the HEC token for the new namespace-specific index. 

Please assist! You have my undying gratitude :)

**Comment by rockb1017** [comment]
hmm, currently, you can only use 1 HEC token in a SCK chart. with HEC token, you can set list of indexes it can ingest to. once HEC is properly configured on splunk side, you can then use annotation to route logs to that index. make sure you are using latest chart. I recommend v1.4.5.

**Comment by itscatherinelam** [comment]
@rockb1017 Ah, that makes sense why I couldn't find it. So if I have the HEC token set up properly, and then the namespace annotated as is shown in the documentation, will that route all the logs from namespace to that index? Or is there an additional step? 

I guess also of concern is - will the namespace logs be duplicated in the original index housing all the events?

**Comment by vinzent** [comment]
The HEC token configured for the SCK deployment needs to be allowed to write to the configured index.

the annotation will ensure all pods in the namespace will have the Splunk index assigned. (can be overriden by annotating a pod).

Any event will ever be stored in one Splunk index only.

**Comment by itscatherinelam** [comment]
Perfect! Thank you for everyone's help : )
