### ISSUE TITLE
Incorrect Timestamp extracted in Splunk

### ISSUE THREAD

**Issue by ndgohel** [splunk/splunk-connect-for-kubernetes#548]
**What happened**:
Splunk does not extract the timestamp from the actual event. 
Sample log in the Container log file:
{"log":"2021-02-03 17:40:58.165 [CONSOLE] switch_core.c:1582 Created ip list domains default (deny)\n","stream":"stdout","time":"2021-02-03T17:40:59.699381681Z"}

**What you expected to happen**:
For following log entry in physical Container log file:
{"log":"2021-02-03 17:40:58.165 [CONSOLE] switch_core.c:1582 Created ip list domains default (deny)\n","stream":"stdout","time":"2021-02-03T17:40:59.699381681Z"}

It is expected that Splunk Shows the timestamp as "2021-02-03 17:40:58.165" which is printed in the beginning of the raw event. But Splunk shows timestamp as "2021-02-03T17:40:59.699381681Z" which is the value of time field.

**How to reproduce it (as minimally and precisely as possible)**:
The issue is still there and continuously printing the incorrect timestamp.

**Anything else we need to know?**:
I tried to add regex for timestamp in the sourcetype definition on our Splunk Cloud Environment but it did not help.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-29T16:15:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Ruby version (use `ruby --version`): N/A
- OS (e.g: `cat /etc/os-release`):
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

- Splunk version: Splunk Cloud 
Version: 8.0.2007
Build: 8db95ae070d0
- Splunk Connect for Kubernetes helm chart version:
Client: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}

apiVersion: v1
appVersion: 1.2.0

- Others:

**Comment by ndgohel** [comment]
Another example where timestamp value is totally different. Splunk displays the timestamp value which is not part of the raw event and also not the value of time field.

Raw Event:
{"log":"**21:19:15.484**  92297 [main] [] DEBUG EventFormatterConfiguration- Found [13] event converters: [[com.arlo.event.converter.SnapshotUploadEventConverter@841e575, com.arlo.event.converter.LowBatteryEventConverter@27a5328c, com.arlo.event.converter.StartTimedStreamConverter@1e5f4170, com.arlo.event.converter.MotionRecordEventConverter@6c345c5f, com.arlo.event.converter.SureNotificationEventConverter@6b5966e1, com.arlo.event.converter.DeviceRenamedNotificationEventConverter@65e61854, com.arlo.event.converter.RemoveRecordEventConverter@1568159, com.arlo.event.converter.DeviceNotificationEventConverter@4fcee388, com.arlo.event.converter.DeviceClaimNotificationEventConverter@6f80fafe, com.arlo.event.converter.ProvisioningFailedNotificationEventConverter@3af17be2, com.arlo.event.converter.DeviceStateUpdatedEventConverter@f9879ac, com.arlo.event.converter.EmailUpdatedNotificationEventConverter@37f21974, com.arlo.event.converter.NonOptimalPlanAssignedNotificationEventConverter@5f4d427e]]\n","stream":"stdout",**"time":"2021-02-05T21:19:15.486481516Z"**}

Splunk Shows the timestamp as:  2/5/21 9:19:33.081 PM

**Comment by vinzent** [comment]
IMHO: 

* either you assign a dedicated sourcetype which is known by the splunk server and parsed accordingly or 
* you configure splunk-connect-for-kubernetes to parse the [timestamp from the log message](https://github.com/splunk/splunk-connect-for-kubernetes/blob/1989ac0c5d56df3fb849772041a0378e7e873032/helm-chart/splunk-connect-for-kubernetes/values.yaml#L179)

**Comment by ndgohel** [comment]
Hello Thomas,
Thanks for the update.
First option did not work. A couple of Splunk Engineers from Splunk Cloud Support looked at the sourcetype definition on Search Heads and Indexers but Splunk Cloud is not extracting the timestamp from the raw event. 

For the second option, can you share an example of that configuration> I looked at the values.yaml file which you have pointed out, but I am not clear what should be values for <name> and <source>.  If you can provide me an example, I can try that option out.

Thanks in advance.

**Comment by vinzent** [comment]
@ndgohel what did you try so far? 

the default values.yml should provide you enough examples to get you started: at https://github.com/splunk/splunk-connect-for-kubernetes/blob/1989ac0c5d56df3fb849772041a0378e7e873032/helm-chart/splunk-connect-for-kubernetes/values.yaml#L179-L340

**Comment by ndgohel** [comment]
I was confused when I looked at the values.yaml which you are referring to. I am running Splunk Connect for Kubernetes version 1.2 and it does not the format you are referring.

Can you please provide an example values.yaml for version 1.2?

**Comment by vinzent** [comment]
Out of luck, I don't know v1.2.

**Comment by rockb1017** [comment]
it is all there?
https://github.com/splunk/splunk-connect-for-kubernetes/blob/41d9573e25d15e7167f43083273102e4dca84521/helm-chart/splunk-kubernetes-logging/values.yaml#L82
anyways, i recommend upgrading it to latest.
