### ISSUE TITLE
fluentd   Plugin Tail causing pod restarts

### ISSUE THREAD

**Issue by bdaoudtdc** [splunk/splunk-connect-for-kubernetes#551]
The logging pods  keep restarting .. on examining  the logs .. we see

 #3 config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Plugin 'tail' does not support multi workers configuration (Fluent::Plugin::TailInput)"
2021-02-07 15:59:59 +0000 [info]: Worker 3 finished unexpectedly with status 2
2021-02-07 15:59:59 +0000 [info]: Received graceful stop

**Environment**:
k8s  v1.17.13
Splunk Connect for Kubernetes 1.4.4
2021-02-07 15:59:57 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2021-02-07 15:59:57 +0000 [info]: gem 'fluentd' version '1.9.1'
2021-02-07 15:59:57 +0000 [info]: gem 'fluent-plugin-concat' version '2.4.0'
2021-02-07 15:59:57 +0000 [info]: gem 'fluent-plugin-jq' version '0.5.1'
2021-02-07 15:59:57 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.5.2'
2021-02-07 15:59:57 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.7.0'
2021-02-07 15:59:57 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.2.4'
2021-02-07 15:59:57 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'

**Comment by vinzent** [comment]
The splunk connect for kubernetes helm chart doesn't configure fluentd multi-worker. So your problems origin isn't Splunk connect for kubernetes.

**Comment by bdaoudtdc** [comment]
I just installed the helm chart as is ... so I am not sure what would cause that error then ,,, according to my understanding .. fleuntd containers gets installed as part of  splunk-kubernetes-logging  without any config from my side ...

This is a very simple  yaml file that causes the above error

#global settings
global:
  logLevel: info
  kubernetes:
    clustername: "nonprod"
  splunk:
    hec:
      protocol: https
      insecureSSL: true
      host: kubsplunkhec.back.tickets.com
      token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      port: 8088

#local config for logging chart
splunk-kubernetes-logging:
  logLevel: info
  journalLogPath: /run/log/journal
  containers:
    logFormatType: cri
    logFormat: "%Y-%m-%dT%H:%M:%S.%N%:z"
  splunk:
    hec:
      indexName: kubernetes-nonprod
      token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


Not sure  what is causing the error..

**Comment by vinzent** [comment]
I'd suggest you to uninstall first before digging further into this with `helm uninstall $name`, then check that there are no more unexpected pods, configmaps, daemonsets, etc.

The configmap created by splunk-kubernetes-logging ( https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml) doesn't contain a `workers` config option. But that would be required to get the error you've got: https://docs.fluentd.org/deployment/multi-process-workers#fluentd-cannot-start-with-multi-process-workers-why

**Comment by bdaoudtdc** [comment]
Thank you for your help.
I am not sure what caused this issue , but uninstalling and installing back resolved the issue.

**Comment by rockb1017** [comment]
@vinzent Thank you!
