### ISSUE TITLE
Splunk Connect for Kubernetes missing some container logs 

### ISSUE THREAD

**Issue by svajr2** [splunk/splunk-connect-for-kubernetes#552]
Hi,

We have deployed Splunk Connect for Kubernetes (1.4.3) on OpenShift platform (v3.11).
But recently we noticed an issue where Splunk logging pod stops reading one container log from the OpenShift node. Other container logs on the same node are being processed by Splunk logging pod. We checked Splunk logging pod logs and did not see any errors but found below line for about 15 mins and then it stops reading that log file,

2021-02-03 16:11:52 +0000 [info]: #0 [containers.log] detected rotation of /var/log/containers/missed_pod-1856d347d9f8022619f4734796af966df4d47e3be8a190736c932d8d47130023.log; waiting 5 seconds

**Comment by vinzent** [comment]
I'd suggest you to followup with the fluentd community  (https://groups.google.com/g/fluentd) regarding fluentd issues.

**Comment by foram-splunk** [comment]
Hey @svajr2 , are you still facing this issue? Please let us know .

**Comment by foram-splunk** [comment]
Closing this issue . Feel free to re-open it ,if you face the same issue again .
