### ISSUE TITLE
Allow logging to multiple separate indexes

### ISSUE THREAD

**Issue by tredmon** [splunk/splunk-connect-for-kubernetes#57]
My organization needs the ability to send kubernetes logs to multiple separate indexes. This could be accomplished by using a custom values.yaml which specifies the index to be used for each `splunk-kubernetes-logging.logs.<name>.index`, and building a filter to set the index to which the fluent_plugin_splunk_hec will send the event.

**Comment by VinceMD** [comment]
Also needed here

**Comment by VinceMD** [comment]
I would be interested in being able to detect events based on patterns and if matching a pattern (security related) for instance, send to another index.

Can that be done with Splunk connect , one way or another?

**Comment by alanzchan** [comment]
I am also looking for a way to route different application/container logs to multiple separate indexes. Currently, I believe it only indexes into the index that was define when HEC is configured and then further abstracted using sourcetypes defined in values.yaml.

**Comment by rockb1017** [comment]
Hello, @alanzchan 
do you mind telling me why you would like to send it to different indexes and by what data point you would like to apply filter ?

**Comment by rockb1017** [comment]
resolved as part of #294

**Comment by provcristianmaluenda** [comment]
Thanks!
