### ISSUE TITLE
Deploying the Kubernetes Logging manifest files only  

### ISSUE THREAD

**Issue by jaypalpatil** [splunk/splunk-connect-for-kubernetes#571]
Dear All,

Can someone pls tell me that can I just implement the kubernetes logging manifests file only..??

And what the changes needs to be done in manifest files..? I am confused in documentation.

Thank you..!!

**Comment by vinzent** [comment]
Use helm to deploy.

**Comment by jaypalpatil** [comment]
For HELM what are the pre-requisites..??

**Comment by vinzent** [comment]
https://github.com/splunk/splunk-connect-for-kubernetes#deploy-with-helm

**Comment by jaypalpatil** [comment]
Is there any issue with Manifest Deployment..??

**Comment by vinzent** [comment]
from the README.md:

> Helm is the only method that the Splunk software supports for installing Splunk Connect for Kubernetes.

**Comment by jaypalpatil** [comment]
But the documentation mentioned that Manifest Deployment method... Why is that..??

**Comment by matthewmodestino** [comment]
to show folks what the automation does. handbombing yaml will lead to pain....we can use helm client with `helm template` to render what you want to run, then you can take that and do what suits your deploys....did you get it working?

**Comment by harshit-splunk** [comment]
Hey @jaypalpatil,  were you able to deploy logging plugin using manifest file? Please let us know.

**Comment by harshit-splunk** [comment]
Closing the issue for now. Feel free to reopen or create a new one if needed.
