### ISSUE TITLE
add additional annotations and labels on top of existing ones. 

### ISSUE THREAD

**Issue by tehlers320** [splunk/splunk-connect-for-kubernetes#574]
**What would you like to be added**: 
an additional annotations and additional labels values.yaml option.

When creating the default helm charts annotations have this setup for example.
```sh
helm create foo
cat foo/values.yaml |grep annotations
  annotations: {}
  annotations: {}
```

**Why is this needed**:
When adding things to your kuberenetes such as mutating webhooks you need to be able to add an annotation and or label in some cases to take/prevent action. (like linkerd and istio for example). While you can enable/disable most mutating webhooks at the namespace level it would still be ideal to have the ability to add annotations/labels to the pods at a minimum.

**Comment by vinzent** [comment]
Alternatively you could use the helm `--post-renderer` option with `kustomize` to inject specific site configs.

https://helm.sh/docs/topics/advanced/#post-rendering
https://github.com/thomastaylor312/advanced-helm-demos/tree/master/post-render

**Comment by rockb1017** [comment]
though there is a workaround, this is nice to have. Thank you for bringing it up. this should be simple. 
I can work on it later or if PR comes, I can merge it.

**Comment by tehlers320** [comment]
@vinzent thanks for the suggestion, but things such as helm-operator do not support this yet. https://github.com/fluxcd/helm-operator/issues/365

**Comment by vinzent** [comment]
@tehlers320 partial kustomize post-render feature was merged Feb 3: https://github.com/fluxcd/helm-controller/pull/202

**Comment by foram-splunk** [comment]
Hey @tehlers320 , you can add annotations here 
https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/daemonset.yaml#L29-L31
