### ISSUE TITLE
After setting up the Splunk app for infrastructure the events are loading from pods to Splunk, but in the entity UI nothing is coming.

### ISSUE THREAD

**Issue by sathishstorm** [splunk/splunk-connect-for-kubernetes#575]
**What happened**: Splunk enterprise is not showing kubernetes entities in the UI but the events are loading

**What you expected to happen**:both events and the kubernetes  entity should load.

**How to reproduce it (as minimally and precisely as possible)**: go to splunk app for infrastructure -> select kubernetes -> fill the details -> run the command that is created. then when checked in indexes the entries are available and updated secs ago.
but in the entity UI is not showing the added kubernetes  details

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Ruby version (use `ruby --version`):-bash: ruby: command not found
- OS (e.g: `cat /etc/os-release`):
NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.3 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.3:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.3"

- Splunk version:Version:8.1.2 Build:545206cc9f70
- Splunk Connect for Kubernetes helm chart version:1.3.0
- Others:

**Comment by Ramkumar1302** [comment]
Even I am facing the same issue. Did we missed anything like port permissions.

**Comment by sathishstorm** [comment]
Hi Team

Issue is resolved, While we are using Splunk app for infrastructure, the dependency app should be installed Splunk Add-on for Infrastructure.

After installing Splunk Add-on for Infrastructure i am able to see the data's flowing in entities UI  :)
