### ISSUE TITLE
Splunk entities group we are unable to filter only active entities using splunk app for infrastructure

### ISSUE THREAD

**Issue by sharlin7** [splunk/splunk-connect-for-kubernetes#577]
Hi All,
kindly help to add only active entities in kubernetes splunk entities group setup
we are able to get all the entities such as active and inactive entities but our requirement is only to group active entities.
while trying to group the entities with status it is throwing error . Kindly help here to achieve the same.

**Comment by Ramkumar1302** [comment]
Even i am facing the same issue not found any solution yet.

**Comment by matthewmodestino** [comment]
Hi @sharlin7 are you refering to an app's use of the data sent? Can you please provide more details as to whether you are referring to something you feel needs to be done at the collector side, or something you need from the Splunk query side...
