### ISSUE TITLE
No Parameter for key_passwd for client certificates in values

### ISSUE THREAD

**Issue by godman-k** [splunk/splunk-connect-for-kubernetes#579]
<

**What would you like to be added**:
`key_passwd` parameter doesn’t exist in [Splunk values](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/values.yaml#L11-L38) Section 
**Why is this needed**:
Some client certs are password protected and needs password to access the key file but i don't see any field for it

**Comment by vinzent** [comment]
As a workaround you could remove the passphrase from the private key.

```
 openssl rsa -in privatekey_with_pass.key -out privatekey_without_pass.key
```

**Comment by godman-k** [comment]
Thanks for the information , I will try it out!
