### ISSUE TITLE
Support different sourcetype per containers in pod

### ISSUE THREAD

**Issue by zeldigas** [splunk/splunk-connect-for-kubernetes#580]
**What would you like to be added**: Ability to associate specific sourcetype (as well as other metadata probably, but it's not that important) with individual containers in pod. Right now `splunk.com/sourcetype` annotation is applied to all containers in pod only.

**Why is this needed**: 
As sourcetype by design is assumed to provide information about log types, current scheme of specifying it on pod level lead to issues with automatically inject sidecars.

For example assume that I have an application that send logs in json (and I'd like sourcetype to be `my_company_json`). If I specify `splunk.com/sourcetype: my_company_json` this would lead that all sidecar containers, e.g. istio-proxy to have same sourcetype but log format there is completely different - plain text, that deserves it's own sourcetype

This fact complicates log filtering and processing.

**Ideas for implemntation**
As container name is known from k8s metadata, it can be possible to lookup sourcetype value with it in mind, e.g. `splunk.com/sourcetype/<container-name>: <value`. With this it'd be possible to craft this kind of annotations:

```
splunk.com/sourcetype/app: my_company_json
splunk.com/sourcetype/istio-proxy: istio-sidecar
```

**Comment by rockb1017** [comment]
if you don't use any annotation, it will have `kube:container:<CONAINER_NAME>` as sourcetype.
`kube:` prefix is also configurable.

**Comment by zeldigas** [comment]
@rockb1017 I consider this as suboptimal approach as it:
1. forces app teams to pick non-intersecting container names (assumind idea let's use unique source types 4 all!) or container names bounded to log format (e.g. if 3 teams use one log format, they need to use same container name)
2. still does not reliably protect from case when containers with different log formats share same computed sourcetype value

**Comment by harshit-splunk** [comment]
@zeldigas I would suggest adding customFilters. Update sourcetype field according to your need using recored_modifier plugin.
Doc referance: https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/values.yaml#L471-L505
