### ISSUE TITLE
SCK unable to read container logs

### ISSUE THREAD

**Issue by vijaymateti** [splunk/splunk-connect-for-kubernetes#588]
**What happened**: Deployed SCK on EKS. All the objects and metrics are showing up on Splunk server but logs are missing.

**What you expected to happen**:

None of the container logs are showing up. The output of fluentd logging pods logs is like follows

2021-03-24 20:33:49 +0000 [warn]: #0 [containers.log] /var/log/pods/splunk_splunk-splunk-kubernetes-logging-5l7ch_d6da5542-6814-45af-bc1e-f97d3264f08d/splunk-fluentd-k8s-logs/0.log unreadable. It is excluded and would be examined next time.

I have tried both log path has /var/log/containers/*.log as well as /var/log/pods/*/*/*.log on helm chart values configuration and  both have same errors. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): EKS 1.17
- Ruby version (use `ruby --version`): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Splunk version:  Version: 8.1.1
- Splunk Connect for Kubernetes helm chart version: splunk-connect-for-kubernetes-1.4.6
- Others:

**Comment by vijaymateti** [comment]
While debugging we found that /var/log/containers/*.log symlinked to /var/pods/*/*.logs and which is inturn symlinked to /usr/docker/containers/*/*.log. Not sure if this is how EKS manages the logs. I find that the splunk daemonset volume mounts do not include the hostpath /usr/docker so after adding this path to deamonset spec the issue is resolved. If this is default EKS behavior can this be fixed on SCK upstream helm chart?

volumeMounts:       
  - mountPath: /usr/docker         
  -   name: usrdocker         
  
volumes:       
- hostPath:          
-  path: /usr/docker           
- type: ""

**Comment by foram-splunk** [comment]
Hey @vijaymateti , any updates on this issue ?

**Comment by foram-splunk** [comment]
Closing this issue . Feel free to re-open it ,if you face the same issue again .
