### ISSUE TITLE
Routing kubernetes-object data to different indexes based on namespace

### ISSUE THREAD

**Issue by sayeedc** [splunk/splunk-connect-for-kubernetes#59]
For the kubernetes-logging data, I am routing data for each namespace to separate indexes based on the value for **| .namespace = $parts[1]** that is defined in **extract index fields and sourcetype for container logs**

I use an additional filter to set the index key for 

<filter tail.containers.**>
        @type jq_transformer
        jq '.record | .index = "prefix_name_"+.namespace+"_cluster_name_suffix"
</filter>

How can I use the same process to route the objects data via namespace to same index. The difference is that namespace is found in the metadata rather than a filename.   For each objects data e.g. kubernetes events, the metadata field that references the namespace is different. 

Do you have any examples for defining an extraction from metadata fields?

**Comment by matthewmodestino** [comment]
Hey SayeedC,

We’re you able to get this sorted?

**Comment by sayeedc** [comment]
Hey Matt,

I’ve got this working now by creating additional filters for the Kube events, objects within a namespace and those at the cluster level.

Sayeed

**Comment by beth2016** [comment]
@sayeedc 
I need to do the same.   is it ok to share the additional filters you have created? thanks.
