### ISSUE TITLE
Getting duplicate application events to splunk each log is  reflecting 2times in splunk where as in standard output of applicaiton log is oly 1 time for few applciation pods

### ISSUE THREAD

**Issue by shanmukha511** [splunk/splunk-connect-for-kubernetes#594]
**What happened**:

Have observed duplicate events getting reflecting in splunk using sck where in standard output there is oly 1 occurrence of that log.
if 1 event occur in standard ouput and its showing 2 events in splunk.

**What you expected to happen**:

Should push whatever the logs display in standard output and shouldnt send duplicates as there not present in standard output.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

This happening for oly some application pods and this is happening even in 1.4.3 as well. We deploying sck via helm chart.

**Values.yaml**

logLevel:

fluentd:
  path: /var/log/containers/*qa*.log,/var/log/containers/*dev*.log
containers:
  path: /var/log
  pathDest: /var/lib/docker/containers
  logFormatType: json
  logFormat:

journalLogPath: /var/log/journal

k8sMetadata:
  podLabels:
    - app
    - k8s-app
    - release
  watch: true
  cache_ttl: 3600

sourcetypePrefix: "kube"
splunk:
  hec:
    host:
    port: 8088
    token:
    protocol: https
    indexName:
    insecureSSL: true
serviceAccount:
  create: true
  name:
  usePullSecrets: true

podSecurityPolicy:
  create: false

secret:
  create: true
  name:

logs:
  docker:
    from:
      journald:
        unit: docker.service
    timestampExtraction:
      regexp: time="(?<time>\d{4}-\d{2}-\d{2}T[0-2]\d:[0-5]\d:[0-5]\d.\d{9}Z)"
      format: "%Y-%m-%dT%H:%M:%S.%NZ"
    sourcetype: kube:docker
  kubelet: &glog
    from:
      journald:
        unit: kubelet.service
    timestampExtraction:
      regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
      format: "%m%d %H:%M:%S.%N"
    multiline:
      firstline: /^\w[0-1]\d[0-3]\d/
    sourcetype: kube:kubelet
  node-problem-detector: &glog
    from:
      journald:
        unit: node-problem-detector.service
    timestampExtraction:
      regexp: \w(?<time>[0-1]\d[0-3]\d [^\s]*)
      format: "%m%d %H:%M:%S.%N"
    multiline:
      firstline: /^\w[0-1]\d[0-3]\d/
    sourcetype: kube:node-problem-detector
  etcd:
    from:
      pod: etcd-server
      container: etcd-container
    timestampExtraction:
      regexp: (?<time>\d{4}-\d{2}-\d{2} [0-2]\d:[0-5]\d:[0-5]\d\.\d{6})
      format: "%Y-%m-%d %H:%M:%S.%N"
  etcd-minikube:
    from:
      pod: etcd-minikube
      container: etcd
    timestampExtraction:
      regexp: (?<time>\d{4}-\d{2}-\d{2} [0-2]\d:[0-5]\d:[0-5]\d\.\d{6})
      format: "%Y-%m-%d %H:%M:%S.%N"
  etcd-events:
    from:
      pod: etcd-server-events
      container: etcd-container
    timestampExtraction:
      regexp: (?<time>\d{4}-[0-1]\d-[0-3]\d [0-2]\d:[0-5]\d:[0-5]\d\.\d{6})
      format: "%Y-%m-%d %H:%M:%S.%N"
  kube-apiserver:
    <<: *glog
    from:
      pod: kube-apiserver
    sourcetype: kube:kube-apiserver
  
  kube-scheduler:
    <<: *glog
    from:
      pod: kube-scheduler
    sourcetype: kube:kube-scheduler
  kube-controller-manager:
    <<: *glog
    from:
      pod: kube-controller-manager
    sourcetype: kube:kube-controller-manager
  kube-proxy:
    <<: *glog
    from:
      pod: kube-proxy
    sourcetype: kube:kube-proxy
  kubedns:
    <<: *glog
    from:
      pod: kube-dns
    sourcetype: kube:kubedns
  dnsmasq:
    <<: *glog
    from:
      pod: kube-dns
    sourcetype: kube:dnsmasq
  dns-sidecar:
    <<: *glog
    from:
      pod: kube-dns
      container: sidecar
    sourcetype: kube:kubedns-sidecar
  dns-controller:
    <<: *glog
    from:
      pod: dns-controller
    sourcetype: kube:dns-controller
  kube-dns-autoscaler:
    <<: *glog
    from:
      pod: kube-dns-autoscaler
      container: autoscaler
    sourcetype: kube:kube-dns-autoscaler
  kube-audit:
    from:
      file:
        path: /var/log/kube-apiserver-audit.log
    timestampExtraction:
      format: "%Y-%m-%dT%H:%M:%SZ"
    sourcetype: kube:apiserver-audit
  test-pod:
    from:
      pod: test-pod
    multiline:
      firstline: /^\d{4}-\d{2}-\d{2}/ 

image:
  registry: docker.io
  name: splunk/fluentd-hec
  tag: 1.2.4
  pullPolicy: Always
  usePullSecret: true

resources:
  requests:
    cpu: 100m
    memory: 200Mi

buffer:
  "@type": memory
  total_limit_size: 600m
  chunk_limit_size: 20m
  chunk_limit_records: 100000
  flush_interval: 5s
  flush_thread_count: 1
  overflow_action: block
  retry_max_times: 5
  retry_type: periodic

sendAllMetadata: false
tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule

nodeSelector:
  beta.kubernetes.io/os: linux

affinity: {}

priorityClassName:

kubernetes:
  clusterName:
  securityContext: false

customMetadata:

customFilters: {}

indexFields: []

global:
  logLevel: info
  splunk:
    hec:
      host:
      port: 8088
      token:
      protocol: https
      indexName:
      insecureSSL: true
      clientCert:
      clientKey:
      caFile:
  kubernetes:
    clusterName: ""
  prometheus_enabled: true
  monitoring_agent_enabled: false

**Environment**:
- Kubernetes version (use `kubectl version`):  GKE
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-dispatcher", GitCommit:"2e298c7e992f83f47af60cf4830b11c7370f6668", GitTreeState:"clean", BuildDate:"2019-09-19T22:31:45Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.7800", GitCommit:"cef3156c566a1d1a4b23ee360a760f45bfbaaac1", GitTreeState:"clean", BuildDate:"2020-12-14T09:12:37Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:
- Splunk Connect for Kubernetes helm chart version: 1.4.6
- Others:

**Comment by matthewmodestino** [comment]
Any warns or errors or retires from your logging pods? whats your splunk architecture look like?

**Comment by shanmukha511** [comment]
No Error or warnings.

Architecture

SCK - Heavy forwarder - splunk 

It been observed sometime back wn i raised not now

wt could be the reason for this ?

**Comment by harshit-splunk** [comment]
@shanmukha511 are you still facing the issue?

**Comment by shanmukha511** [comment]
@harshit-splunk  pls go ahead and close it.

**Comment by harshit-splunk** [comment]
Thanks :)
