### ISSUE TITLE
Default Dashboard for Kubernetes Metrics

### ISSUE THREAD

**Issue by vijaymateti** [splunk/splunk-connect-for-kubernetes#595]
t**What would you like to be added**: I see that SCK support kubernetes metrics on top of logging. Building all the queries required for monitoring could be  cumbersome for few. Do you reference dashboard that works for most kubernetes to copy from ?

**Why is this needed**: Monitor kubernetes metrics and generate any alerts for unusual behavior.

**Comment by vijaymateti** [comment]
@rockb1017 Can you help with this?

**Comment by matthewmodestino** [comment]
HI @vijaymateti metric dashboards are not the realm of the collector itself. Apps to use the data and what collectors are used varied greatly these days. Maybe join us in the slack community splk.it/slack #kubernetes and we can discuss apps that can use this data

**Comment by foram-splunk** [comment]
Hey @vijaymateti , any updates/questions regarding this issue ? Please let us know .

**Comment by foram-splunk** [comment]
Closing this issue . Feel free to re-open it ,if you face the same issue again .
