### ISSUE TITLE
How can I configure Splunk connect for k8s without giving the splunk HEC port

### ISSUE THREAD

**Issue by megnere** [splunk/splunk-connect-for-kubernetes#596]
Hello

I am using a Splunk Enterprise deployment and a reverse proxy server in front of Splunk. So right now we rewrite the HEC endpoint like this : https://external_url/hec => https://splunk_url:8088
To monitor my K8S cluster, I need to use https://external_url/hec. This is not working for me because it seems like the port is always set up in the Splunk connect for k8s configuration. In my case, I dont need the port.

How can I configure the Splunk connect for K8s in this specific case ? 

Thanks

**Comment by rockb1017** [comment]
Hello,

for `https`, you can use port 443 because it is port used by default for https.
for `http` it is 80

**Comment by megnere** [comment]
Hello this solution is not working, because I cannot put the URI in that case. I need to be able to configure this traget **https://external_url:443/hec** . It seems that  is not possible with the available parameters (hec_host, hec_protocol, hec_port).

**Comment by rockb1017** [comment]
Do you have proxy server in between? 
you can use env var for proxy settings
