### ISSUE TITLE
[OpenShift] How would I upgrade from 1.4.6 to 1.4.7 via commandline? 

### ISSUE THREAD

**Issue by catherinelam** [splunk/splunk-connect-for-kubernetes#598]
Hello! I'm new to helm and I'm having a hard time figuring out how to upgrade from my existing version 1.4.6 SplunkConnect to 1.4.7. 

In OpenShift, it does not show there is a version 1.4.7 to upgrade to in the drop down menu, so I'm assuming I have to somehow push new charts that way? 

I also attempted to run:

helm upgrade splunk -f values.yaml https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.4.7/splunk-kubernetes-logging-1.4.7.tgz

With the exact same values.yaml I customized for 1.4.6. However, I noticed that on spin up, the new daemonset had Privileged set to false, instead of true. If I correct it, my pods start throwing a 'pattern not matched' error. I observed this with 1.4.6 and deleted the whole Helm release and redeployed it, whereby Privileged was initially set to true (it's set to true in the values.yaml file) and it went through. I'm not sure why that flag is switching to false. 

What's the right way to do this :(

**Comment by rockb1017** [comment]
Have you deployed 1.4.7 now or are you back to 1.4.6?

**Comment by catherinelam** [comment]
> Have you deployed 1.4.7 now or are you back to 1.4.6?

I'm still at 1.4.6. Do you know which value in the values.yaml corresponds to the pod having the privileged parameter set as true? I want to make sure maybe I'm not missing something.

**Comment by rockb1017** [comment]
you can set this `.Values.kubernetes.securityContext` to true.

**Comment by catherinelam** [comment]
Oh perfect. That's what I was missing. Other than that, my original upgrade command worked. Thank you :)
