### ISSUE TITLE
non-container log files are sendt to the main index 

### ISSUE THREAD

**Issue by sigbjornt** [splunk/splunk-connect-for-kubernetes#603]
**What happened**:
After upgrading splunk connect from v1.4.3 to 1.4.6/1.4.7, some logs are sent to the main splunk index. 

It seems like the issue is  a missing text replacement in the commit https://github.com/splunk/splunk-connect-for-kubernetes/commit/51b94c2a190ec9f8a3f793f5d4d078f1e776d47b
Line 319 in helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml  is using `.index =` instead of `.splunk_index =`

**What you expected to happen**:
The logs should still end up in the specified index

**How to reproduce it (as minimally and precisely as possible)**:
1: ​Set `indexName` to anything except from main. 
2: install splunk connect  v1.4.7
3: place a file to index at the path `/var/log/kube-apiserver/audit.log`

**Anything else we need to know?**:
A PR that shows the exact change have been made here #602 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19 (Openshift 4.6)
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`): coreos
- Splunk version:
- Splunk Connect for Kubernetes helm chart version: 1.4.7
- Others:

**Comment by sigbjornt** [comment]
A pull request that shows the change have been made here #602  (not sure why it failed
)

**Comment by rockb1017** [comment]
just rerunning pipeline passed it. merged! Thank you!

**Comment by sigbjornt** [comment]
@rockb1017 : would it be possible to cut a release that contains this fix any time soon?

**Comment by rockb1017** [comment]
sure. i will try to get a release out soon
