### ISSUE TITLE
metrics(like kube.namespace.memory.limit ) does not get proper value while the pod in the namespace use different unit

### ISSUE THREAD

**Issue by vbasic123** [splunk/splunk-connect-for-kubernetes#605]
**What happened**:
metrics(like kube.namespace.memory.limit ) does not get proper value while the pod in the namespace use different unit(for example, some pod use Gi, while some other use Mi)
**What you expected to happen**:
Expects the memory limit of namespace equal sum of the pods' memory limit in the namespace 
**How to reproduce it (as minimally and precisely as possible)**:
comparing the value in splunk search can see great difference for namespace have pod use different unit for memory limit
```bash
|mstats avg(kube.namespace.memory.limit) WHERE index="xxx" by name
|mstats avg(kube.pod.memory.limit) WHERE index="xxx" by name
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.13-gke.400
- Ruby version (use `ruby --version`): n/a
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5 LTS
- Splunk version: 7.3.5/8.1.3
- Splunk Connect for Kubernetes helm chart version: 1.4.7
- Others:

**Comment by rockb1017** [comment]
can you share the numbers you are seeing with great difference? 
btw, here is info on metrics. https://github.com/splunk/fluent-plugin-kubernetes-metrics/blob/develop/metrics-information.md

**Comment by vbasic123** [comment]
Hi @rockb1017 
One of the metrics(kube.pod.memory.limit) that we get number from splunk is 1289090.189.
While we get the memory limit by kubectl is as below
resources:
  limits:
     cpu: "1"
     memory: 1288490188800m

By comparing the real memory limit and the limit we get in splunk, we noticed that the unit for splunk is KB instead of MB in this case.
And this is only one of the metrics got problem, kube.namespace.memory.limit will also have issue whenever the pods use unaligned memory limit unit defined in its yams.

**Comment by vbasic123** [comment]
Hi @rockb1017 
One of the metrics(kube.pod.memory.limit) that we get number from splunk is 1289090.189.
While we get the memory limit by kubectl is as below
resources:
  limits:
     cpu: "1"
     memory: 1288490188800m

By comparing the real memory limit and the limit we get in splunk, we noticed that the unit for splunk is KB instead of MB in this case.
And this is only one of the metrics got problem, kube.namespace.memory.limit will also have issue whenever the pods use unaligned memory limit unit defined in its yams.

**Comment by harshit-splunk** [comment]
hey @vbasic123 
I have updated metric-aggr plugin. 
Closing the issue. Feel free to reopen the issue or create a new one if needed
