### ISSUE TITLE
Filter journald based on priority

### ISSUE THREAD

**Issue by MikeTomlin19** [splunk/splunk-connect-for-kubernetes#606]
**What would you like to be added**: A way to set the priority level of the journald logs that are sent to splunk.  For example, I only want priority 0-4 to be sent to splunk, and the info-level journald logs can be ignored.

I thought I would be able to do this with the below journald stanza in my configmap, but the info-level logs still come through:

    <source>
      @id journald-kubelet
      @type systemd
      @label @CONCAT
      tag journald.kube:kubelet
      path "/var/log/journal"
      matches [{ "_SYSTEMD_UNIT": "kubelet.service", "PRIORITY": [0,1,2,3,4] }]
      read_from_head true
      <storage>
        @type local
        persistent true
        path /var/log/splunkd-fluentd-journald-kubelet.pos.json
      </storage>
      <entry>
        field_map {"MESSAGE": "log", "_SYSTEMD_UNIT": "source"}
        field_map_strict true
      </entry>
    </source>

**Why is this needed**:  This would allow the user to prevent a large volume of logs from being sent to splunk, that they don't need.

**Comment by MikeTomlin19** [comment]
Update: the above does work if I set the sendAllMetadata var to true in the values.yaml file.  Any idea why that is?

**Comment by matthewmodestino** [comment]
Hey @MikeTomlin19, probably cause it retains the fluentd record to ensure the filter matches is my guess...

**Comment by foram-splunk** [comment]
Hey @MikeTomlin19 , any updates for this issue ? Should we close it ? Please let us know .

**Comment by MikeTomlin19** [comment]
Hello, yes feel free to close as there was a workaround identified above.

**Comment by foram-splunk** [comment]
Thanks :) Closing it .
