### ISSUE TITLE
Helm install not ingesting values for some deployments - issue intermittently happens

### ISSUE THREAD

**Issue by catherinelam** [splunk/splunk-connect-for-kubernetes#607]
**What happened**:
When I run 'helm install splunk-connect -f values.yaml https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.4.7/splunk-kubernetes-logging-1.4.7.tgz' or 'helm install splunk-connect -f values.yaml splunk/splunk-connect-for-kubernetes', sometimes some of the values indicated in the values.yaml are not reflected in the daemonset created. I tried both ways of indicating the repo in case it made a difference. 

Some of the values that affect deployment, but are intermittently not reflected in daemonset / config map include:

- insecure_ssl = true (in config map)
- privileged = true (in daemon set)
- log format = crio (unsure where this is actually reflected)

I have found that retrying the deployment will sometimes create the proper values. I can manually edit the insecure_ssl and privleged parameters in the respective YAMLs. I just haven't been able to figure out where to correct the log format if it is not properly set. I know that I am providing the right values.yaml file because it does at least register the correct Splunk instance details. 

`global:
  splunk:
    hec:
      token: <REMOVED>
      host: <REMOVED>
      port: 8088
      protocol: https
      indexName: <REMOVED>
      insecure_ssl: true
  kubernetes:
    clusterName: <REMOVED>
splunk-kubernetes-logging:
  resources:
    # limits:
    #  cpu: 100m
    #  memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi
  enabled: true
  kubernetes:
    # the next actually sets .securityContext.privileged
    # privileged is required, due to SELinux preventing
    # write access for the *.pos files of fluentd.
    securityContext: true
  containers:
    logFormatType: cri
    logFormat: "%Y-%m-%dT%H:%M:%S.%N%:z"
  logs:
    # The `kube-audit` file has another path on OpenShift
    kube-audit:
      from:
        file:
          path: /var/log/kube-apiserver/audit.log
    # Next 2 logfiles are specific to OpenShift
    openshift-audit:
      from:
        file:
          path: /var/log/openshift-apiserver/audit.log
      timestampExtraction:
        format: "%Y-%m-%dT%H:%M:%SZ"
      sourcetype: kube:openshift-apiserver-audit
    oauth-audit:
      from:
        file:
          path: /var/log/oauth-apiserver/audit.log
      timestampExtraction:
        format: "%Y-%m-%dT%H:%M:%SZ"
      sourcetype: kube:oauth-apiserver-audit
splunk-kubernetes-metrics:
  enabled: false
splunk-kubernetes-objects:
  enabled: false`

**What you expected to happen**:
Every time I install using the values.yaml file, all values indicated in the file will be reflected properly in the objects created by the deployment. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Save the above values.yaml file. 
2. Run 'helm install splunk-connect -f values.yaml https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.4.7/splunk-kubernetes-logging-1.4.7.tgz'
3. Check the daemonset YAML, the splunk-connect-kubernetes-logging configmap, and the pods to ensure proper deployment. Paying close attention to the three values indicated above. 

**Anything else we need to know?**:
This issue only happens sometimes with deployment using the exact same values.yaml. It also occurs when running 'helm upgrade'. 

**Environment**:
- Kubernetes version (use `kubectl version`): OpenShift 4.6
- Ruby version (use `ruby --version`): N/A
- OS (e.g: `cat /etc/os-release`): 
- Splunk version: 
- Splunk Connect for Kubernetes helm chart version: 1.4.7
- Others:

**Comment by catherinelam** [comment]
Ah, I apologize for the values.yaml formatting. Is there a way to retain the indentation?

**Comment by rockb1017** [comment]
It should be taking effects in these places.
* insecure - https://github.com/splunk/splunk-connect-for-kubernetes/blob/eab9ab19617fcd153e47aac417c80727f7edf0e7/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L356
* privileged - https://github.com/splunk/splunk-connect-for-kubernetes/blob/eab9ab19617fcd153e47aac417c80727f7edf0e7/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/daemonset.yaml#L53
* cri - https://github.com/splunk/splunk-connect-for-kubernetes/blob/eab9ab19617fcd153e47aac417c80727f7edf0e7/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L91 
Are you saying your config values are properly applied only sometimes? You can also try `helm template` function to verify and debug mode as well.

**Comment by foram-splunk** [comment]
Hey @catherinelam , were you able to solve this issue ? Please let us know.

**Comment by itscatherinelam** [comment]
> Hey @catherinelam , were you able to solve this issue ? Please let us know.

I was. In the values.yaml file, I defined the values where I think they should have been and now it ingests fine. I think the mapping might be off. I just have them on the first non-indentation level (I apologize, I'm not familiar with the right terminology.)

```
kubernetes:
    securityContext: true
containers:
    logFormatType: cri
splunk:
    hec:
      insecureSSL: true
```

**Comment by foram-splunk** [comment]
Thanks . Closing this issue . :)
