### ISSUE TITLE
Need some clarity on "monitoring_agent"

### ISSUE THREAD

**Issue by gnarc** [splunk/splunk-connect-for-kubernetes#609]
Hi *

I'd like to have some clarity on the current and maybe future usage of the parameter 
>       monitoring_agent_enabled:
in all of the values.yaml files.

ATM (1.4.7 and develop branch) setting this parameter will only affect the configuration of the logging ConfigMap according to 
- https://github.com/splunk/splunk-connect-for-kubernetes/issues/498
- https://github.com/splunk/splunk-connect-for-kubernetes/pull/340 

This parameter is also set to true in all the specific values.yaml files for each chart (metrics, objects), but it will
only have an effect for the logging ConfigMap since only that template does a check for the monitoring_agent parameter
and acts accordingly:
```
{{- if .Values.global.monitoring_agent_enabled }}
@include monit.conf
```
This code is missing in the objects and metrics ConfigMaps's templates so it will never be activated in these charts.

The background is that we use this endpoint as a poor man's liveness probe on OCP to mitigate Ruby crashes in the objects pod.
(I'm open ears for a better idea on the whole livenessprobe issue. It's not ideal but mostly working).
Right now we have to explicitly change the fluent.conf for metrics, metrics-agg and objects which is a bit cumbersome using ansible playbooks. If we could control it using the umbrella values.yaml, that would help a lot.

So my enhancement request would be
1. Add a comment in the umbrella values.yaml explaining what the parameter does (and does not!) would be nice
2. Allow configuration of "monitoring_agent" for all charts in their specific section in the umbrella values.yaml.

thx

**Comment by retraut** [comment]
Hi @gnarc,


Seems like it was my error.
I had a problem described in #498
When I found problem I created PR #340 for these changes but accidentally added parameter in all values.yaml files.
I followed the next steps 

- I have searched `prometheus_enabled`
- Created similar changes with PR #340 

Original `prometheus_enabled` added to the same files where we can find  `monitoring_agent_enabled`

**Comment by gnarc** [comment]
Hi @retraut,
thanks for the quick reply.

What are the chances to get this feature?

From my understanding most of the work has already been done, all there's missing seem to be the code snippets for the remaining three ConfigMap templates,
probably something like this
```
{{- if .Values.global.monitoring_agent_enabled }}
    <source>
      @id fluentd-monitor-agent
      @type monitor_agent
      @label @SPLUNK
      tag monitor_agent
    </source>
{{- end }}
```
plus some tweaks in the values.yaml. For prometheus_enabled the same if desired.

Not much of a coder to provide a PR...

Cheers

**Comment by retraut** [comment]
I think a correct action - is to remove values `monitoring_agent_enabled` and  `prometheus_enabled` from other charts except `splunk-kubernetes-logging`

**Comment by gnarc** [comment]
I see. From the perspective of cleaning up code, I agree.
From an enhancement point of view...is there any reason not to have it? After all it has already been put in place for one out of four components.
