### ISSUE TITLE
Host logs configuration

### ISSUE THREAD

**Issue by vennemp** [splunk/splunk-connect-for-kubernetes#611]
Maybe I’m missing something in docs but how can you forward /var/log directories from the hosts to splunk? The container logs are sending fine but not  the local host logs.

**Comment by matthewmodestino** [comment]
You can update your `values.yaml` to include custom paths, assuming the volume is mounted into the pod...

https://github.com/splunk/splunk-connect-for-kubernetes/blob/eab9ab19617fcd153e47aac417c80727f7edf0e7/helm-chart/splunk-connect-for-kubernetes/values.yaml#L191-L258

**Comment by vennemp** [comment]
So in other words, I need to mount a hostPath volume to the Splunk connect container at the requisite hostPath and then specify the associated container file system path. 

Which section in that Config is that?

**Comment by vennemp** [comment]
Or is that the docker section with docker.log?

**Comment by harshit-splunk** [comment]
Hey @vennemp, 
> So in other words, I need to mount a hostPath volume to the Splunk connect container at the requisite hostPath and then specify the associated container file system path.

yes

> Which section in that Config is that?

you need to mound your path using `volumeMounts` and `volumes` in https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/daemonset.yaml.

**Comment by harshit-splunk** [comment]
I want to add that  host machine's `/var/log` directory is already mounted. So you only need to add your file to `splunk-kubernetes-logging.logs` config .
Reference: https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/values.yaml#L242-L245

**Comment by harshit-splunk** [comment]
Closing the issue for now. Feel free to reopen or create a new one if needed.
