### ISSUE TITLE
path /var/log/kube-apiserver-audit.log should be path /var/log/kube-apiserver/audit.log

### ISSUE THREAD

**Issue by vogtph** [splunk/splunk-connect-for-kubernetes#613]
**What happened**: /var/log/kube-apiserver-audit.log does not exist

**What you expected to happen**: reading of /var/log/kube-apiserver/audit.log

**How to reproduce it (as minimally and precisely as possible)**: 

**Anything else we need to know?**:

splunk-connect-for-kubernetes/manifests/splunk-kubernetes-logging/configMap.yaml
source.files.conf
<  path /var/log/kube-apiserver-audit.log
>  path /var/log/kube-apiserver/audit.log

**Comment by matthewmodestino** [comment]
Hi! 

Can you please provide the distribution of Kubernetes you are using and what instructions were followed to implement audit, as the audit path is configured in the kubelet settings and can be set to any path, technically....

**Comment by vogtph** [comment]
Hi Matthew

I did not realize that kubernetes itself has not a fixed location for the
audit logs. I am using Openshift version 4.5. I hope to upgrade to 4.6 soon
while that also has oauth auditing, something the company desires.

I still have a lot of studying todo on fluentd configuration and helm
charts. Because I would like to send the audit logs to a separate Splunk
index.


regards,

Paul

**Comment by matthewmodestino** [comment]
👋 OpenShift is at least a bit more opinionated

https://docs.openshift.com/container-platform/4.7/security/audit-log-view.html

but ultimately I'm sure they can customize as needed when dropping in the cluster and configuring the kubelet.

**Comment by gnarc** [comment]
@vogtph:
There is a very condensed example for OpenShift (logging chart only) here

https://github.com/splunk/splunk-connect-for-kubernetes/blob/release/1.4.7/helm-chart/splunk-connect-for-kubernetes/examples/openshift4-logging-only.yaml[](url)

which gives a good idea of the differences to plain k8s (cri-o instead of json, 3 separate audit.logs)

**Comment by harshit-splunk** [comment]
Hey @vogtph, were you able to collect audit logs to a separate Splunk index? Please let us know.

**Comment by harshit-splunk** [comment]
Closing the issue for now. Feel free to reopen or create a new one if needed.
