### ISSUE TITLE
How to filter from which pods to collect metrics based on metadata

### ISSUE THREAD

**Issue by osvaldopina** [splunk/splunk-connect-for-kubernetes#615]
Is there a way to filter from which pods to collect metrics based on pod metadata?

**Comment by matthewmodestino** [comment]
yep!

https://github.com/splunk/splunk-connect-for-kubernetes/blob/eab9ab19617fcd153e47aac417c80727f7edf0e7/helm-chart/splunk-connect-for-kubernetes/values.yaml#L60

You can use the path to set regex or comma separated:

https://docs.fluentd.org/input/tail#path

**Comment by osvaldopina** [comment]
Hi Matthew,

Thanks for the response but I'm not sure it's applicable to metrics or only to logs. What I would like to do is to send pod metrics only if they have some specifics annotations. Something like that:

```yaml
...
metadata:
  ...
  annotations:
    send-metrics: true
...
```

**Comment by matthewmodestino** [comment]
Apologies, i had logs on the brain.

Metrics filtering can be done at the fluentd level, but would require implementation of said filtering mechanism.

I suggest using the `stdout` output plugin to examine the record ro see if the meta you want to filter by is present.

If it comes from labels the ruby code in the logging pod would have to be surgically implanted on the metrics fluentd config
