### ISSUE TITLE
Installing 2 releases of helm chart in one cluster fails

### ISSUE THREAD

**Issue by nafets227** [splunk/splunk-connect-for-kubernetes#619]
**What happened**:
When installing a second release of the same helm chart on the same Kubernetes cluster but in different namespaces, even with different release names, fails with
```
Release "splunk-kubelog-preprod" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "kubelet-summary-api-read" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "splunk-kubelog-preprod": current value is "splunk-kubelog"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "preprod": current value is "prod"
Error in helm upgrade --install splunk-kubelog-preprod splunk/splunk-connect-for-kubernetes

```
**What you expected to happen**:
Installation works and defines ClusterRoles with unique names

**How to reproduce it (as minimally and precisely as possible)**:
```
helm repo add splunk https://...
helm repo update
helm install test1 splunk/splunk-connect-for-kubernetes # works ok
helm install test2 splunk/splunk-connect-for-kubernetes # fails
helm install -n secondnamespace test2 splunk/splunk-connect-for-kubernetes # fails

```
**Anything else we need to know?**:
No.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"archive", BuildDate:"2021-05-14T14:09:09Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:
- Splunk Connect for Kubernetes helm chart version:
1.4.7
- Others:

**Comment by harshit-splunk** [comment]
Hey @nafets227, it is expected behaviour. as you can see here (https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/clusterRole.yaml#L6), it uses `kubelet-summary-api-read` name by default. 
So for second deployment, you can disable `.Values.rbac.create` field and it'll not try to create a cluster role with same name again.

**Comment by harshit-splunk** [comment]
Closing the issue for now. Feel free to reopen or create a new one if needed.
