### ISSUE TITLE
Metrics Going but not appearing in metric index

### ISSUE THREAD

**Issue by TechnicalMercenary** [splunk/splunk-connect-for-kubernetes#620]
**What happened**:

Setup a fresh install to test splunk k8s metrics.  Metric pods start etc and I see 200s in the logs but when I want to search my metrics I don't see anything

**What you expected to happen**:

I expect queries like `| mcatalog values(metric_name)` to have recent values and I expect my metric index to show that it's been updated recently.

**How to reproduce it (as minimally and precisely as possible)**:

Create and AWS EKS Cluster 1.18
Use helm to install the metric collector

**Anything else we need to know?**:

I checked the '_internal' index and I see these errors being produced for all metrics entering my cluster

06-15-2021 21:49:02.194 +0000 ERROR JsonLineBreaker - JSON StreamId:0 had parsing error:Unexpected character while looking for value: 'm' - data_source="kube.container.logs.inodes_used", data_host="ip-10-239-175-26.us-west-2.compute.internal", data_sourcetype="_json"

**Environment**:
- Kubernetes version (use `kubectl version`):

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:14:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Ruby version (use `ruby --version`):

2021-06-15 21:43:03 +0000 [info]: gem 'fluentd' version '1.11.5'
2021-06-15 21:43:03 +0000 [info]: gem 'fluent-plugin-jq' version '0.5.1'
2021-06-15 21:43:03 +0000 [info]: gem 'fluent-plugin-kubernetes-metrics' version '1.1.5'
2021-06-15 21:43:03 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.5.3'
2021-06-15 21:43:03 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.8.5'
2021-06-15 21:43:03 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2021-06-15 21:43:03 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.2.5'

- OS (e.g: `cat /etc/os-release`):
- Splunk version:

Saas 7.0.13

- Splunk Connect for Kubernetes helm chart version:

Splunk Connect for Kubernetes 1.4.7 Release

- Others:

**Comment by TechnicalMercenary** [comment]
[values.yaml.txt](https://github.com/splunk/splunk-connect-for-kubernetes/files/6658980/values.yaml.txt)

**Comment by harshit-splunk** [comment]
Hey @TechnicalMercenary,
From the information, it looks like everything seems fine from SCK. If there was any format issue, HEC collector would return `Invalid data format` error but that's not the case. So need some more information to look into this.
Are you using any add-on which may affect data ingested by SCK?

**Comment by harshit-splunk** [comment]
Closing the issue for now. Feel free to reopen the issue or create a new one if still facing the issue.
