### ISSUE TITLE
Metrics customFilters should apply to aggregated metrics

### ISSUE THREAD

**Issue by dmduggan** [splunk/splunk-connect-for-kubernetes#621]
**What happened**: Expected customFilters to be applied to all metrics. Only showed on kube.container.**.

**What you expected to happen**: I believe it also needs to be applied to aggregated metrics.

**How to reproduce it (as minimally and precisely as possible)**:

Using following values:

```
    customFilters:
      custom_metadata:
        tag: kube.**
        type: record_modifier
        body: |-
          @id custom_metadata
          <record>
            cluster_region us-west-2
          </record>
```

**Anything else we need to know?**:

Probably just need to copy this code between two config maps in metrics chart.

```
    # = custom filters specified by users =
    {{- range $name, $filterDef := .Values.customFilters }}
    {{- if and $filterDef.tag $filterDef.type }}
    <filter {{ $filterDef.tag }}>
      @type {{ $filterDef.type }}
      {{- if $filterDef.body }}
      {{ $filterDef.body | indent 8 }}
      {{- end }}
    </filter>
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.8
- Ruby version (use `ruby --version`): N/A (docker image)
- OS (e.g: `cat /etc/os-release`): 
- Splunk version: 7.3.2
- Splunk Connect for Kubernetes helm chart version: 1.4.7
- Others:

**Comment by harshit-splunk** [comment]
Now you can apply custom filters using `customFiltersAggr` config.
So, it should look like
```
    customFiltersAggr:
      custom_metadata:
        tag: kube.**
        type: record_modifier
        body: |-
          @id custom_metadata
          <record>
            cluster_region us-west-2
          </record>

```
