### ISSUE TITLE
No Internet Connection to Add the Splunk Repo

### ISSUE THREAD

**Issue by jaypalpatil** [splunk/splunk-connect-for-kubernetes#623]
**What happened**:
There's no internet connectivity at my cluster so I am unable to run the below command in my cluster :
helm repo add splunk https://splunk.github.io/splunk-connect-for-kubernetes/

Pls suggest how to add the splunk repo..??

**Comment by rockb1017** [comment]
you can download chart package from release page. https://github.com/splunk/splunk-connect-for-kubernetes/releases
and transfer this file to it. but it will need internet to access docker image. 
in that case, you would have to set up your own internal docker image registry and host iamges there and pull it from there.
