### ISSUE TITLE
Wrong index reference in file tail

### ISSUE THREAD

**Issue by donflavour** [splunk/splunk-connect-for-kubernetes#625]
https://github.com/splunk/splunk-connect-for-kubernetes/blob/27b2308371c38d34189c271b6d676014bf726165/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L319

IMO instead of .record.index  it should be .record.splunk_index.
Otherwise I don't receive the audit logs because of "TcpOutputProc - Pipeline data does not have indexKey."

**Comment by rockb1017** [comment]
it has been fixed. please use the latest version. thank you. 
https://github.com/splunk/splunk-connect-for-kubernetes/commit/51e2fa6e3c9915504e661864565d52047541602e#diff-875e8d2016f8ed2c8bf60dfb37a8b1b29b76655270cde0e9e67472125993dd7d
