### ISSUE TITLE
Liveness probes needed for K8s/OpenShift

### ISSUE THREAD

**Issue by gnarc** [splunk/splunk-connect-for-kubernetes#626]
It would be nice to have out-of-the-box endpoints for k8s/Openshift Livenessprobes which is an essential mechanism  for Pod/container health.

We are currently workarounding it using fluentd-mechanisms

- https://docs.fluentd.org/monitoring-fluentd/monitoring-prometheus
- https://docs.fluentd.org/monitoring-fluentd/monitoring-rest-api
  -  https://docs.fluentd.org/input/monitor_agent

The simplest form is to activate the monitor_agent in fluent.conf (this is already done for logging, also see Enhancement Request https://github.com/splunk/splunk-connect-for-kubernetes/issues/609) and add an simple HTTP GET to the  endpoint. Once this endpoint stops 
being available the pod will be restarted.
This is still better than login into the container and executing an arbitrary command; but it will not give us the certainty that the process itself is still working, just that the endpoint is available. 
We used this to mitigate problems with the objects pod where process threads setting up an event watch threw an exception every time a load balancer would kill the connection after 10min. (it would still work afterwards but leave some hundreds defunct processes behind until nothing could be forked and the container was dead)

In a second iteration we used output from the the endpoint to see if somethings changes.
We hope that "emit_count" is a useful metrics for this purpose:

```#   oc rsh  splunk-connect-splunk-kubernetes-metrics-t48rr   bash -c ' curl -sX GET  http://127.0.0.1:24220/api/plugins '
plugin_id:object:c954   plugin_category:input   type:monitor_agent      output_plugin:false     retry_count:
plugin_id:object:c968   plugin_category:input   type:kubernetes_metrics output_plugin:false     retry_count:
plugin_id:object:11e4   plugin_category:output  type:splunk_hec output_plugin:true      buffer_queue_length:0   buffer_timekeys:        buffer_total_queued_size:763465 retry_count:0   emit_records:322709     emit_count:322709       write_count:216 rollback_count:0   slow_flush_count:0      flush_time_count:13662  buffer_stage_length:1   buffer_stage_byte_size:763465   buffer_queue_byte_size:0        buffer_available_buffer_space_ratios:99.8
plugin_id:object:c97c   plugin_category:filter  type:record_modifier    output_plugin:false     retry_count:
plugin_id:object:c990   plugin_category:filter  type:record_modifier    output_plugin:false     retry_count:
plugin_id:object:c9a4   plugin_category:filter  type:record_modifier    output_plugin:false     retry_count:
plugin_id:object:c9b8   plugin_category:filter  type:record_modifier    output_plugin:false     retry_count:
plugin_id:object:c9cc   plugin_category:filter  type:record_modifier    output_plugin:false     retry_count:
```

So if we use emit_count or one those returned metrics we could create a Liveness probe based on a container command (a script oneliner) to save the metrics and compare it with a later one.
Once it stopped changing the probe fails after n times and the pod will be killed.
We used this to mitigate https://github.com/splunk/splunk-connect-for-kubernetes/issues/493.

Since this is a workaround and we do not know if this endpoint will work until all eternity, it would be nice to have something more official and reliable. 

Wishlist:
* Provide endpoints which guarantees the functionality of the given service (metrics, logging, objects)
* Provide the option to enable/disable it using the umbrella values.yaml file
* at least a statement in the docs, that this is a valid way to go for now.

**Comment by mwang2016** [comment]
Hi @gnarc, thank you for reporting this issue. We have added this feature request to our backlog and the team will decide when to work on this in the future. We also welcome anyone to create a pull request if they are so inclined.

**Comment by gnarc** [comment]
Cool. Thanks.

**Comment by rockb1017** [comment]
it was added in `1.4.9`
