### ISSUE TITLE
option to enable proxy for the splunk-connect-for-kubernetes containers

### ISSUE THREAD

**Issue by ramrajkonuganti** [splunk/splunk-connect-for-kubernetes#627]
apiVersion: v1
kind: Template
metadata:
name: "${APP_NAME}"
objects:

- kind: Secret
apiVersion: v1
data:
#.dockerconfigjson:
metadata:
creationTimestamp: null
name:
label:
app: "${APP_NAME}"
type:
#LOGGING

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: "${LOGGING_NAME}"
labels:
app: "${LOGGING_NAME}"
version: "${LOGGING_RELEASE}"
rules:

apiGroups:
extensions
resources:
podsecuritypolicies
verbs:
use
resourceNames:
"${LOGGING_NAME}"
apiGroups:
""
resources:
namespaces
pods
verbs:
list
get
watch
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: "${LOGGING_NAME}"
labels:
app: "${LOGGING_NAME}"
version: "${LOGGING_RELEASE}"
roleRef:
kind: ClusterRole
name: "${LOGGING_NAME}"
apiGroup: rbac.authorization.k8s.io
subjects:

kind: ServiceAccount
name: "${LOGGING_NAME}"
namespace: "${APP_NAME}"
kind: ConfigMap
apiVersion: v1
metadata:
name: "${LOGGING_NAME}"
labels:
app: "${LOGGING_NAME}"
version: "${LOGGING_RELEASE}"
data:
fluent.conf: |-
@include system.conf
@include source.containers.conf
@include source.files.conf
@include source.journald.conf
@include monit.conf
@include output.conf
@include prometheus.conf
system.conf: |-
# system wide configurations

log_level warn
root_dir /tmp/fluentd

prometheus.conf: |-
# input plugin that exports metrics

@type prometheus

@type forward

# input plugin that collects metrics from MonitorAgent

@type prometheus_monitor

host ${hostname}

# input plugin that collects metrics for output plugin

@type prometheus_output_monitor

host ${hostname}

source.containers.conf: |-
# This configuration file for Fluentd / td-agent is used
# to watch changes to Docker log files. The kubelet creates symlinks that
# capture the pod name, namespace, container name & Docker container ID
# to the docker logs for pods in the /var/log/containers directory on the host.
# If running this fluentd configuration in a Docker container, the /var/log
# directory should be mounted in the container.
# reading kubelet logs from journal
#
# Reference:
# https://github.com/kubernetes/community/blob/20d2f6f5498a5668bae2aea9dcaf4875b9c06ccb/contributors/design-proposals/node/kubelet-cri-logging.md
#
# Json Log Example:
# {"log":"[info:2016-02-16T16:04:05.930-08:00] Some log text here\n","stream":"stdout","time":"2016-02-17T00:04:05.931087621Z"}
# CRI Log Example (not supported):
# 2016-02-17T00:04:05.931087621Z stdout [info:2016-02-16T16:04:05.930-08:00] Some log text here

@id containers.log
@type tail
@Label @concat
tag tail.containers.*
path /var/log/containers/.log
pos_file /var/log/splunk-fluentd-containers.log.pos
path_key source
read_from_head true

@type regexp
expression /^(?.+) (?stdout|stderr) [^ ] (?.)$/
time_format %Y-%m-%dT%H:%M:%S.%N%:z
time_key time
time_type string
localtime false
refresh_interval 60

source.files.conf: |-
# This fluentd conf file contains sources for log files other than container logs.

@id tail.file.kube-audit
@type tail
@Label @concat
tag tail.file.kube:apiserver-audit
path /var/log/kube-apiserver-audit.log
pos_file /var/log/splunk-fluentd-kube-audit.pos
read_from_head true
path_key source

@type regexp
expression /^(?.)$/
time_key time
time_type string
time_format %Y-%m-%dT%H:%M:%SZ

source.journald.conf: |-
# This fluentd conf file contains configurations for reading logs from systemd journal.

@id journald-docker
@type systemd
@Label @concat
tag journald.kube:docker
path "/run/log/journal"
matches [{ "_SYSTEMD_UNIT": "docker.service" }]
read_from_head true

@type local
persistent true
path /var/log/splunkd-fluentd-journald-docker.pos.json

field_map {"MESSAGE": "log", "_SYSTEMD_UNIT": "source"}
field_map_strict true

@id journald-kubelet
@type systemd
@Label @concat
tag journald.kube:kubelet
path "/run/log/journal"
matches [{ "_SYSTEMD_UNIT": "kubelet.service" }]
read_from_head true

@type local
persistent true
path /var/log/splunkd-fluentd-journald-kubelet.pos.json

field_map {"MESSAGE": "log", "_SYSTEMD_UNIT": "source"}
field_map_strict true

monit.conf: |-

@id fluentd-monitor-agent
@type monitor_agent
@Label @splunk
tag monitor_agent

output.conf: |-
#Events are emitted to the CONCAT label from the container, file and journald sources for multiline processing.
<label @concat>
# = filters for container logs =
<filter tail.containers.var.log.containers.dns-controllerdns-controller.log>
@type concat
key log
timeout_label @splunk
stream_identity_key stream
multiline_start_regexp /^\w[0-1]\d[0-3]\d/
flush_interval 5s
separator ""
use_first_timestamp true

<filter tail.containers.var.log.containers.kube-dnssidecar.log>
@type concat
key log
timeout_label @splunk
stream_identity_key stream
multiline_start_regexp /^\w[0-1]\d[0-3]\d/
flush_interval 5s
separator ""
use_first_timestamp true

<filter tail.containers.var.log.containers.kube-dnsdnsmasq.log>
@type concat
key log
timeout_label @splunk
stream_identity_key stream
multiline_start_regexp /^\w[0-1]\d[0-3]\d/
flush_interval 5s
separator ""
use_first_timestamp true

<filter tail.containers.var.log.containers.kube-apiserverkube-apiserver.log>
@type concat
key log
timeout_label @splunk
stream_identity_key stream
multiline_start_regexp /^\w[0-1]\d[0-3]\d/
flush_interval 5s
separator ""
use_first_timestamp true

<filter tail.containers.var.log.containers.kube-controller-managerkube-controller-manager.log>
@type concat
key log
timeout_label @splunk
stream_identity_key stream
multiline_start_regexp /^\w[0-1]\d[0-3]\d/
flush_interval 5s
separator ""
use_first_timestamp true

<filter tail.containers.var.log.containers.kube-dns-autoscalerautoscaler.log>
@type concat
key log
timeout_label @splunk
stream_identity_key stream
multiline_start_regexp /^\w[0-1]\d[0-3]\d/
flush_interval 5s
separator ""
use_first_timestamp true

<filter tail.containers.var.log.containers.kube-proxykube-proxy.log>
@type concat
key log
timeout_label @splunk
stream_identity_key stream
multiline_start_regexp /^\w[0-1]\d[0-3]\d/
flush_interval 5s
separator ""
use_first_timestamp true

<filter tail.containers.var.log.containers.kube-schedulerkube-scheduler.log>
@type concat
key log
timeout_label @splunk
stream_identity_key stream
multiline_start_regexp /^\w[0-1]\d[0-3]\d/
flush_interval 5s
separator ""
use_first_timestamp true

<filter tail.containers.var.log.containers.kube-dnskubedns.log>
@type concat
key log
timeout_label @splunk
stream_identity_key stream
multiline_start_regexp /^\w[0-1]\d[0-3]\d/
flush_interval 5s
separator ""
use_first_timestamp true

@type concat
key log
timeout_label @splunk
multiline_start_regexp /^\w[0-1]\d[0-3]\d/
flush_interval 5s

# = custom concat filters specified by users =
# Concatenate indented multi-line logs (e.g. stack traces)
<filter tail.containers.>
@type concat
key log
timeout_label @splunk
stream_identity_key stream
multiline_start_regexp /^[^\t].*/
separator ""
use_first_timestamp true
flush_interval 5s

# = END custom concat filters specified by users =
# Events are relabeled then emitted to the SPLUNK label
<match >
@type relabel
@Label @splunk

<label @splunk>
# Enrich log with k8s metadata
<filter tail.containers.>
@type kubernetes_metadata
annotation_match [ "^splunk.com" ]
de_dot false

<filter tail.containers.>
@type record_transformer
enable_ruby

# set the sourcetype from splunk.com/sourcetype pod annotation or set it to kube:container:CONTAINER_NAME
sourcetype ${record.dig("kubernetes", "annotations", "splunk.com/sourcetype") ? "kube:"+record.dig("kubernetes", "annotations", "splunk.com/sourcetype") : "kube:container:"+record.dig("kubernetes","container_name")}
container_name ${record.dig("kubernetes","container_name")}
namespace ${record.dig("kubernetes","namespace_name")}
pod ${record.dig("kubernetes","pod_name")}
container_id ${record.dig("docker","container_id")}
pod_uid ${record.dig("kubernetes","pod_id")}
container_image ${record.dig("kubernetes","container_image")}
# set the cluster_name field to the configured value, or default to "cluster_name"
cluster_name "${CLUSTER}"
# set the index field to the value found in the pod splunk.com/index annotations. if not set, use namespace annotation, or default to the default_index
index ${record.dig("kubernetes", "annotations", "splunk.com/index") ? record.dig("kubernetes", "annotations", "splunk.com/index") : record.dig("kubernetes", "namespace_annotations", "splunk.com/index") ? (record["kubernetes"]["namespace_annotations"]["splunk.com/index"]) : ("cloudpak")}
label_app ${record.dig("kubernetes","labels","app")}
label_k8s-app ${record.dig("kubernetes","labels","k8s-app")}
label_release ${record.dig("kubernetes","labels","release")}
blacklist ${record.dig("kubernetes", "annotations", "splunk.com/exclude") ? record.dig("kubernetes", "annotations", "splunk.com/exclude") : record.dig("kubernetes", "namespace_annotations", "splunk.com/exclude") ? (record["kubernetes"]["namespace_annotations"]["splunk.com/exclude"]) : ("false")}

<filter tail.containers.>
# Exclude all logs that are blacklisted
@type grep

key blacklist
pattern /^true$/

# extract pod_uid and container_name for CRIO runtime
<filter tail.containers.var.log.pods.>
@type jq_transformer
jq '.record | . + (.source | capture("/var/log/pods/(?<pod_uid>[^/]+)/(?<container_name>[^/]+)/(?<container_retry>[0-9]+).log")) | .sourcetype = ("kube:container:" + .container_name)'

# create source and sourcetype
<filter journald.>
@type jq_transformer
jq '.record.source = "/run/log/journal/" + .record.source | .record.sourcetype = (.tag | ltrimstr("journald.")) | .record.cluster_name = "${CLUSTER}" | .record'

# = filters for non-container log files =
# extract sourcetype
<filter tail.file.>
@type jq_transformer
jq '.record.sourcetype = (.tag | ltrimstr("tail.file.")) | .record.cluster_name = "${CLUSTER}" | .record'

# = filters for monitor agent =

@type jq_transformer
jq ".record.source = "namespace:#{ENV['MY_NAMESPACE']}/pod:#{ENV['MY_POD_NAME']}" | .record.sourcetype = "fluentd:monitor-agent" | .record.cluster_name = "${CLUSTER}" | .record"
  # = custom filters specified by users =
  # remove events that only contain "\n"
  <filter tail.containers.**>
    @type grep
    <exclude>
      key log
      pattern /^\n$/
    </exclude>
  </filter>
  # = END custom filters specified by users =

  # = output =
  <match **>
    @type splunk_hec
    protocol https
    hec_host "${HEC_HOST}"
    hec_port 443
    hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
    index_key index
    insecure_ssl true
    host "#{ENV['K8S_NODE_NAME']}"
    source_key source
    sourcetype_key sourcetype
    <fields>
      # currently CRI does not produce log paths with all the necessary
      # metadata to parse out pod, namespace, container_name, container_id.
      # this may be resolved in the future by this issue: https://github.com/kubernetes/kubernetes/issues/58638#issuecomment-385126031
      container_retry
      pod_uid
      pod
      container_name
      namespace
      container_id
      cluster_name
      label_app
      label_k8s-app
      label_release
    </fields>
    <buffer>
      @type memory
      chunk_limit_records 100000
      chunk_limit_size 200m
      flush_interval 5s
      flush_thread_count 1
      overflow_action block
      retry_max_times 5
      retry_type periodic
      total_limit_size 600m
    </buffer>
    <format monitor_agent>
      @type json
    </format>
    <format>
      # we just want to keep the raw logs, not the structure created by docker or journald
      @type single_value
      message_key log
      add_newline false
    </format>
  </match>
</label>
kind: PodSecurityPolicy
apiVersion: policy/v1beta1
metadata:
name: "${LOGGING_NAME}"
labels:
app: "${LOGGING_NAME}"
version: "${LOGGING_RELEASE}"
annotations:
seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
spec:
privileged: true
allowPrivilegeEscalation: true
allowedCapabilities:
- ""
hostNetwork: false
hostIPC: false
hostPID: false
volumes:
- ""
runAsUser:
rule: RunAsAny
seLinux:
rule: RunAsAny
supplementalGroups:
rule: RunAsAny
fsGroup:
rule: RunAsAny

kind: Secret
apiVersion: v1
metadata:
name: "${LOGGING_NAME}"
labels:
app: "${LOGGING_NAME}"
version: "${LOGGING_RELEASE}"
type: Opaque
data:
splunk_hec_token: "${HEC_TOKEN}"

kind: ServiceAccount
apiVersion: v1
imagePullSecrets:

- name:
metadata:
name: "${LOGGING_NAME}"
labels:
app: "${LOGGING_NAME}"
version: "${LOGGING_RELEASE}"

kind: DaemonSet
apiVersion: apps/v1
metadata:
name: "${LOGGING_NAME}"
labels:
app: "${LOGGING_NAME}"
engine: fluentd
version: "${LOGGING_RELEASE}"
spec:
updateStrategy:
type: RollingUpdate
selector:
matchLabels:
app: "${LOGGING_NAME}"
template:
metadata:
labels:
app: "${LOGGING_NAME}"
version: "${LOGGING_RELEASE}"
#annotations:
# prometheus.io/scrape: 'true'
# prometheus.io/port: ''
spec:
serviceAccountName: "${LOGGING_NAME}"
tolerations:
- effect: NoSchedule
key: node-role.kubernetes.io/master
containers:
- name: splunk-fluentd-k8s-logs
image: REDATCED
imagePullPolicy: IfNotPresent
securityContext:
privileged: true
runAsUser: 0
env:
- name: K8S_NODE_NAME
valueFrom:
fieldRef:
fieldPath: spec.nodeName
- name: MY_NAMESPACE
valueFrom:
fieldRef:
fieldPath: metadata.namespace
- name: MY_POD_NAME
valueFrom:
fieldRef:
fieldPath: metadata.name
- name: SPLUNK_HEC_TOKEN
valueFrom:
secretKeyRef:
name: "${LOGGING_NAME}"
key: splunk_hec_token
resources:
limits:
cpu: 200m
memory: 750Mi
requests:
cpu: 200m
memory: 400Mi
volumeMounts:
- name: varlog
mountPath: "/var/log"
- name: varlogdest
mountPath: "/var/lib/docker/containers"
readOnly: true
- name: journallogpath
mountPath: "/run/log/journal"
readOnly: true
- name: conf-configmap
mountPath: "/fluentd/etc"
- name: secrets
mountPath: "/fluentd/etc/splunk"
readOnly: true
terminationGracePeriodSeconds: 30
volumes:
- name: varlog
hostPath:
path: "/var/log"
- name: varlogdest
hostPath:
path: "/var/lib/docker/containers"
- name: journallogpath
hostPath:
path: "/run/log/journal"
- name: conf-configmap
configMap:
name: "${LOGGING_NAME}"
- name: secrets
secret:
secretName: "${LOGGING_NAME}"

#METRICS

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: "${METRICS_NAME}-kubelet-summary-api-read"
labels:
app: "${METRICS_NAME}"
version: "${METRICS_RELEASE}"
rules:

apiGroups:
extensions
resources:
podsecuritypolicies
verbs:
use
resourceNames:
"${METRICS_NAME}"
apiGroups:
""
resources:
nodes
nodes/stats
nodes/metrics
verbs:
get
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: "${METRICS_NAME}"
labels:
app: "${METRICS_NAME}"
version: "${METRICS_RELEASE}"
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: ClusterRole
name: "${METRICS_NAME}-kubelet-summary-api-read"
subjects:

kind: ServiceAccount
name: "${METRICS_NAME}"
namespace: "${APP_NAME}"
kind: ConfigMap
apiVersion: v1
metadata:
name: "${METRICS_NAME}"
labels:
app: "${METRICS_NAME}"
version: "${METRICS_RELEASE}"
data:
fluent.conf: |
# system wide configurations

log_level info

@type kubernetes_metrics
tag kube.*
node_name "#{ENV['NODE_NAME']}"
use_rest_client_ssl true
insecure_ssl true
cluster_name "${CLUSTER}"
interval 15s

<filter kube.>
@type record_modifier

metric_name ${tag}
cluster_name "${CLUSTER}"

<filter kube.node.>
@type record_modifier

source ${record['node']}

<filter kube.pod.>
@type record_modifier

source ${record['node']}/${record['pod-name']}

<filter kube.sys-container.>
@type record_modifier

source ${record['node']}/${record['pod-name']}/${record['name']}

<filter kube.container.**>
@type record_modifier

source ${record['node']}/${record['pod-name']}/${record['container-name']}

# = custom filters specified by users =

<match kube.**>
  @type splunk_hec
  data_type metric
  metric_name_key metric_name
  metric_value_key value
  protocol https
  hec_host "${HEC_METRIC_HOST}"
  hec_port 443
  hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
  host "#{ENV['NODE_NAME']}"
  source ${tag}
  insecure_ssl true
  <buffer>
    @type memory
    chunk_limit_records 10000
    chunk_limit_size 100m
    flush_interval 5s
    flush_thread_count 1
    overflow_action block
    retry_max_times 5
    retry_type periodic
    total_limit_size 400m
  </buffer>
</match>
kind: PodSecurityPolicy
apiVersion: policy/v1beta1
metadata:
name: "${METRICS_NAME}"
labels:
app: "${METRICS_NAME}"
version: "${METRICS_RELEASE}"
annotations:
seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
spec:
privileged: false
allowPrivilegeEscalation: false
allowedCapabilities:
- ""
hostNetwork: false
hostIPC: false
hostPID: false
volumes:
- ""
runAsUser:
rule: RunAsAny
seLinux:
rule: RunAsAny
supplementalGroups:
rule: RunAsAny
fsGroup:
rule: RunAsAny

kind: Secret
apiVersion: v1
metadata:
name: "${METRICS_NAME}"
labels:
app: "${METRICS_NAME}"
version: "${METRICS_RELEASE}"
type: Opaque
data:
splunk_hec_token: "${HEC_METRIC_TOKEN}"

kind: ServiceAccount
apiVersion: v1
imagePullSecrets:

- name:
metadata:
name: "${METRICS_NAME}"
labels:
app: "${METRICS_NAME}"
version: "${METRICS_RELEASE}"

kind: DaemonSet
apiVersion: apps/v1
metadata:
name: "${METRICS_NAME}"
labels:
app: "${METRICS_NAME}"
engine: fluentd
version: "${METRICS_RELEASE}"
spec:
updateStrategy:
type: RollingUpdate
selector:
matchLabels:
app: "${METRICS_NAME}"
template:
metadata:
name: "${METRICS_NAME}"
labels:
app: "${METRICS_NAME}"
version: "${METRICS_RELEASE}"
annotations:
scheduler.alpha.kubernetes.io/critical-pod: ""
spec:
serviceAccountName: "${METRICS_NAME}"
tolerations:
- effect: NoSchedule
key: node-role.kubernetes.io/master
containers:
- name: splunk-fluentd-k8s-metrics
image: REDATCED
imagePullPolicy: IfNotPresent
env:
- name: KUBERNETES_NODE_IP
valueFrom:
fieldRef:
fieldPath: status.hostIP
- name: NODE_NAME
valueFrom:
fieldRef:
fieldPath: spec.nodeName
- name: SPLUNK_HEC_TOKEN
valueFrom:
secretKeyRef:
name: "${METRICS_NAME}"
key: splunk_hec_token
resources:
limits:
cpu: 200m
memory: 650Mi
requests:
cpu: 200m
memory: 500Mi
volumeMounts:
- name: conf-configmap
mountPath: "/fluentd/etc"
- name: secrets
mountPath: "/fluentd/etc/splunk"
readOnly: true
volumes:
- name: conf-configmap
configMap:
name: "${METRICS_NAME}"
- name: secrets
secret:
secretName: "${METRICS_NAME}"
#METRICS-AGGREGATOR

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: "${METRICS_NAME}-kube-api-aggregator"
labels:
app: "${METRICS_NAME}"
version: "${METRICS_RELEASE}"
rules:

apiGroups:
extensions
resources:
podsecuritypolicies
verbs:
use
resourceNames:
"${METRICS_NAME}-aggregator"
apiGroups:
""
resources:
nodes
nodes/stats
nodes/proxy
pods
verbs:
get
list
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: "${METRICS_NAME}-aggregator"
labels:
app: "${METRICS_NAME}"
version: "${METRICS_RELEASE}"
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: ClusterRole
name: "${METRICS_NAME}-kube-api-aggregator"
subjects:

kind: ServiceAccount
name: "${METRICS_NAME}"
namespace: "${APP_NAME}"
kind: ConfigMap
apiVersion: v1
metadata:
name: "${METRICS_NAME}-aggregator"
labels:
app: "${METRICS_NAME}"
version: "${METRICS_RELEASE}"
data:
fluent.conf: |
# system wide configurations

log_level info

@type kubernetes_metrics_aggregator
tag kube.*
interval 15s

<filter kube.>
@type record_modifier

metric_name ${tag}
cluster_name "${CLUSTER}"

<filter kube.cluster.>
@type record_modifier

source ${record['name']}

<filter kube.namespace.>
@type record_modifier

source ${record['name']}

<filter kube.node.>
@type record_modifier

source ${record['node']}

<filter kube.pod.>
@type record_modifier

source ${record['node']}/${record['pod-name']}

<filter kube.sys-container.>
@type record_modifier

source ${record['node']}/${record['pod-name']}/${record['name']}

<filter kube.container.>
@type record_modifier

source ${record['node']}/${record['pod-name']}/${record['container-name']}

<match kube.>
@type splunk_hec
data_type metric
metric_name_key metric_name
metric_value_key value
protocol https
hec_host "${HEC_METRIC_HOST}"
hec_port 443
hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
host "#{ENV['NODE_NAME']}"
source source
insecure_ssl true

@type memory
chunk_limit_records 10000
chunk_limit_size 100m
flush_interval 5s
flush_thread_count 1
overflow_action block
retry_max_times 5
retry_type periodic
total_limit_size 400m

kind: PodSecurityPolicy
apiVersion: policy/v1beta1
metadata:
name: "${METRICS_NAME}-aggregator"
labels:
app: "${METRICS_NAME}"
version: "${METRICS_RELEASE}"
annotations:
seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
spec:
privileged: false
allowPrivilegeEscalation: false
allowedCapabilities:
- ""
hostNetwork: false
hostIPC: false
hostPID: false
volumes:
- ""
runAsUser:
rule: RunAsAny
seLinux:
rule: RunAsAny
supplementalGroups:
rule: RunAsAny
fsGroup:
rule: RunAsAny

kind: Deployment
apiVersion: apps/v1
metadata:
name: "${METRICS_NAME}-aggregator"
labels:
app: "${METRICS_NAME}-aggregator"
version: "${METRICS_RELEASE}"
spec:
strategy:
type: RollingUpdate
replicas: "${{METRICS_REPLICAS}}"
selector:
matchLabels:
app: "${METRICS_NAME}-aggregator"
template:
metadata:
labels:
app: "${METRICS_NAME}-aggregator"
version: "${METRICS_RELEASE}"
annotations:
scheduler.alpha.kubernetes.io/critical-pod: ""
spec:
serviceAccountName: "${METRICS_NAME}"
#nodeSelector:
# node-role.kubernetes.io/infra: "true"
containers:
- name: splunk-fluentd-k8s-metrics-agg
image: REDATCED
imagePullPolicy: Always
env:
- name: SPLUNK_HEC_TOKEN
valueFrom:
secretKeyRef:
name: "${METRICS_NAME}"
key: splunk_hec_token
- name: NODE_NAME
valueFrom:
fieldRef:
fieldPath: spec.nodeName
resources:
limits:
cpu: 200m
memory: 600Mi
requests:
cpu: 200m
memory: 300Mi
volumeMounts:
- name: conf-configmap
mountPath: "/fluentd/etc"
- name: secrets
mountPath: "/fluentd/etc/splunk"
readOnly: true
volumes:
- name: conf-configmap
configMap:
name: "${METRICS_NAME}-aggregator"
- name: secrets
secret:
secretName: "${METRICS_NAME}"

#OBJECTS

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: "${OBJECTS_NAME}"
labels:
app: "${OBJECTS_NAME}"
version: "${OBJECTS_RELEASE}"
rules:

apiGroups:
extensions
resources:
podsecuritypolicies
verbs:
use
resourceNames:
"${OBJECTS_NAME}"
apiGroups:
""
resources:
pods
namespaces
nodes
verbs:
get
list
apiGroups:
""
resources:
events
verbs:
watch
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: "${OBJECTS_NAME}"
labels:
app: "${OBJECTS_NAME}"
version: "${OBJECTS_RELEASE}"
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: ClusterRole
name: "${OBJECTS_NAME}"
subjects:

kind: ServiceAccount
name: "${OBJECTS_NAME}"
namespace: "${APP_NAME}"
kind: ConfigMap
apiVersion: v1
metadata:
name: "${OBJECTS_NAME}"
labels:
app: "${OBJECTS_NAME}"
version: "${OBJECTS_RELEASE}"
data:
fluent.conf: |

log_level info

@type kubernetes_objects
tag kube.objects.*
api_version "v1"
insecure_ssl true

resource_name pods

resource_name namespaces

resource_name nodes

resource_name events

<filter kube.>
@type jq_transformer
# in ruby '\' will escape and become just '', since we need two '' in the gsub jq filter, it becomes '\\'.
jq '.record.source = "namespace:(env.MY_NAMESPACE)/pod:(env.MY_POD_NAME)" | .record.sourcetype = (.tag | gsub("\\."; ":")) | .record'

<filter kube.>
@type jq_transformer
jq '.record.cluster_name = "${CLUSTER}" | .record'
# = custom filters specified by users =

<match kube.**>
  @type splunk_hec
  protocol https
  hec_host "${HEC_HOST}"
  hec_port 443
  hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
  host "#{ENV['NODE_NAME']}"
  source_key source
  sourcetype_key sourcetype
  insecure_ssl true
  <fields>
    cluster_name
  </fields>
  <buffer>
    @type memory
    chunk_limit_records 10000
    chunk_limit_size 200m
    flush_interval 5s
    flush_thread_count 1
    overflow_action block
    retry_max_times 5
    retry_type periodic
    total_limit_size 600m
  </buffer>
</match>
kind: PodSecurityPolicy
apiVersion: policy/v1beta1
metadata:
name: "${OBJECTS_NAME}"
labels:
app: "${OBJECTS_NAME}"
version: "${OBJECTS_RELEASE}"
annotations:
seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
spec:
privileged: false
allowPrivilegeEscalation: false
allowedCapabilities:
- ""
hostNetwork: false
hostIPC: false
hostPID: false
volumes:
- ""
runAsUser:
rule: RunAsAny
seLinux:
rule: RunAsAny
supplementalGroups:
rule: RunAsAny
fsGroup:
rule: RunAsAny

kind: Secret
apiVersion: v1
metadata:
name: "${OBJECTS_NAME}"
labels:
app: "${OBJECTS_NAME}"
version: "${OBJECTS_RELEASE}"
type: Opaque
data:
splunk_hec_token: "${HEC_TOKEN}"

kind: ServiceAccount
apiVersion: v1
imagePullSecrets:

#name: #
metadata:
name: "${OBJECTS_NAME}"
labels:
app: "${OBJECTS_NAME}"
version: "${OBJECTS_RELEASE}"
kind: Deployment
apiVersion: apps/v1
metadata:
name: "${OBJECTS_NAME}"
labels:
app: "${OBJECTS_NAME}"
version: "${OBJECTS_RELEASE}"
spec:
strategy:
type: RollingUpdate
selector:
matchLabels:
app: "${OBJECTS_NAME}"
replicas: "${{OBJECTS_REPLICAS}}"
template:
metadata:
labels:
app: "${OBJECTS_NAME}"
version: "${OBJECTS_RELEASE}"
annotations: {}
spec:
serviceAccountName: "${OBJECTS_NAME}"
terminationGracePeriodSeconds: 30
#nodeSelector:
# node-role.kubernetes.io/infra: "true"
containers:
- name: splunk-fluentd-k8s-objects
image: REDATCED
imagePullPolicy: IfNotPresent
env:
- name: MY_NAMESPACE
valueFrom:
fieldRef:
fieldPath: metadata.namespace
- name: MY_POD_NAME
valueFrom:
fieldRef:
fieldPath: metadata.name
- name: NODE_NAME
valueFrom:
fieldRef:
fieldPath: spec.nodeName
- name: SPLUNK_HEC_TOKEN
valueFrom:
secretKeyRef:
name: "${OBJECTS_NAME}"
key: splunk_hec_token
resources:
limits:
cpu: 200m
memory: 600Mi
requests:
cpu: 200m
memory: 400Mi
volumeMounts:
- name: conf-configmap
mountPath: "/fluentd/etc"
- name: secrets
mountPath: "/fluentd/etc/splunk"
readOnly: true
volumes:
- name: conf-configmap
configMap:
name: "${OBJECTS_NAME}"
- name: secrets
secret:
secretName: "${OBJECTS_NAME}"

parameters:

name: CLUSTER
description: Cluster name
value: ""
name: ENV
description: environment
value: ""
name: APP_NAME
description: Name of application
value: "splunk-connect-os"
name: PROJECT_NAME
description: Name of project
value: "splunk-connect-os"
name: LOGGING_NAME
description: Name of logging application
value: "splunk-kubernetes-logging"
name: LOGGING_RELEASE
description: Release version of Splunk kubernetes logging
value: "1.4.2"
name: METRICS_NAME
description: Name of metrics application
value: "splunk-kubernetes-metrics"
name: METRICS_REPLICAS
description: Number of pods to run for Metrics
value: "1"
name: METRICS_RELEASE
description: Release version of Splunk kubernetes metrics
value: "1.4.2"
name: OBJECTS_NAME
description: Name of objects application
value: "splunk-kubernetes-objects"
name: OBJECTS_REPLICAS
description: Number of pods to run for Objects
value: "1"
name: OBJECTS_RELEASE
description: Release version of Splunk kubernetes objects
value: "1.4.2"
name: HEC_HOST
description: Hostname of Splunk HTTP Event Collector
value: "REDATCED"
name: HEC_METRIC_HOST
description: Hostname of Splunk HTTP Event Collector for the metrics index
value: "REDATCED"
name: HEC_TOKEN
description: Token used for authenticating to Splunk HTTP Event Collector for cloudpak index
value: "REDATCED"
name: HEC_METRIC_TOKEN
description: Token used for authenticating to Splunk HTTP Event Collector for cloudpak_metric index
value: "NREDATCED"

**Comment by ramrajkonuganti** [comment]
Sorry for the messed up file format. i tried to attach the file to this thread but it is not accepting the format of the file. Let me know if the content i pasted looks confusing.

I just want to know where do I need to add 'environmentVar:' tag to pass on proxy details in my file. We are not using helm charts for deployment. We are deploying via yaml files and we created a single yaml file to include all the info(daemonset and deployment).



This is my Splunk deployment file using yaml. Could you please let me know where can I add following details to pass on Proxy settings?

The name of the pull secret to attach to the respective serviceaccount used to pull the image
pullsecretName:

Environment variable for daemonset
Remove SSL_CERT_FILE environment variable when using OS CA file
environmentVar:

**Comment by rockb1017** [comment]
You can set environment variables for proxy. try setting HTTP_PROXY
