### ISSUE TITLE
Add Volumes to Splunk Pod?

### ISSUE THREAD

**Issue by vennemp** [splunk/splunk-connect-for-kubernetes#629]
How do you add additional volumes to the splunk pod?

**Comment by rockb1017** [comment]
splunk pod or this connector pod?

**Comment by rockb1017** [comment]
if you are asking for connector pod, there is no supported way in the helm chart to add additional volume mounts. you would have to modify the helm templates to do so.

**Comment by vennemp** [comment]
My apologies I thought I replied. 

I see the host path /var/log is already mounted. So if I wanted to forward any host logs that get stored there. I would to calling that out with the logs/from/file/path config in values.yaml

Correct?

**Comment by rockb1017** [comment]
support for mounting extra volume has been added. please upgrade to latest version and see here. 
https://github.com/splunk/splunk-connect-for-kubernetes/blob/8ad1071f31937f156eb8c071c7b6e8370f8997a4/helm-chart/splunk-connect-for-kubernetes/values.yaml#L425
