### ISSUE TITLE
Add index.yaml to allow repo import

### ISSUE THREAD

**Issue by mehstg** [splunk/splunk-connect-for-kubernetes#63]
Hi. I was wondering if you could add the index.yaml mentioned in the spec (https://docs.helm.sh/developing_charts/) to make this a repository. Currently this chart is an edge case for us and has to be installed differently.

**Comment by gmichels** [comment]
Same here, would love to see this is as a repo so we could incorporate the charts on some of our own umbrella charts.

**Comment by mateodelnorte** [comment]
Does anyone have a workaround for this? This seems like an obvious oversight.

**Comment by chaitanyaphalak** [comment]
@mateodelnorte we will be happy to review a pull request for the same. Thanks.

**Comment by rockb1017** [comment]
Starting from chart 1.4.3, you can add repo like this.
`helm repo add splunk https://splunk.github.io/splunk-connect-for-kubernetes/`
Thank you!
