### ISSUE TITLE
Enable Helm chart default tolerations override

### ISSUE THREAD

**Issue by amehub** [splunk/splunk-connect-for-kubernetes#640]
<

**What would you like to be added**:

The ability to remove the default tolerations in the Helm chart which schedule pods onto master nodes.

https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/values.yaml#L166

```
# This default tolerations allow the daemonset to be deployed on master nodes,
# so that we can also collect metrics from those nodes.
tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule

```

Replacing the above with

`tolerations: {}
`

still results in the default tolerations set in the daemonset.

https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/daemonset.yaml#L43

It is not quite clear how this default is getting rendered in the daemonset template from an empty value.

**Why is this needed**:

To allow enabling/disabling of the SCK pods on master nodes

**Comment by rockb1017** [comment]
it should be an empty array. 
`tolerations: []`
but when i test it, both of them works.

**Comment by amehub** [comment]
Interesting.  I tried the empty {} and I tried empty [].   Sounds like both {} and [] work but not for me.  I will need to look into this some more.

**Comment by harshit-splunk** [comment]
@amehub should I close the ticket?

**Comment by harshit-splunk** [comment]
Closing the issue. Feel free to reopen or create a new one if needed.
