### ISSUE TITLE
Logging Pods (DeamonSet) have Permission Issue

### ISSUE THREAD

**Issue by spaspunoori** [splunk/splunk-connect-for-kubernetes#647]
I setup the Splunk Connect on Openshift with Below Steps:

Followed the Steps provided here  https://github.com/splunk/splunk-connect-for-kubernetes

Installed using Helm 3 with below commands. 

$ Kubectl create ns splunk-connect
 
$ helm install  splunk-connect   -f esf_aro_splunk_values.yaml   splunk/splunk-connect-for-kubernetes -n splunk-connect
 
 $ oc adm policy add-scc-to-user privileged "system:serviceaccount:splunk-connect:splunk-connect-splunk-kubernetes-logging"

Object and metrics pods working fine and able to see the events in Splunk. But Container logs are uploaded to Splunk.

Further Investigation found below error in Logging Pods:

2021-08-05 17:45:37 +0000 [info]: #0 starting fluentd worker pid=279 ppid=1 worker=0
2021-08-05 17:45:37 +0000 [info]: #0 listening port port=24224 bind="0.0.0.0"
/usr/share/gems/gems/fluentd-1.11.5/lib/fluent/plugin_helper/http_server/compat/server.rb:84: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/share/gems/gems/fluentd-1.11.5/lib/fluent/plugin_helper/http_server/compat/webrick_handler.rb:26: warning: The called method `build' is defined here
**2021-08-05 17:45:37 +0000 [error]: #0 unexpected error error_class=Errno::EACCES error="Permission denied @ rb_sysopen - /var/log/splunk-fluentd-kube-audit.pos"**
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/lib/fluent/plugin/in_tail.rb:215:in `initialize'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/lib/fluent/plugin/in_tail.rb:215:in `open'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/lib/fluent/plugin/in_tail.rb:215:in `start'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:200:in `block in start'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:189:in `block (2 levels) in lifecycle'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:188:in `each'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:188:in `block in lifecycle'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:175:in `each'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:175:in `lifecycle'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/lib/fluent/root_agent.rb:199:in `start'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/lib/fluent/engine.rb:248:in `start'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/lib/fluent/engine.rb:147:in `run'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/lib/fluent/supervisor.rb:607:in `block in run_worker'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/lib/fluent/supervisor.rb:845:in `main_process'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/lib/fluent/supervisor.rb:598:in `run_worker'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/lib/fluent/command/fluentd.rb:361:in `<top (required)>'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/bin/fluentd:8:in `require'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.11.5/bin/fluentd:8:in `<top (required)>'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/bin/fluentd:23:in `load'
  2021-08-05 17:45:37 +0000 [error]: #0 /usr/bin/fluentd:23:in `<main>'
**2021-08-05 17:45:37 +0000 [error]: #0 unexpected error error_class=Errno::EACCES error="Permission denied @ rb_sysopen - /var/log/splunk-fluentd-kube-audit.pos"**
  2021-08-05 17:45:37 +0000 [error]: #0 suppressed same stacktrace
2021-08-05 17:45:37 +0000 [info]: Worker 0 finished unexpectedly with status 1
2021-08-05 17:45:38 +0000 [info]: adding filter in @CONCAT pattern="tail.containers.var.log.containers.dns-controller*dns-controller*.log" type="concat"
2021-08-05 17:45:38 +0000 [info]: adding filter in @CONCAT pattern="tail.containers.var.log.containers.kube-dns*sidecar*.log" type="concat"
2021-08-05 17:45:38 +0000 [info]: adding filter in @CONCAT pattern="tail.containers.var.log.containers.kube-dns*dnsmasq*.log" type="concat"
2021-08-05 17:45:38 +0000 [info]: adding filter in @CONCAT pattern="tail.containers.var.log.containers.kube-apiserver*kube-apiserver*.log" type="concat"
2021-08-05 17:45:38 +0000 [info]: adding filter in @CONCAT pattern="tail.containers.var.log.containers.kube-controller-manager*kube-controller-manager*.log" type="concat"
2021-08-05 17:45:38 +0000 [info]: adding filter in @CONCAT pattern="tail.containers.var.log.containers.kube-dns-autoscaler*autoscaler*.log" type="concat"
2021-08-05 17:45:38 +0000 [info]: adding filter in @CONCAT pattern="tail.containers.var.log.containers.kube-proxy*kube-proxy*.log" type="concat"
2021-08-05 17:45:38 +0000 [info]: adding filter in @CONCAT pattern="tail.containers.var.log.containers.kube-scheduler*kube-scheduler*.log" type="concat"
2021-08-05 17:45:38 +0000 [info]: adding filter in @CONCAT pattern="tail.containers.var.log.containers.kube-dns*kubedns*.log" type="concat"
2021-08-05 17:45:38 +0000 [info]: adding filter in @CONCAT pattern="journald.kube:kubelet" type="concat"
2021-08-05 17:45:38 +0000 [info]: adding match in @CONCAT pattern="**" type="relabel"

Environment: Openshift  4.7 Running in Azure

**Comment by spaspunoori** [comment]
Attached full log file

**Comment by spaspunoori** [comment]
Adding Values file.
[esf_aro_splunk_values_masked-yaml.txt](https://github.com/splunk/splunk-connect-for-kubernetes/files/6941629/esf_aro_splunk_values_masked-yaml.txt)

**Comment by vinzent** [comment]
Are you on ARO or custom OpenShift on Azure?

Did you try the example: https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/examples/openshift4-logging-only.yaml

**Comment by spaspunoori** [comment]
> Are you on ARO or custom OpenShift on Azure?
> 
> Did you try the example: https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/examples/openshift4-logging-only.yaml

I am on ARO   ( OpenShift Version: 4.5.39 )

**Comment by gnarc** [comment]
The logging pod won't initialize because of lack of access to logfiles on the OpenShift Nodes:
```
:EACCES error="Permission denied @ rb_sysopen - /var/log/splunk-fluentd-kube-audit.pos"
```

Makes sure the Logging container runs with extended permissions to access them using SCC.
For OpenShift you should go through the values.yaml umbrella file and do some more changes in regards to SCC and logfile location, logfile format, additional logfiles (e.g. oauth-auditlog). Search the comments for everything related to OpenShift:

- use this https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/examples/openshift4-logging-only.yaml to get an idea of what needs to be changed

- go through the logging-part of the umbrella values.yaml and check for
  -  containers.pathDest (var(log/pods)
  -  container.logFormatType: cri
  -  rbac/ServiceAccount/podSecurityPolicy should possibly be true (not sure you need a separate SCC-Policy, there is a template which will do it for you but might be too open. YMMV)
  -  I don't think we need AppArmor enabled on CoreOS based OpenShift Nodes
  -  kube-audit: adjust path to /var/log/kube-apiserver/audit.log
  -  If required: add oauth-audit log or additional logs

**Comment by spaspunoori** [comment]
> The logging pod won't initialize because of lack of access to logfiles on the OpenShift Nodes:
> 
> ```
> :EACCES error="Permission denied @ rb_sysopen - /var/log/splunk-fluentd-kube-audit.pos"
> ```
> 
> Makes sure the Logging container runs with extended permissions to access them using SCC.
> For OpenShift you should go through the values.yaml umbrella file/logging-section and do some more changes in regards to SCC and logfile location, logfile format, additional logfiles (e.g. oauth-auditlog). Search the comments for everything related to OpenShift:
> 
> * use this https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/examples/openshift4-logging-only.yaml to get an idea of what needs to be changed
> * go through the logging-part of the umbrella values.yaml and check for
>   
>   * containers.pathDest (var(log/pods)
>   * container.logFormatType: cri
>   * rbac/ServiceAccount/podSecurityPolicy should possibly be true (not sure you need a separate SCC-Policy, there is a template which will do it for you but might be too open. YMMV)
>   * I don't think we need AppArmor enabled on CoreOS based OpenShift Nodes
>   * kube-audit: adjust path to /var/log/kube-apiserver/audit.log
>   * If required: add oauth-audit log or additional logs

Thank you for the input, seems like it resolved permission issue, but, I still dont see my application logs in Splunk.

I mimicked "openshift4-logging-only.yaml" manifest file and update "splunk-kubernetes-logging:" section of values file. Now with that, i am able to see logs. But only from platform. None of my application container logs are offloading to Splunk.

All the Application Containers are deployed in different namespaces, Do I need to add any tag or annotate anything at namespace level so that all the application containers logs flow into Splunk ?

**Comment by gnarc** [comment]
That shouldn't be the issue when you changed the containers.pathDest in the values.yaml.
To be clear: the default path in the values.yaml will not work in OpenShift as it does not use docker any more and CRI-O/RHCOS puts them under a new path. Most of the steps I listed above were not optional.
Just SSH into one of your OCP Master Nodes and look in /var/log/* where all the relevant stuff resides.
Once the path is changed you can verify with `oc logs <name of one logging pod>` if fluentd starts tailing all the container logs you would expect from that pod. Until then you won't see anything in the backend.

You can also upload your latest values.yaml (w/o confidential information).

**Comment by gnarc** [comment]
There might still be something wrong with the SCC, your values.yaml does not have all the settings I would set.
This is not necessary if you have your own Rolebinding etc, as you mentioned above. But this needs to be bulletproof.

Could you -just for testing- roll it out with these settings activated:

```
rbac:
 create: true
 openshiftPrivilegedSccBinding: true
serviceAccount:
    create: true

  podSecurityPolicy:
    create: true
    apparmor_security: false
    apiGroup: policy
```
It will then create its own bindings. They might be too open for your environment but ok for troubleshooting.

If still not working, maybe you could provide the output of `oc logs <name of one logging pod>` (again, omit private data)
(By "working" I mean: have a stable pod with no errors in the logs and listing all the container logs it found; seeing the logs in the backend is the second step.)
You could also set the logging to "debug", but for initial troubleshooting "info" is ok.
Logoutput normally starts with fluentd versions, the complete fluent conf and after some while all the container logs.

You did not mention the version of SCK you are using, I guess 1.4.7/1.4.8?
I am also not too familiar with ARO but I don't think they changed the internal logging of RHOCS.

**Comment by spaspunoori** [comment]
I tried above rbac and podsecuritypolicy settings, still same results. I dont see log entries from application containers in the Splunk.

Here I am attaching one of Logging POD log and values file too.  Please suggest, if i am missing anything.  You also mentioned, you are not seeing all the settings in the values file, can you suggest what all I could add too ?

here is the label for the SCK version on daemon set: splunk-kubernetes-logging-1.4.9 and 
image in logging daemon set is docker.io/splunk/fluentd-hec:1.2.5

[splunk-connect-splunk-kubernetes-logging-x8zl7-splunk-fluentd-k8s-logs.log](https://github.com/splunk/splunk-connect-for-kubernetes/files/7016897/splunk-connect-splunk-kubernetes-logging-x8zl7-splunk-fluentd-k8s-logs.log)
[esf_aro_splunk_values_v1_yaml.txt](https://github.com/splunk/splunk-connect-for-kubernetes/files/7016924/esf_aro_splunk_values_v1_yaml.txt)

**Comment by gnarc** [comment]
1. I"m still confused on the version(s) your are using:
You mention splunk-kubernetes-logging-1.4.9 which is the latest release and fluentd-hec:1.2.5 which is the older version.
--> for 1.4.9 those should be the plugin versions reported by `oc logs ...` when the pod starts: https://github.com/splunk/splunk-connect-for-kubernetes/blob/release/1.4.9/PLUGIN_VERSIONS.sh
--> These basically come from the image tags in the values.yaml file, for 1.4.9: https://github.com/splunk/splunk-connect-for-kubernetes/blob/release/1.4.9/PLUGIN_VERSIONS.sh
--> your values.yaml used the previous containers 1.1.5 and 1.2.6, so you are either running SCK <1.4.8 or a newer version with old container images? I'm speculating here.
--> if you installed it with helm. what is the version reported by `helm list <name of sck installation>`?

2. please clean up log files too. They contain things, you might not want to show here (hec_host, hec_token...)

3. you did not set `podSecurityPolicy.create: true` 
BUT: the pod seems to be stable now and the errors are gone. 
Also: These `following tail of /var/log/containers/...` seem to show, that fluent is in fact processing the logs (this was from a master server I guess, there is only infrastructure stuff). 
There are no real warnings as I could tell, but I'm not a Splunk/Fluent guy.

You could:
1. If you use 1.4.9: start from scratch (tarball from https://github.com/splunk/splunk-connect-for-kubernetes/releases/tag/1.4.9, remove old installation, configure the new values.yaml, use newer container images etc.) 
2. raise loglevel to debug via values.yaml for logging (or change the ConfigMap and restart some logging pods)
3. Check your backend configuration for connection logs, index-Setup...If the pods do not complain, it means they were able to offload their chunks somewhere...

**Comment by spaspunoori** [comment]
Here is the output for "helm list" (I installed via helm chart and it is taking the latest version)

helm list -n splunk-connect
NAME          	         UPDATED                              	                        CHART                                              	APP VERSION
splunk-connect	2021-08-20 11:24:02.8395207 -0400 EDT	splunk-connect-for-kubernetes-1.4.9	1.4.9   

I also enabled debug for the logging and changed podSecurityPolicy.create: true, here is latest log file from one of POD. Did not notice any abnormalities, still not seeing application container logs in Splunk

[splunk-connect-splunk-kubernetes-logging-qlc6t-splunk-fluentd-k8s-logs.log](https://github.com/splunk/splunk-connect-for-kubernetes/files/7022651/splunk-connect-splunk-kubernetes-logging-qlc6t-splunk-fluentd-k8s-logs.log)

**Comment by gnarc** [comment]
The debug logs seem fine too, with chunks being uploaded.
I would recommend to start from scratch. Your values.yaml seems to be for an older version than 1.4.9, it uses older container images and you deleted all the snippets from the logging section, I guess something got lost on the way.

Just do an helm uninstall, get the new values.yaml from the 1.4.9 release and customize it to your needs. Do not delete stuff, just activate it or fix it (OpenShift stuff).

This is a diff from my values.yaml for SCK 1.4.9 showing the global and logging section only(!) with changes to the original values.yaml, running OCP 4.6.x
**Some caveats:**
1. My splunk guys had a different entry in the global section for indexName than in the sections for logging, metrics, objects. I don't remember why. I'm just the OpenShift guy. In the end it depends on your setup in the backend
2. We've also set indexFields: to something. I believe it is optional. The links in the comments weren't helpful...
3. journallogs are not active because the default setting ` journalLogPath: /run/log/journal` will not work for OpenShift. You really should think twice if you want that kubelet output in splunk as the amount of logging is immense. This might need some more configuration for systemd-units I guess.
4. That audit-log stuff for oauth-audit hasn't been tested much by us. Just be careful who can access it in Splunk.

```
# diff <(grep -v '#' sck_149_official_values_yaml)  <(grep -v '#' sck_my_ocp_values.yaml) 
6c6
<       host:
---
>       host: $HOST
8c8
<       token:
---
>       token: $TOKEN
10,11c10,11
<       indexName:
<       insecureSSL:
---
>       indexName: $INDEXNAME
>       insecureSSL: true
17c17
<     clusterName: "cluster_name"
---
>     clusterName: $CLUSTERNAME
40,41c40,41
<     pathDest: /var/lib/docker/containers
<     logFormatType: json
---
>     pathDest: /var/log/pods
>     logFormatType: cri
57c57
<     openshiftPrivilegedSccBinding: false
---
>     openshiftPrivilegedSccBinding: true
64,65c64,65
<     create: false
<     apparmor_security: true
---
>     create: true
>     apparmor_security: false
74,75c74,75
<       indexName:
<       insecureSSL:
---
>       indexName: $INDEXNAME_LOGGING
>       insecureSSL: true
187c187
<           path: /var/log/kube-apiserver-audit.log
---
>           path: /var/log/kube-apiserver/audit.log
190a191,204
>     oauth-audit:
>       from:
>         file:
>           path: /var/log/oauth-apiserver/audit.log
>       timestampExtraction:
>         format: "%Y-%m-%dT%H:%M:%SZ"
>       sourcetype: kube:oauth-apiserver-audit
>     openshift-audit:
>       from:
>         file:
>           path: /var/log/openshift-apiserver/audit.log
>       timestampExtraction:
>         format: "%Y-%m-%dT%H:%M:%SZ"
>       sourcetype: kube:apiserver-audit-openshift
238c252
<     securityContext: false
---
>     securityContext: true
```

**Comment by itscatherinelam** [comment]
Thank you for posting the YAML - that was exactly what I need! Apologies for the late reply. This work sort of fell to the wayside and got tabled. 

I'm not sure why when I try the example, it didn't seem to ingest it, but I manually replaced the config map with the values you had above and it works. I am sooooo thankful. Have a lovely holiday season!
