### ISSUE TITLE
 unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

### ISSUE THREAD

**Issue by wrahmann** [splunk/splunk-connect-for-kubernetes#648]
Hi,

I just installed the sck1.4.9 with service

  # deploy a ServiceMonitor object for usage of the PrometheusOperator
  serviceMonitor:
    enabled:  **true**

    metricsPort: 24231
    interval: ""
    scrapeTimeout: "15s"

    additionalLabels: { }

However, upgrade or install is giving the following error:

 unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

Is there any pre-requisite with this feature?

Regards,

**Comment by mwang2016** [comment]
Hi @wrahmann, we made some changes in this latest release. Can you try to deploy the connector using this command?

**Comment by mwang2016** [comment]
Hi @wrahmann, we made some changes in this latest release. Can you try to deploy the connector using this command? `helm install ci-sck --set global.splunk.hec.token=$CI_SPLUNK_HEC_TOKEN \
--set global.splunk.hec.host=$CI_SPLUNK_HOST \
--set kubelet.serviceMonitor.https=true \
-f <your_values>.yml helm-artifacts/splunk-connect-for-kubernetes*.tgz`

**Comment by rockb1017** [comment]
Good question,
These are CRDs utilized in this repo. https://github.com/prometheus-operator/prometheus-operator.
You would need prometheus operator to create these CRDs in your cluster first.

**Comment by wrahmann** [comment]
Hi Mei Wang,

I installed CRD and after that it worked. Thanks for your time and support.

Best Regards,

Wajih Ur Rehman
Email: ***@***.***
