### ISSUE TITLE
Splunk Connect pods consuming too much memory

### ISSUE THREAD

**Issue by gvoden** [splunk/splunk-connect-for-kubernetes#65]
We are seeing our pods are consuming a lot of memory over time.

NAME                                                        CPU(cores)   MEMORY(bytes)
splunk-dev-eks-splunk-kubernetes-logging-hkdkh              5m           206Mi
splunk-dev-eks-splunk-kubernetes-logging-hnzj2              7m           497Mi
splunk-dev-eks-splunk-kubernetes-logging-jf766              23m          350Mi
splunk-dev-eks-splunk-kubernetes-logging-k9fp5              9m           238Mi
splunk-dev-eks-splunk-kubernetes-logging-qr4dg              27m          827Mi
splunk-dev-eks-splunk-kubernetes-logging-rl4ct              73m          489Mi
splunk-dev-eks-splunk-kubernetes-metrics-6c469697f8-sr926   0m           76Mi
splunk-dev-eks-splunk-kubernetes-objects-bbccdd967-tp26s    30m          329Mi

For example splunk-dev-eks-splunk-kubernetes-logging-qr4dg  is already at 828MB and eventually goes up to at least 2GB.

**Comment by matthewmodestino** [comment]
Just a follow up on this one. 

We were able to rectify by ensuring the filters and multiline regex rules were optimized. 

So far so good. 

Will be updating docs to assist in avoiding issues in the future
