### ISSUE TITLE
Add logging and metrics for window nodes

### ISSUE THREAD

**Issue by samfry** [splunk/splunk-connect-for-kubernetes#650]
<

**What would you like to be added**:
windows node metrics and container logs

**Why is this needed**:
We run a large infrastructure with about 140 windows nodes (same for linux). Would be good to be able to pull in that data alongside this current setup

**Comment by cheneysplunk** [comment]
Hi @samfry , we have following EPIC to support Windows nodes 2 years ago, however, it's deferred due to limited resources. Added a note there, and will discuss it with PM in the future. Thank you.
https://jira.splunk.com/browse/ADDON-22890
