### ISSUE TITLE
Additional "splunk-kubernetes-metrics" pod labels

### ISSUE THREAD

**Issue by nhalstead** [splunk/splunk-connect-for-kubernetes#652]
Deploying "splunk-kubernetes-metrics" has the [aggregator deployment](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/deploymentMetricsAggregator.yaml) pods labeled the same as [daemonset](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/daemonset.yaml) pods.

**What would you like to be added**:

The daemonset and the deployment configs should have an additional label to tag the _app-type_ or mode to help distinct the deployed pods by the two resource types.

Deploy the "splunk-kubernetes-metrics" and the "splunk-kubernetes-logging" sharing the same  `.global.splunk.hec` and `.global.kubernetes` section in the values.yaml file.

**Why is this needed**:

Better filtering on the pods when querying kubernetes.

I use a tool called [k9s](https://github.com/derailed/k9s) that allows you to view your Kubernetes cluster using VIM-like commands. On the deployment page (`:deploy`) once you enter into a deployment it reads the deployment filters to find the pods that are managed by the deployment (using `.spec.selector.matchLabels`).

![image](https://user-images.githubusercontent.com/5577816/130265670-6c99c4d4-7b98-40dc-9a22-57c87fc5dc86.png)

**Comment by rockb1017** [comment]
i see. we will add this in the back log. it seems to be a simple fix. Would you like to give it a try and create PR?

**Comment by nhalstead** [comment]
Hello @rockb1017, I've made a PR to add the additional labels to make the distinctions in the pod types.
