### ISSUE TITLE
SCK Logging file logs not implementing regex in multiline properly

### ISSUE THREAD

**Issue by shane-emery** [splunk/splunk-connect-for-kubernetes#655]
Hello,
When defining a custom file log to capture and parse multiline events, the regex does not seem to be executed properly.

For example:
  tomcat:
    from:
      file:
        path: /var/log/tomcat/*/*.log
    multiline:
      firstline: /\d{4}-\d{2}-\d{2}.\d{2}:\d{2}:\d{2}.\d{3}/
      separator: "\n"
    sourcetype: tomcat

**What happened**: multilines were ignored

**What you expected to happen**: multiline to be captured and expression evaluted and parsed properly

**How to reproduce it (as minimally and precisely as possible)**: You can implement a sample log with standard java stack trace exception. Point SCK to tail the sample log and watch to see splunk ingest the events.

**Anything else we need to know?**: 

**Environment**:
- Kubernetes version (use `kubectl version`): Openshift OKD 4.7.0
- Ruby version (use `ruby --version`): 2.7.3
- OS (e.g: `cat /etc/os-release`): CentOS 8
- Splunk version: Enterprise 8.0.6
- Splunk Connect for Kubernetes helm chart version: 1.4.9
- Others:

**Comment by cheneysplunk** [comment]
@shane-emery , thanks for reporting this issue.
We can try it but I'm afraid the log format(such as timestamp) might be different, then the regex doesn't work anyways. Could you please provide some sample logs then we can just validate the regex? 
Also please try to remove the first and last slash like this: \d{4}-\d{2}-\d{2}.\d{2}:\d{2}:\d{2}.\d{3}.
Thank you.

**Comment by shane-emery** [comment]
General, it applies to any multiline event message that can be generated in a log file, for example java exception stack traces.
Here is a sample regex:
.{3} \d{2}, \d{4} \d{1,2}:\d{2}:\d{2} .{2}
java exception stack trace that I would like to bundle up into a single event message:
Sep 20, 2021 9:21:47 PM org.apache.catalina.startup.HostConfig deployWAR
SEVERE: Error deploying web application archive /usr/local/tomcat/webapps/ROOT.war
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1022)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:994)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1127)
at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2021)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by shane-emery** [comment]
I am using the default helm chart 1.4.9 with only values.yaml customized.  Here is the relevant sections from the generated configMap and output.conf from the pod. I updated the regex, which still matches the above logs.

ConfigMap source.files.conf:
    <source>
      @id tail.file.tomcat
      @type tail
      @label @CONCAT
      tag tail.file.tomcat
      path /var/log/tomcat/*/*.log
      pos_file /var/log/splunk-fluentd-tomcat.pos
      read_from_head true
      path_key source
      multiline_flush_interval 5s
      <parse>
        @type multiline
        format_firstline /.{3}\s\d{2},\s\d{4}\s\d{1,2}:\d{2}:\d{2}\s.{2}/
      </parse>
    </source>

the pods error out with the following message:
2021-09-22 16:21:07 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Invalid regexp '': No named captures"

I tried a simple regex: /\d{3}/. and got the same error.

Is there a different format for custom files vs containers? This is what I am using to try and get some part of multiline to work:

  tomcat:
    from:
      file:
        path: /var/log/tomcat/*/*.log
    sourcetype: tomcat
    multiline:
      firstline: /\d{3}/
      separator: "\n"

**Comment by cheneysplunk** [comment]
I guess we need to add following filter in output.conf, under <label @CONCAT>

<filter tail.file.tomcat>
        @type concat
        key log
        timeout_label @SPLUNK
        multiline_start_regexp /.{3}\s\d{2},\s\d{4}\s\d{1,2}:\d{2}:\d{2}\s.{2}/
        flush_interval 5
</filter>

**Comment by shane-emery** [comment]
failing...

  output.conf: |-
    #Events are emitted to the CONCAT label from the container, file and journald sources for multiline processing.
    <label @CONCAT>
      <filter tail.file.tomcat>
        @type concat
        key log
        timeout_label @splunk
        multiline_start_regexp /.{3}\s\d{2},\s\d{4}\s\d{1,2}:\d{2}:\d{2}\s.{2}/
        flush_interval 5
      </filter tail.file.tomcat>

bundler: failed to load command: fluentd (/usr/bin/fluentd)
/usr/share/gems/gems/fluentd-1.11.5/lib/fluent/config/basic_parser.rb:92:in `parse_error!': expected character in tag name at output.conf line 9,11 (Fluent::ConfigParseError)
  8:     flush_interval 5
  9:   </filter tail.file.tomcat>

**Comment by shane-emery** [comment]
Yes, I have and still failing:

  output.conf: |-
    #Events are emitted to the CONCAT label from the container, file and journald sources for multiline processing.
    <label @CONCAT>
      <filter tail.file.tomcat>
        @type concat
        key log
        timeout_label @splunk
        multiline_start_regexp /.{3}\s\d{2},\s\d{4}\s\d{1,2}:\d{2}:\d{2}\s.{2}/
        use_first_timestamp true
      </filter tail.file.tomcat>

**Comment by cheneysplunk** [comment]
The end of filter should be "\</filter\>"?

**Comment by shane-emery** [comment]
That did the trick.  So My request would be:
I would like to see the values.yaml support defining multiline for log files and process the filters into the output.conf file properly. 

Currently I need to manually change the configMap.yaml file.

  output.conf: |-
    #Events are emitted to the CONCAT label from the container, file and journald sources for multiline processing.
    <label @CONCAT>
      <filter tail.file.tomcat>
        @type concat
        key log
        timeout_label @splunk
        multiline_start_regexp /.{3}\s\d{2},\s\d{4}\s\d{1,2}:\d{2}:\d{2}\s.{2}/
        flush_interval 5
        separator "\n"
        use_first_timestamp true
      </filter>
      <filter tail.file.python>
        @type concat
        key log
        timeout_label @splunk
        multiline_start_regexp /\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/
        flush_interval 5
        separator "\n"
        use_first_timestamp true
      </filter>

**Comment by rockb1017** [comment]
Glad it got resolved for you. 
if you could create a PR, that would be great.

**Comment by foram-splunk** [comment]
Hi @shane-emery  , 

I tried ingesting logs and installed sck using my_values.yaml . I was able to collect multiliine logs using regex in Splunk .

**Sample logs:**

Nov 23, 2021 10:33:47 AM log main
INFO: java.lang.ArithmeticException: / by zero
	at log.generateException(log.java:36)
	at log.gen1(log.java:22)
	at log.gen2(log.java:31)
	at log.gen1(log.java:24)
	at log.gen2(log.java:31)
	at log.gen1(log.java:24)
	at log.main(log.java:52)

**Changes in my_values.yaml :**

splunk-kubernetes-logging:
  logs:
    loggen:
      from:
        file:
          path: /var/log/sample.log
      timestampExtraction:
        format: "%b %d, %Y %k:%M:%S %p"
      multiline:
        firstline: /([A-Z]{1}[a-z]{2}\s*\d{2},\s*\d{4})/


<img width="1066" alt="Screenshot 2021-11-23 at 4 22 14 PM" src="https://user-images.githubusercontent.com/89519924/143011587-3bc5a2f0-8bff-4fad-9586-719ce91d19f9.png">

**Comment by foram-splunk** [comment]
Hey @shane-emery ,closing this issue . You can re-open it if you face the same issue again . Thanks :)
