### ISSUE TITLE
Not ingesting OpenShift log locations into config map

### ISSUE THREAD

**Issue by itscatherinelam** [splunk/splunk-connect-for-kubernetes#661]
**What happened**: I created a Splunk Connect deployment using the example and specified these two log locations for our cluster's logs:

`  logs:
    # The kube-audit file has another path on OpenShift
    kube-audit:
      from:
        file:
          path: /var/log/kube-apiserver/audit.log
    # Next 2 logfiles are specific to OpenShift
    openshift-audit:
      from:
        file:
          path: /var/log/openshift-apiserver/audit.log
      timestampExtraction:
        format: "%Y-%m-%dT%H:%M:%SZ"
      sourcetype: kube:openshift-apiserver-audit
    oauth-audit:
      from:
        file:
          path: /var/log/oauth-apiserver/audit.log
      timestampExtraction:
        format: "%Y-%m-%dT%H:%M:%SZ"`

However, the config map that spawns does not seem to have those values anywhere. 

**What you expected to happen**: I had expected the configmap created from the values.yaml to point to the two audit locations for OpenShift, but instead I only see one reference to the kube log, which is not applicable to our cluster:

`  source.files.conf: >-
    # This fluentd conf file contains sources for log files other than container
    logs.

    <source>
      @id tail.file.kube-audit
      @type tail
      @label @CONCAT
      tag tail.file.kube:apiserver-audit
      path /var/log/kube-apiserver/audit.log
      pos_file /var/log/splunk-fluentd-kube-audit.pos
      read_from_head true
      path_key source
      <parse>
        @type regexp
        expression /^(?<log>.*)$/
        time_key time
        time_type string
        time_format %Y-%m-%dT%H:%M:%SZ
      </parse>
    </source>`

**How to reproduce it (as minimally and precisely as possible)**: This is the values.yaml file I used. Note, the fixes file was because it didn't seem like the values of those specified were also being ingested in the right place, so I redefined the variables at a higher level so they can be taken in. I think it's a bug? 

`global:
  splunk:
    hec:
      token: TOKEN
      host: URL
      port: PORT
      protocol: https
      indexName: INDEXNAME
      insecure_ssl: true
  kubernetes:
    clusterName: CLUSTERNAME
FIXES HERE
kubernetes:
    securityContext: true
containers:
    logFormatType: cri
splunk:
    hec:
      insecureSSL: true
END FIXES
splunk-kubernetes-logging:
  resources:
    # limits:
    #  cpu: 100m
    #  memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi
  enabled: true
  kubernetes:
    # the next actually sets .securityContext.privileged
    # privileged is required, due to SELinux preventing
    # write access for the *.pos files of fluentd.
    securityContext: true
  containers:
    logFormatType: cri
    logFormat: "%Y-%m-%dT%H:%M:%S.%N%:z"
  logs:
    # The kube-audit file has another path on OpenShift
    kube-audit:
      from:
        file:
          path: /var/log/kube-apiserver/audit.log
    # Next 2 logfiles are specific to OpenShift
    openshift-audit:
      from:
        file:
          path: /var/log/openshift-apiserver/audit.log
      timestampExtraction:
        format: "%Y-%m-%dT%H:%M:%SZ"
      sourcetype: kube:openshift-apiserver-audit
    oauth-audit:
      from:
        file:
          path: /var/log/oauth-apiserver/audit.log
      timestampExtraction:
        format: "%Y-%m-%dT%H:%M:%SZ"
      sourcetype: kube:oauth-apiserver-audit
splunk-kubernetes-metrics:
  enabled: false
splunk-kubernetes-objects:
  enabled: false
`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): OpenShift 4.7
- Ruby version (use `ruby --version`): N/A
- OS (e.g: `cat /etc/os-release`): RHCOS
- Splunk version: 
- Splunk Connect for Kubernetes helm chart version: 1.4.9
- Others:

**Comment by chaitanyaphalak** [comment]
You can change https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/values.yaml#L363
to suit your purpose and pass it through the values.yaml you are using to configure your deployment.

**Comment by itscatherinelam** [comment]
how would i pass both the location of the audit log and the location of the oauth logs? i see i can only substitute one value there. 

@chaitanyaphalak

**Comment by chaitanyaphalak** [comment]
@itscatherinelam @gnarc has shared an awesome example.

**Comment by vinzent** [comment]
@itscatherinelam did you have a look at: https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/examples/openshift4-logging-only.yaml

**Comment by vinzent** [comment]
I tried the openshift example. 

```
$ helm repo update | grep splunk
...Successfully got an update from the "splunk" chart repository

$ helm \
    template \
    test splunk/splunk-connect-for-kubernetes \
    -f https://raw.githubusercontent.com/splunk/splunk-connect-for-kubernetes/develop/helm-chart/splunk-connect-for-kubernetes/examples/openshift4-logging-only.yaml   | \
    grep -E -B5 -A12 '(/var/log/kube-apiserver/audit.log|/var/log/openshift-apiserver/audit.log|/var/log/oauth-apiserver/audit.log)'

    <source>
      @id tail.file.kube-audit
      @type tail
      @label @CONCAT
      tag tail.file.kube:apiserver-audit
      path /var/log/kube-apiserver/audit.log
      pos_file /var/log/splunk-fluentd-kube-audit.pos
      read_from_head true
      path_key source
      <parse>
        @type regexp
        expression /^(?<log>.*)$/
        time_key time
        time_type string
        time_format %Y-%m-%dT%H:%M:%SZ
      </parse>
    </source>
    <source>
      @id tail.file.oauth-audit
      @type tail
      @label @CONCAT
      tag tail.file.kube:oauth-apiserver-audit
      path /var/log/oauth-apiserver/audit.log
      pos_file /var/log/splunk-fluentd-oauth-audit.pos
      read_from_head true
      path_key source
      <parse>
        @type regexp
        expression /^(?<log>.*)$/
        time_key time
        time_type string
        time_format %Y-%m-%dT%H:%M:%SZ
      </parse>
    </source>
    <source>
      @id tail.file.openshift-audit
      @type tail
      @label @CONCAT
      tag tail.file.kube:openshift-apiserver-audit
      path /var/log/openshift-apiserver/audit.log
      pos_file /var/log/splunk-fluentd-openshift-audit.pos
      read_from_head true
      path_key source
      <parse>
        @type regexp
        expression /^(?<log>.*)$/
        time_key time
        time_type string
        time_format %Y-%m-%dT%H:%M:%SZ
      </parse>
    </source>
```

Conclusion: all 3 openshift specific logfiles `/var/log/kube-apiserver/audit.log`, `/var/log/kube-apiserver/audit.log`, `/var/log/kube-apiserver/audit.log` show up in rendered configmap

Tested with: 

* Helm version: 3.5.1
* Chart version: 1.4.10

**Comment by itscatherinelam** [comment]
@vinzent 

Thank you for posting the YAML - that was exactly what I need! Apologies for the late reply. This work sort of fell to the wayside and got tabled.

I'm not sure why when I try the example, it didn't seem to ingest it, but I manually replaced the config map with the values you had above and it works. I am sooooo thankful. Have a lovely holiday season!
