### ISSUE TITLE
Add useACK feature to Splunk Forwarder

### ISSUE THREAD

**Issue by sonaikar** [splunk/splunk-connect-for-kubernetes#666]
<

**What would you like to be added**: Splunk feature useACK 

**Why is this needed**:  Protect against loss of in-flight data. It is Splunk feature need to be enabled/integrated in Helm Chart for Splunk forwarder.  Below are required links for more details. 

https://docs.splunk.com/Documentation/Forwarder/8.2.2/Forwarder/Protectagainstthelossofin-flightdata
https://community.splunk.com/t5/Splunk-Enterprise/Setting-useACK-in-outputs-conf-in-a-Distributed-Environment/m-p/547914

**Comment by tehlers320** [comment]
https://github.com/splunk/fluent-plugin-splunk-hec/pull/65

**Comment by rockb1017** [comment]
Hello, @sonaikar just to make sure, in this helm chart, we do not use Splunk Forwarder. we only use Fluentd to send data to Splunk HEC endpoint. (HTTP)
Splunk Forwarder and Splunk Indexer is S2S communication, which is different protocol to HTTP.

**Comment by harshit-splunk** [comment]
not stale

**Comment by vinzent** [comment]
Related: https://github.com/splunk/fluent-plugin-splunk-hec/pull/199
