### ISSUE TITLE
Inconsistent tag search results for some fields with logFormatType=cri on OpenShift 4.7

### ISSUE THREAD

**Issue by ryancastle** [splunk/splunk-connect-for-kubernetes#667]
**What happened**: Exact match search results for numerous fields are not consistent with the underlying data, nor are they consistent with field statistics presented in the _Fields_ sidebar or in `stats` results. Using wildcards in place of special characters (e.g. dashes) _and_ as a field value prefix match returns _more_ consistent results, but still under-counts slightly.

Only log data coming from _Splunk Connect for Kubernetes_ seems to be affected.

Some results are returned for exact field searches in some contexts (<1% of the total expected), which suggests something about the data arriving at the collector might be to blame. 

It affects sourcetypes `kube:container:*` and `kube:apiserver-audit` in different indices.

**What you expected to happen**: Search results for exact field matches such as `namespace=<NAMESPACE>` to return results consistent with index statistics

**How to reproduce it (as minimally and precisely as possible)**: 

_Example: Index Statistics_
```
> index=ocp_apps | top pod_uid limit=1
cf3f2b38-ab12-494f-ae4e-d43cd4e1a379 | 275974
```

_Example: Zero results_
```
> index=ocp_apps pod_uid="cf3f2b38-ab12-494f-ae4e-d43cd4e1a379"
0 events
```

_Example: 270k results_
```
> index=ocp_apps pod_uid="*cf3f2b38*ab12*494f*ae4e*d43cd4e1a379"
275,974 events
```

_Example: Like Search_
```
> index=ocp_apps | where like(pod_uid,"cf3f2b38-ab12-494f-ae4e-d43cd4e1a379")
275,974 events
```

**Anything else we need to know?**:
Fields confirmed affected:
- container_name
- container_id
- pod
- pod_uid
- cluster_name
- namespace

Fields confirmed unaffected:
- host
- sourcetype
- source
- eventtype
- splunk_server
- id

**Environment**:
- OpenShift CLI version: 4.7.19 (Kubernetes 1.20)
- Ruby version: ruby 2.7.3p183
- OS: Red Hat Enterprise Linux 8.4
- Splunk version: 8.2.2.1
- Splunk Connect for Kubernetes helm chart version: 1.4.9
- fluentd-hec: 1.2.7
- OpenShift: 4.7.30
- CRIO: 1.20.4-14.rhaos4.7.gitbce257b.el8
- Splunk Cloud and Splunk Enterprise both appear to be affected

**Comment by chaitanyaphalak** [comment]
Have you tried searching for metadata using https://github.com/splunk/splunk-connect-for-kubernetes#searching-for-sck-metadata-in-splunk ?

**Comment by ryancastle** [comment]
That's helpful to understand the different fields. The issue isn't so much that we can't get the data out of it - it's that end users need documentation to understand how to find their logs. And the discovery interfaces are essentially broken on these fields. Ease of use and enabling a quality discovery experience is what motivated us to replace EFK with Splunk. The Splunk UI clearly believes it can filter on these fields using the standard syntax.

**Comment by rockb1017** [comment]
`index=ocp_apps pod_uid::"cf3f2b38-ab12-494f-ae4e-d43cd4e1a379"` 
should give you right results. (`=` replaced with `::`) 

it needs to be configured in fields.conf file as documented https://github.com/splunk/splunk-connect-for-kubernetes#searching-for-sck-metadata-in-splunk to be able to search with `=`
