### ISSUE TITLE
Anyone success retrieve AKS master node log and API Server logs ?

### ISSUE THREAD

**Issue by kkkelvinkk** [splunk/splunk-connect-for-kubernetes#671]
Hi ALL,

Anyone success pulling AKS master logs such as host log (e.g. /var/log/auth.log) or container logs (e.g. kube-apiserver log) using splunk connect for kubernetes ? I am playing with 1.4.10 and able to receive all logs from node including host log and container log, but no luck with any AKS master node log. Any suggestions are welcome. Thanks a lot.

**Comment by kkkelvinkk** [comment]
I am using AKS, the Kubernetes v1.20.9. I cannot find a way to ssh into AKS master node. However, from Azure Log Analytics Workspace, "AzureDiagnostics" shows the log path of API server is something like "/var/log/pods/<pod_uid>/kube-apiserver/0.log".

**Comment by rockb1017** [comment]
so you are not getting container logs nor host logs from master node? is the daemonset deployed to the master node?

**Comment by matthewmodestino** [comment]
Anything from AKS control plane would have to come from Event Hub, I believe. AKS does not let you access the control plane directly. We will only pick up logs off the node.

**Comment by lastcoolnameleft** [comment]
Check out: https://docs.microsoft.com/en-us/azure/aks/monitor-aks#collect-resource-logs

**Comment by matthewmodestino** [comment]
@lastcoolnameleft Tommy!! Good to bump into you here virtually! Hope to get to see ya at a Kubecon again in the future! Thanks for the share!

**Comment by kkkelvinkk** [comment]
@lastcoolnameleft @matthewmodestino Thanks for your information. I can grab the host log (e.g. /var/log/auth.log) for VM, Virtual Machine Scale Set and AKS non-autoscale set. However, seems it does not apply to AKS autoscale set. We have tried Azure policy, deploy Log Analytics agent for Linux VMs & deploy Log Analytics agent for Linux virtual machine scale sets, custom log. Seems all those cannot applied to AKS autoscale set.

Also, I have tried to override the default Azure Log Analytics, install Splunk agent(https://github.com/CyberSecThreat-Corporation-Limited/Splunk) or Splunk-connect-for-kubernetes. All these methods seems can collect host log on worker node, but not AKS master node. 

I haven't tried "EventHub" way, but it should works just like send to "Log Analytics workspace". Just want to check if anyone has successfully grab "/var/log/auth.log" on AKS autoscale set master node. 

Thanks again.

**Comment by matthewmodestino** [comment]
Do you have direct access to the master node? my understanding is that MSFT runs the control plane in AKS, can you point me to what exactly the "master node" appears like to you?

**Comment by kkkelvinkk** [comment]
@matthewmodestino Thanks for your reply again. I cannot find any documentation how can I access to "master node". What I refer to "master node" is actually the "control plane" usually running kube-api, etcd, kube-scheduler and kube-controller. For on-premise environment, we will install those components to a "master node" to interact with, while other worker nodes will run application service workloads. I was asked to check if there are any "dedicated machines" if an AKS auto-scale set is provisioned. If that control plane is shared among other customer, I think there are no needs monitor the host log. Just want to check if anyone had experience regarding this. Thanks again.

**Comment by matthewmodestino** [comment]
Yeah, because AKS is a managed control plane, MSFT will expose what logging is available as seen in the document above. 

The only host logs you will need are from the worker nodes.

**Comment by kkkelvinkk** [comment]
@matthewmodestino Thanks a million! I will close this question.
