### ISSUE TITLE
Events do not show up when filtering by container_name

### ISSUE THREAD

**Issue by epernice** [splunk/splunk-connect-for-kubernetes#675]
**What happened**:

When I search by container_name, I do not see all of the events that have that container_name.

**What you expected to happen**:

When I search by container_name I should see all of the events that have that container_name

**How to reproduce it (as minimally and precisely as possible)**:

Run this search:

`index=kube host=*dev*  sourcetype="kube:container:my-server"`

I see all of the events that I expect to see (298 events in my time period). The field statistics indicate that all 298 events have the same container_name, which is also as expected.

Run this search with container_name included:

`index=kube host=*dev*  sourcetype="kube:container:my-server" container_name="my-server"`

Now I only get 41 events, even though I expect to get 298 events.

Then I run this search, with sourcetype removed, which I assumed would be broader:

`index=kube host=*dev* container_name="my-server"`

And I only get 1 event.

**Anything else we need to know?**:

I see this behavior with some other fields, like pod, but I do not see this behavior with some other fields, like host.

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):

NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9

- Splunk version: 8.2.2 Build 87344edfcdb4
- Splunk Connect for Kubernetes helm chart version: splunk-connect-for-kubernetes-1.4.9

**Comment by rockb1017** [comment]
Here is related doc
https://github.com/splunk/splunk-connect-for-kubernetes#searching-for-sck-metadata-in-splunk
