### ISSUE TITLE
Unable to download S-C-K from 

### ISSUE THREAD

**Issue by harmanbirdi** [splunk/splunk-connect-for-kubernetes#680]
Not really a bug but I am unable to download s-c-k from https://splunk.github.io/splunk-connect-for-kubernetes/
It has been giving me 404 not found at least since Wed, Nov 24, 2021

This URL is referenced in the README file documentation for s-c-k at
https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/README.md

**What happened**:
Unable to download from https://splunk.github.io/splunk-connect-for-kubernetes/
Keep seeing the following

404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

**What you expected to happen**:
Expect to be able access the web location to download it.

**How to reproduce it (as minimally and precisely as possible)**:
Paste - https://splunk.github.io/splunk-connect-for-kubernetes/ in any browser

**Anything else we need to know?**:
Is the link just broken or has it been moved and the documentation has not been updated?

**Environment**:
Nope

**Comment by harshit-splunk** [comment]
Hey @harmanbirdi, we are using docs directory to keep track of SCK releases. 
You can use SCK chart by cloning the repo, download from release or download from https://github.com/splunk/splunk-connect-for-kubernetes/tree/develop/docs.

**Comment by harshit-splunk** [comment]
Closing the issue, feel free to reopen or create a new one if required
