### ISSUE TITLE
Sending logs from specific pod only

### ISSUE THREAD

**Issue by ALNBAND** [splunk/splunk-connect-for-kubernetes#690]
Hi,

Is there a way to send logs from **only one pod**?
e.g. fluent is reading all cluster/nodes pod logs, if there is a way to configure it to send to splunk only one pod logs ?

**Comment by chaitanyaphalak** [comment]
You can achieve that using annotations, checkout https://github.com/splunk/splunk-connect-for-kubernetes#managing-sck-log-ingestion-by-using-annotations

**Comment by ALNBAND** [comment]
1. So by default it doesn't send any data, I need explicitly configure from which pods to send the data? 
2. Does the tool have buffering on a disk, e.g. if Splunk is down to prevent a data loss ?

**Comment by harshit-splunk** [comment]
> 1. So by default it doesn't send any data? I need explicitly configure from which pods to send the data?  or there is option to disable all and one by one explicitly ?

By default it will send logs from all the container. You can exclude log from any container by adding splunk.com/exclude annotation.

> 2. Does the tool have buffering on a disk, e.g. if Splunk is down to prevent a data loss ?

Yes, it'll buffer data in memory. Here you can modify the configuration from here (https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/values.yaml#L418-L427)

**Comment by harshit-splunk** [comment]
You can also add customFilter to only allow from only specific containers. For example,
```
splunk-kubernetes-logging:
  customFilters:
    includeOnlyFilter:
      tag: tail.containers.**
      type: grep
      body: |
        <regexp>
          key container_name
          pattern /^etcd$/
        </regexp>
```
Reference: https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/values.yaml#L471-L506

**Comment by ALNBAND** [comment]
@harshit-splunk  - thanks, ok the customFilter looks promising, can I disable all the pods logs with simple config? and then add the fiter

**Comment by harshit-splunk** [comment]
@ALNBAND, there is no direct way to disable log collection from all pods unless you modify template file.
By applying previous filter, fluend will capture and drop all other logs except from etcd pod

**Comment by harshit-splunk** [comment]
@ALNBAND should I close the issue?

**Comment by matthewmodestino** [comment]
you can also set the path value to focus in on specifc regex or comma separated values:

https://github.com/splunk/splunk-connect-for-kubernetes/blob/4b460c24c13bfa8f3d240bcbd29cfb6e25be1076/helm-chart/splunk-connect-for-kubernetes/values.yaml#L79

By default we scoop up everything. With a bit of thought you could scope the path we watch down to just a specific namespace or pod by examining the path to the pod on the node and adjusting the path value as necessary....

https://docs.fluentd.org/input/tail#path
