### ISSUE TITLE
logLevel selection does not appear to work

### ISSUE THREAD

**Issue by f0rkth1s** [splunk/splunk-connect-for-kubernetes#691]
**What happened**:
Specifying the loglevel does not restrict the level of logs sent to Splunk

**What you expected to happen**:
If I pick error, I expected only error logs to be sent through to splunk from the cluster

**How to reproduce it (as minimally and precisely as possible)**:
Set logLevel in global or a specific daemon set to a level below the default info and update the cluster

**Anything else we need to know?**:
This was discovered after I pushed it out to a dev cluster and I have replicated on my home cluster as well

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20
- Ruby version (use `ruby --version`): n/a
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04 & centos 7
- Splunk version: 8.0.4
- Splunk Connect for Kubernetes helm chart version: latest 20/12/2021
- Others:

**Comment by chaitanyaphalak** [comment]
@f0rkth1s the log level selection if for the the logging of the fluentd pod itself, not for filtering/controlling the logs by log level

**Comment by f0rkth1s** [comment]
Thanks for the update, are there any plans in the future to introduce such a feature?

**Comment by vinzent** [comment]
How should fluentd know the log level of a line that an application printed on stdout/stderr? It's completely up to the application how to structure the output. Some send errors to stderr, some to stdout as all the other messages. There is IMHO no universally valid pattern to match log line severity.

Maybe you could use [customFilters](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/values.yaml#L471). But this is nothing an application can influence. The SCK deployer needs to define the settings. Also, you need to have good  fluentd config knowledge.

**Comment by f0rkth1s** [comment]
Many thanks
