### ISSUE TITLE
K8s Node memory metrics not reporting to Splunk. 

### ISSUE THREAD

**Issue by cdahal100** [splunk/splunk-connect-for-kubernetes#695]
**What happened**: Node memory metrics not ingesting to Splunk. Example - kube.node.memory.usage_bytes

**What you expected to happen**:  Metrics data available from kube.node.memory* metrics

**How to reproduce it (as minimally and precisely as possible)**: | mstats avg(kube.node.memory.usage_bytes) as AvgMemoryUsage WHERE index="*" AND cluster_name="*

**Anything else we need to know?**:

**Environment**: Splunk connect for kubernetes
- Kubernetes version (use `kubectl version`):
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`): 
- Splunk version: 8.2
- Splunk Connect for Kubernetes helm chart version: 1.4.10
- Others:

**Comment by harshit-splunk** [comment]
Hey, @cdahal100, can you please provide logs of metrics-agg pod? Also which k8s distribution are you using?
