### ISSUE TITLE
1.4.11 does not have helm chart artifacts

### ISSUE THREAD

**Issue by pc-mreeves** [splunk/splunk-connect-for-kubernetes#716]
**What happened**: 
I went to https://github.com/splunk/splunk-connect-for-kubernetes/releases/tag/1.4.11
and there is only source code in the "artifacts" section.
![image](https://user-images.githubusercontent.com/22081352/152581751-86405f98-bf65-4b0b-aa11-0f7f4e3debb7.png)

**What you expected to happen**:
I expected the various helm chart artifacts to be available as they are for 1.4.10 and earlier releases:
https://github.com/splunk/splunk-connect-for-kubernetes/releases/tag/1.4.10
![image](https://user-images.githubusercontent.com/22081352/152581875-67cd5bf1-fa6e-49e7-9946-66819d810c15.png)

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:
Nope.

**Environment**:
- Kubernetes version (use `kubectl version`): n/a
- Ruby version (use `ruby --version`): n/a
- OS (e.g: `cat /etc/os-release`): n/a
- Splunk version:  n/a
- Splunk Connect for Kubernetes helm chart version: 1.4.11
- Others: n/a

**Comment by harshit-splunk** [comment]
@pc-mreeves, thanks for pointing out this. We have updated artifacts of release 1.4.11
