### ISSUE TITLE
How can I pass value from the Pod labels to the jq_filter?

### ISSUE THREAD

**Issue by provcristianmaluenda** [splunk/splunk-connect-for-kubernetes#72]
Hi,
I need to be able to select an index per service. I am thinking to add a label with the index name in each pod.
Another option is to create a custom function in the `splunk-kubernetes-logging.container_jq_filter` with a lot of `if` for each service. The tradeoff of this is, I need to kill all the logging pods because they do not update the configuration if I do a `helm update`.

Any suggestion? Am I on the right way?
Thanks,
Cristian.

**Comment by beth2016** [comment]
@matthewmodestino 
Hi Matt,
Need it too.   Can you kindly share if you have any updates of routing to index based on namespace/deployment annotations?  thanks.

**Comment by chaitanyaphalak** [comment]
resolved as part of https://github.com/splunk/splunk-connect-for-kubernetes/pull/294
