### ISSUE TITLE
[Question][Enhancement] Support output to multiple indexes

### ISSUE THREAD

**Issue by mnhat3896** [splunk/splunk-connect-for-kubernetes#726]
**What would you like to be added**:
Hi team, 
I'm looking to implement Splunk helm which can **_output to multiple indexes_** in one helm chart. 

**Why is this needed**:
Because our case is each of project will stay in a namespace, and we want only one Splunk helm to scrape the logs from each namespace and then output to the correct index.
For instance:
```
    Splunk logs (one helm chart):
        namespace A (project A) => output to index A
        namespace B (project B) => output to index B
        ......
```
Therefore we can avoid having multiple fluentd installations (not installing many times Splunk helm).
Or if you don't have time, that would be nice if you could give me some solution to workaround. Thank you

**Comment by vinzent** [comment]
See README.md section [Managing SCK Log Ingestion by Using Annotations](https://github.com/splunk/splunk-connect-for-kubernetes#managing-sck-log-ingestion-by-using-annotations)

**Comment by harshit-splunk** [comment]
> How Splunk know with logs of the pod should be sent to the correct index? since there are could be many indexes.

SCK decides in which index logs should be sent. If SCK finds an index in pod annotations, it will be sent it to the given index otherwise it will be sent to the default index.

> I guess because if I set annotation for namespace then all the pods inside that namespace will be sent to the index that I set in annotation, isn't it?

Yes, you are correct. If you are interested in how it is done, here is the code where it happens:

https://github.com/splunk/splunk-connect-for-kubernetes/blob/928a45d36819eb9fa415272e5582a0ef89ec8ef6/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L276-L277

**Comment by mnhat3896** [comment]
@harshit-splunk many thanks for your support, now I can use annotation with multiple indexes <3

**Comment by nitinsinghit** [comment]
> I am trying to achieve similar objective and was able to get it done using annotation . But issue is we have an index called openshift where we collect all the namespaces and I was hoping once I set annotation for namespace then all the pods inside that namespace will be sent to the index that I set in annotation and I will not see same namespace in index called "openshift". This is causing redundant namespaces in index. Any way I can filter out /exclude namespaces in index ? Thanks
