### ISSUE TITLE
Does this version of splunk connect support kubernetes log with containerd in vresion 1.22 of kubernetes

### ISSUE THREAD

**Issue by saiharshitachava** [splunk/splunk-connect-for-kubernetes#727]
Does this version of splunk connect support kubernetes log with containerd in vresion 1.22 of kubernetes

**Comment by chaitanyaphalak** [comment]
@saiharshitachava yes it should work! Please try it out/test it and let us know if you face any issues.

Closing this issue for now, please open a new one if you have problems!

**Comment by nikhil-nomula** [comment]
@chaitanyaphalak we are on 1.4.15. Do you anticipate to run into issues with kubernetes 1.22 as we stopped getting logs once we upgraded to 1.22?

**Comment by vijaymck** [comment]
As kube 1.22+ transitioning to containerd, do we have to update manifest that references all containerd locations etc?

https://github.com/splunk/splunk-connect-for-kubernetes/blob/main/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml#L32
