### ISSUE TITLE
serviceMonitor template should allow release label to be overridden

### ISSUE THREAD

**Issue by Rohlik** [splunk/splunk-connect-for-kubernetes#730]
Hey there 👋🏽 ,
let's consider that you have Prometheus operator up and running in your k8s infrastructure and you have `serviceMonitorSelector.matchLabels` set to `release: kube-prometheus-stack`. That's mean that Prometheus will check only monitors with this label `release = kube-prometheus-stack`.
Later on you decide to use _Splunk connect for Kubernetes_ in your deployment and you want to enable `serviceMonitor` (config bellow) to collect some metrics via your Prometheus.

**What happened**:
```
Helm upgrade failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 12: mapping key "release" already defined at line 10
```
**What you expected to happen**:
I would expected that label `release` for  `serviceMonitor` will be overridden by my settings (bellow) as I need to match my Prometheus Operator config `serviceMonitorSelector.matchLabels` with Splunk's `serviceMonitor`.

**How to reproduce it (as minimally and precisely as possible)**:
Use this settings:
```
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
```

**Anything else we need to know?**:
The root cause is here:
https://github.com/splunk/splunk-connect-for-kubernetes/blob/928a45d36819eb9fa415272e5582a0ef89ec8ef6/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/serviceMonitor.yaml#L10
Take a look how it is handled in different project - https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/helm/aws-load-balancer-controller/templates/servicemonitor.yaml. They do not have `release` label in their template.
**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.2
- Ruby version (use `ruby --version`): 2.7.4p191
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 11 (bullseye)
- Splunk version: N/A
- Splunk Connect for Kubernetes helm chart version: 1.4.12
- Others:

**Comment by vinzent** [comment]
I think the current labels were at some time recommended or what everybody was using with helm charts. 

The current list of recommended labels can be found here: https://helm.sh/docs/chart_best_practices/labels/#standard-labels

Maybe SCK could switch to the new names.

**Comment by Rohlik** [comment]
Not close this issue as it is still issue 😞 .
