### ISSUE TITLE
Directory was change to * due to path(pathDest) was set to /data2/docker-lib/docker/containers/*/*/*.log

### ISSUE THREAD

**Issue by liuce1-lenovo** [splunk/splunk-connect-for-kubernetes#731]
Directory was change to * due to path(pathDest) was set to /data2/docker-lib/docker/containers/*/*/*.log
What's wrong with my values.yaml ? How to recover this ?

The directory was change to /data2/docker-lib/docker/containers/*/*/  and all the files were missing under the directory , some splunk file was left on the directory without any data .

**Comment by harshit-splunk** [comment]
Hey @liuce1-lenovo, can you please share more info on precisely what the issue is? Can you share your `values.yaml` file and which k8s distribution you are using?

**Comment by harshit-splunk** [comment]
Closing as the issue is inactive.
