### ISSUE TITLE
Unable to install another instance of Splunk in same cluster different namespace (Kubernetes)

### ISSUE THREAD

**Issue by nattvasan** [splunk/splunk-connect-for-kubernetes#735]
Hi,

I'm trying to install multiple instances of Splunk in different namespace in Kubernetes. I have used the chart in the location "https://github.com/splunk/splunk-connect-for-kubernetes/tree/develop/helm-chart/splunk-connect-for-kubernetes" and successfully installed on one namespace but while trying to replicate the same installation with different namespace, facing below error.

-----------
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /home/xxxx/splunk-connect-for-kubernetes

Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "splunk-connect-splunk-kubernetes-logging" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "xx-xxx": current value is "splunk"
helm.go:88: [debug] ClusterRole "splunk-connect-splunk-kubernetes-logging" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "xx-xxx": current value is "splunk"
rendered manifests contain a resource that already exists. Unable to continue with install
helm.sh/helm/v3/pkg/action.(*Install).Run
-----------

I have tried modifying the clusterRole.yaml to have a condition to verify the clusterrole but its failing. 

https://stackoverflow.com/questions/65110332/clusterrole-exists-and-cannot-be-imported-into-the-current-release

Could you please help me on this.

Thank you.

**Comment by nattvasan** [comment]
@luckyj5  We have uninstalled another splunk release which was causing conflicts. We have removed the old one because its not required anymore. Now, we're able to install splunk-connect now. 

>>The error you are getting is related to the static resource name which will need to be modified if there is a need to install >>more than one connector within the same cluster.

Do we need to edit resources such as ClusterRoles with new name and install it ? Please clarify.

**Comment by harshit-splunk** [comment]
Hey @nattvasan, if you are using default configurations, you only need to provide unique `.Values.secret.name` for logging, object and metric plugin. 
https://github.com/splunk/splunk-connect-for-kubernetes/blob/01bf0876e5f355b26825821a3b1d1a398cde4fde/helm-chart/splunk-connect-for-kubernetes/values.yaml#L220-L223
