### ISSUE TITLE
Multiple vulnerabilities detected in Splunk connect for kubernetes - expat library

### ISSUE THREAD

**Issue by ravis-splunk** [splunk/splunk-connect-for-kubernetes#737]
Several vulnerabilities which has been reported/identified have been fixed in recent past.

**Comment by harshit-splunk** [comment]
hey @ravis-splunk, can you please provide CVE details?

**Comment by gnarc** [comment]
can confirm
screenshot show growing vulnerabilities over time, which makes updates for older images necessary
(caveat: this is a disconnected environment; haven't checked if old images have been updated)

![quay_disconnect](https://user-images.githubusercontent.com/37799887/159893880-1b67be6d-e473-424b-90f1-03d0179c2d25.png)

![quay_disconnect2](https://user-images.githubusercontent.com/37799887/159894054-66f27384-177b-4e24-8ff1-e519ddf17f87.png)

in this case it is RHSA-2022:0951: https://access.redhat.com/errata/RHSA-2022:0951
