### ISSUE TITLE
Typo in values.yaml for "myhost:" instead of "host:"

### ISSUE THREAD

**Issue by gnarc** [splunk/splunk-connect-for-kubernetes#740]
1.4.11 must have introduced a small typo in the values.yaml which can still be found in 1.4.13
in the local config section for logging:

https://github.com/splunk/splunk-connect-for-kubernetes/blob/ed0a0f3506155ac08c057fe33768a3508215ad9a/helm-chart/splunk-connect-for-kubernetes/values.yaml#L166

>      myhost:

Should be 

>       host:

**Comment by harshit-splunk** [comment]
@gnarc, thanks for bringing it to the light. I will update it ASAP.
