### ISSUE TITLE
Allow HEC endpoint to be configured

### ISSUE THREAD

**Issue by vears91** [splunk/splunk-connect-for-kubernetes#742]
<

**What would you like to be added**:

The HTTP Event Collector provides a number of REST API endpoints ([reference ](https://docs.splunk.com/Documentation/SplunkCloud/latest/Data/HECRESTendpoints)). We would like to have the possibility to configure the endpoint to use through the `splunk-connect-for-kubernetes` charts. 

Please see [#221](https://github.com/splunk/fluent-plugin-splunk-hec/issues/221) for the corresponding issue in `fluent-plugin-splunk-hec` and a proposed PR.

**Why is this needed**:

Advanced use cases and custom setups can require the configuration of a particular endpoint

**Comment by matthewmodestino** [comment]
Pretty sure this has already been added?

https://github.com/splunk/splunk-connect-for-kubernetes/blob/2a3345517d67554ddb078af28a17857cc7f65503/helm-chart/splunk-connect-for-kubernetes/values.yaml#L22-L23

**Comment by vears91** [comment]
The full URL can be configured, but `services/collector` is hard-coded and appended to the URL. You can see this is the linked issue for the plugin

**Comment by matthewmodestino** [comment]
Ah! Gotcha, thanks!
