### ISSUE TITLE
Release note for v1.4.13 is available but no chart for this version

### ISSUE THREAD

**Issue by ndctrb** [splunk/splunk-connect-for-kubernetes#744]
**What happened**: Release note for v1.4.13 is available but no chart for this version

**What you expected to happen**: A chart for v1.4.13

**How to reproduce it (as minimally and precisely as possible)**: there's no chart 1.4.13 when using helm search repo -l splunk

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:
- Splunk Connect for Kubernetes helm chart version:
- Others:

**Comment by harshit-splunk** [comment]
@ndctrb, the issue is resolved.
