### ISSUE TITLE
customFilters does not work on openshift4

### ISSUE THREAD

**Issue by MichaelLi202112** [splunk/splunk-connect-for-kubernetes#745]
**What happened**:
on openshift4.7, when add the examples to customFilters, it does not work
customFilters:
     NamespaceSourcetypeFilter:
       tag: tail.containers.**
       type: jq_transformer
       body: jq '.record.cluster_name = "my_awesome_cluster" | .record'

**What you expected to happen**:
expect it would add the cluster_name to logs records.

**How to reproduce it (as minimally and precisely as possible)**:
on openshift4.7, use the sample [openshift4-logging-only.yaml file](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/examples/openshift4-logging-only.yaml) and enable NamespaceSourcetypeFilter 
 
**Anything else we need to know?**:
No.

**Environment**:
- Kubernetes version (use `kubectl version`):
openshift 4.7
michael.li@M-C02X6157JGH7 tmp % kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10+bbbc079", GitCommit:"c252961cae6d88fe6aae01264619dabf4552e8a5", GitTreeState:"clean", BuildDate:"2021-09-17T20:21:04Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
Red Hat Enterprise Linux CoreOS 47.84.202111031903-0 (Ootpa)
- Splunk version:
Splunk Enterprise
Version:
8.2.0
- Splunk Connect for Kubernetes helm chart version:
splunk-connect-for-kubernetes-1.4.12
- Others:

**Comment by vinzent** [comment]
Why not use  `.global.kubernetes.clusterName` helm var? I think normally the cluster_name is rather a static value.

What do you want to achieve by using jq, reading the cluster_name from a log message?

**Comment by vinzent** [comment]
`cluster_name` is a rather special field. Maybe try another one first.

Also, ensure you use the latest helm chart version. There was some issue with the ordering of the processing of customFilters lately.

**Comment by MichaelLi202112** [comment]
yes, tried other filed names with the latest helm chart version, and latest image version. But they don't work.

**Comment by harshit-splunk** [comment]
In SCK-1.4.12, custom filters' order was changed due to that, some key fields were being overwritten to default values (i.e. source, source type, index, cluster_name, etc).
The issue was resolved on 1.4.13. If you are still facing the same issue with the newer version, can you please share values.yaml file?

**Comment by aryznar-splunk** [comment]
Please check Harshit comment.
