### ISSUE TITLE
Logging Pods are crashing (crashloopbackoff)

### ISSUE THREAD

**Issue by anilchaithu** [splunk/splunk-connect-for-kubernetes#747]
**What happened**: Logging pods are getting crashed within few seconds of creation and the status is **crashloopbackoff**

**What you expected to happen**: we have this integration completed on 2 clusters and we followed the same process. But here we are having issues with Logging pods. Object & Metric pods are coming up.

**How to reproduce it (as minimally and precisely as possible)**: redeploy the sck app OR upgrade sck app

**Anything else we need to know?**: Below is the Error

oc logs -f stageapi-splunk-splunk-kubernetes-logging-bprjj
2022-03-02 00:07:50 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2022-03-02 00:07:50 +0000 [info]: gem 'fluentd' version '1.9.1'
2022-03-02 00:07:50 +0000 [info]: gem 'fluent-plugin-concat' version '2.4.0'
2022-03-02 00:07:50 +0000 [info]: gem 'fluent-plugin-jq' version '0.5.1'
2022-03-02 00:07:50 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.5.2'
2022-03-02 00:07:50 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.7.0'
2022-03-02 00:07:50 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.2.4'
**2022-03-02 00:07:50 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
bundler: failed to load command: fluentd (/usr/bin/fluentd)
/usr/share/gems/gems/fluentd-1.9.1/lib/fluent/supervisor.rb:532:in `rescue in run_supervisor': failed to create root directory:/tmp/fluentd, #<Errno::EROFS: Read-only file system @ dir_s_mkdir - /tmp/fluentd> (Fluent::InvalidRootDirectory)**
from /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/supervisor.rb:529:in `run_supervisor'
from /usr/share/gems/gems/fluentd-1.9.1/lib/fluent/command/fluentd.rb:330:in `<top (required)>'
from /usr/share/gems/gems/fluentd-1.9.1/bin/fluentd:8:in `require'
from /usr/share/gems/gems/fluentd-1.9.1/bin/fluentd:8:in `<top (required)>'
from /usr/bin/fluentd:23:in `load'
from /usr/bin/fluentd:23:in `<top (required)>'
from /usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `load'
from /usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `kernel_load'
from /usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:28:in `run'
from /usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/cli.rb:494:in `exec'
from /usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
from /usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
from /usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
from /usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/cli.rb:30:in `dispatch'
from /usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
from /usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/cli.rb:24:in `start'
from /usr/local/share/gems/gems/bundler-2.2.15/exe/bundle:49:in `block in <top (required)>'
from /usr/local/share/gems/gems/bundler-2.2.15/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
from /usr/local/share/gems/gems/bundler-2.2.15/exe/bundle:37:in `<top (required)>'
from /usr/local/bin/bundle:23:in `load'
from /usr/local/bin/bundle:23:in `<main>'

**Environment**: 
- Kubernetes version (use `kubectl version`): 1.4.3 & 1.4.12
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`): OpenShift Container Platform Version – 4.5.28
- Splunk version: 8.2.4
- Splunk Connect for Kubernetes helm chart version: 1.4.3 & 1.4.12
- Others:
-

**Comment by matthewmodestino** [comment]
Hi, this looks permissions related. Can you please review the security contexts in this cluster you are deploying to?

https://github.com/splunk/splunk-connect-for-kubernetes/blob/a9881ac89bfe1caa240a573be963572a20dedb55/helm-chart/splunk-connect-for-kubernetes/values.yaml#L133-L137

we provide options for privileged bindings, this is almost certainly something you need to review with your openshift admins to ensure the workload can run.

**Comment by anilchaithu** [comment]
Hi,

There is no issue with objects & metric pods. 

Will it help If I change the "openshiftPrivilegedSccBinding" flag to true

**openshiftPrivilegedSccBinding: true**

**Comment by anilchaithu** [comment]
We ran the below command. Is this different than setting the flag?

`$ oc create sa splunk-kubernetes-logging
$ oc adm policy add-scc-to-user privileged "system:serviceaccount:<project>:splunk-kubernetes-logging"`

**Comment by harshit-splunk** [comment]
I am not sure if it will work, what if we create a volume with emptyDir and mount it as /tmp.
I did the following changes and I was able to run sck successfully with read-only fs.

https://github.com/harshit-splunk/splunk-connect-for-kubernetes/commit/8dc8696caded2b5355a920ab8d2e3e3783bad42c

**Comment by matthewmodestino** [comment]
I think they will both work, but definitely not requiring privileged context will be better for admins/users.

**Comment by anilchaithu** [comment]
but this /tmp directory is with in the pod.

**Comment by harshit-splunk** [comment]
> but this /tmp directory is with in the pod.

We are mounting an empty directory to `/tmp` directory of the pod.

**Comment by matthewmodestino** [comment]
Did using the privileged binding allow the pod to start?

**Comment by anilchaithu** [comment]
After using the privileged binding, we are not seeing the /tmp directory error message. But the containers keeps getting terminated. Below is the error log.

splunk-fluentd-k8s-logs:
Container ID: cri-o://0fa794d70d5f3d121a394d8b765b638700e8fae4f43ee0df1a36274bae604210
Image: docker.io/splunk/fluentd-hec:1.2.10
Image ID: docker.io/splunk/fluentd-hec@sha256:0c4d38f9bed1ebcadd53b4a3cdd97b306538242ee7c14d8b07c2d777efa218cc
Port: <none>
Host Port: <none>
State: Waiting
Reason: CrashLoopBackOff
Last State: Terminated
Reason: Error
Exit Code: 1
Started: Wed, 06 Apr 2022 12:36:31 -0400
Finished: Wed, 06 Apr 2022 12:36:32 -0400
Ready: False
Restart Count: 5

`Events:
Type Reason Age From Message
---- ------ ---- ---- -------
Normal Scheduled 3m41s default-scheduler Successfully assigned splunk-hec-logging/stageapi-splunk-splunk-kubernetes-logging-q4gpl to avsddslapic2.stageapi.mskcc.org
Normal AddedInterface 3m39s multus Add eth0 [10.128.0.72/24]
Normal Pulled 2m10s (x5 over 3m39s) kubelet Container image "docker.io/splunk/fluentd-hec:1.2.10" already present on machine
Normal Created 2m10s (x5 over 3m38s) kubelet Created container splunk-fluentd-k8s-logs
Normal Started 2m10s (x5 over 3m38s) kubelet Started container splunk-fluentd-k8s-logs
Warning BackOff 109s (x10 over 3m34s) kubelet Back-off restarting failed container`

**Comment by harshit-splunk** [comment]
Hey @anilchaithu, the logs don’t have any information to find the root cause of CrashLoopBackOff. We need some more info to figure out the issue.

**Comment by anilchaithu** [comment]
checked couple of other pods and read only access file system issue is still there.

Error Message

2022-04-12 18:40:10 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2022-04-12 18:40:10 +0000 [info]: gem 'fluentd' version '1.14.4'
2022-04-12 18:40:10 +0000 [info]: gem 'fluent-plugin-concat' version '2.4.0'
2022-04-12 18:40:10 +0000 [info]: gem 'fluent-plugin-jq' version '0.5.1'
2022-04-12 18:40:10 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.9.4'
2022-04-12 18:40:10 +0000 [info]: gem 'fluent-plugin-prometheus' version '2.0.1'
2022-04-12 18:40:10 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2022-04-12 18:40:10 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.2.10'
2022-04-12 18:40:10 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
bundler: failed to load command: fluentd (/usr/bin/fluentd)
/usr/share/gems/gems/fluentd-1.14.4/lib/fluent/supervisor.rb:656:in `rescue in run_supervisor': failed to create root directory:/tmp/fluentd, #<Errno::EROFS: Read-only file system @ dir_s_mkdir - /tmp/fluentd> (Fluent::InvalidRootDirectory)
	from /usr/share/gems/gems/fluentd-1.14.4/lib/fluent/supervisor.rb:653:in `run_supervisor'
	from /usr/share/gems/gems/fluentd-1.14.4/lib/fluent/command/fluentd.rb:352:in `<top (required)>'
	from /usr/share/gems/gems/fluentd-1.14.4/bin/fluentd:15:in `require'
	from /usr/share/gems/gems/fluentd-1.14.4/bin/fluentd:15:in `<top (required)>'
	from /usr/bin/fluentd:23:in `load'
	from /usr/bin/fluentd:23:in `<top (required)>'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli.rb:484:in `exec'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli.rb:25:in `start'
	from /usr/local/share/gems/gems/bundler-2.3.6/exe/bundle:48:in `block in <top (required)>'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /usr/local/share/gems/gems/bundler-2.3.6/exe/bundle:36:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>'
/usr/share/ruby/fileutils.rb:247:in `mkdir': Read-only file system @ dir_s_mkdir - /tmp/fluentd (Errno::EROFS)
	from /usr/share/ruby/fileutils.rb:247:in `fu_mkdir'
	from /usr/share/ruby/fileutils.rb:228:in `block (2 levels) in mkdir_p'
	from /usr/share/ruby/fileutils.rb:226:in `reverse_each'
	from /usr/share/ruby/fileutils.rb:226:in `block in mkdir_p'
	from /usr/share/ruby/fileutils.rb:211:in `each'
	from /usr/share/ruby/fileutils.rb:211:in `mkdir_p'
	from /usr/share/gems/gems/fluentd-1.14.4/lib/fluent/supervisor.rb:654:in `run_supervisor'
	from /usr/share/gems/gems/fluentd-1.14.4/lib/fluent/command/fluentd.rb:352:in `<top (required)>'
	from /usr/share/gems/gems/fluentd-1.14.4/bin/fluentd:15:in `require'
	from /usr/share/gems/gems/fluentd-1.14.4/bin/fluentd:15:in `<top (required)>'
	from /usr/bin/fluentd:23:in `load'
	from /usr/bin/fluentd:23:in `<top (required)>'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli.rb:484:in `exec'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli.rb:25:in `start'
	from /usr/local/share/gems/gems/bundler-2.3.6/exe/bundle:48:in `block in <top (required)>'
	from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /usr/local/share/gems/gems/bundler-2.3.6/exe/bundle:36:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>'

will try the fix provided by @harshit-splunk

**Comment by anilchaithu** [comment]
Hi @harshit-splunk 

Tried redeploying with updated deamonset config. got the same error

`oc logs -f stageapi-splunk-splunk-kubernetes-logging-tdrqm
2022-04-15 13:59:21 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2022-04-15 13:59:21 +0000 [info]: gem 'fluentd' version '1.14.4'
2022-04-15 13:59:21 +0000 [info]: gem 'fluent-plugin-concat' version '2.4.0'
2022-04-15 13:59:21 +0000 [info]: gem 'fluent-plugin-jq' version '0.5.1'
2022-04-15 13:59:21 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.9.4'
2022-04-15 13:59:21 +0000 [info]: gem 'fluent-plugin-prometheus' version '2.0.1'
2022-04-15 13:59:21 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2022-04-15 13:59:21 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.2.10'
2022-04-15 13:59:21 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
bundler: failed to load command: fluentd (/usr/bin/fluentd)
/usr/share/gems/gems/fluentd-1.14.4/lib/fluent/supervisor.rb:656:in `rescue in run_supervisor': failed to create root directory:/tmp/fluentd, #<Errno::EROFS: Read-only file system @ dir_s_mkdir - /tmp/fluentd> (Fluent::InvalidRootDirectory)
        from /usr/share/gems/gems/fluentd-1.14.4/lib/fluent/supervisor.rb:653:in `run_supervisor'
        from /usr/share/gems/gems/fluentd-1.14.4/lib/fluent/command/fluentd.rb:352:in `<top (required)>'
        from /usr/share/gems/gems/fluentd-1.14.4/bin/fluentd:15:in `require'
        from /usr/share/gems/gems/fluentd-1.14.4/bin/fluentd:15:in `<top (required)>'
        from /usr/bin/fluentd:23:in `load'
        from /usr/bin/fluentd:23:in `<top (required)>'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli.rb:484:in `exec'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli.rb:31:in `dispatch'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli.rb:25:in `start'
        from /usr/local/share/gems/gems/bundler-2.3.6/exe/bundle:48:in `block in <top (required)>'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        from /usr/local/share/gems/gems/bundler-2.3.6/exe/bundle:36:in `<top (required)>'
        from /usr/local/bin/bundle:23:in `load'
        from /usr/local/bin/bundle:23:in `<main>'
/usr/share/ruby/fileutils.rb:247:in `mkdir': Read-only file system @ dir_s_mkdir - /tmp/fluentd (Errno::EROFS)
        from /usr/share/ruby/fileutils.rb:247:in `fu_mkdir'
        from /usr/share/ruby/fileutils.rb:228:in `block (2 levels) in mkdir_p'
        from /usr/share/ruby/fileutils.rb:226:in `reverse_each'
        from /usr/share/ruby/fileutils.rb:226:in `block in mkdir_p'
        from /usr/share/ruby/fileutils.rb:211:in `each'
        from /usr/share/ruby/fileutils.rb:211:in `mkdir_p'
        from /usr/share/gems/gems/fluentd-1.14.4/lib/fluent/supervisor.rb:654:in `run_supervisor'
        from /usr/share/gems/gems/fluentd-1.14.4/lib/fluent/command/fluentd.rb:352:in `<top (required)>'
        from /usr/share/gems/gems/fluentd-1.14.4/bin/fluentd:15:in `require'
        from /usr/share/gems/gems/fluentd-1.14.4/bin/fluentd:15:in `<top (required)>'
        from /usr/bin/fluentd:23:in `load'
        from /usr/bin/fluentd:23:in `<top (required)>'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli.rb:484:in `exec'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli.rb:31:in `dispatch'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/cli.rb:25:in `start'
        from /usr/local/share/gems/gems/bundler-2.3.6/exe/bundle:48:in `block in <top (required)>'
        from /usr/local/share/gems/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        from /usr/local/share/gems/gems/bundler-2.3.6/exe/bundle:36:in `<top (required)>'
        from /usr/local/bin/bundle:23:in `load'
        from /usr/local/bin/bundle:23:in `<main>'
`

**Comment by anilchaithu** [comment]
@harshit-splunk @matthewmodestino 

any suggestions on the next steps?

**Comment by vinzent** [comment]
@anilchaithu did you try the openshift example: https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/examples/openshift4-logging-only.yaml

**Comment by vinzent** [comment]
@anilchaithu for fluentd to be able to read logfiles it needs to run privileged on openshift. When running without privileged, SELinux will prevent access to the log files.

**Comment by anilchaithu** [comment]
@vinzent As @matthewmodestino suggested I have added **openshiftPrivilegedSccBinding: true** to the values file and deployed. But no luck.

Is there any other way?

**Comment by matthewmodestino** [comment]
@anilchaithu yeah, it is most certainly security context / environment settings related. Make sure you have enabled privileged bindings and applied the scc correctly. Otherwise, have you worked with your OpenShift team to review and advise?

**Comment by vinzent** [comment]
@anilchaithu I would suggest you to start with the example. this is known to work on openshift 4.  https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/examples/openshift4-logging-only.yaml

**Comment by matthewmodestino** [comment]
Did you take care to ensure you ran the ` oc adm policy add-scc-to-user privileged "system:serviceaccount:<project>:splunk-kubernetes-logging"` command against the right project and service account name? 

That's been a common stumbling block in the past for allowing the pods the proper privs.

**Comment by anilchaithu** [comment]
@vinzent will try the suggested example but I don't see any changes in the values file

**Comment by vinzent** [comment]
also check if multiple SCC apply to the service account. First one matching wins but order is undefined... upstream has deprecated the PodSecurityPolicy (which was probably a clone of SCC).
