### ISSUE TITLE
Splunk connect for Kubernetes stopped pulling data after moving from Docker to Container-d runtime

### ISSUE THREAD

**Issue by karuntech** [splunk/splunk-connect-for-kubernetes#748]
**What happened**:
After migrating from docker to container-runtime, Splunk Connect for Kuberentes is not pulling in data.

**What you expected to happen**:
Logs to flow as usual, without interruption

**How to reproduce it (as minimally and precisely as possible)**:
None of the logs produced by the containers in the container-d environment are being captured by Splunk Connect for Kubernetes

**Anything else we need to know?**:
Here is the error message:

2022-03-22 14:21:46 +0000 [warn]: #0 [containers.log] pattern not matched: "2022-03-22T09:21:33.26779623-05:00 stdout P 2022-03-22 14:21:33 +0000 [warn]: #0 [containers.log] pattern not matched: \"2022-03-22T09:21:25.765143286-05:00 stdout P 2022-03-22 14:21:25 +0000 [warn]: #0 [containers.log] pattern not matched: \\\"2022-03-22T09:21:10.977741447-05:00 stdout P

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`): Linux
- Splunk version: 8.1.4
- Splunk Connect for Kubernetes helm chart version: 1.4.9
- Others:

**Comment by harshit-splunk** [comment]
Hey @karuntech, your issue looks similar to https://github.com/splunk/splunk-connect-for-kubernetes/issues/599.

https://github.com/splunk/splunk-connect-for-kubernetes/blob/01bf0876e5f355b26825821a3b1d1a398cde4fde/helm-chart/splunk-connect-for-kubernetes/values.yaml#L101-L102

Change `logFormatType` from `json` to `cri`

**Comment by karuntech** [comment]
Yes, that worked. Thanks Harshit.
