### ISSUE TITLE
Cannot set consume_chunk_on_4xx_errors, "incompatible types for comparison"

### ISSUE THREAD

**Issue by szymonpk** [splunk/splunk-connect-for-kubernetes#754]
**What happened**:

When setting `global.splunk.hec.consume_chunk_on_4xx_errors` to anything else than `nil`, it fails with the following error:

```
Error: Failed to render chart: exit status 1: Error: template: splunk-kubernetes-logging/templates/daemonset.yaml:24:28: executing "splunk-kubernetes-logging/templates/daemonset.yaml" at <include (print $.Template.BasePath "/configMap.yaml") .>: error calling include: template: splunk-kubernetes-logging/templates/_helpers.tpl:165:12: executing "splunk-kubernetes-logging.should_consume_chunk_on_4xx_errors" at <ne .Values.global.splunk.hec.consume_chunk_on_4xx_errors nil>: error calling ne: incompatible types for comparison
```

It does not matter if I use a string `"false"`, bool `false` or any number `0`.

**What you expected to happen**:

Properly rendered chart.

**How to reproduce it (as minimally and precisely as possible)**:

Set `global.splunk.hec.consume_chunk_on_4xx_errors` and try to render/install the logging chart.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19
- Ruby version (use `ruby --version`): n/a
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Splunk version: n/a
- Splunk Connect for Kubernetes helm chart version: 1.4.14
- Others: Helm 3.6.1

**Comment by szymonpk** [comment]
@harshit-splunk 

```
$ helm upgrade splunk https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.4.14/splunk-kubernetes-logging-1.4.14.tgz --values test-case-values.yaml --dry-run --install
Release "splunk" does not exist. Installing it now.
Error: template: splunk-kubernetes-logging/templates/daemonset.yaml:24:28: executing "splunk-kubernetes-logging/templates/daemonset.yaml" at <include (print $.Template.BasePath "/configMap.yaml") .>: error calling include: template: splunk-kubernetes-logging/templates/_helpers.tpl:165:12: executing "splunk-kubernetes-logging.should_consume_chunk_on_4xx_errors" at <ne .Values.global.splunk.hec.consume_chunk_on_4xx_errors nil>: error calling ne: incompatible types for comparison

$ cat test-case-values.yaml 
global:
  splunk:
    hec:
      consume_chunk_on_4xx_errors: false
      host: foo.bar
```

If I remove 'host' it works. Basically, if I add anything except `consume...`, it works.

**Comment by harshit-splunk** [comment]
I am not sure why it's. not working for you. I installed SCK-1.4.13 and upgraded to SCK-1.4.14 with the command you have provided. I didn't receive any errors.

```
$ helm upgrade sck https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.4.14/splunk-kubernetes-logging-1.4.14.tgz --values my_values.yaml --dry-run --install
Release "sck" has been upgraded. Happy Helming!
```

**Comment by harshit-splunk** [comment]
Can you try a fresh install and see if it's working there?

**Comment by szymonpk** [comment]
@harshit-splunk maybe it is helm bug? Which version are you running?

**Comment by harshit-splunk** [comment]
I am using helm v3.8.1

**Comment by szymonpk** [comment]
Looks like it works with newer helm :/ We will resolve this internally then.

**Comment by harshit-splunk** [comment]
So, there must be bug within older version of helm itself.
Closing the issue now.

**Comment by szymonpk** [comment]
Thanks for the assistance debugging this.

**Comment by vinzent** [comment]
I also stumbled upon this issue. I was using Helm 3.3.4 from Red Hat. Upgraded to Helm 3.6.2 provided by Red Hat (ocp-tools-4.8-for-rhel-8-x86_64 repo). Now it works.
