### ISSUE TITLE
splunk-connect-for-kubernetes pod is only running on the worker nodes

### ISSUE THREAD

**Issue by prageetika** [splunk/splunk-connect-for-kubernetes#755]
**What happened**:
I've tried with splunk-connect-for-kubernetes v 1.4.12 and 1.4.14, splunk-connect-for-kubernetes pod is only running on the worker nodes
**What you expected to happen**:
splunk-connect-for-kubernetes pod is only running on all the nodes 

**How to reproduce it (as minimally and precisely as possible)**:
helm install splunk-kubernetes-logging -f values.yaml https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.4.12/splunk-connect-for-kubernetes-1.4.12.tgz

**Anything else we need to know?**:
[root@ip-10-93-56-106 ~]# oc get po
NAME                              READY   STATUS    RESTARTS   AGE
splunk-kubernetes-logging-xxxx  1/1     Running   0          13m
splunk-kubernetes-logging-xxxx   1/1     Running   0          13m
[root@ip-10-93-56-106 ~]#

I've 15 nodes with different node roles, and  splunk-kubernetes-logging is only running on the worker role nodes. 

**Environment**:
- openshift 4.8.35
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version:
- 1.4.11
- Others:

**Comment by prageetika** [comment]
Found the issue.. It was a configuration mistake.

**Comment by nitinsinghit** [comment]
@prageetika can you share what config you used to install splunk-connect-kubernetes on all nodes? I have currently installed on master and worker nodes or I will say every-time I  install splunk-connect-kubernetes only master and worker nodes have running splunk-kubernetes-logging pods. None of the infra nodes have pods running for splunk-kubernetes-logging.
Thanks
Nitin

**Comment by nitinsinghit** [comment]
> @prageetika can you share what config you used to install splunk-connect-kubernetes on all nodes? I have currently installed on master and worker nodes or I will say every-time I install splunk-connect-kubernetes only master and worker nodes have running splunk-kubernetes-logging pods. None of the infra nodes have pods running for splunk-kubernetes-logging. Thanks Nitin



> Found the issue.. It was a configuration mistake.

@prageetika can you share what config you used to install splunk-connect-kubernetes on all nodes? I have currently installed on master and worker nodes or I will say every-time I install splunk-connect-kubernetes only master and worker nodes have running splunk-kubernetes-logging pods. None of the infra nodes have pods running for splunk-kubernetes-logging.
Thanks
Nitin

**Comment by vinzent** [comment]
For the records: 

If nodes have custom taints, like normally openshift infra-nodes have, the SCK pods need to be configured with tolerations.

Example helm-values for logging pod tolerations. It matches any taint on a node ("universal toleration").

```yaml
splunk-kubernetes-logging:
  tolerations:
  - operator: Exists
```
