### ISSUE TITLE
hardening by the securityContext

### ISSUE THREAD

**Issue by briner** [splunk/splunk-connect-for-kubernetes#760]
**What would you like to be added**:

I've seen that the daemonset and the derived pods are using the:
- securityContext: Privileged
- runAsUser: 0

This give great privileges to the pods.

Could you work on hardening these pods by restricting as much the securityContext.

**Why is this needed**:

The moto of the security is : less is more.

**Informations**:

This ticket has a relation with #761

**Comment by vinzent** [comment]
if you move to pos files to ephemeral volumes, every time a pod gets recreated, all logs will be re-read and re-sent to splunk, 

on OpenShift privileged is also required to overrule SELinux restrictions.

**Comment by tangoFoxtrott** [comment]
yeah, i just figured out the hard way that it is not so simple ;-)

I wonder whether there is a way to "fix" this at all. And I do wonder whether the problem with this is as big as I imagine it to be.

**Comment by harshit-splunk** [comment]
In Opentelemetry collector, they have mounted host directory to the deamonset and stored checkpoints there. Also, they are using the init container with root privileges and provided read access to non-root use. 

https://github.com/signalfx/splunk-otel-collector-chart/blob/99fa46a0c5e6f3158aa835a101fe9c173d01ef60/helm-charts/splunk-otel-collector/templates/daemonset.yaml#L135-L175
