### ISSUE TITLE
explain why the securityContext Privileged is needed

### ISSUE THREAD

**Issue by briner** [splunk/splunk-connect-for-kubernetes#761]
**What would you like to be added**:
Reading the documentation, I did not find why the:
- securityContext: Privileged 
- runAsUser: 0
are needed.

I do think, that the fluentd tool need to read all the containers logs, and that it need to find a way to catalog the containers to find out in which namespace, pods it runs and what are the label and annotations on these elements.

Could you provide in you documentation a brief summary on why you need such privilege.

**Why is this needed**:

The security teams often needs to understand the reason/motivation to allow privileged pods to run on the infrastructure.

**Informations**:

This ticket has a relation with #760

**Comment by harshit-splunk** [comment]
Closing this issue as the discussion has started in issue #760. It will be easier to track only one issue.
