### ISSUE TITLE
metric_name:kube.container.cpu.usage

### ISSUE THREAD

**Issue by ShimingLee** [splunk/splunk-connect-for-kubernetes#766]
Some pod lack of `metric_name:kube.container.cpu.usage` item, is there any way to get it to show  ？

**Comment by harshit-splunk** [comment]
Hi @ShimingLee, SCK will collect and send all the metrics that it receives from the API. `kube.container.cpu.usage` is collected from the `/stats/summary` endpoint. It doesn't filter any metrics.

Can you specify which k8s distro you are using? And do you see any error logs for metric pod?
