### ISSUE TITLE
"splunk-kubernetes-metrics.should_consume_chunk_on_4xx_errors" at <ne .Values.splunk.hec.consume_chunk_on_4xx_errors nil>: error calling ne: invalid type for comparison

### ISSUE THREAD

**Issue by chenli-appD** [splunk/splunk-connect-for-kubernetes#767]
**What happened**:
I am seeing error when deployed splunk helm chart.

`Error: template: splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/deploymentMetricsAggregator.yaml:35:28: executing "splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/deploymentMetricsAggregator.yaml" at <include (print $.Template.BasePath "/configMapMetricsAggregator.yaml") .>: error calling include: template: splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/_helpers.tpl:71:7: executing "splunk-kubernetes-metrics.should_consume_chunk_on_4xx_errors" at <ne .Values.splunk.hec.consume_chunk_on_4xx_errors nil>: error calling ne: invalid type for comparison`

I followed instruction of this [thread](https://github.com/bitnami/charts/issues/1007) to change _helpers.tpl and fixed the issue.

```
-{{- if ne .path "/" -}}
+{{- if (.path) and ne .path "/" -}}
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Deployed with helm 3 with command in README.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version: 1.4.15
- Splunk Connect for Kubernetes helm chart version: 1.4.15
- Others:

**Comment by harshit-splunk** [comment]
Hi, there was a bug in the older version of the helm. If you update your helm version, you will not face this issue ( https://github.com/splunk/splunk-connect-for-kubernetes/issues/754 )
