### ISSUE TITLE
Splunk Connect for Kubernetes - 'Pattern Not Matched' errors on AWS EKS 1.21 and Azure AKS 1.21

### ISSUE THREAD

**Issue by akandimalla** [splunk/splunk-connect-for-kubernetes#771]
What Happened: 
When installed Splunk Connect for Kubernetes via helm on both AWS EKS and Azure AKS we are beginning to see the following errors

`2022-05-24 07:10:20 +0000 [warn]: #0 [containers.log] pattern not matched: "2022-05-24T07:10:08.200551701Z stdout F \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\""
2022-05-24 07:10:20 +0000 [warn]: #0 [containers.log] pattern not matched: "2022-05-24T07:10:08.200555911Z stdout F 2022-05-24 07:10:08 +0000 [warn]: #0 [containers.log] pattern not matched: \"2022-05-24T07:10:02.2374453Z stdout F \\\\\\\"\""
`

**What you expected to happen**: The logs get onboarded to splunk

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: AWS-EKS and Azure AKS
- Kubernetes version (use `kubectl version`):1.21.7
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`): Amazon Linux in AWS and Ubuntu 18.0.x in Azure and we ar using docker 
- Splunk version: Splunk Enterprise.
- Splunk Connect for Kubernetes helm chart version: 1.4.14
- Others:
Read many of the links given below. None of the addressed the issue for AWS EKS and AKS

1. https://github.com/splunk/splunk-connect-for-kubernetes/issues/599
2. https://github.com/splunk/splunk-connect-for-kubernetes/issues/604
3. https://github.com/fluent/fluentd/issues/2407
4. https://github.com/fluent/fluentd/issues/2545
5. https://github.com/splunk/splunk-connect-for-kubernetes/issues/700

**Comment by vinzent** [comment]
please share your values.yaml

did you enable cri logging format? https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/values.yaml#L104

**Comment by akandimalla** [comment]
@vinzent  - Here is my values.yaml 

`global:
  logLevel: info
  splunk:
    # Configuration for HEC (HTTP Event Controller)
    hec:
      # host is required and should be provided by user
      host: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      # port to HEC, optional, default 8088
      port: 443
      # token is required and should be provided by user
      token:  xxxxxxxxxxxxxxxxxxxxx
      # protocol has two options: "http" and "https", default is "https"
      protocol: https
      # indexName tells which index to use, this is optional. If it's not present, will use "main".
      indexName: eks-default
      # insecureSSL is a boolean, it indicates should it allow inscure SSL connection (when protocol is "https"). Default is false.
      insecureSSL: true
`

Yes, I enabled CRI in the splunk-connect-for-kubernetes/values.yaml 

Here is how I install and upgrade it. 

helm install splunk-connect -f values.yaml splunk-connect-for-kubernetes -n splunk-connect
helm upgrade splunk-connect -f values.yaml splunk-connect-for-kubernetes -n splunk-connect

**Comment by vinzent** [comment]
I do not see `logFromatType: cri` in your shared values.yaml string.

**Comment by akandimalla** [comment]
@vinzent - I think I figured out the issue. It's related to `logFromatType: cri` 

Thanks for the assistance.

**Comment by Alpanakabra** [comment]
@akandimalla  can you please how did you fix the issue i am having the same issue but i am using manifests

**Comment by akandimalla** [comment]
logFromatType: cri
