### ISSUE TITLE
Install Splunk, run in a container on Openshift Cluster

### ISSUE THREAD

**Issue by Shilpi0306** [splunk/splunk-connect-for-kubernetes#772]
I need help on how to install splunk on Openshift cluster. Could you please provide the documentation on complete steps as well as pre-requisite info? What should be the system requirements etc. I am new to Splunk and working first time on it. Kindly assist.

Its a project requirement. I have to run splunk in a container on Openshift Cluster for 40 TB data consumption on daily basis. Thanks.

**Comment by aryznar-splunk** [comment]
Hi,
Splunk Connect for Kubernetes is intended to collect data from Kubernetes and push them to Splunk. It is nothing to do with installing Splunk itself in Openshift cluster. Please clarify if you would like to install Splunk on Openshift or Splunk Connect for Kubernetes on Openshift?

**Comment by Shilpi0306** [comment]
My client is having separate Splunk and Kubernetes set ups. Now, I got the requirement where I need to run splunk in containerized form on Kubernetes/Openshift/GKE cluster. I need to install and run all components in containerized form like Splunk Cluster installation, Indexing Cluster at least 100, license master, deployer, Seachhead cluster, deployment server, UF etc and need to collect the logs and metrics. It would be a very huge set up to capture logs for 40TB daily transactions. Hope I am able to clarify the requirement now. Could you please assist how I can proceed to achieve same?
