### ISSUE TITLE
After updating kubernetes I am unable to start Splunk connect for k8s pods.

### ISSUE THREAD

**Issue by AH0000** [splunk/splunk-connect-for-kubernetes#774]
When I changed the version of Kubernetes, three pods of SplunkConnect logging, objects, and metrics-argg of SplunkConnect with the following error and cannot be started.
How can I work around this error?

Kubernetes version
- Before change: 1.18.14
- After change: 1.23.5

SplunkConnect version
- 1.4.15

Error Description
- 2022-06-07 03:18:49 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"	
- 2022-06-07 03:18:49 +0000 [info]: gem 'fluentd' version '1.14.6'	
- 2022-06-07 03:18:49 +0000 [info]: gem 'fluent-plugin-concat' version '2.4.0'	
- 2022-06-07 03:18:49 +0000 [info]: gem 'fluent-plugin-jq' version '0.5.1'	
- 2022-06-07 03:18:49 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.9.4'	
- 2022-06-07 03:18:49 +0000 [info]: gem 'fluent-plugin-prometheus' version '2.0.2'	
- 2022-06-07 03:18:49 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'	
- 2022-06-07 03:18:49 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.2.13'	
- 2022-06-07 03:18:49 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'	
- bundler: failed to load command: fluentd (/usr/bin/fluentd)	
- /usr/share/ruby/net/protocol.rb:44:in `connect_nonblock': SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello (OpenSSL::SSL::SSLError)	
- 	from /usr/share/ruby/net/protocol.rb:44:in `ssl_socket_connect'
- 	from /usr/share/ruby/net/http.rb:1009:in `connect'
- 	from /usr/share/ruby/net/http.rb:943:in `do_start'
- 	from /usr/share/ruby/net/http.rb:932:in `start'
- 	from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
- 	from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
- 	from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
- 	from /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/resource.rb:51:in `get'
- 	from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:522:in `block in api'
- 	from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:121:in `handle_exception'
- 	from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:522:in `api'
- 	from /usr/share/gems/gems/kubeclient-4.9.3/lib/kubeclient/common.rb:515:in `api_valid?'
- 	from /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.9.4/lib/fluent/plugin/filter_kubernetes_metadata.rb:278:in `configure'
- 	from /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/plugin.rb:187:in `configure'
- 	from /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/agent.rb:154:in `add_filter'
- 	from /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/agent.rb:72:in `block in configure'
- 	from /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/agent.rb:64:in `each'
- 	from /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/agent.rb:64:in `configure'
- 	from /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/label.rb:31:in `configure'
- 	from /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/root_agent.rb:146:in `block in configure'
- 	from /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/root_agent.rb:146:in `each'
- 	from /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/root_agent.rb:146:in `configure'
- 	from /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/engine.rb:105:in `configure'
- 	from /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/engine.rb:80:in `run_configure'
- 	from /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/supervisor.rb:668:in `run_supervisor'
- 	from /usr/share/gems/gems/fluentd-1.14.6/lib/fluent/command/fluentd.rb:356:in `<top (required)>'
- 	from /usr/share/gems/gems/fluentd-1.14.6/bin/fluentd:15:in `require'
- 	from /usr/share/gems/gems/fluentd-1.14.6/bin/fluentd:15:in `<top (required)>'
- 	from /usr/bin/fluentd:23:in `load'
- 	from /usr/bin/fluentd:23:in `<top (required)>'
- 	from /usr/local/share/gems/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `load'
- 	from /usr/local/share/gems/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
- 	from /usr/local/share/gems/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:23:in `run'
- 	from /usr/local/share/gems/gems/bundler-2.3.12/lib/bundler/cli.rb:483:in `exec'
- 	from /usr/local/share/gems/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
- 	from /usr/local/share/gems/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
- 	from /usr/local/share/gems/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
- 	from /usr/local/share/gems/gems/bundler-2.3.12/lib/bundler/cli.rb:31:in `dispatch'
- 	from /usr/local/share/gems/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
- 	from /usr/local/share/gems/gems/bundler-2.3.12/lib/bundler/cli.rb:25:in `start'
- 	from /usr/local/share/gems/gems/bundler-2.3.12/exe/bundle:48:in `block in <top (required)>'
- 	from /usr/local/share/gems/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
- 	from /usr/local/share/gems/gems/bundler-2.3.12/exe/bundle:36:in `<top (required)>'
- 	from /usr/local/bin/bundle:23:in `load'
- 	from /usr/local/bin/bundle:23:in `<main>'
-

**Comment by harshit-splunk** [comment]
Which k8s distro are you using? Can you also share values.yaml file?

**Comment by harshit-splunk** [comment]
Closing the issue since it is inactive for a long time. Feel free to reopen this issue or create new one.
