### ISSUE TITLE
Exporting Openshift Prometheus Metrics to Splunk

### ISSUE THREAD

**Issue by Animeshkamble** [splunk/splunk-connect-for-kubernetes#782]
**What happened**:
We are trying to push prometheus metircs to splunk via splunk connect, but after making changes and restarting pods we are not seeing metrics in splunk
**What you expected to happen**:
We have artemis amq broker deployed on openshift and we have exposed amq metrics to prometheus, we would like to get all the amq metrics exported to splunk via splunk connect
**How to reproduce it (as minimally and precisely as possible)**:
We are using below yaml files which are currently deployed via fluxcd
Base yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: splunk-connect
  namespace: splunk-connect
spec:
  releaseName: splunk-connect
  chart:
    spec:
      chart: splunk-connect-for-kubernetes
      sourceRef:
        kind: HelmRepository
        name: splunk-connect
        namespace: flux-system
  interval: 1m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/values.yaml
  values:
    global:
      logLevel: info
    splunk-kubernetes-logging:
      image:
        registry: dockerhub.artifactory.davita.com
      splunk:
        hec:
          indexName: openshift
      podSecurityPolicy:
        create: true
      rbac:
        openshiftPrivilegedSccBinding: true
      kubernetes:
        securityContext: true
      containers:
        logFormatType: cri
        logFormat: "%Y-%m-%dT%H:%M:%S.%N%:z"
    splunk-kubernetes-objects:
      enabled: true
      image:
        registry: dockerhub.artifactory.davita.com
      splunk:
        hec:
          indexName: openshift-objects
      podSecurityPolicy:
        create: true
      rbac:
        openshiftPrivilegedSccBinding: true
      kubernetes:
        securityContext: true
    splunk-kubernetes-metrics:
      enabled: true
      image:
        registry: dockerhub.artifactory.davita.com
      splunk:
        hec:
          indexName: openshift-metrics
      podSecurityPolicy:
        create: true
      rbac:
        openshiftPrivilegedSccBinding: true
      kubernetes:
        securityContext: true

Environment specific yaml merged with base using flux
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: splunk-connect
  namespace: splunk-connect
spec:
  releaseName: splunk-connect
  chart:
    spec:
      version: 1.4.14

  # Default values
  # https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/values.yaml
  values:
    global:
      logLevel: info
      splunk:
        hec:
          # host is required and should be provided by user
          host: sea1l2splua02.davita.corp
          # port to HEC, optional, default 8088
          port: 8088
          # token is required and should be provided by user
          token: e7f9aef5-a108-43ee-ad83-3bce0a1ab034
          insecureSSL: true
      prometheus_enabled: true
      monitoring_agent_enabled: true
      monitoring_agent_index_name: openshift-metrics
      metrics:
       service:
         enabled: true
         headless: true
      serviceMonitor:
        enabled: true

        metricsPort: 24231
        interval: ""
        scrapeTimeout: "120s"

        additionalLabels: { }

      kubernetes:
        clusterName: sbx
        openshift: true
    splunk-kubernetes-logging:
      enabled: true
      splunk:
        hec:
          token: e7f9aef5-a108-43ee-ad83-3bce0a1ab034
    splunk-kubernetes-objects:
      enabled: true
      splunk:
        hec:
          token: d73deb09-de51-4379-b253-c4ac2abf4869
    splunk-kubernetes-metrics:
      enabled: true
      splunk:
        hec:
          token: d73deb09-de51-4379-b253-c4ac2abf4869
          insecureSSL: true
      kubernetes:
        openshift: true
        useRestClientSSL: true
        insecureSSL: true

**Anything else we need to know?**:

**Environment**: Openshift
- Kubernetes version (use `kubectl version`):  Kubernetes 1.23
- Ruby version (use `ruby --version`): NA
- OS (e.g: `cat /etc/os-release`): RHCOS
- Splunk version: 8.2.3.2
- Splunk Connect for Kubernetes helm chart version: 1.4.14
- Others:

**Comment by harshit-splunk** [comment]
Hi @Animeshkamble, SCK cannot scrape metrics from the Prometheus endpoint. Maybe you can move to [SCK OTel](https://github.com/signalfx/splunk-otel-collector-chart) that supports collecting metrics from the Prometheus endpoint.

Migration guide: https://github.com/signalfx/splunk-otel-collector-chart/blob/main/docs/migration-from-sck.md
