### ISSUE TITLE
Fluentd metrics plugin issue - Splunk does not show actual value but just "metric" string for all metrics

### ISSUE THREAD

**Issue by f6fss** [splunk/splunk-connect-for-kubernetes#786]
We are using Fluentd metrics plugin to send data into our Splunk environment. I wonder if there is any config/settings issue from our end? Please see our settings at bottom.

**What happened**: Metric data shows "metric" word (string) instead of actual metrics

**What you expected to happen**: Metric data shows actual meaningful metric

**How to reproduce it (as minimally and precisely as possible)**: N/A

**Anything else we need to know?**:

![image](https://user-images.githubusercontent.com/83304017/178552343-25dc2264-6cdc-4846-89fd-22ba17b059dd.png)

**Environment**:
- Openshift 4.8
- OS (e.g: `cat /etc/os-release`):
- Splunk version: 8.1.4
- Splunk Connect for Kubernetes helm chart version: 1.3.5
- Others:

<match kube.**>
    @type splunk_hec
    data_type metric
    metric_name_key "metric_name"
    metric_value_key "value"
    protocol https
    hec_host "XXXXXXX"
    hec_port 8088
    consume_chunk_on_4xx_errors true
    hec_token xxxxxx
    host "ose-dev45-kxzgv-master-2"
    index "rd_openshift_metrics"
    source "${tag}"
    sourcetype "kube:metrics"
    insecure_ssl true
    app_name "splunk-kubernetes-metrics"
    app_version "1.4.15"

**Comment by harshit-splunk** [comment]
You need to create metric index. Select `Metrics` index data type and provide that index in config.
For example:
```
splunk-kubernetes-metrics:
  enabled: true
  splunk:
    hec:
      indexName: metric_index
```

Refer following image for creating metric index.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/89519921/178656038-0710340f-05cb-48e5-9dab-2f096ede4aba.png">
