### ISSUE TITLE
customFilters for sourcetype override don't seem to be working

### ISSUE THREAD

**Issue by burchfjt** [splunk/splunk-connect-for-kubernetes#788]
Unable to get customerFilters in SCK ( version 1.4.15 ) to work...

I’m upgrading from a very customized older version of SCK and need to change the sourcetyping to how we currently have it deployed in the ~8 other k8s environments ( then upgrade them to latest SCK )

The current default sourcetypes in SCK is “kube:container:<container_name>”

But that is too granular ( would generate over 1000+ sourcetypes )

Our current deployments we just have/need   “kubec:<namespace_name>”    for the sourcetype to match our existing implementations.

Tried several different variations of a jq_transformer or record_modifier in the customFilter… but it either doesn’t work or errors out and the pod goes into CrashLoop

Is there a way to get customFilters to do this... or am i forced to generate the manifest files ( which i can change the dynamic sourcetyping to what i need ) from helm and just deploy those versus helm ??

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.2
- OS (e.g: `cat /etc/os-release`): CentOS
- Splunk version: 8.2.3
- Splunk Connect for Kubernetes helm chart version: 1.4.15

**Comment by harshit-splunk** [comment]
Maybe you can set namespace as `sourcetype_key`
https://github.com/splunk/splunk-connect-for-kubernetes/blob/ebc676a32b911a5238710775990515de1f6cce4f/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L427

Alternatively you can use customFIlters
