### ISSUE TITLE
Broken links in the README

### ISSUE THREAD

**Issue by tioumen** [splunk/splunk-connect-for-kubernetes#8]
Links in the README are broken.

**Comment by dbaldwin-splunk** [comment]
@jenworthington Can you follow up and check on the readme links.  @tioumen Was there a specific reference that wasn't working for you?

**Comment by jenworthington** [comment]
I just manually tested all the links in the README. they all work. Was it another readme by any chance? If you can send me in the right direction, i'm happy to fix whatever is broken

**Comment by abisnar** [comment]
https://github.com/splunk/splunk-connect-for-kubernetes/blob/master/helm-chart/splunk-connect-for-kubernetes/README.md check the last 3 links here I believe the pathing is off
