### ISSUE TITLE
Not getting pod health

### ISSUE THREAD

**Issue by oarusoft** [splunk/splunk-connect-for-kubernetes#807]
I am not seeing pod health like pod counts, pod restarts, etc.

Or is this already there? can someone please advice.

Also how can I see all the data this collector is collecting without using mstats?
I want to do something like Index=xyz_metrics

Thank You

**Comment by harshit-splunk** [comment]
Hi @oarusoft, SCK doesn't collect pod counts/pod restarts as metrics. Here is the list of all collected metrics: https://github.com/splunk/fluent-plugin-kubernetes-metrics/blob/develop/metrics-information.md

But you can monitor pods/deployments by enabling splunk-kubernetes-objects.
https://github.com/splunk/splunk-connect-for-kubernetes/blob/15d8023c3669cdd430f29ccbe0181baa2ecc0a63/helm-chart/splunk-connect-for-kubernetes/values.yaml#L650-L703

**Comment by aryznar-splunk** [comment]
Please reopen ticket when proposed solution do not work for you.

**Comment by oarusoft** [comment]
> 

@harshit-splunk I am bit confused. Am Isuppose to use splunk-otel-collector-chart or "splunk-connect-for-kubernetes"
Can you please advice which one to use.

Thank You.

**Comment by harshit-splunk** [comment]
You should migrate to splunk-otel-collector-chart as we are planning to deprecate SCK in future.

**Comment by oarusoft** [comment]
Thanks @harshit-splunk for info.

One quick question. How can I enable splunk-kubernetes-objects from helm?
I am looking for helm that will enable all the features like Logging, Metrics and Objects.

Thank You.
