### ISSUE TITLE
splunk-kubernetes-logging won't collect application logs

### ISSUE THREAD

**Issue by whigley** [splunk/splunk-connect-for-kubernetes#814]
**What happened**:
splunk-kubernetes-logging collects kubernetes container logs, but it does not for application container logs

**What you expected to happen**:
See my application container logs 

**How to reproduce it (as minimally and precisely as possible)**:
Use the default splunk-kubernetes-logging.
for log path, I tried both:
/var/log/containers/*.log
or
/var/log/pods/*.log

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.23
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`): Linux
- Splunk version: 9.0.1 (latest)
- Splunk Connect for Kubernetes helm chart version: 1.5.0 & develop branch
- Others:

**Comment by harshit-splunk** [comment]
Hi @whigley, what do you mean by application container logs? splunk-kubernetes-logging is built to collect logs from kubernetes container only.

**Comment by whigley** [comment]
yes, I am looking to collect application logs which run into EKS cluster.
