### ISSUE TITLE
Helm package

### ISSUE THREAD

**Issue by NBRAZ22** [splunk/splunk-connect-for-kubernetes#815]
My dev team will be performing an upgrade to SCK v1.5 and would like to know where to locate the Helm package and how to install

From dev:
“I got this downloaded from github but we need helm package of v1.5 downloaded from splunk account since we use helm package to install from Rafay which I need help since I don't have an account so that i can use this to install splunk connect in Q1 and plan to get this to prod next weekend.”

**Comment by harshit-splunk** [comment]
It is documented here: https://github.com/splunk/splunk-connect-for-kubernetes#deploy-with-helm
