### ISSUE TITLE
How we can send kubernetes audit logs to splunk in puppet

### ISSUE THREAD

**Issue by kavita1205** [splunk/splunk-connect-for-kubernetes#820]
Hi Team,

How we can send kubernetes audit logs to splunk if we are using puppet. We are using below configurations , so in case of sending audit logs what would be the configurations here. Can someone please help me here.

```
# SplunkForwarder file input parameters
profile::splunkforwarder::input_files_parameters_sections:
  'syslog-input':
    section: 'monitor:///var/log/syslog'
    setting: 'disabled'
    value: '0'
    tag: 'splunk_input_syslog'
  'syslog-index':
    section: 'monitor:///var/log/syslog'
    setting: 'index'
    value: 'ml_logs'
    tag: 'splunk_input_syslog'
```

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.24
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version: 8.0.0
- Splunk Connect for Kubernetes helm chart version: 1.4.15
- Others:

**Comment by kavita1205** [comment]
@matthewmodestino can you please help me here.

**Comment by matthewmodestino** [comment]
This appears to have nothing to do with connect for kubernetes (fluentd) ??? 

Splunk doesn't provide customers support for puppet, and it looks like you are asking how to configure the universal forwarder??
