### ISSUE TITLE
Support index annotations per namespace - but for Metric Indexes

### ISSUE THREAD

**Issue by barronen1** [splunk/splunk-connect-for-kubernetes#822]
Hi,

from the doc page "Managing SCK Log Ingestion by Using Annotations" using this command:

`kubectl annotate namespace kube-system splunk.com/index=k8s_events`

It's possible to seperate to different indexes per namespace, but it does work only for event indexes - not for object event index OR metric index.

Bar

**Comment by harshit-splunk** [comment]
Is there a specific use case where you need index routing for objects or metrics?

**Comment by barronen1** [comment]
We want to give each customer only his namespace data for all openshift indexes, separated by namespace, for permission management

**Comment by omerbeni** [comment]
Is there anything new about this?
