### ISSUE TITLE
ingest custom log sources with custom index names

### ISSUE THREAD

**Issue by AtulSinghMothi** [splunk/splunk-connect-for-kubernetes#827]
Hello Team,
Our application is deployed on multiple VMs and application is generating multiple log files. UFs are installed on all VMs and log1 is indexed with index=log1,log2 is indexed with index=log2 etc.

Now, VMs are going to be replaced by kubernetes and it is expected that log generation is going to remain same. Could you please advise how can I assign index=log1 for log1,index=log2 for log2 etc.

Thank you!

**Comment by harshit-splunk** [comment]
You can add `splunk.com/index` pod annotation. SCK will automatically send logs to index defined in `splunk.com/index`.

You can refer [doc](https://github.com/splunk/splunk-connect-for-kubernetes#managing-sck-log-ingestion-by-using-annotations) for detailed information.

**Comment by Kiyoshi-Miyake** [comment]
Hi harshit-splunk,
Your sugestion is helpful me too. thanks!
but, i tried to set these annotation, but, these are overwridden by the following parts.

```
      # extract pod_uid and container_name for CRIO runtime
      {{- if eq .Values.containers.logFormatType "cri" }}
      <filter tail.containers.var.log.pods.**>
        @type jq_transformer
        jq '.record | . + (.source | capture("/var/log/pods/(?<pod_uid>[^/]+)/(?<container_name>[^/]+)/(?<container_retry>[0-9]+).log")) | .sourcetype = ("{{ .Values.sourcetypePrefix }}:container:" + .container_name) | .splunk_index = {{ or .Values.global.splunk.hec.indexName .Values.splunk.hec.indexName | default "main" | quote }}'
      </filter>
      {{- end }}

```
[templates/configMap.yaml line 308...](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L266:~:text=%23%20extract%20pod_uid%20and%20container_name%20for%20CRIO%20runtime)

Do I need to remove the matching of regex for these sourcetype, index from the line?

Thanks!

**Comment by harshit-splunk** [comment]
Hey @Kiyoshi-Miyake, that is actually a bug. It's a good catch. I would love if you raise a PR to fix this :)

**Comment by Kiyoshi-Miyake** [comment]
Hi @harshit-splunk, I created [the PR](https://github.com/splunk/splunk-connect-for-kubernetes/pull/833).
Can you check it. It is confilict with [my another PR](https://github.com/splunk/splunk-connect-for-kubernetes/pull/831)
