### ISSUE TITLE
Can HEC be configured to talk to 2 indexers?

### ISSUE THREAD

**Issue by achilu** [splunk/splunk-connect-for-kubernetes#829]
Can HEC be configured to talk to 2 or more indexers? Per the below template, we pass 1 host ..can we pass an array ?
global:
  splunk:
    hec:
      protocol: https
      insecureSSL: true
      token: **********
      host: *.*.*.*
      port: *****
      indexName: *********

example as below?
global:
  splunk:
    hec:
      protocol: https
      insecureSSL: true
      token: **********
      host
      - *.*.*.*
      - *.*.*.*
      port: *****
      indexName: *********

**Comment by harshit-splunk** [comment]
No, it can be configured to send to one indexer only. Is there any specific requirements for sending events to multiple host?

**Comment by achilu** [comment]
with multiple indexers being available
sending events to only one host can overload it right?

**Comment by eperezvcc** [comment]
@achilu can you use a load balancer to point to? or a service if you are on kubernetes? something that somehow would distribute the load coming from the forwarders.
