### ISSUE TITLE
EKS cluster is not showing logs for some apps. Turns out some of are going to this namespace called ".Orphaned"

### ISSUE THREAD

**Issue by aseemand** [splunk/splunk-connect-for-kubernetes#842]

**Comment by aseemand** [comment]
Values.yml file :: 

USER-SUPPLIED VALUES:
global:
  kubernetes:
    clusterName: eks-ist-prd
  logLevel: info
  metrics:
    service:
      enabled: true
      headless: true
  monitoring_agent_enabled: null
  monitoring_agent_index_name: null
  prometheus_enabled: null
  serviceMonitor:
    additionalLabels: {}
    enabled: false
    interval: ""
    metricsPort: 24231
    scrapeTimeout: 10s
  splunk:
    hec:
      caFile: null
      clientCert: null
      clientKey: null
      consume_chunk_on_4xx_errors: null
      fullUrl: null
      host: http-inputs-esri.splunkcloud.com
      indexName: esri_kube_prd
      indexRouting: null
      insecureSSL: null
      port: 443
      protocol: https
      token: PLACEHOLDER
splunk-kubernetes-logging:
  affinity: {}
  buffer:
    '@type': memory
    chunk_limit_records: 100000
    chunk_limit_size: 20m
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 10
    retry_type: periodic
    retry_wait: 30
    total_limit_size: 600m
  charEncodingUtf8: false
  containers:
    localTime: false
    logFormat: null
    logFormatType: json
    path: /var/log
    pathDest: /var/lib/docker/containers
    refreshInterval: null
    removeBlankEvents: true
  customFilters: {}
  customMetadata: null
  customMetadataAnnotations: null
  enabled: true
  environmentVar: null
  extraVolumeMounts: []
  extraVolumes: []
  fluentd:
    exclude_path: null
    path: /var/log/containers/*.log
  image:
    name: splunk/fluentd-hec
    pullPolicy: IfNotPresent
    pullSecretName: null
    registry: docker.io
    tag: 1.2.12
    usePullSecret: false
  indexFields: []
  journalLogPath: /run/log/journal
  k8sMetadata:
    cache_ttl: 3600
    podLabels:
    - app
    - k8s-app
    - release
    watch: true
  kubernetes:
    clusterName: null
    securityContext: false
  logLevel: null
  logs:
    dns-controller:
      from:
        pod: dns-controller
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:dns-controller
    dns-sidecar:
      from:
        container: sidecar
        pod: kube-dns
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kubedns-sidecar
    dnsmasq:
      from:
        pod: kube-dns
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:dnsmasq
    docker:
      from:
        journald:
          unit: docker.service
      sourcetype: kube:docker
    etcd:
      from:
        container: etcd-container
        pod: etcd-server
    etcd-events:
      from:
        container: etcd-container
        pod: etcd-server-events
    etcd-minikube:
      from:
        container: etcd
        pod: etcd-minikube
    kube-apiserver:
      from:
        pod: kube-apiserver
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kube-apiserver
    kube-audit:
      from:
        file:
          path: /var/log/kube-apiserver-audit.log
      sourcetype: kube:apiserver-audit
      timestampExtraction:
        format: '%Y-%m-%dT%H:%M:%SZ'
    kube-controller-manager:
      from:
        pod: kube-controller-manager
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kube-controller-manager
    kube-dns-autoscaler:
      from:
        container: autoscaler
        pod: kube-dns-autoscaler
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kube-dns-autoscaler
    kube-proxy:
      from:
        pod: kube-proxy
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kube-proxy
    kube-scheduler:
      from:
        pod: kube-scheduler
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kube-scheduler
    kubedns:
      from:
        pod: kube-dns
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kubedns
    kubelet:
      from:
        journald:
          unit: kubelet.service
      multiline:
        firstline: /^\w[0-1]\d[0-3]\d/
      sourcetype: kube:kubelet
  nodeSelector:
    beta.kubernetes.io/os: linux
  podAnnotations: null
  podSecurityPolicy:
    apiGroup: policy
    apparmor_security: true
    create: false
  priorityClassName: null
  rbac:
    create: true
    openshiftPrivilegedSccBinding: false
  resources:
    limits:
      cpu: 50m
      memory: 400Mi
    requests:
      cpu: 45m
      memory: 200Mi
  secret:
    create: true
    name: null
  sendAllMetadata: false
  serviceAccount:
    create: true
    name: null
  sourcetypePrefix: kube
  splunk:
    hec:
      caFile: null
      clientCert: null
      clientKey: null
      consume_chunk_on_4xx_errors: null
      fullUrl: null
      host: null
      indexName: null
      insecureSSL: null
      port: null
      protocol: null
      token: null
    ingest_api:
      debugIngestAPI: null
      eventsEndpoint: null
      ingestAPIHost: null
      ingestAuthHost: null
      serviceClientIdentifier: null
      serviceClientSecretKey: null
      tenant: null
      tokenEndpoint: null
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
splunk-kubernetes-metrics:
  affinity: {}
  aggregatorBuffer:
    '@type': memory
    chunk_limit_records: 10000
    chunk_limit_size: 10m
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 10
    retry_type: periodic
    retry_wait: 30
    total_limit_size: 400m
  aggregatorTolerations: {}
  buffer:
    '@type': memory
    chunk_limit_records: 10000
    chunk_limit_size: 10m
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 10
    retry_type: periodic
    retry_wait: 30
    total_limit_size: 400m
  customFilters: {}
  customFiltersAggr: {}
  enabled: false
  environmentVar: null
  environmentVarAgg: null
  image:
    name: splunk/k8s-metrics
    pullPolicy: IfNotPresent
    pullsecretName: null
    registry: docker.io
    tag: 1.1.11
    usePullSecret: false
  imageAgg:
    name: splunk/k8s-metrics-aggr
    pullPolicy: IfNotPresent
    pullsecretName: null
    registry: docker.io
    tag: 1.1.11
    usePullSecret: false
  kubernetes:
    bearerTokenFile: null
    caFile: null
    clusterName: null
    insecureSSL: false
    kubeletAddress: null
    kubeletPort: null
    kubeletPortAggregator: null
    secretDir: null
    useRestClientSSL: true
  logLevel: null
  metricsInterval: 15s
  nodeSelector:
    beta.kubernetes.io/os: linux
  podAnnotations: null
  podAnnotationsAgg: null
  podSecurityPolicy:
    apiGroup: policy
    apparmor_security: true
    create: false
  priorityClassName: null
  priorityClassNameAgg: null
  rbac:
    create: true
  resources:
    fluent:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 200m
        memory: 300Mi
  secret:
    create: true
    name: null
  serviceAccount:
    create: true
    name: null
    usePullSecrets: false
  splunk:
    hec:
      caFile: null
      clientCert: null
      clientKey: null
      consume_chunk_on_4xx_errors: null
      fullUrl: null
      host: null
      indexName: null
      insecureSSL: null
      port: null
      protocol: null
      token: null
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
splunk-kubernetes-objects:
  affinity: {}
  buffer:
    '@type': memory
    chunk_limit_records: 10000
    chunk_limit_size: 20m
    flush_interval: 5s
    flush_thread_count: 1
    overflow_action: block
    retry_max_times: 10
    retry_type: periodic
    retry_wait: 30
    total_limit_size: 600m
  checkpointFile:
    name: kubernetes-objects.pos
    volume: null
  customFilters: {}
  enabled: false
  environmentVar: null
  image:
    name: splunk/kube-objects
    pullPolicy: IfNotPresent
    pullSecretName: null
    registry: docker.io
    tag: 1.1.11
    usePullSecret: false
  indexFields: []
  kubernetes:
    bearerTokenFile: null
    caFile: null
    clientCert: null
    clientKey: null
    clusterName: null
    insecureSSL: false
    secretDir: null
    url: null
  logLevel: null
  nodeSelector:
    beta.kubernetes.io/os: linux
  objects:
    core:
      v1:
      - name: pods
      - name: namespaces
      - name: nodes
      - mode: watch
        name: events
  podAnnotations: null
  podSecurityPolicy:
    apiGroup: policy
    apparmor_security: true
    create: false
  priorityClassName: null
  rbac:
    create: true
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
  secret:
    create: true
    name: null
  serviceAccount:
    create: true
    name: null
    usePullSecrets: false
  splunk:
    hec:
      caFile: null
      caPath: null
      clientCert: null
      clientKey: null
      consume_chunk_on_4xx_errors: null
      fullUrl: null
      host: null
      indexName: null
      indexRouting: null
      insecureSSL: null
      port: null
      protocol: null
      token: null
  tolerations: []

**Comment by aseemand** [comment]
[Raw sample data of k8s.log](https://github.com/splunk/splunk-connect-for-kubernetes/files/10406924/Raw.sample.data.of.k8s.log)
[Splunk log of k8s.log](https://github.com/splunk/splunk-connect-for-kubernetes/files/10406925/Splunk.log.of.k8s.log)

**Comment by aseemand** [comment]
1. Kubernetes version (use `kubectl version`)
>>>> 1.21
2. Ruby version (use `ruby --version`)
>>>> The SCK s/w dependencies are bundled into the container image that is deployed through the Daemon set. SCK is running on an out-of-the-box EKS with the following OS/Runtime configuration.
3. OS (e.g: `cat /etc/os-release`)
>>>>> OS: linux (amd64)
             OS Image: Amazon Linux 2
             Kernel version: 5.4.141-67.229.amzn2.x86_64
4. Splunk Connect for Kubernetes helm chart version
>>>> splunk-connect-for-kubernetes-1.4.15
5. Is the version of the SCK setup is same throughout the deployment (with version name)?
>>>> It appears to be the same. All are using the same images and are deployed from the same DaemonSet. I do not see any labels other than this - which is consistent across all the pods.( controller-revision-hash=59cfbf9f74)

**Comment by harshit-splunk** [comment]
Hey @aseemand, from where [Splunk log of k8s.log](https://github.com/splunk/splunk-connect-for-kubernetes/files/10406925/Splunk.log.of.k8s.log) is coming from? And what does it indicate?

It is expected behaviour from the metadat_filter plugin.

In one of the issue, they stated:
_Pod info is scraped from the container log file name which provides the name of namespace but not its unique id. This means in a scenario where NS is created, deleted, recreated from the same name and logs still exist on disk, you could potentially be trying to associate meta from the original version of the NS even though its uuid is different then the latest.
The plugin has some logic to try and cache metadata based on ns, podname, uids, and creation dates. If using this combo of info it is unable to "match" a log entry to a known container, it will fall back to orphan. If you are creating a number of short lived pods you may be pushing the meta out of the LRU cache._
Source: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/234#issuecomment-634931613

**Comment by aseemand** [comment]
Hi @harshit-splunk , 

I got the update from the customer, can you please look into this and help me with the mentioned concerns: 

The resolution for this issue is unclear in your previous email. Splunk connect is misrouting logs and this still the case – we need a way to get these logs back to the correct namespaces. Please advise – this is happening on the production cluster.

In your response, you mentioned this is expected behavior for the plugin but none of those scenarios from the comment apply.

None of the namespaces that are misrouting have been deleted or re-created.
We are not creating workloads that are short-lived – the pod that is misrouting logs has been stable for the last 42 days without any restarts.
 
Moreover, the kube-system namespace holds multiple pods, and only one of those pods is misrouting. (That pod also belongs to the K8s node which contains other pods that are also misrouting.) This is the same node from which I shared log snippets earlier.

The screenshot below is from a query that filters out all the “.Orphaned” namespace entries. 100% of them are coming from one node from the cluster.

![image](https://user-images.githubusercontent.com/122571312/213292684-c66de657-b85e-4dc5-8905-2d5f6cd71510.png)

Thanks!
