### ISSUE TITLE
buffer values configurable

### ISSUE THREAD

**Issue by MarcoSchaar** [splunk/splunk-connect-for-kubernetes#86]
hello 
could you please adjust configmap to be able to set values for buffer and retries etc.

https://github.com/splunk/splunk-connect-for-kubernetes/blob/master/helm-chart/splunk-kubernetes-logging/templates/configMap.yaml#L232

kind regards
Marco

**Comment by dtregonning** [comment]
@chaitanyaphalak can you add this please

**Comment by chaitanyaphalak** [comment]
This was Fixed in the 1.1.0 release
