### ISSUE TITLE
How do I add kube api audit.log to splunk ?  

### ISSUE THREAD

**Issue by rufengxu** [splunk/splunk-connect-for-kubernetes#94]
How do I add kube api audit.log to splunk ?  How do I add it to the configmap.yaml ? The log is in json format.

https://kubernetes.io/docs/tasks/debug-application-cluster/audit/

Thanks a lot !

**Comment by rufengxu** [comment]
Some additional info.  we’d like to have the logs(including Audit.log), of Kubernetes’ Control Plane sent to Splunk.

    Splunk Connect for Kubernetes only cover Data Plane.

**Comment by matthewmodestino** [comment]
Hey rufengxu!

The audit log can be added by creating another fluentd `source` in the configmap or helm chart. 

I will turn on logging in my cluster and post and example asap!

**Comment by matthewmodestino** [comment]
Hey Rufeng!

I managed to update my config map to collect kube api audit logs, using the following steps:


Updated source.files.conf in the configmap to pick up the audit log

```
<source>
      @id kube-api-audit.log
      @type tail
      @label @SPLUNK
      tag kube.api.audit.*
      path /var/log/kube-audit/kube-api-audit.log
      pos_file /var/log/splunk-kube-api-audit.log.pos
      path_key source
      read_from_head true
      <parse>
        @type json
        time_key requestReceivedTimestamp
        time_type string
        time_format %Y-%m-%dT%H:%M:%S.%NZ
        keep_time_key true
        localtime false
      </parse>
    </source>
```

The update the filters to ensure I send the container logs to one index, while sending the audit logs to another

```
  <filter tail.containers.**>
      @type jq_transformer
      jq ".record.index = \"cm_events\" | .record"
    </filter>

  <filter kube.api.audit.**>
      @type jq_transformer
      jq ".record.index = \"kube-api-audit\" | .record.sourcetype = \"kube:api:audit\" | .record"
    </filter>
```

Then updated the HEC plugin to set the `index_key index` and add a format block to tell the plugin to send the audit logs in JSON format. 

```
<match **>
      @type splunk_hec
      protocol https
      hec_host "standalone"
      hec_port 8088
      hec_token "00000000-0000-0000-0000-000000000000"
      host "myHost"
      source_key "source"
      sourcetype_key "sourcetype"
      index_key "index"
      insecure_ssl true
      <fields>
        pod 
        namespace 
        container_name 
        container_id 
      </fields>
      <buffer>
        @type "memory"
        chunk_limit_records 100000
        flush_interval 5s
        flush_thread_count 1
        overflow_action block
        retry_max_times 3
      </buffer>
      <format kube.api.audit.**>
        @type "json"
      </format>
      <format monitor_agent>
        @type "json"
      </format>
      <format>
        @type "single_value"
        message_key "log"
        add_newline false
      </format>
    </match>


![image](https://user-images.githubusercontent.com/31549209/52883729-f4b65e00-3139-11e9-9cf2-381623a23c57.png)

**Comment by rufengxu** [comment]
Thanks, Matt. So we need a separate index for audit log files ?  It should
not or can not go to the same index we send kube logs/objects ?

Thanks,
Rufeng

**Comment by matthewmodestino** [comment]
You absolutely can send it all to one index.

I figured I’d show some routing options. If you would like it all in one index, just skip adding the filters and the `index_key index`

**Comment by dtregonning** [comment]
Thanks @matthewmodestino.
@rufengxu if you have more questions please reopen. 
Closing

**Comment by rufengxu** [comment]
Mark, thanks for your help.  I am getting an error "unable to find the directory".  My pods are running on the worker nodes, but the audit.log is located on the api server.  How does it get the files from another server then ?

**Comment by dmcnaught** [comment]
I configured with these instructions - thanks @matthewmodestino 
@rufengxu I put my audit log to /var/log/kube-apiserver-audit.log so I don't get the unable to find directory error. I see `/var/log/kube-apiserver-audit.log not found. Continuing without tailing it.` on my nodes, which seems fine, and the audit logs are sent to splunk from my masters.

**Comment by holmesb** [comment]
Any idea how to specify this audit config in the helm chart?  Eg I can't see how to specify ``@type "json"`` in the helm values
