### ISSUE TITLE
Wildcards needed to search for pod, namespace, container_name, and container_id

### ISSUE THREAD

**Issue by alfresh** [splunk/splunk-connect-for-kubernetes#97]
I have splunk-connect installed on my openshift cluster and logs showing up in Splunk. Events do have the fields pod, namespace, container_name, and container_id and value populating them. The issue is searching by any of these fields, searching namespace="openshift-node" will return no results, but namespace="*openshift-*node" with wildcards will return all the expected results. I'm not sure if this is something with Splunk itself or how splunk-connect is using jq to parse the filename in the fluentd config:

`jq "def find_sourcetype(pod; container_name): container_name + \"/\" + pod | if startswith(\"dns-controller/dns-controller\") then \"kube:dns-controller\" elif startswith(\"sidecar/kube-dns\") then \"kube:kubedns-sidecar\" elif startswith(\"dnsmasq/kube-dns\") then \"kube:dnsmasq\" elif startswith(\"etcd-container/etcd-server\") then \"kube:etcd\" elif startswith(\"etcd-container/etcd-server-events\") then \"kube:etcd-events\" elif startswith(\"kube-apiserver/kube-apiserver\") then \"kube:kube-apiserver\" elif startswith(\"kube-controller-manager/kube-controller-manager\") then \"kube:kube-controller-manager\" elif startswith(\"autoscaler/kube-dns-autoscaler\") then \"kube:kube-dns-autoscaler\" elif startswith(\"kube-proxy/kube-proxy\") then \"kube:kube-proxy\" elif startswith(\"kube-scheduler/kube-scheduler\") then \"kube:kube-scheduler\" elif startswith(\"kubedns/kube-dns\") then \"kube:kubedns\" else empty end;  def extract_container_info:   (.source | ltrimstr(\"/var/log/containers/\") | split(\"_\")) as $parts   | ($parts[-1] | split(\"-\")) as $cparts   | .pod = $parts[0]   | .namespace = $parts[1]   | .container_name = ($cparts[:-1] | join(\"-\"))   | .container_id = ($cparts[-1] | rtrimstr(\".log\"))   | .;    .record | extract_container_info | .sourcetype = (find_sourcetype(.pod; .container_name) // \"kube:container:\\(.container_name)\")" `

**Comment by dtregonning** [comment]
Hi @alfresh - Searching for metadata that comes through with logs via HEC fields often just needs a small tweak to work as expected.

could you try the search 
namespace::"openshift-node"

This article can provide some more information - https://answers.splunk.com/answers/635676/why-do-i-need-to-search-metadata-in-a-fields-argum.html

**Comment by alfresh** [comment]
@dtregonning That was the issue. Thanks for the info!
