### ISSUE TITLE
Logging pod to reflush buffered files after restart 

### ISSUE THREAD

**Issue by sayeedc** [splunk/splunk-connect-for-kubernetes#98]
Is it possible for the logging pod to clear backlogged buffer files after a restart. This is a known problem with the EFK stack and possibly a constraint on fluentd. Sometimes, it’s not possible to avoid a pod restart, and we’ll end up with orphaned buffered files that we’d need to manually delete. 

One option that we’ve considered is to configure a readiness probe to delete buffered files on restart.

**Comment by dtregonning** [comment]
Hi @sayeedc - currently no.
Its definitely something thats been floated around the team as to how we could solve the issue. We wont be covering this in our upcoming release but is something we will look at in the next one.

**Comment by sayeedc** [comment]
That's great. Thanks.

**Comment by sayeedc** [comment]
Hi @dtregonning

We recently experienced this issue with substantial log loss for certain users as the worker now was affected. Since we buffer to file what workaround could we implement to mitigate loss in future scenarios?

**Comment by rockb1017** [comment]
https://github.com/fluent/fluentd/issues/2698
i think this was fixed by fluentd.
